### ISSUE TITLE
Add snap functionality to Stop watch Task 18

### ISSUE THREAD

**Issue by Hetu1107** [swapnilsparsh/30DaysOfJavaScript#10]
means on click snap adding h1 tag with the time when snap button clicked. Can i work on this ?

**Comment by dolamanee6122** [comment]
I would like to work in this issue, please asign this issue to me.

**Comment by swapnilsparsh** [comment]
> means on click snap adding h1 tag with the time when snap button clicked. Can i work on this ?

Ok

**Comment by swapnilsparsh** [comment]
> I would like to work in this issue, please asign this issue to me.

First come, first serve is considered in this project.😕
Please look after other issues, waiting for your valuable contribution to the project.😊
