### ISSUE TITLE
Fix the Feeback UI

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1000]
[Feedback UI](https://30daysofjs.netlify.app/33%20-%20feedback%20ui/)

Images are not showing up in Unhappy/Neutral/Satisified so fix it.

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Assign to me sir

**Comment by Bharadwajshivam28** [comment]
And please elaborate it sir

**Comment by GitWiz01** [comment]
@swapnilsparsh please assign me this issue I have solved the problem will get back with a pr asap

**Comment by Bharadwajshivam28** [comment]
thanks sir

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 If you will visit [here](https://30daysofjs.netlify.app/33%20-%20feedback%20ui/) there you can see that there are images missing from unhappy, neutral, satisfied that you have to fix it.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Bharadwajshivam28** [comment]
i will fix it

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Sir in this the links are not valid because when i am doing it with other image the image is shown

**Comment by Bharadwajshivam28** [comment]
so can you drop which image or logo to use as link is not valid

**Comment by Bharadwajshivam28** [comment]
as these links are wrong

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28  **These were the images which were used earlier or you can replace with them emoji. Anything which is more suitable**

![screenshot1](https://user-images.githubusercontent.com/69387608/221343101-0898abb2-9335-495e-8921-47008b4b52a3.png)

**Comment by Bharadwajshivam28** [comment]
ok sir
