### ISSUE TITLE
Fix IP Address Tracker

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1001]
IP Address Tracker is not working, check it [here](https://30daysofjs.netlify.app/62%20-%20ip%20address%20tracker/)

**Comment by abhishek-kumar-91** [comment]
I want to work on this issue, Can you assign me?

**Comment by abhishek-kumar-91** [comment]
hey @swapnilsparsh can you tag this issue with hacktoberfest?

**Comment by abhishek-kumar-91** [comment]
“HACKTOBERFEST-ACCEPTED” LABEL,

**Comment by rahul0x00** [comment]
hi @swapnilsparsh  , it seems abhishek is not working on this, if you assign it to me i'd love to solve this

**Comment by rahul0x00** [comment]
Hi @swapnilsparsh,

I've identified an issue related to the API key in the project. It seems there might be a problem with the current API key configuration. I would like to discuss this further and possibly request a new API key to resolve the issue.

Could you please provide some guidance on how to proceed or let me know if you would be open to issuing a new API key for the project?

**Comment by rahul0x00** [comment]
@swapnilsparsh Hi, swapnil i've created PR for this issue, can you check the status of it?
