### ISSUE TITLE
Add delete option in Notes Taking App

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1002]
Add a delete option to delete a particular note [here](https://30daysofjs.netlify.app/53%20-%20notes%20taking%20app/)

**Comment by ananyakushal** [comment]
Hey @swapnilsparsh please assign me this task under IWOC'23.

**Comment by swapnilsparsh** [comment]
@ananyakushal You are already assigned with 2 tasks so finish them off then get it assign on new task.

**Comment by ananyakushal** [comment]
Sure.

**Comment by Talbert500** [comment]
@swapnilsparsh this is my first project but please assign me to this task
