### ISSUE TITLE
Enhance Color Game

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1003]
Check it live [here](https://30daysofjs.netlify.app/59%20-%20color%20choosing%20game/)

1. Remove the Get colors button which is showing by default
2. When user selects the correct color then only show Get Colors button
3. When users lost the game then it should show the correct color stating you lost the game and correct option was this.

**Comment by subhamkumarr** [comment]
Please assign to me

**Comment by vinitsingh-13** [comment]
please assign to me i can help to make better UI of the game for better user intersection

**Comment by rahul0x00** [comment]
Hi, @swapnilsparsh, could you assign it to me as it seems the previous assignee is not working on this issue?

**Comment by vinitsingh-13** [comment]
bro i am working on it you can see my previous pull request of the BMI calculator after the admin merge that request then you can see the UI that i have updated.

**Comment by rahul0x00** [comment]
@vinitsingh-13 oh nvm then, i thought you're not working on this issue.

**Comment by Kedarnath-Rothe** [comment]
Please assign me this issue

**Comment by Vivek-GuptaXCode** [comment]
hello maintainers i would like to work on this issue,please assign it to me.Have a great day!!

**Comment by PallavJain01** [comment]
Please assign this to me, I know a way of fixing it.

**Comment by Vivek-GuptaXCode** [comment]
thanks for showing interest but i am working on this issue and will submit a PR soon.

**Comment by PallavJain01** [comment]
Oh sorry, I thought you weren't working on this issue as it had been 2 weeks
