### ISSUE TITLE
Add Swap option

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1004]
In [Currency Converter](https://30daysofjs.netlify.app/67%20-%20currency%20converter/) add a option to swap the two currency like if someone chooses to convert from USD -> INR then a button should be there when clicking on it swaps the options and make it INR -> USD

**Comment by ananyakushal** [comment]
Hey @swapnilsparsh please assign me this task under IWOC'23. I will try my best to resolve this issue asap.

**Comment by swapnilsparsh** [comment]
@ananyakushal You are already assigned with 2 tasks so finish them off then get it assign on new task.

**Comment by ananyakushal** [comment]
Sure.

**Comment by amaan-lari** [comment]
Hey!! can you please assign me this issue under IWOC'23. I have solved the issue.
