### ISSUE TITLE
Enhance Casino Slot Machine Game

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1006]
[Casino Slot Machine Game](https://30daysofjs.netlify.app/73%20-%20casino%20slot%20machine%20game/) 

1. When opening the page the game should not start by default
2. The speed should be bydefault set to 10 and make it disbale once the game is started
3. When clicking on Start then it should start the game and tht button should be disabled.
4. When clicking on stop button it should stop the Game and show all the 3 emoji then it should show the result accordingly that you win or loose.
5. After the game is finished then it should make the Start button and speed option active and you can play the game again.

**Comment by Marin303** [comment]
I would like to be assigned here.
