### ISSUE TITLE
Add download option

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1012]
In Random Anime Profile , check it [here](https://30daysofjs.netlify.app/74%20-%20random%20anime%20profile/)

1. Add a button to save the image 
2. Add a loder to whole card when data is getting fetched up and showing up on the webpage

**Comment by ananyakushal** [comment]
Hey @swapnilsparsh please assign me this task under IWOC'23. I have already made changes in the file.
![random anime](https://user-images.githubusercontent.com/123202108/221767366-5435df00-56ea-47ae-8b42-c0e657b3e899.png)
