### ISSUE TITLE
Fix Car Game

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1013]
Check the Car Game [here](https://30daysofjs.netlify.app/76%20-%20car%20game/)

1. When page gets load up then automatically game should not start instead add a button to start the game
2. The red boxes are automatically getting disappeared when car is getting close to it.
3. Show score also when game starts and reset it when someone restarts the game also shows the highest score of that user.
4. When Game gets over then a button should be there to restart the Game

**Comment by A91y** [comment]
Please merge and close this issue if everthing works alright as today is iwoc closing date.
Thank You

**Comment by A91y** [comment]
Please assign this issue to me but I already sent the PR resolving the issue and upgrading the quality of images as well as game.

**Comment by swapnilsparsh** [comment]
@A91y Good you have upgraded the images quality but you have to optimise it so that it loads fast
Also you haven't fixed point numbers 2 ,3 4

You dont have to make a new page to show start button instead show the start button on the game page and when game is in progress then you have to disable the start button. At last when game over then you have to enable the start button to play again the game.

**Comment by A91y** [comment]
No I have not created new page for start button, it's just a single page application being operated by plain javascript and css visibility.![Screenshot_2023-02-28-03-43-12-66_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/65825207/221697877-ddacd848-1908-4086-afc3-377532c95f24.jpg)

**Comment by swapnilsparsh** [comment]
@A91y When you open the car game now then there is no car game shown Only the start button is there which should not be the case.

The game should be there with the start button and when clicking on the start button it should disable it and when the game gets over then the start button should be enabled again

Point number 2 is when you start the game then you will notice that the red cars start getting disappeared  even though the yellow car is not even closer to it. Instead the cars should not disappear as it should go away when the lane is out of range from screen .

**Comment by A91y** [comment]
No I have not created new page for start button, it's just a single page application being operated by plain javascript and css visibility.![Screenshot_2023-02-28-03-43-12-66_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/65825207/221697877-ddacd848-1908-4086-afc3-377532c95f24.jpg)

    Sir I have tried to solve the rest of the problems in lastest PR.

**Comment by A91y** [comment]
Sir I have tried to resolve rest of the problems in lastest PR.
