### ISSUE TITLE
Fix the Clock

### ISSUE THREAD

**Issue by dhruv-porwal** [swapnilsparsh/30DaysOfJavaScript#1015]
### What happened?
Made clock chrome browser compatible as earlier it was crashing on some versions of chrome browsers.

### How can we reproduce this bug?

On running it on previous versions of chrome browser.

### Urgency (Optional)

Medium priority

**Comment by dhruv-porwal** [comment]
sir please assign this issue to me under IWOC tag

**Comment by swapnilsparsh** [comment]
@dhruv-porwal Can you plase provide the screenshots

**Comment by dhruv-porwal** [comment]
> @dhruv-porwal Can you plase provide the screenshots

Sir I can't provide the screen shot at present but this code was showing warning signs at degree symbols in inspection.

**Comment by dhruv-porwal** [comment]
Please assign this issue to me under iwoc
