### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by Bharadwajshivam28** [swapnilsparsh/30DaysOfJavaScript#1017]
I have created a complete Blog of project and published it on hashnode.
It have Github repositary link and all details of project of project.
I have also attached the link of blog in Readme file

@swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
I have created a pull request so  please assign to me, add IWOC tag and medium/hard tag

**Comment by Bharadwajshivam28** [comment]
https://codeshivam28.hashnode.dev/30-days-of-javascript

**Comment by Bharadwajshivam28** [comment]
Reach the blog sir

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 Great that you have created Blog and published on hashnode but why you have opened the issue , what will you make changes in this ?

**Comment by Bharadwajshivam28** [comment]
like sir

**Comment by Bharadwajshivam28** [comment]
without issue i cant be assigned so like in IWOC  i wll not get points if not assigned with tags

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 This issue is irrelevant. Have a look at different issues which are already opened.
