### ISSUE TITLE
Extra ( > )in tic-tac-toe box appearing

### ISSUE THREAD

**Issue by SK-21** [swapnilsparsh/30DaysOfJavaScript#1032]
## Extra > is appearing in the box of tic-tac-toe game.

> Attaching the screenshot of the issue-
![issues](https://cdn.discordapp.com/attachments/1110569329541513277/1110581411586527282/Screenshot_2023-05-23_at_8.17.09_PM.png)

## Yes, I have tried to rectify the issue which is appearing in the box of the tic-tac-toe game as It's breaking the UI. 

> Attaching screenshot after removing the >
![issues-resolved](https://cdn.discordapp.com/attachments/1110569329541513277/1110792468099772416/Screenshot_2023-05-24_at_10.22.25_AM.png)

### Urgency (Optional)

None

**Comment by swapnilsparsh** [comment]
@SK-21 NIce catch on the bug
