### ISSUE TITLE
Fix dark mode button responsiveness 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1035]

**Comment by parth656** [comment]
@swapnilsparsh please assign it to me

**Comment by subhamkumarr** [comment]
Please assign it to me

**Comment by subhamkumarr** [comment]
@swapnilsparsh which file i need to change there are lots of file

**Comment by swapnilsparsh** [comment]
[This](https://github.com/swapnilsparsh/30DaysOfJavaScript/tree/master/30DaysOfJavaScript) is the folder @subhamkumarr

**Comment by shauryakushwaha08** [comment]
can you please assign it to me
