### ISSUE TITLE
UI Enhancement for BMI CALCULATOR

### ISSUE THREAD

**Issue by subhamkumarr** [swapnilsparsh/30DaysOfJavaScript#1037]
### Which pre-existing JavaScript project will you be working on?

BMI Calculator

### Describe your enhancement/improvement

The interface of the BMI calculator looks disarranged and unaligned.

Describe the solution you'd like:
I would like to restructure the interface to give the user a user-friendly experience.
Provide List details under what BMI values a person is overweight, underweight...... 

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/99977240/72477fe5-62cb-4a1b-8fc9-e6a272ea1943)

**Comment by subhamkumarr** [comment]
@swapnilsparsh please review the issue. I would like to work on this

**Comment by vinitsingh-13** [comment]
i can make the UI better for better user intersection. assign this task to me

**Comment by Vivek-04022001** [comment]
@swapnilsparsh, Hello! I'm new to this repository, and I'm eager to contribute to this project. Could you please assign me a task or suggest an area where I can get started? Thank you!

**Comment by vinitsingh-13** [comment]
> @swapnilsparsh, Hello! I'm new to this repository, and I'm eager to contribute to this project. Could you please assign me a task or suggest an area where I can get started? Thank you!

This issue is already resolved you can try on other repo of same repository

**Comment by devdeep2003** [comment]
Hey I can improvise the UI and make it look professional ! Assign me to it
