### ISSUE TITLE
Country Detail Footer is not fixed

### ISSUE THREAD

**Issue by subhamkumarr** [swapnilsparsh/30DaysOfJavaScript#1039]
The footer is not fixed. It is moving up and down on data displacement.

![Screenshot (731)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/99977240/92b5cd99-dd69-44b4-a2e3-3325bb02c693)
![Screenshot (730)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/99977240/f0424bc4-f4f5-4003-8c35-6ae98ded03a0)

**Comment by subhamkumarr** [comment]
@mansi-singla-31215 Please review the issue. I would like to work on this.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Kedarnath-Rothe** [comment]
Please add hactoberfest label to this issue
