### ISSUE TITLE
Footer Issue In Note Taking App

### ISSUE THREAD

**Issue by subhamkumarr** [swapnilsparsh/30DaysOfJavaScript#1041]
### Which pre-existing JavaScript project will you be working on?

Note Maker App

### Describe your enhancement/improvement

1. The footer is not sticky. It's moving up and down on the creation of a new notes footer.
2.  notes card UI should be enhance. 

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/99977240/d4228d83-e272-4477-8bee-e0b5e5781099)

**Comment by swapnilsparsh** [comment]
@subhamkumarr Work only The footer is not sticky. It's moving up and down on the creation of a new notes footer.

**Comment by subhamkumarr** [comment]
@swapnilsparsh please check the require changes
