### ISSUE TITLE
Title: Fixing Image Issue 

### ISSUE THREAD

**Issue by Dimple-Choudhary** [swapnilsparsh/30DaysOfJavaScript#1052]
### Which pre-existing JavaScript project will you be working on?

I would Like to fix image on page 3,4,5,6,7  .

### Describe your enhancement/improvement

I will add a Screenshot of a particular project in their respective image card component.

### Anything you need to say to the Reviewers

@swapnilsparsh  will you assign me this issue under GSSOC'23?

**Comment by swapnilsparsh** [comment]
@Dimple-Choudhary You can work on this issue but this repo is not part of GSSoC 23. Would you still want to contribute ?

**Comment by swapnilsparsh** [comment]
No time limit but keep me updated with your progress if it is taking time.
