### ISSUE TITLE
Title: Option to bold, italic and underline in the Notes Taking App - 53

### ISSUE THREAD

**Issue by shauryakushwaha08** [swapnilsparsh/30DaysOfJavaScript#1079]
### Is your feature request related to a problem? Please describe.

There is no option to bold, italic, or underline the notes-taking app.
Adding this will enhance its features.

### Describe the solution you'd like.

At the bottom, there will be 3 buttons available to bold, italic, or underline the text.

### Describe alternatives you've considered.

The user can press - 
Bold - Ctrl + B
Italics - Ctrl + I
Underline - Ctrl + U

**Comment by Vivek-04022001** [comment]
Im interested to create this feature. Assign this task to me.

**Comment by rituraj12797** [comment]
@swapnilsparsh  ploease assign this issue to me i would love to work on this issue

**Comment by swapnilsparsh** [comment]
@rituraj12797 It is already assigned to @shauryakushwaha08. You can look after for some other issues.
