### ISSUE TITLE
Title: Weather App

### ISSUE THREAD

**Issue by manmohanhunjan** [swapnilsparsh/30DaysOfJavaScript#1085]
### Which pre-existing JavaScript project will you be working on?

I'm making a weather app for hacktoberfest.

### Describe your enhancement/improvement

This project uses openweather-api and fetch to seamlessly load the data we search for.

**Comment by swapnilsparsh** [comment]
@manmohanhunjan This project is already there, you can check out [here](https://30daysofjs.netlify.app/25%20-%20Weather%20App/index.html)
