### ISSUE TITLE
Title: Javascript tool that can Encode & Decode Text

### ISSUE THREAD

**Issue by M3hank** [swapnilsparsh/30DaysOfJavaScript#1099]
### Is your feature request related to a problem? Please describe.

This tool Can Encode as Well as decode text in Several formats.

### Describe the solution you'd like.

I have added Several modules that can handle Encoding & Decoding formats such as base64, url-encode, unicode, html entity, binary & hex.

### Describe alternatives you've considered.

The text encoding are very essential for cyber-security enthusiasts as they help in various security research such as bypassing Firewalls.

### Add any other context or screenshots about the feature request here.

![Screenshot from 2023-10-11 08-14-21](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/70057473/a3dc1936-57f9-4ba1-92a8-251ade0d59dd)

**Comment by Kedarnath-Rothe** [comment]
Pease assign to me
