### ISSUE TITLE
Enhancement: Searchbar is bottom is touching projects cards and need some improvements

### ISSUE THREAD

**Issue by ratishjain12** [swapnilsparsh/30DaysOfJavaScript#1101]
### What happened?

@swapnilsparsh currently the search bar does not look right and is colliding with the cards
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/43003421/618d5d84-e6e0-448f-9383-ecacf992693c)

I want to improve this section kindly assign me this issue :)

### How can we reproduce this bug?

-

### Desktop Information (Optional)

-

### Urgency (Optional)

None

**Comment by Kedarnath-Rothe** [comment]
Pease assign to me
