### ISSUE TITLE
On hovering project backtotop button is not visible

### ISSUE THREAD

**Issue by harshita-2003** [swapnilsparsh/30DaysOfJavaScript#1109]
### What happened?

When you hover over any project on back top top mentioned it goes behind the project which should not be the case

### How can we reproduce this bug?

we need togive it correct z-index so it wont go behind 

### Urgency (Optional)

High priority

**Comment by ashurohilla** [comment]
assign me that issue

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
