### ISSUE TITLE
[DOCS] CONTRIBUTING.md requires an update 🔥

### ISSUE THREAD

**Issue by 0Armaan025** [swapnilsparsh/30DaysOfJavaScript#1118]
### Description

Hey there!
If you are reading this, you are amazing! 🔥

while reading contributing.md, it feels a bit plain, a bit less encouraging/fun, I thought why not make it more fun, engaging, emojified and to the  next level? 🚀

**Comment by HimanshuMahto** [comment]
Hey, Can you assign me this issue? I would love to work on this.
