### ISSUE TITLE
Fix naming in directory

### ISSUE THREAD

**Issue by tmsagarofficial** [swapnilsparsh/30DaysOfJavaScript#1126]
### What happened?

First of all, I'm delighted to see this huge repo with all the rules and best practices in place. Kudos @swapnilsparsh 🤝 

While going through this repo I found that all the individual directories containing each project were named very perfectly.
😓 except for this one project
I mean yeah this is acceptable out of 200+ projects
<img width="274" alt="image" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/110724849/e3c93861-5e5d-41e7-8244-f675ebdd6039">
I would love to fix this issue by making sure the spacing is right in the folder name. Pls, assign this issue to me.

### How can we reproduce this bug?

Go to https://github.com/swapnilsparsh/30DaysOfJavaScript
scroll till u see
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/110724849/9f242dd7-c90c-4b1a-ac79-8166f701e382)

or go to `19 -Traffic Lights` i.e https://github.com/swapnilsparsh/30DaysOfJavaScript/tree/master/19%20-Traffic%20Lights to see the missing ` ` in the name just after `-`

### Urgency (Optional)

Low priority

**Comment by swapnilsparsh** [comment]
@tmsagarofficial Good Luck 👍
