### ISSUE TITLE
Fix: Weather App

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1137]
Live Website [here](https://30daysofjs.netlify.app/25%20-%20Weather%20App/index.html)

When you type wrong Country/City name for the first time then it shows message "Enter Correct Country/City Name" but if you have searched any correct name you will get the result but when you search again with wrong name then the message is not showing.

**Comment by avelynhc** [comment]
Hello, can I work on this issue? Thanks!

**Comment by Tgreen2709** [comment]
**I fixed it like this** [Link](https://github.com/Tgreen2709/30DaysOfJavaScript/blob/master/25%20-%20Weather%20App/script.js)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141889394/fa88d9e6-6e4e-4f3a-8c0c-2ddc4c03ac88)

**Comment by swapnilsparsh** [comment]
@avelynhc Good Luck 👍
@Tgreen2709 Issues are assigned on first come first serve basis if @avelynhc did not do any progress in this issue in 2-3days then I will assign the issue to you.

**Comment by Tgreen2709** [comment]
@avelynhc Can you give it to me? I really enjoyed this issue

**Comment by Tgreen2709** [comment]
@swapnilsparsh if @avelynhc  agree to give me this issue, may I have it? I really want to do it

**Comment by swapnilsparsh** [comment]
@Tgreen2709 Yes sure.

**Comment by avelynhc** [comment]
@Tgreen2709 @swapnilsparsh I am working on it right now.

**Comment by Tgreen2709** [comment]
**Solution**
Just check when calling the API, if the API returns code 404, it will immediately show the message that that city does not exist.
https://30daysofjs.netlify.app/25%20-%20Weather%20App/index.html
**I fixed it like this** 
[Link code](https://github.com/Tgreen2709/30DaysOfJavaScript/blob/master/25%20-%20Weather%20App/script.js)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141889394/fa88d9e6-6e4e-4f3a-8c0c-2ddc4c03ac88)

**Comment by swapnilsparsh** [comment]
@avelynhc Thanks for your contribution! Excited for more in the future! 🥂
