### ISSUE TITLE
Fix Notes Taking App options

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1142]
When someone writes anyting in the note then there are no option shown to delete, bold, italics, underline. If you dont write anything in note then options will be shown.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/7649f5c6-69f9-49e3-aee4-818cfd746cd0)

**Comment by gautamjuyal** [comment]
Can I work on this issue?
