### ISSUE TITLE
Fix Coin Game

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1143]
Repo [Link](https://github.com/swapnilsparsh/30DaysOfJavaScript/tree/master/100%20-%20Coin%20Game)
Live website [here](https://30daysofjs.netlify.app/100%20-%20Coin%20Game/index.html)

**Comment by HarishBisht97** [comment]
Can you please add details regarding the issue?

**Comment by deolekar** [comment]
Tried recreating, but didn't get any issue.
![ScreenRecording2024-02-21at14 20 50-ezgif com-video-to-gif-converter](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/57721854/99bda52d-e521-41da-8c63-5faeb0063b4d)

**Comment by TechSenseiX** [comment]
Hii, I believe I can tackle this issue effectively. I've also taken the time to thoroughly understand the problem and have some ideas on how to approach it.
Could you please assign this issue to me.
I'm eager to contribute and make a meaningful impact.

**Comment by TechSenseiX** [comment]
> @deolekar If you move your cursor fast then game will be over instantly.
 I also tried recreating and figured out that if you touched the wall, immediately game gets over. So, by moving the cursor fast we unknowingly touched the wall.So, that's why game get over instantly.
![Screenshot (30)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/110850648/1e3ff69e-ab9d-4406-a6a2-cb33c151615f)

**Comment by Sanujkumar** [comment]
I will resolve this issue please assign to me

**Comment by AmbitiousCoder-07** [comment]
@swapnilsparsh I think the issue you're describing is not with moving the cursor fast but instead moving it outside the path i.e., in the walls region. Don't you think we should be making some changes in the logic of the game like maybe adding some danger zones or something of that sort to improve this one?

**Comment by swapnilsparsh** [comment]
@Sanujkumar All the best and you can consider @AmbitiousCoder-07 idea.

**Comment by PoojaGadagi08** [comment]
Hello @swapnilsparsh  sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by swapnilsparsh** [comment]
@Sanujkumar Any update ?
