### ISSUE TITLE
Fix: No Project found

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#1144]
Fix two things:
1. If there is no project with sucj name then show a text in middle of the screen "No Project found"
2. Footer should stick to bottom

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/05100f00-f77b-4202-b852-5aa80ae922c3)

**Comment by Bayyana-kiran** [comment]
Hello @swapnilsparsh i would like to contribute to this issue ? 
1st suggestion : solving the footer alignment 
2nd suggestion : solving use javascript by adding function and syntax name for this

Thank You

**Comment by Bayyana-kiran** [comment]
reply

**Comment by swapnilsparsh** [comment]
> Hello @swapnilsparsh i would like to contribute to this issue ? 1st suggestion : solving the footer alignment 2nd suggestion : solving use javascript by adding function and syntax name for this
> 
> Thank You

Good Luck 👍🏻

**Comment by Bayyana-kiran** [comment]
Done with issue @swapnilsparsh kindly check once

**Comment by Bayyana-kiran** [comment]
hello @swapnilsparsh , can u please change the tag to iwoc2024 because i could get the points

**Comment by swapnilsparsh** [comment]
> hello @swapnilsparsh , can u please change the tag to iwoc2024 because i could get the points

Thank you for contributing but this repo is not under iwoc this time.
