### ISSUE TITLE
Title: Navbar missing

### ISSUE THREAD

**Issue by khushi-joshi-05** [swapnilsparsh/30DaysOfJavaScript#1149]
### Is your feature request related to a problem? Please describe.

The project is great but the UI isn't that interactive moreover there is no navnar and the footer also need to be improved

### Describe the solution you'd like.

I have some different colour combinations that will suit it, moreover in the navbar you can add option based on difficulty. i want to make the changes kindly assign me

### Describe alternatives you've considered.

Categorising the projects will be really helpfull.

**Comment by swapnilsparsh** [comment]
@khushi-joshi-05 Do share some color combinations and designs before starting the implementation.

**Comment by Jithendranath8** [comment]
please assign this issue to me . I want to work on it

**Comment by anushkapal28** [comment]
I have some exciting ideas to enhance the project, including new color combinations and adding difficulty-based options to the navbar. Could you assign me this task?

**Comment by Gokilp** [comment]
please assign to me

**Comment by reshamsai150** [comment]
I want to work on this issue  assign me

**Comment by swapnilsparsh** [comment]
@khushi-joshi-05 Than you for providing your insight but it is not required as of now.
