### ISSUE TITLE
In GSSoC'24, GitHub Topics will help the discoverability of your project.

### ISSUE THREAD

**Issue by Princegupta101** [swapnilsparsh/30DaysOfJavaScript#1150]
I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by swapnilsparsh** [comment]
@Princegupta101 Thank you for contributing to the repo but this is not needed as of now.
