### ISSUE TITLE
UI need to be Change in Pagination Section(footer)

### ISSUE THREAD

**Issue by akash6810** [swapnilsparsh/30DaysOfJavaScript#1158]
### Is your feature request related to a problem? Please describe.

For the pagination section, I have an alternative color scheme that is more attractive. In light mode, we cannot determine in which page we are.

### Describe the solution you'd like.

I will select the active button in light mode and change the color and background color.
Before:
![WhatsApp Image 2024-05-09 at 20 04 23_5585df36](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/126563565/832bd7e7-bd9b-4bbf-a481-15700958f5d9)

After:
![WhatsApp Image 2024-05-09 at 20 46 21_53566a4c](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/126563565/51ee2d0b-c608-4315-b6c1-e4d79cb64104)

I roughly made the UI. I want to make the changes kindly assign me.

### Describe alternatives you've considered.

The JavaScript approach involves toggling slide visibility based on a current index, incremented or decremented by button clicks, enabling basic carousel functionality.

**Comment by Gokilp** [comment]
please assign to me

**Comment by sarthak-stranger** [comment]
Hi, can you please assign this issue to me, i have so experience in designing so i will improve the designing of buttons as well as when the button is selected i will show it different.

**Comment by Sathya-reddy1658** [comment]
I CAN MAKE IT LOOKS GREAT BY APPLYING THE KNOWLEDGE I HAVE

**Comment by GarimaSingh0109** [comment]
I can fix this issue & make a good UI for better user experience kindly assign me the issue under #1164 #gssoc'24

**Comment by swapnilsparsh** [comment]
@akash6810 All the best 👍🏻

**Comment by swapnilsparsh** [comment]
@akash6810 Any update on this ?
