### ISSUE TITLE
Title:  Footer layout should be enhanced in terms of layout and and UI

### ISSUE THREAD

**Issue by Ridhima10** [swapnilsparsh/30DaysOfJavaScript#1159]
### Which pre-existing JavaScript project will you be working on?

I will be working on the "30 days of Javascript" website

### Describe your enhancement/improvement

I will fix the layout by giving proper space and move the pagination above the footer section so it will be better in terms of UI and UX.

### Anything you need to say to the Reviewers

It looks so congested and there is no links of sections there.
i will also work on the color palette so it will look more appealing

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot 2024-05-09 214754](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/85826117/41df8e88-a9ac-4e70-a6fd-8666f8a1cf86)
i will make layout somewhat like this so it will be simple yet informative. Since it is more popular these days!

**Comment by AakankshaSarode** [comment]
@Ridhima10  i want to work on this issue please assign me this issue

**Comment by swapnilsparsh** [comment]
@Ridhima10
