### ISSUE TITLE
Title:  Navbar is not proper in the Movie Search APP  and add the smoothness in the web page

### ISSUE THREAD

**Issue by suraj-9849** [swapnilsparsh/30DaysOfJavaScript#1161]
### Describe your enhancement/improvement

I will fix the issue and also make it responsive and also add the smooth scrolling effect by using the Locomotive JS and also include the animation library like the GSAP so can u please assign this to me

**Comment by GarimaSingh0109** [comment]
I am willing to work on this project kindly assign me this task under #gssoc'24

**Comment by swapnilsparsh** [comment]
@suraj-9849 Than you for providing your insight but it is not required as of now.
