### ISSUE TITLE
[GSSOC '24]   - Creating a Expense Splitter using JavaScript

### ISSUE THREAD

**Issue by animex007** [swapnilsparsh/30DaysOfJavaScript#1162]
# EXPENSE SPLITTER
- Building an application that helps groups of people split expenses evenly, such as when dining out or traveling together.
- the application allows users to input expenses incurred during a shared activity and calculates the amount owed by each participant.

## SKILL LEARNED

- JavaScript Fundamentals  >  such as variables, functions, arrays, objects, and control flow.
- DOM Manipulation > learn how to manipulate the (DOM) to  dynamically update content, and handle user input.
- Event Handling >   learn how to handle user events such as clicks, inputs, and form submissions, and respond to them appropriately within the application.

**Comment by EnchantedRepoRuler** [comment]
please assign this issue to me . I want to work on it

**Comment by swapnilsparsh** [comment]
@animex007 Than you for providing your insight but it is not required as of now.
