### ISSUE TITLE
 Issue with Card Click Redirect Functionality

### ISSUE THREAD

**Issue by kumar1397** [swapnilsparsh/30DaysOfJavaScript#1163]
### Is your feature request related to a problem? Please describe.

When users click on a card within the application, it does not redirect them to the desired page as expected. However, I've noticed that the link attached below the card does successfully redirect users to the intended page. This inconsistency in behavior may lead to confusion and frustration among users who expect the card click action to perform the same function as the link provided.

### Describe the solution you'd like.

We can add an event handler to the image tag of the card to redirect the user to the desired page when it clicks on it.

### Describe alternatives you've considered.

As an alternative, we can provide a "click here"  button that will give the user an idea that he/she will be redirected upon clicking the button.

### Add any other context or screenshots about the feature request here.
please assign this issue to me under GSSoC '24 as I want to resolve this issue.
![Screenshot 2024-05-10 071833](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/122858524/7bf81b9f-c12b-464c-bc80-bc9789dbe8fe)

**Comment by EnchantedRepoRuler** [comment]
please assign this issue to me . I want to work on it

**Comment by EnchantedRepoRuler** [comment]
we can create a hover effect with both the button the link and the github in the center and then writing a smmal description of the problem or topics covered in the problem.

**Comment by swapnilsparsh** [comment]
@kumar1397 Than you for providing your insight but it is not required as of now.
