### ISSUE TITLE
Calculator Value Overflow

### ISSUE THREAD

**Issue by root-0101** [swapnilsparsh/30DaysOfJavaScript#1166]
when the input value is larger it didn't fit properly and get overflowed 

![Screenshot (66)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/142779809/a440e900-8327-4545-bda7-268d57cb2257)

**Comment by root-0101** [comment]
Hey @swapnilsparsh assign me this issue

**Comment by hellosamyak** [comment]
Hey assignee please assign this to me.

**Comment by swapnilsparsh** [comment]
@root-0101 All the best 👍🏻

**Comment by shristipandey128** [comment]
Hey @swapnilsparsh please assigned me this issue
