### ISSUE TITLE
Add Minesweeper game

### ISSUE THREAD

**Issue by praveen-p09** [swapnilsparsh/30DaysOfJavaScript#1169]
I want to add a minesweeper game made using HTML, CSS & JS. Can I contribute under GSSoC '24?

**Comment by swapnilsparsh** [comment]
@praveen-p09 All the best 👍🏻

**Comment by hasmithagunda123** [comment]
I want to add this game. Please assign me this issue

**Comment by praveen-p09** [comment]
Please check #1277
