### ISSUE TITLE
Sizing the dark mode icon

### ISSUE THREAD

**Issue by NARAYANAM-SAITEJASWI** [swapnilsparsh/30DaysOfJavaScript#1170]
# It's look to big and the picture in it was not in the center 
screenshot-
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/143615798/89068464-7e0c-4ce4-89cf-22a1be7301d2)

**Comment by NARAYANAM-SAITEJASWI** [comment]
please assign me this issue.

**Comment by sys-atasi** [comment]
please assign me this task

**Comment by AakankshaSarode** [comment]
@NARAYANAM-SAITEJASWI  i want work on this issue please assign me this issue

**Comment by swapnilsparsh** [comment]
@NARAYANAM-SAITEJASWI Than you for providing your insight but it is not required as of now.
