### ISSUE TITLE
spacing between the projects and search bar

### ISSUE THREAD

**Issue by NARAYANAM-SAITEJASWI** [swapnilsparsh/30DaysOfJavaScript#1171]
if we increase space between the search bar  and projects it looks good
and also decrease the space between "30 days of Javascript" and search bar
screenshot-
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/143615798/513d616f-f515-4447-b9a0-7f673327deff)

**Comment by NARAYANAM-SAITEJASWI** [comment]
please assign me this issue

**Comment by hellosamyak** [comment]
can you please assign me this issue?

**Comment by anshsaxena1703** [comment]
I have added space between search bar and projects and made a pr for same.

**Comment by swapnilsparsh** [comment]
@NARAYANAM-SAITEJASWI Than you for providing your insight but it is not required as of now.
