### ISSUE TITLE
Title: Addition and Enhancement of features

### ISSUE THREAD

**Issue by Sparsh865** [swapnilsparsh/30DaysOfJavaScript#1174]
### Which pre-existing JavaScript project will you be working on?

Random Color Generator
Random Password Generator

### Random Color Generator

1. Adding different types of pallette Shades like Analogus Monochromatic etc.
2. Add Color Picker to the project
3. Add download option for the palette in form of css json and png

### Random Password Generator

1. Adding button for famous password conditions like for gmail numbers and symbol required for any other app capital required and many other things

**Comment by swapnilsparsh** [comment]
@Sparsh865 Than you for providing your insight but it is not required as of now.
