### ISSUE TITLE
Title: Improvisation of the ReadMe and Documentation of the Repo

### ISSUE THREAD

**Issue by nishantharkut** [swapnilsparsh/30DaysOfJavaScript#1175]
### Which pre-existing JavaScript project will you be working on?

Whole Repository

### Describe your enhancement/improvement

The readmen and documentation needs to be improved

### Anything you need to say to the Reviewers

The readme will be enhanced so that the users coming to the repo could easily know abou the repo and take the full use of it.

### **Please assign to me under GSSoC'24**

**Comment by swapnilsparsh** [comment]
@nishantharkut Than you for providing your insight but it is not required as of now.
