### ISSUE TITLE
A login/Sign-Up page is required to keep up with the projects done by a visitor

### ISSUE THREAD

**Issue by nishantharkut** [swapnilsparsh/30DaysOfJavaScript#1176]
### Is your feature request related to a problem? Please describe.

The login and sign-up page of a website are crucial elements, serving as the gateway for users to access personalized content, services, and features. These pages not only authenticate users but also collect valuable data for user profiling and personalized experiences, enhancing user engagement, security, and retention.

### Describe the solution you'd like.

A specific login and sign up page for the users

### Describe alternatives you've considered.

User can login as guest and then track the projects they have done

**Comment by Ishika0-0** [comment]
@swapnilsparsh kindly let me work on this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@nishantharkut Than you for providing your insight but it is not required as of now.
