### ISSUE TITLE
Previous button should disable for 1st page 

### ISSUE THREAD

**Issue by upsaurav12** [swapnilsparsh/30DaysOfJavaScript#1177]
### What happened?

In the home page when we are in home-page of the website we can see the button previous button and next button should be disable when we are in 1st and the last page 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116784047/90b82ccb-c87f-4179-a4f1-e9f969ddcc1e)

### How can we reproduce this bug?

1. Go to the website https://30daysofjs.netlify.app/
2. Scroll down and see the pages button 
3. see 

### Urgency (Optional)

Low priority

**Comment by swapnilsparsh** [comment]
@upsaurav12 Than you for providing your insight but it is not required as of now.
