### ISSUE TITLE
Title:  Add Marking Like what we completed and not complete . 

### ISSUE THREAD

**Issue by divyansh2375** [swapnilsparsh/30DaysOfJavaScript#1179]
### Is your feature request related to a problem? Please describe.

I am frustrated with of what i have done and what are remaining to do the task

### Describe the solution you'd like.

I will be adding the toggle tick mark so that once anyone click here he or she can track all over the projects whether they have done this project before or not 

### Describe alternatives you've considered.

Marking page of all the project what we completed and what we not completed

**Comment by swapnilsparsh** [comment]
@divyansh2375 Than you for providing your insight but it is not required as of now.
