### ISSUE TITLE
Title: Improving the UI for Search bar in home-page 

### ISSUE THREAD

**Issue by upsaurav12** [swapnilsparsh/30DaysOfJavaScript#1180]
### Is your feature request related to a problem? Please describe.

Currently the search-containers is good but we can improve it 
1. The border color of the container is not looking good with the black background
2. The outline when the user clicks on the input container 
3. The text much towards the left so we can fix this by shifting towards right 

### Describe the solution you'd like.

Currently this is the search bar in home-page but it is not looking good in term of UI so we can improve it by changing the border color from ``white`` to ``grey`` it will look better
2. We can remove outline of the search bar in search-bar container that will look better
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116784047/bae8bf9a-bc3c-4a96-bedc-17315c239fc7)

**This is how it will look like**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116784047/51c4b3b8-141a-4efd-b66a-2fea1d57781f)

3. Also we can shift the texting in search-input toward right 

### Describe alternatives you've considered.

I will if i can improve by other method but i think this is better approach

**Comment by upsaurav12** [comment]
Hello maintainer pls assign me this issue for Gssoc 2024

**Comment by sarthu210** [comment]
hello sir I am good at UI/UX please can you assign this to me.

**Comment by Varsani2520** [comment]
Hi,please assign this issue me ,i have a good knowledge of designing ,also make a lots of web ,also add label of this issues...

**Comment by swapnilsparsh** [comment]
@upsaurav12 Than you for providing your insight but it is not required as of now.
