### ISSUE TITLE
Number converter from decimal to binary/octal/hexadecimal Format Project

### ISSUE THREAD

**Issue by sukritcharredsoul** [swapnilsparsh/30DaysOfJavaScript#1181]
I wish to make a project which will help in number conversion amongst different types (binary, octal, hexadecimal, decimal )
There was a decimal to binary converter , if it's alright i can also work on that project too.

**Comment by saketh-05** [comment]
I'm reaching out to request the assignment of a project aimed at developing a Number Converter from Decimal to Binary/Octal/Hexadecimal format. This tool will serve to streamline number conversion processes and enhance efficiency in various applications.

**Comment by swapnilsparsh** [comment]
@sukritcharredsoul Than you for providing your insight but it is not required as of now.
