### ISSUE TITLE
Title: Adding A Tetris Javascript game

### ISSUE THREAD

**Issue by SumitKumar-17** [swapnilsparsh/30DaysOfJavaScript#1183]
### Is your feature request related to a problem? Please describe.

I would like to add a Tetris Game made in javascript to this repository

### Describe the solution you'd like.

I have a Tetris Game built in JavaScript which will help to make learn people javascript by following this repository

### Describe alternatives you've considered.

I have features which would teach them controls,constructor,conditional statements etc in javaScript

**Comment by swapnilsparsh** [comment]
@SumitKumar-17 Than you for providing your insight but it is not required as of now.
