### ISSUE TITLE
Title: Updating the Weather App Ui 

### ISSUE THREAD

**Issue by SumitKumar-17** [swapnilsparsh/30DaysOfJavaScript#1184]
### Which pre-existing JavaScript project will you be working on?

The existing Weather App project in the repository serail No-25

### Describe your enhancement/improvement

I would like to update teh UI of the whole page and make it better

### Anything you need to say to the Reviewers

Can I start contributing for it under GSSoc'24? .

**Comment by swapnilsparsh** [comment]
@SumitKumar-17 Than you for providing your insight but it is not required as of now.
