### ISSUE TITLE
Title: Enhance Search Functionality with Voice Command Support

### ISSUE THREAD

**Issue by Prince-kushwaha-2004** [swapnilsparsh/30DaysOfJavaScript#1185]
### Is your feature request related to a problem? Please describe.

The current search functionality on our website **lacks support for voice commands**, limiting user interaction options.

### Describe the solution you'd like.

Integrate a speech recognition API (Web Speech API) to enable **voice input.**
Implement a voice command trigger or **button next to the search bar** to initiate voice search.
Ensure compatibility with popular browsers and devices that support **voice input**

### Describe alternatives you've considered.

_Web Speech API_ is feature of JavaScript to integrate voice input.

### Add any other context or screenshots about the feature request here.

**After integrating this feature Search bar will look similar to this!!**

![Screenshot 2024-01-26 121254](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/149922307/77dc0107-00be-4532-8d17-3f8831b5d4f2)

**Comment by Prince-kushwaha-2004** [comment]
Kindly assign this issue to me under GSSOC"24

**Comment by swapnilsparsh** [comment]
@Prince-kushwaha-2004 Than you for providing your insight but it is not required as of now.
