### ISSUE TITLE
Title: Body Mass Index Calculator

### ISSUE THREAD

**Issue by PrathicaShettyM** [swapnilsparsh/30DaysOfJavaScript#1186]
### Is your feature request related to a problem? Please describe.

The Body mass calculator is used to assess the health of a person using height and weight.

### Describe the solution you'd like.

This will be a beginner friendly project where the user will be able to enter height and weight and will get to his/her BMI. This helps the programmer to learn about DOM manipulation using JS.

### Describe alternatives you've considered.

--

### Add any other context or screenshots about the feature request here.

--

**Comment by swapnilsparsh** [comment]
@PrathicaShettyM Thank you for providing your insight but it is not required as of now.
