### ISSUE TITLE
Title: Simple Login Page 

### ISSUE THREAD

**Issue by PrathicaShettyM** [swapnilsparsh/30DaysOfJavaScript#1187]
### Is your feature request related to a problem? Please describe.

Beginner JS developers always like to work on some building clones of websites, where **login feature** is one the basic and yet important functionality to be implemented. 

### Describe the solution you'd like.

Beginner JS developers will be curious to know the logic behind login functionality and I'll be implementing it in one of the most simplest manner.

### Describe alternatives you've considered.

--

### Add any other context or screenshots about the feature request here.

--

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task for GSSoC 24.

**Comment by swapnilsparsh** [comment]
@PrathicaShettyM Thank you for providing your insight but it is not required as of now.
