### ISSUE TITLE
Mutual Fund Calculator Project

### ISSUE THREAD

**Issue by Manav173** [swapnilsparsh/30DaysOfJavaScript#1188]
### Is your feature request related to a problem? Please describe.

I'm looking to develop a JavaScript project for a mutual fund calculator.

### Describe the solution you'd like.

 The calculator should allow users to input their initial investment amount, annual contribution, expected annual return rate, and investment duration. Upon submission, it should calculate the future value of the investment and display the result to the user.

### Describe alternatives you've considered.

N/A

**Comment by swapnilsparsh** [comment]
@Manav173 Thank you for providing your insight but it is not required as of now.
