### ISSUE TITLE
Random Quote Generator using JS

### ISSUE THREAD

**Issue by Yashpreeth** [swapnilsparsh/30DaysOfJavaScript#1189]
`// Array of quotes
const quotes = [
    "The only way to do great work is to love what you do. Steve Jobs",
    "Innovation distinguishes between a leader and a follower. Steve Jobs",
    "Stay hungry; stay foolish. Steve Jobs",
    "Life is what happens when you're busy making other plans. John Lennon",
    "You miss 100% of the shots you don't take. Wayne Gretzky",
    "The only limit to our realization of tomorrow will be our doubts of today. Franklin D. Roosevelt"
];

function to generate random quote
function generateRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

Example usage
console.log(generateRandomQuote());
`

**Comment by swapnilsparsh** [comment]
Thank you for providing your insight but it is not required as of now.
