### ISSUE TITLE
Title: Online JavaScript code editor

### ISSUE THREAD

**Issue by roysammy123** [swapnilsparsh/30DaysOfJavaScript#1190]
### Is your feature request related to a problem? Please describe.

The goal is to integrate a lightweight JavaScript code editor allowing users to write, edit, and review JavaScript code snippets. The editor should support syntax highlighting, basic code formatting, and essential editing functionalities such as code selection, copy-paste

### Describe the solution you'd like.

I propose adding a JavaScript code editor to the repository, which would enable users to write, edit, and execute JavaScript code directly within the browser. This feature would provide users with a convenient way to experiment with JavaScript code snippets, test functionalities, and learn JavaScript concepts in an interactive environment.

### Describe alternatives you've considered.

NA

#### I will be thankful if you kindly assign me this issue as part of GSSoC'24

**Comment by swapnilsparsh** [comment]
@roysammy123 Than you for providing your insight but it is not required as of now.
