### ISSUE TITLE
A tic-tac-toe game with js

### ISSUE THREAD

**Issue by gargimukherjee25** [swapnilsparsh/30DaysOfJavaScript#1191]
What is your feature request related to a problem? Please describe.
The goal is  to make a proper game with html,css and javascript.

Describe the solution you'd like.
I propose making a responsive tic-tac-toe game with different effects and make it more attractive.

Describe alternatives you've considered.
NA

![Screenshot 2024-05-11 221219](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/165171994/726f37b6-cacc-47ad-9ae0-ce335739443e)
![Screenshot 2024-05-11 221406](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/165171994/52a8c345-3f4f-4297-8185-6b02918eeb30)

I will be thankful if you( @swapnilsparsh  ) kindly assign me this issue as part of GSSoC'24.

**Comment by ShrestyTyagi** [comment]
What is your feature request related to a problem? Please describe.
The goal is to make a proper tic-tac-toe game with javascript.

Describe the solution you would like.
I will make a tic-tac-toe game with the use of javascript with proper user interface where it will tell whose turn is this, who is the winner or whether the game is draw or not , use of reset button.

Screenshot for reference:
![Screenshot (594)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/166687676/5891561b-31f1-49ca-9280-64f78c3d7fec)

I will be highly obliged to you if you could assign this issue to me.

**Comment by swapnilsparsh** [comment]
@gargimukherjee25 Thank you for providing your insight but it is not required as of now.
