### ISSUE TITLE
A to-do-list

### ISSUE THREAD

**Issue by gargimukherjee25** [swapnilsparsh/30DaysOfJavaScript#1192]
What is your feature request related to a problem? Please describe.
The goal is  to make a to-do-list with html, css and javascript.

Describe the solution you'd like.
I propose making a responsive to-do-list that will keep note of our actions to be done.

Describe alternatives you've considered.
NA

I will be thankful if you kindly assign me this issue as part of GSSoC'24

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by swapnilsparsh** [comment]
@gargimukherjee25 Thank you for providing your insight but it is not required as of now.
