### ISSUE TITLE
testimonial display

### ISSUE THREAD

**Issue by Anamika-Ratna** [swapnilsparsh/30DaysOfJavaScript#1193]
### Is your feature request related to a problem? Please describe.

Addition of testimonial box feature

### Describe the solution you'd like.

Just like various games and features, I am willing to add a box for testimonial. 

### Describe alternatives you've considered.

NA

**Comment by swapnilsparsh** [comment]
@Anamika-Ratna Than you for providing your insight but it is not required as of now.
