### ISSUE TITLE
CGPA TO PERCENTAGE CONVERTER

### ISSUE THREAD

**Issue by Damini2004** [swapnilsparsh/30DaysOfJavaScript#1194]
### Which pre-existing JavaScript project will you be working on?

here it help to convert the cgpa to percentage and vice versa. It also contribute in calculating overall SGPA.

### Describe your enhancement/improvement

It calculate the cgpa and sgpa as per the formula of delhi university

**Comment by Monika3002** [comment]
Hello Swapnil,

I hope you are doing well. I am eager to contribute to the project and would appreciate it if you could assign me a task or let me know how I can get started. I am looking forward to collaborating with all of you!

Best regards,
Monika

**Comment by swapnilsparsh** [comment]
@Damini2004 Thank you for providing your insight but it is not required as of now.

**Comment by Damini2004** [comment]
Hello @swapnilsparsh i have more idea like email Subscription form with google sheet Using HTML,CSS,Javascript.
The project generally states that the once the user subscribe to the form this email will get store into google sheet.
Can you assign this issue to me if i raised it ?

**Comment by swapnilsparsh** [comment]
@Damini2004 Thank you for showing your interest but come up with some new and unique idea as these types of projects are already there.
