### ISSUE TITLE
Title: Simple Blog App using JavaScript 

### ISSUE THREAD

**Issue by PrathicaShettyM** [swapnilsparsh/30DaysOfJavaScript#1195]
### Is your feature request related to a problem? Please describe.

Most of the concepts of DOM manipulation can be easily understood with the implementation of a Blog app using JS

### Describe the solution you'd like.

Users will be able to add a title, author name and a blog post

### Describe alternatives you've considered.

--

### Add any other context or screenshots about the feature request here.

--

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by swapnilsparsh** [comment]
@PrathicaShettyM Thank you for providing your insight but it is not required as of now.
