### ISSUE TITLE
Title: Rock Paper Scissor Game using JS

### ISSUE THREAD

**Issue by PrathicaShettyM** [swapnilsparsh/30DaysOfJavaScript#1196]
### Is your feature request related to a problem? Please describe.

I would like to make a fun Rock-Paper-Scissor gaming app for users using JS

### Describe the solution you'd like.

---

### Describe alternatives you've considered.

---

### Add any other context or screenshots about the feature request here.

---

**Comment by AmrutaJayanti** [comment]
@PrathicaShettyM  Can you assign this project to me. I'm interested in working on it.

**Comment by Anshu3301** [comment]
Hello @PrathicaShettyM @swapnilsparsh  , i would like to work on the Rock-Paper-Scissor game, can you assign me this under GSSOC'24?

**Comment by Poushik11** [comment]
hello @PrathicaShettyM @swapnilsparsh , I already build this project of stone paper scissor can you please assign it to me .

**Comment by swapnilsparsh** [comment]
@PrathicaShettyM Thank you for providing your insight but it is not required as of now.
