### ISSUE TITLE
[GSSOC - 2024] - Markdown Previewer

### ISSUE THREAD

**Issue by AmrutaJayanti** [swapnilsparsh/30DaysOfJavaScript#1198]
**MARKDOWN PREVIEWER**
This project tries to convert the given markdown text input to HTML code.

**SKILLS LEARNED**

- About marked.js library (But tried to implement using general code concerning patterns)

**Comment by swapnilsparsh** [comment]
@AmrutaJayanti Than you for providing your insight but it is not required as of now.
