### ISSUE TITLE
Title: Adding Project description to the listed projects

### ISSUE THREAD

**Issue by Rupa-Rd** [swapnilsparsh/30DaysOfJavaScript#1199]
### Is your feature request related to a problem? Please describe.

The website lists many projects, but it's hard to understand what each one does without going to a separate GitHub repos for each project. It's too much work to visit so many sites!

Website : https://30daysofjs.netlify.app/

### Describe the solution you'd like.

Instead of making users visit separate GitHub repos, we can add short descriptions directly to the website. When someone holds their mouse over a project (hovers over it), the project description will appear on top of the slightly faded image. This way, users can learn about each project without needing to jump around to different websites.

### Describe alternatives you've considered.

The alternative approach is to add a `README.md` file for each project describing the project's functionalities.

**Comment by Rupa-Rd** [comment]
I am a GSSoC '24 contributor. I would like to work on this feature. Project admin @swapnilsparsh kindly assign this issue to me!

**Comment by swapnilsparsh** [comment]
@Rupa-Rd All the best 👍🏻

**Comment by Rupa-Rd** [comment]
@swapnilsparsh Sure!, Can you add GSSoC '24 label also?

**Comment by anushkaaa34** [comment]
if this issue is not resolved, I would like to contibute to this. kindly assign me this @swapnilsparsh

**Comment by swapnilsparsh** [comment]
Due to inactiveness assignee is being changed to @anushkaaa34

**Comment by swapnilsparsh** [comment]
@anushkaaa34 All the best 👍🏻

**Comment by Rupa-Rd** [comment]
Since, the number of projects are high its taking much time to update the project description.  @swapnilsparsh , I'm working on this issue.

**Comment by swapnilsparsh** [comment]
> Since, the number of projects are high its taking much time to update the project description. @swapnilsparsh , I'm working on this issue.

Thank you for informing but if its taking time then please tell.

**Comment by Rupa-Rd** [comment]
Sure, thank you @swapnilsparsh

**Comment by I-Manjari** [comment]
Hi @swapnilsparsh , I am a GSSoC '24 contributor. I would like to work on this issue

**Comment by kunwarnaunihalsingh** [comment]
hey @swapnilsparsh , please assign this issue to me since I believe that my skills in HTML, CSS and JS make me an ideal fit to contribute for your project.
