### ISSUE TITLE
[GSSoC'24] [New Game] <Hand Cricket Game>

### ISSUE THREAD

**Issue by CoderUzumaki** [swapnilsparsh/30DaysOfJavaScript#1200]
### Is your feature request related to a problem? Please describe.

Yes, my feature request is related to providing a fun and engaging game option in the 30DaysOfJavaScript repository under **GSSoC 2024**. Currently, there might be some interactive games, and adding **Hand Cricket** would add a count of this by offering users an enjoyable way to take breaks.

### Describe the solution you'd like.

I would like to propose adding the game of Hand Cricket to the 30DaysOfJavaScript repository. Hand Cricket is a simple yet entertaining game that requires minimal resources and can be easily integrated into the existing structure of the repository. Players can compete against the computer making it a versatile addition to the repository's offerings.

### Describe alternatives you've considered.

One alternative could be adding a different game or interactive feature, but I believe Hand Cricket stands out due to its simplicity, popularity, and ease of implementation.

**Comment by swapnilsparsh** [comment]
@CoderUzumaki All the best 👍🏻

**Comment by CoderUzumaki** [comment]
Thanks @swapnilsparsh

**Comment by CoderUzumaki** [comment]
Please add GSSoC'24 label 🙏
