### ISSUE TITLE
Title:  Making clock to World Clock

### ISSUE THREAD

**Issue by VaibhavDhanani** [swapnilsparsh/30DaysOfJavaScript#1201]
### Is your feature request related to a problem? Please describe.

If we have a clock then why we just see time of our country and not other.

### Describe the solution you'd like.

i want to transform existing clock to world clock so we can see time of any country by just selecting that country. Just select any country and you will be able to see the time, i will also add digital clock

### Describe alternatives you've considered.

There might not have any other feature than this.

### Add any other context or screenshots about the feature request here.

![Screenshot from 2024-05-11 09-21-02](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/130571437/4a27f462-77ce-4907-ac32-0c65627c0fd6)

**Comment by VaibhavDhanani** [comment]
Assign this issue to me to improve existing clock.

**Comment by VaibhavDhanani** [comment]
**Assign** this issue to me to improve existing clock.

**Comment by swapnilsparsh** [comment]
@VaibhavDhanani Create a seperate project for this. All the best 👍🏻

**Comment by VaibhavDhanani** [comment]
ok, i have added as 112 - world clock
