### ISSUE TITLE
Title: Adding HOME button

### ISSUE THREAD

**Issue by madhurima316** [swapnilsparsh/30DaysOfJavaScript#1202]
### Is your feature request related to a problem? Please describe.

Some of the games require HOME button , it would ensure smooth and easier user experience.

### Describe the solution you'd like.

There should be a HOME button to the games.

### Describe alternatives you've considered.

I don't have any alternate feature for this.

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by swapnilsparsh** [comment]
@madhurima316 Than you for providing your insight but it is not required as of now.
