### ISSUE TITLE
Title: Currency Converter using JS

### ISSUE THREAD

**Issue by Priyanshu2631** [swapnilsparsh/30DaysOfJavaScript#1203]
### Which pre-existing JavaScript project will you be working on?

I have made a simple currency converter website using HTML,CSS and Javascript which converts currency based on current exchange ratio thus helping the users to see how external links can be imported in code and used

### Describe your enhancement/improvement

--

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by swapnilsparsh** [comment]
@Priyanshu2631 Thank you for providing your insight but it is not required as of now.
