### ISSUE TITLE
Title: Enhancement of the UI of Home page

### ISSUE THREAD

**Issue by madhurima316** [swapnilsparsh/30DaysOfJavaScript#1204]
### Which pre-existing JavaScript project will you be working on?

Home page of the project

### Describe your enhancement/improvement

In HOME page , I want to add distinct hover effect to the Project link and to the Github link , for all the projects . This would ensure better user experience .

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by swapnilsparsh** [comment]
@madhurima316 Than you for providing your insight but it is not required as of now.
