### ISSUE TITLE
Title: HOVER OVER THE DARK MODE AND LIGHT MODE BUTTON

### ISSUE THREAD

**Issue by VShalini01** [swapnilsparsh/30DaysOfJavaScript#1205]
### Which pre-existing JavaScript project will you be working on?

I would like to enhance the feature of Night/Dark mode in  the HOME page.

### Describe your enhancement/improvement

I want to add text and style (hover) to the Night/Dark Mode option in the home page

### Anything you need to say to the Reviewers

Please assign me this issue.

**Comment by VShalini01** [comment]
@swapnilsparsh Please assign me the issue sir.

**Comment by swapnilsparsh** [comment]
@VShalini01 Than you for providing your insight but it is not required as of now.
