### ISSUE TITLE
Title: ADD A FEATURE TO SHOW THE PLAYER'S TURN (X/O) IN TIC-TAC-TOE GAME

### ISSUE THREAD

**Issue by VShalini01** [swapnilsparsh/30DaysOfJavaScript#1206]
### Is your feature request related to a problem? Please describe.

In the tic tac toe game, there is no feature to display which player(X/O) is supposed to play next. I want to add that feature.

### Describe the solution you'd like.

As a part of GSSoC'24 contribution, I want to add the feature to display the player that is supposed to play next in the tic-tac-toe game.

### Describe alternatives you've considered.

I would like to add a feature to display the player that is supposed to play next (X/O)

**Comment by VShalini01** [comment]
@swapnilsparsh Please assign this issue to me sir.

**Comment by ShrestyTyagi** [comment]
Describe:
In the given tic-tac-toe game there is no feature to display whether it's player X's turn or player Y's turn. I will add this feature of whose turn is this with another feature of reset button where the player can reset the game in between.

Screenshot:
![Screenshot 2024-05-11 124824](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/166687676/64c6a0d4-4931-4f9e-a591-5ea6549881ea)

Also in the issue #1191 I have commented to make the tic-tac-toe game. 
I will make sure to add as many features available for tic-tac-toe game with the best UI experience.
I will make sure to do this as soon as possible.
I will be obliged if you could assign this to me. @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@VShalini01 Add this feature to the this project
