### ISSUE TITLE
Real time date update in quiz app 

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1207]
### What happened?

In quiz app the date and time is not real and also time is not updating 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105542579/207da717-fb2e-444e-baa9-9e26bfeab88d)

### How can we reproduce this bug?

1.add function to get real time date and time from system itself
2.run the function each second.

### Urgency (Optional)

Medium priority

**Comment by Pratik2401** [comment]
please assign me these issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Pratik2401 All the best 👍🏻

**Comment by Sujitmaurya123** [comment]
@swapnilsparsh please assign me these issue under GSSOC'24

**Comment by Pratik2401** [comment]
Can you add level label pls to it
