### ISSUE TITLE
Title: Addition of 'Copy to clipboard' button in Random Password Generator

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1208]
### Is your feature request related to a problem? Please describe.

- There is no specific button to copy the generated password to clipboard, and we have to do it manually.

### Describe the solution you'd like.

- I can add a Button which will trigger a JS function to copy the generated password to the user's clipboard.
- I've already worked on many functions like this so i can fix the issue.

### Describe alternatives you've considered.

- Addition of a 'Copy' button to copy password to clipboard.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/108543702/fd5c20de-6b63-4daa-8cf8-784b5334325c)

@swapnilsparsh Can i work on this issue under GSSoC'24, i would love to contribute to this project.

Thank You!

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Thank you for providing your insight but it is not required as of now.
