### ISSUE TITLE
Disable next button if on last page and previous if on first page

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1209]
### What happened?

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105542579/3619f2c3-5ca8-4d4e-ac9d-a27ff87b3d95)
The previous button should be disabled if on page 1 and next if on last page

### How can we reproduce this bug?

1.create function if on last page then  disable next button 
2.create function if on first page then  disable previous button 

### Urgency (Optional)

Low priority

**Comment by aatmajajoshi** [comment]
Please can u assign this issue to me, i have good knowledge of javascript, also i have done several projects before @Pratik2401

**Comment by swapnilsparsh** [comment]
@Pratik2401 All the best 👍🏻

**Comment by Pratik2401** [comment]
Can you add label to these pls
