### ISSUE TITLE
Title: UI improvements in TO-DO List and addition of button to mark TODO as completed

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1210]
### Is your feature request related to a problem? Please describe.

- The buttons to edit and remove 'TODO' aren't centered horizontally inside the TODO's element.
- Additionally, a separate checkbox or a button can be added to mark the TODO/task as completed.

### Describe the solution you'd like.

Addition of a button and fixing the UI changes.

### Describe alternatives you've considered.

UI improvements to make it look more appealing to the users.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/108543702/b9b1c73b-1c3c-47d0-8d1b-150cb81439b6)

@swapnilsparsh Can you please assign this issue to me under GSSoC'24 to work on this. It would be great for me to work on this.

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 All the best 👍🏻
