### ISSUE TITLE
Alignment of the text "Random Password Generator" in the home page

### ISSUE THREAD

**Issue by Brinda-07** [swapnilsparsh/30DaysOfJavaScript#1212]
### What happened?

The alignment of the text "Random Password Generator" in the home page is not correct its attached to the body of the selected box.There should be some space in the left of the text.

Please assign this issue to me

### How can we reproduce this bug?

Go to the home page
Scroll down
Find "Random Password Generator" tab
![Screenshot 2024-05-11 110948](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/154052901/8872ceb1-5361-44a6-bd31-78a33bcd4401)

### Urgency (Optional)

None

**Comment by Brinda-07** [comment]
Respected sir plz add the labels gssoc'24 and level 1 to this issue

**Comment by swapnilsparsh** [comment]
@Brinda-07 Thank you for providing your insight but it is not required as of now.
