### ISSUE TITLE
Title: Workout Tracker

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1213]
### Is your feature request related to a problem? Please describe.

It is always important to track the exercise and number of reps you do while working out to calculate how much calories are burned and which body part is trained

### Describe the solution you'd like.

The project will include number of exercises and how much weight did they picked to do the exercise and how much reps is done by the user and in the end calculate the total weight and which body parts are trained

### Describe alternatives you've considered.

Alternative solutions could include integrating a feature for users to track their rest intervals between sets, incorporating a rest timer within the app, or providing recommendations for workout routines based on users' fitness goals and preferences.

**Comment by Pratik2401** [comment]
Pls assign these to me under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Pratik2401 Thank you for providing your insight but it is not required as of now.
