### ISSUE TITLE
Cryptocurrency Price Tracker addition

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1216]
A cryptocurrency price tracker app which displays the realtime prices of the cryptocurrencies.
Users can also search for other cryptos

Clean and minimal easy to use UI for the Crypto price tracker

Fetching the data from the web

@swapnilsparsh Can you please assign this issue to me under GSSoC'24 to work on this. I would love to work on this addition too.

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Thank you for providing your insight but it is not required as of now.
