### ISSUE TITLE
Title: Improve UI of Multiply Math Game 

### ISSUE THREAD

**Issue by Priyal208** [swapnilsparsh/30DaysOfJavaScript#1218]
### Which pre-existing JavaScript project will you be working on?

The UI looks very plain static and old fashioned

### Describe your enhancement/improvement

I can make it more appealing and catchy kindly assign to me under gssoc '24

**Comment by swapnilsparsh** [comment]
@Priyal208 Thank you for providing your insight but it is not required as of now.
