### ISSUE TITLE
Title: Adding a Logo to the Website & Expanding of Footer Section

### ISSUE THREAD

**Issue by mayank2mahi** [swapnilsparsh/30DaysOfJavaScript#1219]
### Overall development of the website/project.

I want to work on the overall development of the website/project.
Addressing these issues can help improve the overall appearance and usability of your website, potentially leading to a better user experience and increased engagement.

### Descriptions of issues & Solutions

- **Description 1:** The website currently lacks a logo, which can affect its branding and visual appeal. We should add a logo to enhance the overall design.
- **Tasks:** 
      1. Find or design a suitable logo for the website.
      2. Integrate the logo into the website's header or designated logo area.
- **Labels:** Design & Enhancement
------------------------------------------------------------------------------------------------------------

- **Description 2:** The footer section of the website is very short, which might make it look incomplete or unprofessional. We should expand the footer to include more useful information or links.
- **Tasks:** 
      1. Determine the additional content to include in the footer (e.g., contact information, links to social media pages, etc).
      2. Design and implement the expanded footer section.
- **Labels:** Design, Enhancement & Content

### Code of Conduct
- I agree to follow this project's "[Code of Conduct](https://github.com/swapnilsparsh/30DaysOfJavaScript/blob/master/CODE_OF_CONDUCT.md)".

**Comment by mayank2mahi** [comment]
Hi @swapnilsparsh  ,

I hope you're doing well! I'm excited to contribute to the project and would like to work on the issue related to adding a logo and expanding the footer section. 
Could you please assign this issue to me under GSSoC'24 ? I believe this will be a great opportunity to enhance the project's visual appeal and user experience.

Looking forward to your response!

Best regards,
Mayank Singh
@mayank2mahi

**Comment by swapnilsparsh** [comment]
@mayank2mahi Thank you for providing your insight but it is not required as of now.
