### ISSUE TITLE
Title: Adding theme features on Multiply Math game

### ISSUE THREAD

**Issue by RithikaSundaram** [swapnilsparsh/30DaysOfJavaScript#1221]
### Which pre-existing JavaScript project will you be working on?

i had worked on changing the UI design of the project

### Describe your enhancement/improvement

i would like to add the light and dark theme functionality in the UI by having this feature the user will be able to change the theme as per their wish 

### Anything you need to say to the Reviewers

No

**Comment by swapnilsparsh** [comment]
@RithikaSundaram Thank you for providing your insight but it is not required as of now.
