### ISSUE TITLE
ROCK PAPER SCISSOR GAME

### ISSUE THREAD

**Issue by vedanshipathak** [swapnilsparsh/30DaysOfJavaScript#1222]
@swapnilsparsh ,i wanted to add a ROCK PAPER SCISSOR game which will have the following tech stack features:
HTML,CSS and JAVASCRIPT.
Basic logic: Rock kills scissors; paper kills rock & scissor kills paper .User can choose any one of them and the computer will generate a random input against it .
Here are some features of the game :
1) The user will be able to play against the computer reflecting scores of both user and computer .
2)There will also be a reset button that will reset the score back to 0 ,so that the user can start fresh again.
3)Used CSS to give  the game a layout and appearance & JAVASCRIPT for the logic behind the game.

**Comment by Aryan-joh** [comment]
hii @vedanshipathak  please assign this project to me .. as i want to contribute in this project as i am GSSoC24 contributer...??

**Comment by nishthaaggarwal15** [comment]
Hey @vedanshipathak ! Please assign this project to me, I want to contribute in this project as GSSOC'24 contributor.

**Comment by swapnilsparsh** [comment]
@vedanshipathak Thank you for providing your insight but it is not required as of now.
