### ISSUE TITLE
[Bug Title here] snowy particle page not found

### ISSUE THREAD

**Issue by nagamukesh** [swapnilsparsh/30DaysOfJavaScript#1224]
### What happened?

I found out a fact that snowy particle page is not found 
please assign me this issue under gssoc 
I can solve it right away

### How can we reproduce this bug?

I think either the page is not present or the page is not properly routed
If it is not properly router, we can fix it by using correct relative location
if it is not at all present, I can get to know about this task a little bit more and can create one

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@nagamukesh Thank you for providing your insight but it is not required as of now.
