### ISSUE TITLE
Title: Tip Calculator using HTML, CSS and JS

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1227]
### Is your feature request related to a problem? Please describe.

- I would like to add a Tip Calculator in this project, where users can enter the initial amount and the tip will be calculated with the help of percentage inputs from the user.

### Describe the solution you'd like.

- A Tip Calculator app to calculate tips on the amount/bill by percentages or pre-defined values.
- Besides, you can also see your past tips.
- Clean and Minimal easy to use UI

### Describe alternatives you've considered.

Additional user inputs can also be taken for more calculations.

### Add any other context or screenshots about the feature request here.

@swapnilsparsh Can you please assign this to me under GSSoC'24 as I would love to add this in the project.
I've previously submitted a couple of PR's in GSSoC'24.

Thank You!

**Comment by Harshil-kumar-4** [comment]
hey @swapnilsparsh 
I would like to work on this title
before that i would like to have a clear instructions,
things which am i able to do are:
    -calculating the tip according to the total amount and the persentage entered by the user
    -i will try to add an feature to view past calculations / history
    -i assure that the page will definitely gonna look awesom regarding to UI, Color Theory, etc,.
what i understood:
i need to create a new file for tip calculator in your repo by forking it into my acc, 
an user can calculate the tip ammount by giving input [total amount, tip percentage ]
page should looks attractive with come kind of hover animationa etc
waiting for your replay

**Comment by Aryan-joh** [comment]
hii @swapnilsparsh please assign this project to me .. as i want to contribute in this project as i am GSSoC24 contributer

**Comment by Syed0206** [comment]
I would like to work on this issue @swapnilsparsh can you please assign me this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Come up with some unique projects as there are already many projects like this.
