### ISSUE TITLE
Title: Enhancing the CSS to make it more attractive

### ISSUE THREAD

**Issue by Janani-m17** [swapnilsparsh/30DaysOfJavaScript#1229]
### Which pre-existing JavaScript project will you be working on?

I will be working on Random color generator to enhance its CSS to make it more attractive.

### Describe your enhancement/improvement

By enhancing the CSS the overall look of the project will be very attractive and unique.

### Anything you need to say to the Reviewers

Kindly assign me this issue to work on it. I will contribute my level best to make it unique.

**Comment by swapnilsparsh** [comment]
@Janani-m17 Thank you for providing your insight but it is not required as of now.
