### ISSUE TITLE
Title: Adding the feature of Password Strength Analysis 

### ISSUE THREAD

**Issue by Janani-m17** [swapnilsparsh/30DaysOfJavaScript#1231]
### Is your feature request related to a problem? Please describe.

Along with generating a password if a user can check the strength of their password it will be useful to modify it.

### Describe the solution you'd like.

To elaborate the code to analyze the strength of the password.

### Describe alternatives you've considered.

Based of characters of password the strength is analyzed. It can be added as additional features to enhance this project.

**Comment by Shukria-Arghawan** [comment]
Hello, I am Shukria one of the GSSOC'24 contributors. With HTML, CSS and JavaScript I would like to add this features to this project: 
 - The program will first check the strength of the password then show the result to the users according to below criteria:
        - Length
        - Complexity(uppercase  letters, lowercase letters, numbers, symbols)
 - Then The program will suggest some strong passwords.

**Comment by swapnilsparsh** [comment]
@Janani-m17 Thank you for providing your insight but it is not required as of now.
