### ISSUE TITLE
Title: Add more math operations in project math addition to make it more useful.

### ISSUE THREAD

**Issue by Janani-m17** [swapnilsparsh/30DaysOfJavaScript#1233]
### Is your feature request related to a problem? Please describe.

As it is only adding two numbers it is not much efficient so by adding more operations it will be more unique.

### Describe the solution you'd like.

Adding more operations like Calculated percentage, performing multiplication, division, multiplication and many more to add the weightage of the project.

### Describe alternatives you've considered.

More operations like Calculated percentage, performing multiplication, division, multiplication and many more.

**Comment by Jatin-gumber12** [comment]
Please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@Jatin-gumber12 Thank you for providing your insight but it is not required as of now.
