### ISSUE TITLE
Title: Password Strength Generator

### ISSUE THREAD

**Issue by cxde-Sujal** [swapnilsparsh/30DaysOfJavaScript#1236]
### Is your feature request related to a problem? Please describe.

Users choose very weak and common passwords for apps 

### Describe the solution you'd like.

So they need to check whether that password is apt strong or not

### Describe alternatives you've considered.

So this application would be determining you whether your password is weak strong or medium

### Add any other context or screenshots about the feature request here.

![Screenshot (142)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/137087363/28721ddd-2310-4c62-8cb8-228a13aa26d6)

**Comment by Janani-m17** [comment]
I am proficient in html, css, javascript. So I am able to contribute to this issue. Kindly assign this issue to me.

**Comment by sancharigandhi** [comment]
I possess proficiency in HTML, CSS, and JavaScript, and I am interested in enhancing the user experience by implementing a password visibility toggling feature. I kindly request to be assigned to this issue.

**Comment by swapnilsparsh** [comment]
@cxde-Sujal Thank you for providing your insight but it is not required as of now.
