### ISSUE TITLE
Title: Enhancing the design of Dark mode toggle and project search bar

### ISSUE THREAD

**Issue by AnandK-pm** [swapnilsparsh/30DaysOfJavaScript#1237]
### Which pre-existing JavaScript project will you be working on?

Home page.

### Describe your enhancement/improvement

Currently the home page search bar and dark mode toggle switches seems to have not utilized the functionalities of CSS well .
I intend to make the homepage a bit more tidy.
Please assign me this issue so that i can work on making the home page a little more exquisite.
( Requesting as a part of GSSoC '24 )

**Comment by swapnilsparsh** [comment]
@AnandK-pm Thank you for providing your insight but it is not required as of now.
