### ISSUE TITLE
TODO List issues.

### ISSUE THREAD

**Issue by TejaKumar123** [swapnilsparsh/30DaysOfJavaScript#1238]
### Which pre-existing JavaScript project will you be working on?

When we add a new task In the TODO List, the items in task is not aligned perfectly
![Screenshot from 2024-05-11 19-11-42](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/97971538/fb4756b0-c987-4441-8eef-869f9f48e47a)

### Describe your enhancement/improvement

I will align the icons and new task name correctly and make it looks nice

### Anything you need to say to the Reviewers

You can go through this link and add new task.
https://30daysofjs.netlify.app/29%20-%20to%20do%20list/

**Comment by TejaKumar123** [comment]
Please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@TejaKumar123 there is already an issue related to this.
