### ISSUE TITLE
Title: Adding a " mark as done " feature in Todo list JS app

### ISSUE THREAD

**Issue by AnandK-pm** [swapnilsparsh/30DaysOfJavaScript#1239]
### Is your feature request related to a problem? Please describe.

Marking a task as done is an important aspect of any Todo list app.  This feature seems to be missing in the TODO list JS project on your 30daysofJavaScript repo.

### Describe the solution you'd like.

I intend to add a mark as done feature through checkbox and strikethrough. So whenever the user clicks on the checkbox corresponding to a task , the task will be striked indicating the completion of task.

### Describe alternatives you've considered.

An alternate solution will be to remove the task whenever the user indicates the completion of it. But users wont be able to refer to their completed tasks to track their progress. So leverage checkbox and strikethrough is a good option for implementation.

**Comment by swapnilsparsh** [comment]
@AnandK-pm Thank you for providing your insight but it is not required as of now.
