### ISSUE TITLE
Title: UI improvement for the page navigation in homepage

### ISSUE THREAD

**Issue by AnandK-pm** [swapnilsparsh/30DaysOfJavaScript#1240]
### Which pre-existing JavaScript project will you be working on?

Homepage

### Describe your enhancement/improvement

Currently the page navigation in the footer of home page is of primitive HTML+CSS design.
I intend to improve then UI of this part so that it looks a bit more tidy and matches to the overall aesthetic of the homepage.

### Anything you need to say to the Reviewers

Please assign me this issue so that i can work on the UI. I'am confident that i can pull off this issue conforming to the requirements.
(requesting as a part of GSSoC '24 )

**Comment by swapnilsparsh** [comment]
@AnandK-pm Thank you for providing your insight but it is not required as of now.
