### ISSUE TITLE
Title: Any project does not have a back to home button 

### ISSUE THREAD

**Issue by vanisharma2003** [swapnilsparsh/30DaysOfJavaScript#1241]
### Is your feature request related to a problem? Please describe.

Any project does not have a back to home button. If there is this feature user can directly go to home page and will explore all others projects.

### Describe the solution you'd like.

I will add a home button to each and every project so that user can easily redirect to any project. This will not only save user time but also allow user to explore more projects at a time.

### Describe alternatives you've considered.

Home button  should be present at each and every page so that user can easily redirect to any project of their choice.

**Comment by swapnilsparsh** [comment]
@vanisharma2003 All projects open in new tab so there is no need of back button
