### ISSUE TITLE
Title:  Addition of Password Generation Options

### ISSUE THREAD

**Issue by yasharth-0910** [swapnilsparsh/30DaysOfJavaScript#1242]
### Is your feature request related to a problem? Please describe.

The current password generator lacks flexibility in allowing users to specify the types of characters included in the generated password, limiting customization and potentially compromising security.

### Describe the solution you'd like.

I propose adding four options below the password generation area: include lowercase letters, include uppercase letters, include symbols, and include numbers. These options will empower users to customize the composition of their generated passwords according to their preferences and security requirements.

The inclusion of these four options will enhance the usability and security of the password generator. Users will have the flexibility to select or deselect each option based on their specific password requirements. This customization capability will result in stronger and more secure passwords, thereby addressing the limitations of the current password generation process.

### Describe alternatives you've considered.

One alternative could be providing predefined password templates with varying levels of complexity, or integrating third-party password generation libraries. However, these approaches may not fully cater to the diverse needs of users. Another alternative could be incorporating an option for users to specify the length of the generated password, allowing for greater customization and flexibility.

**Comment by yasharth-0910** [comment]
I'd like to take the lead on this task because I believe in my ability to make it even better. So if you can assign this task to me I can start working on the issue.

**Comment by yasharth-0910** [comment]
![my changes](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/143637324/086b60a1-e7c0-4a54-a39d-da8c1b1cf603)

**Comment by yasharth-0910** [comment]
@swapnilsparsh can you please also attach level for GSSoC'24, like level 1,2 or 3. Sorry for tagging.
Regards

**Comment by swapnilsparsh** [comment]
@yasharth-0910 Done
