### ISSUE TITLE
Title: Addition of Toggling feature, Dynamic Strength evaluation & Copy to clipboard button in Random Password Generator

### ISSUE THREAD

**Issue by sancharigandhi** [swapnilsparsh/30DaysOfJavaScript#1243]
### Is your feature request related to a problem? Please describe.

The current Random Password Generator lacks provisions for users to assess the strength of their generated passwords or make modifications if necessary. Additionally, there's a need for improved password visibility management during user interaction.There is no specific button to copy the generated password to clipboard, and we have to do it manually.

### Describe the solution you'd like.

 I will introduce a toggle feature that enables users to manage the visibility of their passwords within the generator interface. By default, passwords should be obscured with dots or asterisks to prevent unauthorized viewing. However, users will have the option to temporarily reveal the password for verification purposes or when making modifications. 
I will implement a feature that allows users to assess the strength of their generated passwords. The outline colour of the box will change green for strong, yellow for medium, red for weak.
I will add a Button which will trigger a JS function to copy the generated password to the user's clipboard.

### Describe alternatives you've considered.

Addition of 'eye image' button for the visibility on and off of the password.
Addition of a 'Copy Password' button to copy password to clipboard.
The outline color of the box will change according to strength, and a message will be show whether it is strong, medium or weak.

**Comment by sancharigandhi** [comment]
Can I work on this issue under GSSoC'24, I would love to contribute to this project.

Thank You!

> ### Is your feature request related to a problem? Please describe.
> The current Random Password Generator lacks provisions for users to assess the strength of their generated passwords or make modifications if necessary. Additionally, there's a need for improved password visibility management during user interaction.There is no specific button to copy the generated password to clipboard, and we have to do it manually.
> 
> ### Describe the solution you'd like.
> I will introduce a toggle feature that enables users to manage the visibility of their passwords within the generator interface. By default, passwords should be obscured with dots or asterisks to prevent unauthorized viewing. However, users will have the option to temporarily reveal the password for verification purposes or when making modifications. I will implement a feature that allows users to assess the strength of their generated passwords. The outline colour of the box will change green for strong, yellow for medium, red for weak. I will add a Button which will trigger a JS function to copy the generated password to the user's clipboard.
> 
> ### Describe alternatives you've considered.
> Addition of 'eye image' button for the visibility on and off of the password. Addition of a 'Copy Password' button to copy password to clipboard. The outline color of the box will change according to strength, and a message will be show whether it is strong, medium or weak.
> 
> ### Add any other context or screenshots about the feature request here.
> _No response_

Can I work on this issue under GSSoC'24, I would love to contribute to this project.

Thank You!

**Comment by swapnilsparsh** [comment]
@sancharigandhi Thank you for providing your insight but it is not required as of now.
