### ISSUE TITLE
Title:  footer

### ISSUE THREAD

**Issue by harsh160311** [swapnilsparsh/30DaysOfJavaScript#1248]
### Which pre-existing JavaScript project will you be working on?

i work on footer for best view 

### Describe your enhancement/improvement

footer is not good 

### Add any other context or relevant screenshots about the enhancement here.

i am a contributer in gssosc 24

**Comment by swapnilsparsh** [comment]
@harsh160311 Thank you for providing your insight but it is not required as of now.
