### ISSUE TITLE
Title: in To Do list > My progress button + complete button

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1249]
### Is your feature request related to a problem? Please describe.

you can add My progress button + complete task button. so user can track it. how many task he/she done yet now. please assign issue to me as contributor to GSSoC 2024.

### Describe the solution you'd like.

add My progress button + complete task button. my progress button store user progress in their local machine using js

### Describe alternatives you've considered.

you can ignore also, but i recomand to add it

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now.
