### ISSUE TITLE
Title: Customized Player Names in Tic Tac Toe

### ISSUE THREAD

**Issue by khavya-798** [swapnilsparsh/30DaysOfJavaScript#1250]
### Which pre-existing JavaScript project will you be working on?

Tic Tac Toe is a two-player game with a grid of nine squares. The goal is to get three in a row. Players take turns, aiming to win or draw.

### Describe your enhancement/improvement

Giving players to input their names in their  own boxes where they can type their names and showing which symbol (like "X" or "O") each player will use makes the game feel more personal and fun. It helps players connect with the game and enjoy it more.

### Anything you need to say to the Reviewers

@swapnilsparsh I would like to add this feature .Could you please assign this task to me.

**Comment by swapnilsparsh** [comment]
@khavya-798 Thank you for providing your insight but it is not required as of now.
