### ISSUE TITLE
Title: Enhance the features of Weather website

### ISSUE THREAD

**Issue by sinhaudita** [swapnilsparsh/30DaysOfJavaScript#1251]
### Which pre-existing JavaScript project will you be working on?

I would like to work on "Weather" which is a pre-existing project. It basically inputs name of the city and provides the temperature of that city at that particular instance.

### Describe your enhancement/improvement

I would like to add on some features like humidity, wind speed, precipitation level and so on to make it more informative for the users. Additionally, I would also like to add a search button so as to make sure that the searching process can be performed by keyboard and mouse both. Kindly assign this issue to me under GSSoC'24.

**Comment by shristipandey128** [comment]
Hey please assign me this issue, @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@sinhaudita All the best 👍🏻

**Comment by sinhaudita** [comment]
@swapnilsparsh can you please label this task under GSSoC'24.
