### ISSUE TITLE
Title: speed button in Whack a Mole Game

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1253]
### Which pre-existing JavaScript project will you be working on?

add speed button to increase or decrease speed of mole

### Describe your enhancement/improvement

add speed button to increase or decrease speed of mole

### Anything you need to say to the Reviewers

what a game!!!

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now.
