### ISSUE TITLE
Adding Guess-The-Country using flag game

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1254]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like.

I would like to add a game Guess the country where a country's flag is displayed and the users have to guess the country based on it. Or from the given options, they've to choose one

### Describe alternatives you've considered.

I didnt found this game on the website and its a fun game too so i thought of adding this.

### Add any other context or screenshots about the feature request here.

@swapnilsparsh Can you please assign this game addition to me under GSSoC'24. Thank you!

**Comment by hasmithagunda123** [comment]
Hey I am GSSOC COntributor Please assign me this issue to work on

**Comment by Amit7212** [comment]
@AtharvKasar04 can you please assign this task to me please? I am a GGSoC contributor.

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 All the best 👍🏻

**Comment by Ayusha-a07** [comment]
@AtharvKasar04 hi, i am gssoc contributor.could you please assign this to me?

**Comment by AtharvKasar04** [comment]
> @AtharvKasar04 All the best 👍🏻

Hey @swapnilsparsh Thank you for assigning. But can i start working on this in just 1-2 days as my End-Sem exams are going on. 
Apologies for the delay.

**Comment by Siddhi561** [comment]
hey, can you assign me this issue? This is my first time in open source contribution and i really want to showcase skills.
