### ISSUE TITLE
Title: Add auto suggestions while typing in search bar

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1256]
### Which pre-existing JavaScript project will you be working on?

on the main page

### Describe your enhancement/improvement

While typing in search bar auto suggestions should be provided

**Comment by Pratik2401** [comment]
plz assign me these issue under GSSOC'24 @swapnilsparsh

**Comment by shristipandey128** [comment]
please assign me this issue, @swapnilsparsh

**Comment by hasmithagunda123** [comment]
please assign me this issue

**Comment by swapnilsparsh** [comment]
@Pratik2401 All the best 👍🏻

**Comment by Pratik2401** [comment]
> @Pratik2401 All the best 👍🏻 and suggestions should come from the existing projects without using any external library.

Yes,I can make that happen

**Comment by Pratik2401** [comment]
okie do you need any changes in UI

**Comment by Pratik2401** [comment]
I have don these just now Can i apply i simple Pr @swapnilsparsh
