### ISSUE TITLE
Title: Add Weather Application Project

### ISSUE THREAD

**Issue by Swapnilden** [swapnilsparsh/30DaysOfJavaScript#1257]
### Is your feature request related to a problem? Please describe.

I would like to contribute a weather application project to this repository. The project is a simple JavaScript application that fetches and displays the current weather information for a given city. It includes basic HTML, CSS, and JavaScript files. 

### Describe the solution you'd like.

I believe this project would be a valuable addition to the repository as it provides a practical example of working with APIs and asynchronous JavaScript.

### Describe alternatives you've considered.

I have tested the project locally and it's ready to be added to the repository. Please add label of gssoc'24 for this issue and assign it to me @swapnilsparsh

**Comment by hasmithagunda123** [comment]
Hey I am GSSOC COntributor Please assign me this issue to work on

**Comment by Debanjannnn** [comment]
please assign me the project I have already coded it in my local system

**Comment by swapnilsparsh** [comment]
@Swapnilden This project is already there.
