### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [swapnilsparsh/30DaysOfJavaScript#1260]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by alishasingh06** [comment]
@swapnilsparsh please assign this issue to me

**Comment by suhanipaliwal** [comment]
Could you please add a label of appropriate level like level 1, 2 or 3 for GSSOC'24 on this issue.

**Comment by MrudulaTeegala** [comment]
@swapnilsparsh kindly assign this issue to me
