### ISSUE TITLE
Add Readme file to the Drum-Kit project 

### ISSUE THREAD

**Issue by AtharvaShinde253** [swapnilsparsh/30DaysOfJavaScript#1261]
Adding a README file to a GitHub project is crucial for providing essential information about the project to potential users and contributors. It  will enhance the project visibility, fosters collaboration, and ensures a smoother onboarding process for newcomers.
Please assign me with this issue.

**Comment by swapnilsparsh** [comment]
@AtharvaShinde253 Thank you for providing your insight but it is not required as of now.
