### ISSUE TITLE
Eraser tool missing in Drawing pad

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1263]
### Is your feature request related to a problem? Please describe.

We have to directly clear the whole pad instead of erasing one by one.

### Describe the solution you'd like.

I would like to add an eraser tool which will enable users to erase any drawing one by one.

@swapnilsparsh Can i please work on this issue under GSSoC'24?
I have already one PR merged in the same repo :)

### Describe alternatives you've considered.

An eraser tool

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/108543702/35cbd830-f39b-42f2-8582-a4100a3388d3)

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 All the best 👍🏻

**Comment by AtharvKasar04** [comment]
> @AtharvKasar04 Any update on this ?

Yess @swapnilsparsh actually My end-sems exams are going on and i replied regarding this in my other issue as well, Apologies for the delay caused but I'll start working on the issues ASAP in just 1-2 days

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Any update on this ?
