### ISSUE TITLE
Voice icon not working in dictionary app

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1264]
### What happened?

When we search a word the voice icon doesnt function by pronouncing the word
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105542579/7d0bb2a1-39ea-47eb-962c-5396875b4679)

### How can we reproduce this bug?

1.search a word
2.press the voice icon

### Urgency (Optional)

Medium priority

**Comment by Pratik2401** [comment]
@swapnilsparsh pls assign me these issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Pratik2401 All the best 👍🏻

**Comment by Pratik2401** [comment]
Can you please add level label to it @swapnilsparsh
