### ISSUE TITLE
Weather app search field should become empty after every search

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1265]
### Is your feature request related to a problem? Please describe.

- We have to manually remove the previous city entered
- Cities input field has spellcheck = true, which results in an unnecessary line under the name making it look incorrect.

### Describe the solution you'd like.

I would like to make the search field become empty after every search.
Will make spellcheck = false for the input field.

### Describe alternatives you've considered.

n/a

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/108543702/498852c4-23ed-4364-a148-f0ea5622aebc)

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Thank you for providing your insight but it is not required as of now.
