### ISSUE TITLE
Title: Points counter in Rock paper scissor 

### ISSUE THREAD

**Issue by Pratik2401** [swapnilsparsh/30DaysOfJavaScript#1267]
### Which pre-existing JavaScript project will you be working on?

Rock Paper Scissors

### Describe your enhancement/improvement

Add points table of user and computer becauseit is a game which can be played again and again

**Comment by Pratik2401** [comment]
pls assign these issue to me under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Pratik2401 Thank you for providing your insight but it is not required as of now.
