### ISSUE TITLE
Add Astronomy Picture of the Day using NASA API [NEW_PROJECT]

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1268]
### Is your feature request related to a problem? Please describe.

n/a

### Describe the solution you'd like.

I would like to add a new project which displays the latest today's Astronomy Picture of the Day which will fetch that image using NASA API.

### Describe alternatives you've considered.

n/a

### Add any other context or screenshots about the feature request here.

@swapnilsparsh Can i please work on this issue under GSSoC'24? 
Thank You!

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 Thank you for providing your insight but it is not required as of now. There are already many project using API. So come up with some new ideas.
