### ISSUE TITLE
Get In: Password Manager 

### ISSUE THREAD

**Issue by Ayushhurkat22** [swapnilsparsh/30DaysOfJavaScript#1270]
https://github.com/Ayushhurkat22/GET-IN-Password-Manager

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
