### ISSUE TITLE
Visit Counter not updating

### ISSUE THREAD

**Issue by AtharvKasar04** [swapnilsparsh/30DaysOfJavaScript#1271]
### What happened?

The visit counter stays at `0` all the time even after refreshing the web page.

### How can we reproduce this bug?

- Visit the Visit Counter project
- Look at the counter
- Does not update

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/108543702/b25e287c-c3a0-4eec-b11f-644c502ca44c)

@swapnilsparsh Can i please work on this issue under GSSoC'24?
Thank You!

### Urgency (Optional)

None

**Comment by swapnilsparsh** [comment]
@AtharvKasar04 All the best 👍🏻

**Comment by KapsG23** [comment]
Hello @swapnilsparsh , If there is no updation on this project then please assign the project to me. This is my first time to contribute in an open source project and guide me through it.

Maybe I have found the problem that is causing the visit counter to not work.
I want to some ideas that can make the program better. So please do consider the request.

**Comment by swapnilsparsh** [comment]
@KapsG23 Sorry to say but @AtharvKasar04 will be working on it in 2-3 days as he is having exams right now.

**Comment by KapsG23** [comment]
Thank you for letting me know!!

**Comment by KapsG23** [comment]
@swapnilsparsh , Actually I want to know about how should I find the perfect problem statement for myself which I could really solve and work on it. In all the projects of 30 days of JavaScript , already someone is assigned but I really want to work for the problem because I think it's doable. 
So can you please guide me through  it.

**Comment by amanjaiswal7236** [comment]
Hey @swapnilsparsh  can i work on this issue??

**Comment by swapnilsparsh** [comment]
@amanjaiswal7236 There is already an issue open related to this.
