### ISSUE TITLE
Title: Addition of a Drum Kit game

### ISSUE THREAD

**Issue by yasharth-0910** [swapnilsparsh/30DaysOfJavaScript#1272]
### Is your feature request related to a problem? Please describe.

I've recently developed a game called "Drum Set" and I'd like to integrate it into my website. The game allows users to play drum sounds by clicking on buttons or pressing corresponding keys on their keyboard.

### Describe the solution you'd like.

Integrate the game into the website's HTML structure, ensuring it's visually appealing and functional.
Add buttons or keyboard controls for users to interact with the drums.
Enhance the game's UI/UX with graphics, animations, or effects.
Ensure mobile compatibility and accessibility.

### Describe alternatives you've considered.

Adding a canvas element for more complex interactions.
Implementing a multiplayer mode for collaborative drumming.
Integrating social sharing features to allow users to share their drumming sessions.
Including a recording feature to save and replay users' drum performances.

### Add any other context or screenshots about the feature request here.

![113 - Drum Kit](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/143637324/5c533b31-a87f-419b-a4d4-544ed38baffe)

**Comment by yasharth-0910** [comment]
I would request you too please assign this to me under GSSoC'24 tag

**Comment by swapnilsparsh** [comment]
@yasharth-0910 This project is already there.
