### ISSUE TITLE
Footer of the website needs to be improved

### ISSUE THREAD

**Issue by Sneha123-zudo** [swapnilsparsh/30DaysOfJavaScript#1274]
### Which pre-existing JavaScript project will you be working on?

In the main page

### Describe your enhancement/improvement

In the main page of the website the footer is not looking good.
I want to improved the footer of the website.

### Add any other context or relevant screenshots about the enhancement here.

Please assign me this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Sneha123-zudo Thank you for providing your insight but it is not required as of now.
