### ISSUE TITLE
Title: Pet Adoption Site

### ISSUE THREAD

**Issue by cxde-Sujal** [swapnilsparsh/30DaysOfJavaScript#1275]
### Is your feature request related to a problem? Please describe.

For the adoption of pets that are abondoned due to miscellaneous reasons

### Describe the solution you'd like.

Will create a page about different types of pets from different locations to be adopted based on users needs

### Describe alternatives you've considered.

It will be an intuitive page with each and every details about the pets , so that users can adopt it

**Comment by cxde-Sujal** [comment]
Can You assign it to me under GSSoC'24 label will complete this project

**Comment by swapnilsparsh** [comment]
@cxde-Sujal Thank you for providing your insight but it is not required as of now.
