### ISSUE TITLE
Title: Add features in Sorting Visualizer

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1276]
### Which pre-existing JavaScript project will you be working on?

Sorting Visualizer

### Describe your enhancement/improvement

The current Sorting Visualizer seems pretty basic. I want to add give more control to the user. I want to add features like control array size, speed of sorting and option to choose from various sorting algorithms.

### Anything you need to say to the Reviewers

hlo @swapnilsparsh , please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 All the best 👍🏻. You can add new sorting algorithms also.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Any update on this ?

**Comment by anushkaaa34** [comment]
if this issue is not resolved, I would like to work on it.please assign it to me

**Comment by jinx-vi-0** [comment]
> @jinx-vi-0 Any update on this ?

will submit pr by tonight.

**Comment by jinx-vi-0** [comment]
Hey @swapnilsparsh , I've submitted a PR. Could you please take a look and provide any feedback you have? Thanks!

**Comment by Siddhi561** [comment]
hey, can youe assign me this issue if the issue still not solved?

**Comment by jinx-vi-0** [comment]
> hey, can youe assign me this issue if the issue still not solved?

pr had been already created yesterday.

**Comment by jinx-vi-0** [comment]
Hey @swapnilsparsh , I've submitted a PR. Could you please take a look and provide any feedback you have? Thanks!
