### ISSUE TITLE
Footer overlaps the game

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1278]
### What happened?

The footer alignment in the memory matching game overlaps the game box. I'm attaching the screenshot below.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/120160355/c1d013c7-104d-40b4-a750-56acdba23dc7)

### How can we reproduce this bug?

We need to either align the box upward or need to push footer below the box.

### Urgency (Optional)

None

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh , please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 In my system it is working fine. Specify the screen size at which you are checking

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/7c97c33e-449c-43ff-9b05-6b9a6cd966b1)
