### ISSUE TITLE
Title: Add features in Music Player

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1279]
### Is your feature request related to a problem? Please describe.

I like to add more features to give more control to users, so that they can play random track, slide song to play from particular section, etc.

### Describe the solution you'd like.

Add features:
- Slider for song time
- button to repeat track
- button to select random track

### Describe alternatives you've considered.

Slider for song track
Repeat song functionality
Random play functionality

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh , please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Add this only: Slider for song track
All the best 👍🏻

**Comment by jinx-vi-0** [comment]
Hey @swapnilsparsh, I've submitted a PR. Could you please take a look and provide any feedback you have? Thanks!
