### ISSUE TITLE
Add some interaction to Traffic Light Project

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#128]

**Comment by Shady2320** [comment]
Can you explain me a little bit?

**Comment by Shady2320** [comment]
Can you explain what interaction is need to be added?

**Comment by swapnilsparsh** [comment]
> Can you explain what interaction is need to be added?

Anything which you can 🙂

**Comment by Vartika511** [comment]
Hello, Myself a contributor from **GSSOC-22**. I would like to work on this issue. I have an idea of making it more interactive using JavaScript. Please assign me this issue.

**Comment by shouryap1** [comment]
Hello, I am a contributor from GSSoC'22. I think I can make traffic lighter more interactive using JavaScript. Can you assign me the issue?
Thank you

**Comment by swapnilsparsh** [comment]
@Vartika511 Any Updates?

**Comment by Vartika511** [comment]
yes almost work is done but as my contribution is of GSSOC 22 of I thought I should send pull request after 2nd rgt?

**Comment by flow6979** [comment]
hey, gssoc contributor this side. can u please assign this issue to me?
Thank you.

**Comment by swapnilsparsh** [comment]
> yes almost work is done but as my contribution is of GSSOC 22 of I thought I should send pull request after 2nd rgt?

Update?

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by Tiya0310** [comment]
Can I work on this issue?
