### ISSUE TITLE
Title: To Do List UI Enhancement

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1280]
### Which pre-existing JavaScript project will you be working on?

To Do List

### Describe your enhancement/improvement

I like to improve the UI of the existing To Do List. I have already added a sample screenshot.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/120160355/7f94521c-6bf1-4472-a19b-04c24c1ed81c)

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh , please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Thank you for providing your insight but it is not required as of now.
