### ISSUE TITLE
New Project : BMI Calculator

### ISSUE THREAD

**Issue by sakshii00** [swapnilsparsh/30DaysOfJavaScript#1281]
I want to add my project here which is BMI calculator. 
It calculates BMI of a person and tells what category they are in.

Please assign me this under GSSOC'24

**Comment by sakshii00** [comment]
Please add label gssoc24 and assign me this issue

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by swapnilsparsh** [comment]
@sakshii00 Thank you for providing your insight but it is not required as of now.

**Comment by sakshii00** [comment]
I added this project because in issue #4 you mentioned that anyone can add their JS projects..
