### ISSUE TITLE
Title:  Add a Navbar to the website

### ISSUE THREAD

**Issue by Sapta-Dev27** [swapnilsparsh/30DaysOfJavaScript#1282]
### Is your feature request related to a problem? Please describe.

Adding a Navbar would help the users to facilate the use of the projects

### Describe the solution you'd like.

Navbar using HTML CSS

### Describe alternatives you've considered.

no alternatives

**Comment by swapnilsparsh** [comment]
@Sapta-Dev27 Thank you for providing your insight but it is not required as of now.
