### ISSUE TITLE
Snake Game Title overlaps

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1283]
### What happened?

The game overlaps the instruction of the game. I have added a screenshot where it can be clearly seen that the game is blocking the view.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/120160355/6e2a9332-6ba4-42a7-8511-a9f391a7272d)

### How can we reproduce this bug?

The instructions need to be above the game and none of them should overlaps each other.

### Urgency (Optional)

None

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh  , please assign this issue to me.

**Comment by aditig80** [comment]
hey @swapnilsparsh , kindly assign this issue to me!

**Comment by AnanyaChauhan17** [comment]
Hi @swapnilsparsh I trust this message finds you well . As a GSSoC contributor I am writing to express my interest in assisting with the resolution of the project issue you mentioned . 
Kindly assisgn this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Provide the screen size also at which you are checking

**Comment by jinx-vi-0** [comment]
> @jinx-vi-0 Provide the screen size also at which you are checking

Its 14 inch

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Thank you for providing your insight but it is not required as of now.
