### ISSUE TITLE
Title:  A page dedicated towards js basics

### ISSUE THREAD

**Issue by MetiUmashri** [swapnilsparsh/30DaysOfJavaScript#1284]
### Is your feature request related to a problem? Please describe.

This particular page will contain the tips and tricks to conquer js, which will help to revise 

### Describe the solution you'd like.

At the beginning of the page introduce Basics link wherein onclicking it, will redirect to tips and tricks of JS. I hope this shall enhance the page. Please assign this to me

### Describe alternatives you've considered.

By adding this will definitely enhance the quality if the website.

### Add any other context or screenshots about the feature request here.

Kindly assign this issue to me

**Comment by swapnilsparsh** [comment]
@MetiUmashri Thank you for providing your insight but it is not required as of now.
