### ISSUE TITLE
Title: Enhance HangMan UI

### ISSUE THREAD

**Issue by jinx-vi-0** [swapnilsparsh/30DaysOfJavaScript#1287]
### Which pre-existing JavaScript project will you be working on?

HangMan Game

### Describe your enhancement/improvement

I like to improve the UI of HangMan game making it more visually appears which improves the user experience. I have added a sample screenshot.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/120160355/8c3b9045-c572-4fb3-9720-a24e78d457da)

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh , please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 Also make it responsive for mobile and tablet screens. All the best 👍🏻

**Comment by jinx-vi-0** [comment]
hey @swapnilsparsh, there are some differences between the current hangman game and the one I'm proposing. The current one just shows the word to guess, while the one I'm proposing includes hints. Should I add mine as a new version or replace the existing one with mine?

**Comment by swapnilsparsh** [comment]
@jinx-vi-0 You can add a new version of yours but remove the older hangman game and its related files. Also check your UI to be consistent on all screens.

**Comment by jinx-vi-0** [comment]
Hey @swapnilsparsh , I've submitted a PR. Could you please take a look and provide any feedback you have? Thanks!
