### ISSUE TITLE
Title: Flappy bird project addition

### ISSUE THREAD

**Issue by Ankitapanda25** [swapnilsparsh/30DaysOfJavaScript#1288]
### Is your feature request related to a problem? Please describe.

I believe flappy bird is one of the project done while learning javascript. This one would be a major addition

### Describe the solution you'd like.

I have actually built a flappy bird project during my initial days of learning javascript. It would be a major help contributing to this project.

@swapnilsparsh Please assign me this so that I can work on this under GSSOC'24 with appropriate label

### Describe alternatives you've considered.

A high score in the flappy bird would be a good feature.

**Comment by siddub306** [comment]
**Issue:** Flappy Bird project addition

**Description:**

It is one of the basic projects that a newcomer/beginner works upon to clear their doubts and understand the working of JS easily.

**Request:**

Kindly assign me this project @swapnilsparsh under GSSOC'24 with an appropriate label as I have worked upon this project and would like to contribute for same.

**Enhancements:**

To add some powerups that can make the game tricky and fun-playing.

**Screenshot about the feature request:**

**Comment by swapnilsparsh** [comment]
@Ankitapanda25 Thank you for providing your insight but it is not required as of now.
