### ISSUE TITLE
Title: Improvement in start button of Countdown timer project.

### ISSUE THREAD

**Issue by aditig80** [swapnilsparsh/30DaysOfJavaScript#1292]
### Which pre-existing JavaScript project will you be working on?

Countdown Timer

### Describe your enhancement/improvement

The start button is not placed correctly in right position. I would like to fix that issue.
I also like to improve the UI of Countdown Timer project making it more visually appears which improves the user experience.
@swapnilsparsh Please assign me this so that I can work on this under GSSOC'24 with appropriate label.

**Comment by swapnilsparsh** [comment]
@aditig80 Thank you for providing your insight but it is not required as of now.
