### ISSUE TITLE
Title: Improving the UI of the Music player

### ISSUE THREAD

**Issue by Abhishek-465** [swapnilsparsh/30DaysOfJavaScript#1294]
### Which pre-existing JavaScript project will you be working on?

Music Player

### Describe your enhancement/improvement

I want to improve the existing UI of the music player to make it more appealing.

### Add any other context or relevant screenshots about the enhancement here.

Screenshot of the existing Music player:
![Screenshot (50)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127030695/e54cb09d-2f4a-42e7-8629-f5a103bdcdb4)

**Comment by swapnilsparsh** [comment]
@Abhishek-465 Thank you for providing your insight but it is not required as of now.
