### ISSUE TITLE
TicTacToe game using 

### ISSUE THREAD

**Issue by Sunainabhave** [swapnilsparsh/30DaysOfJavaScript#1296]
Hello @swapnilsparsh, i would like to add Tic Tac Toe game using java script to this repository. Please assign me this task under GSSOC'24.
Thank you!

**Comment by Tarungupta18** [comment]
Hello, @swapnilsparsh, I have to work on this repo (Tic Tac Toe). please assign me this task.

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!

**Comment by swapnilsparsh** [comment]
@Sunainabhave Thank you for providing your insight but it is not required as of now.
