### ISSUE TITLE
Title: NEW GAME: Color Match Challenge

### ISSUE THREAD

**Issue by Bindusree1515** [swapnilsparsh/30DaysOfJavaScript#1298]
### Is your feature request related to a problem? Please describe.

**Game Description:** Match the displayed color by selecting the corresponding color from a palette within a limited time.
Please assign this issue under GSSOC'24

### Describe the solution you'd like.

**HTML:** Create the game layout and structure.
**CSS:** Style the elements, including color palettes and timer.
**JavaScript:** Implement game logic, color generation, timer functionality, and score tracking.

### Describe alternatives you've considered.

**Gameplay:**
When the game starts, display the target color.
Start a countdown timer (e.g., 30 seconds).
Allow the player to click on the color button that matches the displayed target color.
If the correct color button is clicked within the time limit, increase the score.
If the wrong color button is clicked or time runs out, end the game.

### Add any other context or screenshots about the feature request here.

The game will look like this : 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/91887086/cb96c02a-0ec4-4e06-b5ee-aa242484bf09)

**Comment by swapnilsparsh** [comment]
@Bindusree1515 This game is already there.
