### ISSUE TITLE
Title:  Adding Guess The Number Game

### ISSUE THREAD

**Issue by Rehan52004** [swapnilsparsh/30DaysOfJavaScript#1299]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

I already made it in my learning and i want to add

### Describe alternatives you've considered.

No

### Add any other context or screenshots about the feature request here.

I want to add Guess the number game in the website.

**Comment by swapnilsparsh** [comment]
@Rehan52004 Thank you for providing your insight but it is not required as of now.
