### ISSUE TITLE
Title: New Project: Meme Generator

### ISSUE THREAD

**Issue by shrutikajha2603** [swapnilsparsh/30DaysOfJavaScript#1300]
### Is your feature request related to a problem? Please describe.

Project Description: The website will showcase some funny memes fetched from an api.
Please assign this issue to me under GSSOC'24!

### Describe the solution you'd like.

HTML: For creating basic structure of the project.
CSS: For adding styling effects to make the UI attractive.
Javascript: Fetches memes from API and displays it on the page.

### Describe alternatives you've considered.

User experience can be enhanced by adding rating system, allowing users to upload their own memes and integrating social media sharing options.
Also some other color themes can be used to make the website more appealing and attractive.

### Add any other context or screenshots about the feature request here.

Preview: The site would look something like this
![Screenshot 2024-05-12 235049](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116791993/070adb16-bb38-40aa-bafb-17317a924889)

**Comment by swapnilsparsh** [comment]
@shrutikajha2603 Thank you for providing your insight but it is not required as of now.
