### ISSUE TITLE
New Project: Language Translator using Javascript

### ISSUE THREAD

**Issue by PradnyaGaitonde** [swapnilsparsh/30DaysOfJavaScript#1301]
I am reaching out to propose the addition of a JavaScript project language translator to your GitHub repository. This open-source project aims to provide a simple yet effective tool for translating text between different languages. The translator will be developed using JavaScript, making it easy to integrate into web applications. I believe this project can be a valuable addition to your repository and would appreciate it if you could assign it to me.

**Comment by PradnyaGaitonde** [comment]
Also, can you please assign it to me under GSSoc'24 tag

**Comment by swapnilsparsh** [comment]
@PradnyaGaitonde Thank you for providing your insight but it is not required as of now.
