### ISSUE TITLE
Title: add sort button

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1303]
### Which pre-existing JavaScript project will you be working on?

30 days of javascript

### Describe your enhancement/improvement

add sort button like most played , most liked ...in DB behind we can keep track of no of users after every game played .
 assign issue to me as GSSoC 2024 contributor.

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now.
