### ISSUE TITLE
Title: add income-expense tracker system

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1304]
### Which pre-existing JavaScript project will you be working on?

30 days of javascript

### Describe your enhancement/improvement

add income-expense tracker system.
![Screenshot 2024-05-13 072421](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/cd0f5615-fe63-49e1-b991-587f6514a196)

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now.
