### ISSUE TITLE
Bug in tetris game

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1305]
### What happened?

after game over user can move tetris at top it use down arrow and rotate button.

### How can we reproduce this bug?

after game over we ask user to l**eave game** or **restart game**

### Desktop Information (Optional)

![Screenshot 2024-05-13 073046](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/c2e9a74a-b2a3-4a80-9865-fd8af25eea0a)

### Urgency (Optional)

High priority

**Comment by Tarungupta18** [comment]
assign me this bug

**Comment by Vipullakum007** [comment]
assign me this bug as contributer GSSoC 2024 please

**Comment by swapnilsparsh** [comment]
@Vipullakum007 All the best 👍🏻

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Any update on this ?

**Comment by Siddhi561** [comment]
hey, can youe assign me this issue?

**Comment by KavyaBS123** [comment]
Hey @swapnilsparsh I am GSSOC contributor can you please assign this issue to me, I would like to work on it !

**Comment by satyendushukla** [comment]
hey @swapnilsparsh ,I am GSSOC contributor can you please assign it to me ,,i believe that i can fix it in very less time ,,i will do my best.

**Comment by Vipullakum007** [comment]
no sorry i don't have laptop till 2 days . please re-assign to me
