### ISSUE TITLE
I want to add new feature todo app

### ISSUE THREAD

**Issue by Abhishek0732** [swapnilsparsh/30DaysOfJavaScript#1306]
### Is your feature request related to a problem? Please describe.

No I want to add todo app

### Describe the solution you'd like.

In this todo app anyone can add their day to day schedule which he wants to do

### Describe alternatives you've considered.

In this todo app the task created can also be modified and deleted

**Comment by Dhiya-Natarajan** [comment]
Hey there! 
I'm super excited to jump in and add an awesome feature to-do app! Plus, it is also my very first repository, so you can bet I'm pumped to get started. Could you please assign this thrilling issue to me?  And can you please assign this issue to me under GSSOC'24. Let's make some magic happen!"

**Comment by AnanyaChauhan17** [comment]
Hi 
I hope this message reaches you in good spirits. I'm reaching out to convey my eagerness to contribute to your ToDo app by suggesting a new feature. Having recently completed my own project on a ToDo app, I'm filled with enthusiasm to lend a hand. I kindly request you to consider assigning this task to me.

Looking forward to the opportunity to collaborate!

**Comment by swapnilsparsh** [comment]
@Abhishek0732 Thank you for providing your insight but it is not required as of now.
