### ISSUE TITLE
Displaced link image of memory matching game in mobile screen 

### ISSUE THREAD

**Issue by vishnuvardhanreddy31** [swapnilsparsh/30DaysOfJavaScript#1311]
![Screenshot_20240513_143900](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104411008/d0ad2619-b715-493a-b99a-d5520227a7bd)

Assign me with this issue under GSSOC'2024

**Comment by vishnuvardhanreddy31** [comment]
Thanks for Assigning it to me I will work on it.

**Comment by swapnilsparsh** [comment]
@vishnuvardhanreddy31 Any update on this ?

**Comment by vishnuvardhanreddy31** [comment]
It's not a Bug its the issue with the length of the project name so if i can change entire css i can fix it, but this will change the styling of the other projects too.

**Comment by swapnilsparsh** [comment]
> It's not a Bug its the issue with the length of the project name so if i can change entire css i can fix it, but this will change the styling of the other projects too.

Change the entire CSS but check it should not affect others

**Comment by vishnuvardhanreddy31** [comment]
@swapnilsparsh  I have made changes and raised a pull request, can you please check.
