### ISSUE TITLE
Title: Create Number Plate Generator

### ISSUE THREAD

**Issue by dhruv8433** [swapnilsparsh/30DaysOfJavaScript#1312]
@swapnilsparsh 
### Is your feature request related to a problem? Please describe.

If user want new number-plate for their vehical they can come this site and generate random number plate for  their vehical.

### Describe the solution you'd like.

we can create a new component for that which provide new number plate everytime when we reload the website

### Describe alternatives you've considered.

we can give "random 4 no with character based number plate"

### Add any other context or screenshots about the feature request here.

something like 

XX10 - XX -   2024

**Comment by swapnilsparsh** [comment]
@dhruv8433 Thank you for providing your insight but it is not required as of now.
