### ISSUE TITLE
Title: Create Loading Effect

### ISSUE THREAD

**Issue by dhruv8433** [swapnilsparsh/30DaysOfJavaScript#1313]
### Is your feature request related to a problem? Please describe.

@swapnilsparsh 
we can create new designed loading spinner effects

### Describe the solution you'd like.

we can use library to build that

### Describe alternatives you've considered.

we can build spinner loading effect using css

### Add any other context or screenshots about the feature request here.

something like this

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114583978/f787d86f-9202-408f-aa73-136727eaf5c7)

**Comment by vanirastogi** [comment]
hi can you assign this issue to me under GSSoC'24

**Comment by swapnilsparsh** [comment]
@dhruv8433 Thank you for providing your insight but it is not required as of now.
