### ISSUE TITLE
Title: We can add swiper based picture gallery

### ISSUE THREAD

**Issue by dhruv8433** [swapnilsparsh/30DaysOfJavaScript#1314]
### Is your feature request related to a problem? Please describe.

@swapnilsparsh 
When user swipe the card next image display

### Describe the solution you'd like.

we can use swiper.js for build various kind of image gallery

### Describe alternatives you've considered.

or we can create it custom image library using css and js

### Add any other context or screenshots about the feature request here.

something like this
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114583978/6b106b6a-7f7b-428e-9fbb-a0d0be507442)

**Comment by swapnilsparsh** [comment]
@dhruv8433 Thank you for providing your insight but it is not required as of now.
