### ISSUE TITLE
Footer of website can be improved

### ISSUE THREAD

**Issue by yashwagh30** [swapnilsparsh/30DaysOfJavaScript#1315]
### Is your feature request related to a problem? Please describe.

I hope this message finds you well. I'm writing to discuss some potential improvements to the styling of the footer on your website. As a part of the ongoing #30DaysOfJavaScript challenge, I've taken a closer look at the footer and have some suggestions to enhance its appearance and functionality.

### Describe the solution you'd like.

Ensure that the elements are aligned properly to maintain a neat and organized appearance.Evaluate the color scheme used in the footer and its consistency with the rest of the website. Harmonizing the colors can create a cohesive look and reinforce brand identity. Consider using accent colors or subtle gradients to add visual interest without overwhelming the design. Ensure that the footer includes accurate copyright information to protect your intellectual property rights. This typically includes the copyright symbol, the year, and the name of the website or company.

### Describe alternatives you've considered.

Alternate way is to just style the footer only using css.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-13 160459](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/120586606/16c355e9-03d8-4c34-8e4c-1e6212501397)

**Comment by SantoshiVerma** [comment]
hey @swapnilsparsh ,I would like to work on this issue under gsssoc2024.please assign this me.

**Comment by tanya-54** [comment]
hey @swapnilsparsh ,I would like to improve my skills on this issue under gsssoc2024.
please assign this me.
waiting for your response .
thankYou

**Comment by swapnilsparsh** [comment]
@yashwagh30 Thank you for providing your insight but it is not required as of now.
