### ISSUE TITLE
Title: styling of the wesite

### ISSUE THREAD

**Issue by Mitali-Pandey** [swapnilsparsh/30DaysOfJavaScript#1318]
### Which pre-existing JavaScript project will you be working on?

Hi, @swapnilsparsh I'd suggest that the styling of the website should be improved. It should be classy and eye catchy, that would enhance the interest of the user .

### Describe your enhancement/improvement

It should be classy and eye catchy, that would increase the user interest to use it.

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by swapnilsparsh** [comment]
@Mitali-Pandey Thank you for providing your insight but it is not required as of now.
