### ISSUE TITLE
Title: Addition of a button in the projects cards .

### ISSUE THREAD

**Issue by Riya922003** [swapnilsparsh/30DaysOfJavaScript#1319]
### Is your feature request related to a problem? Please describe.

There are many games in website that need a proper "how to play" part for the users that dont know about the game and also who are no willing to see the github readme that is attached

### Describe the solution you'd like.

There can be a button that can be clicked to see the "how to play" or any specific guidelince for the project.

### Describe alternatives you've considered.

Also if a button is a rigorus procedure there could be a page dedicated to this where user can search and find about the projects.

### Add any other context or screenshots about the feature request here.

I would like to adderess the issue .

**Comment by swapnilsparsh** [comment]
@Riya922003 Thank you for providing your insight but it is not required as of now.
