### ISSUE TITLE
Title: Improving the website look in background.

### ISSUE THREAD

**Issue by MUKUL-RAJPUT2004** [swapnilsparsh/30DaysOfJavaScript#1320]
### Which pre-existing JavaScript project will you be working on?

.

### Describe your enhancement/improvement

I will modify the background to a new background related to your prestigious project. Please assign it to me in GSSOC 24.
Thank you

### Anything you need to say to the Reviewers

It will bring the more customer attraction and increase the staying time of user on website.

### Add any other context or relevant screenshots about the enhancement here.

.

**Comment by swapnilsparsh** [comment]
@MUKUL-RAJPUT2004 Thank you for providing your insight but it is not required as of now.
