### ISSUE TITLE
Create a login and Signp page for the whole site

### ISSUE THREAD

**Issue by SantoshiVerma** [swapnilsparsh/30DaysOfJavaScript#1322]
### Is your feature request related to a problem? Please describe.

Adding  a login  and signp would help the users to facilate the use of the projects

### Describe the solution you'd like.

using html,css and javascript

### Describe alternatives you've considered.

I am capable of building a responsive and interactive login page for the site please assign this to me with lebels

**Comment by aasthabagrawal** [comment]
I would love to create login page for the website. Please assign this task to me.

**Comment by swapnilsparsh** [comment]
@aasthabagrawal Thank you for providing your insight but it is not required as of now.
