### ISSUE TITLE
Title: Welcome Page for Site

### ISSUE THREAD

**Issue by Prashant-2024** [swapnilsparsh/30DaysOfJavaScript#1323]
### Is your feature request related to a problem? Please describe.

There is no proper welcome or greeting page for users, adding it can make the experience unique

### Describe the solution you'd like.

Simple and minmalistic Welcome page with greetings for the user for good UX experience

### Describe alternatives you've considered.

A dedicated Welcome page based on current time and weather conditions using APIs

### Add any other context or screenshots about the feature request here.

None

**Comment by swapnilsparsh** [comment]
@Prashant-2024 Thank you for providing your insight but it is not required as of now.
