### ISSUE TITLE
Adding a search icon

### ISSUE THREAD

**Issue by Soumya6Tiwari** [swapnilsparsh/30DaysOfJavaScript#1324]
### Is your feature request related to a problem? Please describe.

since the search bar is located , but adding a search icon would enhance user experience

### Describe the solution you'd like.

Adding the search icon beside the search bar would enhance its look.

### Describe alternatives you've considered.

Alternative solution is nothing just to add the search icon

**Comment by Soumya6Tiwari** [comment]
@swapnilsparsh  kindly assign me this issue under gssoc'24

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by swapnilsparsh** [comment]
@Soumya6Tiwari All the best 👍🏻

**Comment by varshithar12** [comment]
Can you please assign me the issue ?

**Comment by swapnilsparsh** [comment]
@Soumya6Tiwari Any update on this ?

**Comment by jha-niraj** [comment]
Hey, @swapnilsparsh Can you give a try to this issue?

**Comment by Soumya6Tiwari** [comment]
@swapnilsparsh  i tried solving it the way you want bt as soon as i do the same the  other functionalities of your website began working inappropriately,
and also my issue was just to put the search icon so as to increase user experience, it is not that which u r thinking.

**Comment by jha-niraj** [comment]
@Soumya6Tiwari Hey, can I give it a try?

**Comment by Soumya6Tiwari** [comment]
@swapnilsparsh kindly take the decision

**Comment by Siddhi561** [comment]
hey, can youe assign me this issue?

**Comment by I-Manjari** [comment]
Hi @Soumya6Tiwari , please assign this issue to me under gssoc'24 as I am eager to contribute to your project and showcase my skills to make meaningful contributions. I am very familiar with languages like Java, HTML, CSS, and JS.

**Comment by kunwarnaunihalsingh** [comment]
hey @swapnilsparsh , please assign this issue to me under GSSOC'24 since I believe that my skills in HTML, CSS and JS make me an ideal fit to contribute for your project.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh i tried solving it the way you want bt as soon as i do the same the other functionalities of your website began working inappropriately, and also my issue was just to put the search icon so as to increase user experience, it is not that which u r thinking.

Sorry to say then I have to close this issue.
