### ISSUE TITLE
Title: Ceaser Cipher Conversion using javascript 

### ISSUE THREAD

**Issue by Damini2004** [swapnilsparsh/30DaysOfJavaScript#1325]
### Which pre-existing JavaScript project will you be working on?

The Caesar cipher implemented in JavaScript offers a simple encryption and decryption method by shifting each letter of the plaintext by a fixed number of positions in the alphabet. This technique is useful for educational purposes or basic security needs. The process involves converting characters to Unicode values, shifting them, and converting them back. It typically includes functions for both encryption and decryption, where each character is shifted by a specified key value. While easy to implement, the Caesar cipher is also easy to break due to its limited number of possible keys. Therefore, it's not suitable for secure communications but can aid in learning cryptographic concepts. It can be extended to support various character sets, handle case sensitivity, and manage spaces and punctuation. Overall, implementing a Caesar cipher in JavaScript offers an accessible introduction to encryption algorithms and is a fun project for beginners to explore cryptography.

### Describe your enhancement/improvement

Enhancement taken as follows :-
1.Dark theme integration
2. User defined key for conversion of text to cipher.
3. Easy can convert from Plain text to cipher text and vice versa.

### Anything you need to say to the Reviewers

Kindly assign this issue to me under GSSOC24, i can resolve it within 2-3 days.

### Add any other context or relevant screenshots about the enhancement here.

![dark](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119414762/b030f164-6044-4c79-9fef-072d75c728d8)
![light](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119414762/b025ecb6-8790-406f-9fb7-4a24234771a6)

It will look like this.... with more enhancement.

**Comment by swapnilsparsh** [comment]
@Damini2004 Thank you for providing your insight but it is not required as of now.
