### ISSUE TITLE
Missing CONTRIBUTING.md File in the Repository

### ISSUE THREAD

**Issue by deekshithapalla** [swapnilsparsh/30DaysOfJavaScript#1328]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by swapnilsparsh** [comment]
@deekshithapalla Thank you for providing your insight but it is not required as of now.
