### ISSUE TITLE
Add card

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#133]
One card for one project, design it accordingly.

**Comment by Jagroop2000** [comment]
Hello !!
Can i work on this issue ??
Also if it is assigned to me can your please elaborate like i have to create a new file.js and design card there or at some specific javascript page.

**Comment by swapnilsparsh** [comment]
@Jagroop2000 Any Updates?

**Comment by Jagroop2000** [comment]
@swapnilsparsh , yes i will pull it by today night or tomorrow morning.

**Comment by Akshata-Gunapache** [comment]
@swapnilsparsh I am interested in this project. Could you please assign it to me?

**Comment by swapnilsparsh** [comment]
#165
