### ISSUE TITLE
[New Game Feature]: Adding Candy Crush Game along with proper score

### ISSUE THREAD

**Issue by nehavaishnav** [swapnilsparsh/30DaysOfJavaScript#1331]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

I would like to add the game Candy Crush. This will be more entertaining for the users to play the classic Candy Crush game. It will have feature of swapping candy pieces, crushing candy pieces, and generating new ones.

### Describe alternatives you've considered.

I couldn't find the game on the website. It will be entertaining to play so I thought of adding this.

### Add any other context or screenshots about the feature request here.

@swapnilsparsh Can you please assign this game addition to me under GSSoC'24. Thank you!

**Comment by swapnilsparsh** [comment]
@nehavaishnav Thank you for providing your insight but it is not required as of now.
