### ISSUE TITLE
Title: Heading Bar is not good , needs improvement 

### ISSUE THREAD

**Issue by technicalkuldeep** [swapnilsparsh/30DaysOfJavaScript#1333]
### Which pre-existing JavaScript project will you be working on?

I am not workinng on any pre existing javascript project , I am intrested in improving your Header of main site
![Screenshot 2024-05-14 104417](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/148907278/f578f9fc-e373-41a4-8ca5-efa17069559d)

This thing needs improvement 

### Describe your enhancement/improvement

I am very good on HTML, CSS and Java Script , I noticed that your main site is not good looking from the header side so I want to improve it 
please assign me this issue 
Thank You 

### Add any other context or relevant screenshots about the enhancement here.

![Uploading Screenshot 2024-05-14 104417.png…]()

**Comment by architajain05** [comment]
Hello PA
Can you please assign me this issue? 

I am good at HTML, CSS, JS. I notices that header is not looking good, i want to improve it.
Thank you!

**Comment by SohaFarhana** [comment]
Helloo
As a GSSOC'24 contributor can u assign me this issue

**Comment by technicalkuldeep** [comment]
I am also a GSSOC ' 24 contributor and also I figured out this problem and I am very good in html and css so kindly assign me this issue

**Comment by swapnilsparsh** [comment]
@technicalkuldeep Thank you for providing your insight but it is not required as of now.
