### ISSUE TITLE
Title: Footer needs improvement

### ISSUE THREAD

**Issue by technicalkuldeep** [swapnilsparsh/30DaysOfJavaScript#1334]
### Which pre-existing JavaScript project will you be working on?

I am not working on any pre existing javascript project , I am interested in improving your footer of main site
![Screenshot 2024-05-14 104459](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/148907278/d4142806-f12c-4847-9be9-e5bcf3a58aca)

### Describe your enhancement/improvement

This footer is very cluttered , needs proper spacing as well as proper content should be added to it so that it looks good 
I am very good in html , css so this is my field and I can easily resolve this issue 
so kindly assign me this issue 
waiting for your positive feedback 
Thank You 
![Screenshot 2024-05-14 104459](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/148907278/e0168883-963e-40d9-9a4e-9c3c0c3e2cfb)

**Comment by bhairabmahato** [comment]
Hey, I want to improve the footer, please assign the issue ,I am GSSoC'24 contributor .

**Comment by swapnilsparsh** [comment]
@technicalkuldeep Thank you for providing your insight but it is not required as of now.
