### ISSUE TITLE
Title: Proper spacing and design improvement 

### ISSUE THREAD

**Issue by technicalkuldeep** [swapnilsparsh/30DaysOfJavaScript#1335]
### Which pre-existing JavaScript project will you be working on?

Stopwatch

### Describe your enhancement/improvement

In this stopwatch project proper spacing and design is not there , It should be improved 
I am good and experienced in HTML , CSS and Javascript 
so I request you to kindly assign me this issue 
I will resolve this issue for sure 
Thank You

![Screenshot 2024-05-14 112119](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/148907278/bd7495f7-5749-4bda-a0eb-36f4063f01a1)

**Comment by swapnilsparsh** [comment]
@technicalkuldeep Thank you for providing your insight but it is not required as of now.
