### ISSUE TITLE
Title: Enhancement in the Project Cards

### ISSUE THREAD

**Issue by nandita27iitp** [swapnilsparsh/30DaysOfJavaScript#1336]
### Which pre-existing JavaScript project will you be working on?

I would like to improve the UI of all the project cards.

### Describe your enhancement/improvement

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/94813932/e797ecd6-53a3-434e-9572-48b86b8a21aa)

Something like this.

**Comment by nandita27iitp** [comment]
Please assign this issue to me under GSSOC'24

**Comment by swapnilsparsh** [comment]
@nandita27iitp Thank you for providing your insight but it is not required as of now.
