### ISSUE TITLE
Title: Login and SignUp pages

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1337]
### Is your feature request related to a problem? Please describe.

There is no login or signup pages ,where user cannot login or signup properly.

### Describe the solution you'd like.

I would like to create a login and sign up page with unique design I already have experience in website development using html and css so, I can make it in a most effective and unique way. Looking forward for your approval. Thank You!!

### Describe alternatives you've considered.

I'm goot at creating pages using html and css , i want to make it more user friendly and look attractive.

**Comment by SrijaVuppala295** [comment]
Please assign this issue to me!!

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now.
