### ISSUE TITLE
Title: Adding Speech Recognition Project

### ISSUE THREAD

**Issue by nandita27iitp** [swapnilsparsh/30DaysOfJavaScript#1338]
### Is your feature request related to a problem? Please describe.

Yes, my feature request is related to providing a speech recognition project option in the 30DaysOfJavaScript repository under GSSoC 2024.

### Describe the solution you'd like.

As an interesting JavaScript project, beginners can easily build a speech detection API or a text-to-speech web application using the web speech API to integrate with your JavaScript code.

### Describe alternatives you've considered.

I have used a speech detection API to build this project.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/94813932/90a63dd4-0123-47c7-a435-02bf260035cb)

Its something like this.

**Comment by nandita27iitp** [comment]
Please assign this issue to me under GSSOC24

**Comment by swapnilsparsh** [comment]
@nandita27iitp Thank you for providing your insight but it is not required as of now.
