### ISSUE TITLE
Marriage predictor Game

### ISSUE THREAD

**Issue by Nih1tGupta** [swapnilsparsh/30DaysOfJavaScript#1339]
### Is your feature request related to a problem? Please describe.

USE OF SIMPLE JS, HTML AND CSS

### Describe the solution you'd like.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119615342/b1d982e5-8009-4d4e-a733-096f076918b0)

### Describe alternatives you've considered.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119615342/f0584fdd-f92e-4faf-92b5-fa113d9d4fa2)

**Comment by Nih1tGupta** [comment]
@swapnilsparsh can i add this to your project?
Please assign me this issue if accepted

**Comment by swapnilsparsh** [comment]
@Nih1tGupta Thank you for providing your insight but it is not required as of now.
