### ISSUE TITLE
Enhance the UI/UX of the website

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#134]

**Comment by ishika1501** [comment]
@swapnilsparsh  i would like to take up this project as i  feel quite confident over my front end and UX /UI skills

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh  i would like to take up this project as i  feel quite confident over my front end and UX /UI skills 

Good Luck 😃

**Comment by ishika1501** [comment]
@swapnilsparsh  thankyou sir.

**Comment by priyanshi1282** [comment]
Hey @swapnilsparsh, I would like to contribute to enhance UI/UX of this project.
can you please guide me steps for contributing.

**Comment by LakshayN** [comment]
Hi @swapnilsparsh I would like to enhance the UI/UX of the website, can you provide me with the required things that need improvement?

**Comment by swapnilsparsh** [comment]
@ishika1501 Any updates?

**Comment by Anthima** [comment]
Hi, @swapnilsparsh I would like to take up this project.

**Comment by ishika1501** [comment]
@swapnilsparsh  sorry sir , yesterday i texted you about the project in the channel , but didn't get any reply ,i am getting it get done by tomorrow .

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?
