### ISSUE TITLE
Adding New Project : Movie Guessing Game  

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1343]
### Which pre-existing JavaScript project will you be working on?

Movie Guessing Game , The user has to simply press the letters which forms a movie's name and if he guesses it correctly then he will win the game and if not so then he will lose the game.

### Describe your enhancement/improvement

Movie Guessing Game , The user has to simply press the letters which forms a movie's name and if he guesses it correctly then he will win the game and if not so then he will lose the game.

### Add any other context or relevant screenshots about the enhancement here.

This is a game based on guessing. A user will have to guess the movie name by carefully observing the emojis which corresponds to a particular movie.
![Movie_Guessing_Game](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/59fdff22-9bbc-44ee-997a-466c0c12f35a)

**Comment by swapnilsparsh** [comment]
@codewithganeshhh All the best 👍🏻

**Comment by Ayusha-a07** [comment]
i am gssoc contributor.could you please assign this to me?
