### ISSUE TITLE
ADDING THE README FILE

### ISSUE THREAD

**Issue by SohaFarhana** [swapnilsparsh/30DaysOfJavaScript#1344]
### Description

All of the projects lack the readme section. There can be description to all of the projects as they make it more understandable and user friendly

**Comment by SohaFarhana** [comment]
I would like to work on this issue
I am a GSSOC'24 contributor and would like to work on this issue

**Comment by swapnilsparsh** [comment]
@SohaFarhana Thank you for providing your insight but it is not required as of now.
