### ISSUE TITLE
NEW GAME: Chopsticks_Challenge

### ISSUE THREAD

**Issue by Bindusree1515** [swapnilsparsh/30DaysOfJavaScript#1345]
### What happened?

**Chopsticks** is a hand game typically played between two players, although it can be adapted for more players. The goal of the game is to eliminate your opponent's hands by strategically attacking and redistributing points between hands.

please assign me this game under **GSSOC'24**.

### How can we reproduce this bug?

****How to Play:**
Setup:**

Each player starts with one point (represented by fingers) on each hand.

**Gameplay:**

- Players take turns performing one of two actions: Attack or Split.
**Actions:**

- Attack: A player can use one of their hands to attack an opponent's hand. To attack:
- Choose one of your hands (e.g., left hand).
- Use that hand to "attack" one of your opponent's hands (e.g., their right hand).
- The attacked hand accumulates points equal to the attacking hand's points. For example, if your left hand has 2 points and you attack your opponent's right hand (which has 1 point), their right hand will now have 3 points (1 + 2).
- Split: A player can redistribute points between their own hands. To split:
Choose a hand.
- Split the points from that hand equally between both of your hands. For example, if you have 4 points on your left hand, split them to have 2 points on each hand.
Game Objective:

The game continues with players taking turns attacking and splitting.
A player loses a hand (becomes inactive) when one of their hands reaches a certain point threshold (usually 5 points).
Winning:

The game ends when one player loses both hands (both hands reach the threshold and become inactive).
The remaining player is declared the winner!

### Desktop Information (Optional)

Here is the **screenshot** of sample game :
I will enhance it.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/91887086/e8c43f73-ea4e-447d-95ff-3120772f7ef4)

### Urgency (Optional)

None

**Comment by swapnilsparsh** [comment]
@Bindusree1515 Thank you for providing your insight but it is not required as of now.
