### ISSUE TITLE
Title: Calculator

### ISSUE THREAD

**Issue by tanu-agarwal0101** [swapnilsparsh/30DaysOfJavaScript#1347]
### Which pre-existing JavaScript project will you be working on?

In the calculator multiple operators are getting added to the value. 
Text is overlapping in the footer in mobile view(rotated)

### Describe your enhancement/improvement

Proper padding in footer is needed because text is overlapping

### Anything you need to say to the Reviewers

Please assign me to work on this under gssoc'24

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/162132053/639644c8-aef8-4e72-b4c7-ef665a96adda)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/162132053/5bcb0db5-a190-41cc-8aee-5d39758bf648)

**Comment by bhairabmahato** [comment]
Please assign me to work on this under gssoc'24

**Comment by traptijindal** [comment]
Please assign me to work on this under gssoc'24.

**Comment by swapnilsparsh** [comment]
@tanu-agarwal0101 Thank you for providing your insight but it is not required as of now.
