### ISSUE TITLE
Fixing search Bar

### ISSUE THREAD

**Issue by Shivangi015** [swapnilsparsh/30DaysOfJavaScript#1348]
### What happened?

The UI of the website is not appealing and does not look attractive. The Fonts are not good, the search bar needs to be fixed.

### How can we reproduce this bug?

The search Bar should be more attractive and the fonts needs to fixed to make the website more appealing.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/115791035/59caa3ad-88c3-40cd-98f0-1e5c7940fd31)

### Urgency (Optional)

None

**Comment by Shivangi015** [comment]
I want to work on this issue under Gssoc'24.

**Comment by swapnilsparsh** [comment]
@Shivangi015 Thank you for providing your insight but it is not required as of now.
