### ISSUE TITLE
Fixing Drum Kit

### ISSUE THREAD

**Issue by Shivangi015** [swapnilsparsh/30DaysOfJavaScript#1349]
### Is your feature request related to a problem? Please describe.

The UI of the drum kit should be changed to make it look more attractive.
The photos on the buttons should be added to make the user clear about which sound would play on clicking that button.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/115791035/07397524-48b3-4336-856a-dc9df34c6503)

### Describe the solution you'd like.

Adding images on the button.

### Describe alternatives you've considered.

The background image of this project should have a image related to voices and sounds.

**Comment by Shivangi015** [comment]
I want to work on this issue under Gssoc'24.

**Comment by swapnilsparsh** [comment]
@Shivangi015 Thank you for providing your insight but it is not required as of now.
