### ISSUE TITLE
Adding Navbar to the website

### ISSUE THREAD

**Issue by Shivangi015** [swapnilsparsh/30DaysOfJavaScript#1350]
### Is your feature request related to a problem? Please describe.

The Navbar should be added to the website to make it easier for the users to interact with the website.

### Describe the solution you'd like.

The Navbar should have link to About Page, Contact Page, Project, Search.

### Describe alternatives you've considered.

You can tell me what you want to add into your Navbar, I will add it.

**Comment by bhairabmahato** [comment]
Hey, I can solve this issue, please add gssoc and level tag and  assign me the issue ,I am GSSoC'24 contributor .

**Comment by PrashantAnand03** [comment]
I would like to work on this issue, please assign this to me.

**Comment by arpitarout01** [comment]
please assign me this issue and also add the gssoc and the level tags
