### ISSUE TITLE
Title: font change

### ISSUE THREAD

**Issue by Aishikap** [swapnilsparsh/30DaysOfJavaScript#1354]
### Is your feature request related to a problem? Please describe.

nope

### Describe the solution you'd like.

The font can be changed

### Describe alternatives you've considered.

we can provide more tech oriented font rather than the normal one

**Comment by Utkarsh7368** [comment]
Please assign this issue to me

**Comment by swapnilsparsh** [comment]
@Aishikap Thank you for providing your insight but it is not required as of now.
