### ISSUE TITLE
Add a new Project : Flash Game

### ISSUE THREAD

**Issue by nilamkumari11** [swapnilsparsh/30DaysOfJavaScript#1356]
### Is your feature request related to a problem? Please describe.

This is game where a picture of any number or pattern will be displayed to the users for a second and the user will be then provided with options, and they will have to choose the correct one. The number of Options will be depending on the level they select easy or difficult..

### Describe the solution you'd like.

 It combines elements of memory, pattern recognition, and decision-making into an engaging gameplay experience.

### Describe alternatives you've considered.

This is simple memory fun game.

**Comment by nilamkumari11** [comment]
@swapnilsparsh kindly assign me this under gssoc'24

**Comment by swapnilsparsh** [comment]
@nilamkumari11 Thank you for providing your insight but it is not required as of now.
