### ISSUE TITLE
Wall Breaker Game

### ISSUE THREAD

**Issue by Ancha2003** [swapnilsparsh/30DaysOfJavaScript#1357]
### Which pre-existing JavaScript project will you be working on?

In Wall Breaker Game ,
There should be an option to control the speed of the ball
There should be an option to increase or decrease the speed of the ball.

### Describe your enhancement/improvement

I can fix this problem . And I can make this game even better.
By giving the option of speed control , whoever wants to play fast can play fast or slow .

**Comment by swapnilsparsh** [comment]
@Ancha2003 Thank you for providing your insight but it is not required as of now.
