### ISSUE TITLE
Add Random Quote Generator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [swapnilsparsh/30DaysOfJavaScript#136]
The main objective of this project is to fetches a new random quote from an API, upon the click of a button, and displays it in the browser.
Please assign this issue to me.!

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue. I can do this using zen quotes.

**Comment by sagnik2001** [comment]
Can you assign this issue to me??

**Comment by kalashvasaniya** [comment]
Hey, I want to work on this issue!

**Comment by varisha-025** [comment]
Hey @swapnilsparsh . Can you assign this issue to me?

**Comment by swapnilsparsh** [comment]
@kalashvasaniya @Kushal-2002 @sagnik2001 @varisha-025 
Don't open new issues by just adding your projects in this repo, you can directly make a PR if you have some JS project with you that is not yet on the website.
Good Luck 👍🏻

**Comment by adi7yashah** [comment]
I am a GSSOC'22 participant, I want to work on this issue
