### ISSUE TITLE
Title: Shifting Search box at the top -right  side  of the navbar with the icons on it

### ISSUE THREAD

**Issue by codewithishu** [swapnilsparsh/30DaysOfJavaScript#1360]
### Which pre-existing JavaScript project will you be working on?

Search-box is not placed properly . There is no search- icons available on it.

![Screenshot 2024-05-15 081508](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146975269/f3a1a055-e59e-4e02-872c-b71735408e89)

### Describe your enhancement/improvement

Search-box should be placed at the top-right side of the  title  [30 days of Javascript] and the  search-icons should be provided within it. 

### Anything you need to say to the Reviewers

 I am a GSSoc'24 contributor .
kindly assign this issue to me
please add gssoc label to it.

**Comment by codewithishu** [comment]
@swapnilsparsh please label this under gssoc and assign this to me

**Comment by swapnilsparsh** [comment]
@codewithishu Thank you for providing your insight but it is not required as of now.
