### ISSUE TITLE
Title: Adding Social links eg: Linkedin ,twitter and GitHub to the footer section.

### ISSUE THREAD

**Issue by codewithishu** [swapnilsparsh/30DaysOfJavaScript#1361]
### Is your feature request related to a problem? Please describe.

Social links should be available to the footer section so that viewers can follow your page.
It will help you to connect with more people.

### Describe the solution you'd like.

I would like to add your linkedin ,twitter and github profile at the bottom of the landing page.

### Describe alternatives you've considered.

I will add your twitter ,github , linkedin profile to the landing page of your website.

### Add any other context or screenshots about the feature request here.

 @swapnilsparsh  I am a GSSOC'24 contributor . kindly assign this issue to me.

**Comment by codewithishu** [comment]
@swapnilsparsh  please label this issue and assign this to me.

**Comment by aditig80** [comment]
@swapnilsparsh please label this issue as gssoc.
kindly assign this issue to me!

**Comment by im-shivaay4u** [comment]
sir I would be vey thankful to you if you would assign this project to me

**Comment by swapnilsparsh** [comment]
@codewithishu Thank you for providing your insight but it is not required as of now.
