### ISSUE TITLE
Title: Image Search App

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1362]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

This image search app is a simple web application built using HTML, CSS, and JavaScript. It allows users to enter keywords or phrases into an input field, then click a button to search for images related to their query. Upon searching, the app sends a request to the  API, a popular image-sharing platform, to retrieve a list of images matching the user's query. The app then dynamically displays these images on the page.

### Describe alternatives you've considered.

 Initially, we considered integrating only one image API such as Unsplash or Pixabay. While this approach simplifies development, it limits the diversity of available images and may result in dependency on a single provider.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-15 090011](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/0c035d0b-f643-413f-8c0b-256bffeb7b97)

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now.
