### ISSUE TITLE
Title: Enhancing Calendar UI

### ISSUE THREAD

**Issue by Changingthegame** [swapnilsparsh/30DaysOfJavaScript#1366]
### Which pre-existing JavaScript project will you be working on?

Calendar 

### Describe your enhancement/improvement

Actually, the calendar page  lacks an attractive look. I want to make some changes in it which are as follows:
Firstly , there should be subtle borders to make it good looking .Secondly, introducing a more dynamic color scheme for dates, months, and years can make the calendar more engaging and visually appealing. Also, a nice color combination will improve readability and visual appearance of the calendar. I'm enthusiastic about contributing to this enhancement and have the necessary skills.

**Comment by Changingthegame** [comment]
Can you please assign this to me as I am very interested in it.

**Comment by swapnilsparsh** [comment]
@Changingthegame Thank you for providing your insight but it is not required as of now.
