### ISSUE TITLE
Adding New Project: Food Recipe Webpage

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1368]
### Is your feature request related to a problem? Please describe.

Many users find it difficult to find out what recipes they can prepare using the limited ingredients they've.

### Describe the solution you'd like.

This Food Recipe extension will allow users to get varieties of meals and their preparation procedures, just by entering the ingredients they've.

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Food Recipe webpage should seamlessly run in any browser, and should have a clean UI, along with the buttons working properly so as to ensure a great User Experience.

**Comment by im-shivaay4u** [comment]
sir I would be very thankful to you if you will assign this project to me
as it will help me to make my foundation stronger

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
