### ISSUE TITLE
Add BMI Calculator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [swapnilsparsh/30DaysOfJavaScript#137]
The objective of this JavaScript project is to wire up a very basic JavaScript BMI Calculator.
Please assign this issue to me.

**Comment by kalashvasaniya** [comment]
Pls. assign this to me!

**Comment by Kushal-2002** [comment]
I am a GSSOC'22 participant, I want to work on this issue. I have previously created a BMI calculator using JS.

**Comment by vaishnavighiradkar** [comment]
I'm a contributor in GSSOC-22.
Can you assign this issue to me?

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22

**Comment by kalash2205** [comment]
hi @swapnilsparsh 
can i work on this issue?

thanks
gssoc contributor

**Comment by Utkarsh575** [comment]
Hey there, I specialize in Frontend web development and would like to add a Cool Looking BMI Calculator into this project.
I've made a similar project called GlassCalculator you can check it out.
![Uploading glass.png…]()

**Comment by swapnilsparsh** [comment]
@kalashvasaniya @Kushal-2002 @vaishnavighiradkar @sulogna2001 @kalash2205 @Utkarsh575 
Don't open a new issues by just adding your projects in this repo, you can directly make a PR if you have some JS project with you that is not yet on the website.
Good Luck 👍🏻
