### ISSUE TITLE
Adding New Project : Expense Tracker

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1370]
### Is your feature request related to a problem? Please describe.

Many households find it difficult to track their expenses, thus spending more than their budget, which leaves them with very less or almost no money at the end of a month.

### Describe the solution you'd like.

The Expense Tracker Extension would take care of the expenditure of the household. The user have to set their budget, and keep on updating their regular expenses. The Extension will show them how much money they've sent and also the remaining budget, thus allowing the household to track their expenses regularly.

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Expense Tracker project should seamlessly run in any browser and should've an easy-to-use simple UI and great functionality to provide a great User experience.

**Comment by im-shivaay4u** [comment]
sir I would be very thankful to you if you will assign this project to me
as it will help me to make my foundation stronger

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
