### ISSUE TITLE
Adding New Project : Bill Splitter 

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1371]
### Is your feature request related to a problem? Please describe.

Many users find it difficult to split a bill among a group of friends after coming back from a trip, or after having meal at any restaurant.

### Describe the solution you'd like.

This Bill Splitter extension will allow users to generate and split the bill among their group, by entering the total amount, total number of people and the tip amount.

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Bill Splitter should seamlessly run in any browser, and should have a clean UI, along with the buttons working properly so as to ensure a great User Experience.

**Comment by ShahHetviIT** [comment]
I'm enthusiastic about spearheading the 30 days of Js project, leveraging my expertise in HTML, CSS, JavaScript, and ReactJS. I'm eager to contribute my skills to this innovative endeavor. Could you please assign me this issue through GSSOC?
also add label to it.

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
