### ISSUE TITLE
Adding New Project : Resume Builder 

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1372]
### Is your feature request related to a problem? Please describe.

Nowadays, everyone, ranging from a student to a working professional, needs a well-built resume to apply to companies for jobs and internships. A resume not only reflects their skills but also reflects their personality and character. Companies believe much on first impression, and a good resume is what impresses them. But, the applicants either become unsuccesful to create a good resume or it takes a lot of time finding a good template for resume, and edit it.

### Describe the solution you'd like.

<ul>
<li>The Resume Builder JS Extension would make the resume building process a cakewalk!</li>
<li>Just enter the details like, name, personal details, academic details, work experience, skills, etc and boom, the resume will be ready in just a click! </li>
<li>Also, the user will be able to update the details dynamically, including adding or removing sections, update personal information, or update new skills that they've learnt.</li>
<li>More interestingly, the users will also be able to download their generated resume as PDF.</li>
</ul>

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Resume Builder project should seamlessly run in any browser and should be able to meet the user's requirements. Also, a clean UI is a must for providing a great User Experience.

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Come up with some new and unique idea where some interesting JS concepts are used.
