### ISSUE TITLE
Adding New Project : Text to Image Generator

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1373]
### Is your feature request related to a problem? Please describe.

Currently, there is a lack of user-friendly tools that allow non-technical users to convert text to images directly within a web browser using JavaScript. Most available solutions require advanced technical knowledge or involve using external software, which can be inconvenient and time-consuming.

### Describe the solution you'd like.

<ul>
<li>By addressing these problems, the feature request aims to enhance user experience by providing a seamless, customizable, and easy-to-use text-to-image conversion tool.</li>
<li>This would make it more accessible for a broader audience, including those with limited technical skills, and provide the necessary flexibility for diverse use cases.</li>
<li>Also, this project would allow the users to customise the generated output by having the feature of unlimited customizations.</li>
<li>The users will also be able to choose the number of images they want to generate, based on their given input.</li>
<li>The users will also be able to download the images, as per their requirements.</li>
</ul>

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Text to Image generator project should seamlessly run in any browser and should be able to meet the user's requirements. Also, a clean UI is a must for providing a great User Experience.

**Comment by eiva078** [comment]
I'd like to work on this issue. Please assign it under GSSOC

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
