### ISSUE TITLE
Adding a Project : Chatbot using JS

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1374]
### Is your feature request related to a problem? Please describe.

<ul>
<li>Currently, integrating a chatbot into a website requires substantial technical expertise. Existing solutions often involve complex setup processes and configuration, making it difficult for developers, especially those with limited experience, to implement an effective chatbot.</li>
<li>Websites often struggle to maintain user engagement and provide instant support. Without an easily deployable chatbot, users might leave the site without finding the information they need, leading to lower user satisfaction and higher bounce rates.</li>
<li> Many available chatbot solutions lack the flexibility to be easily customized to fit specific business needs and branding requirements. Users need a tool that allows for easy customization of responses, appearance, and behavior to align with their website’s goals and aesthetics.</li>
</ul>

### Describe the solution you'd like.

<ul>
<li>Users should have the ability to easily define and update the chatbot’s responses through a user-friendly interface or a configuration file.</li>
<li>This includes setting up pre-defined responses, creating decision trees, and enabling the chatbot to handle common user queries effectively.</li>
<li>In this chatbot, users will be able to ask any question and receive instant responses. This chatbot has an elegant and responsive user interface, ensuring a seamless experience across various devices.</li>
</ul>

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The Chatbot should seamlessly run in any browser, and must have a clean UI, in order to provide a great User Experience.

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Come up with some new and unique idea where some interesting JS concepts are used.
