### ISSUE TITLE
Enhancement: STACK GAME

### ISSUE THREAD

**Issue by Changingthegame** [swapnilsparsh/30DaysOfJavaScript#1376]
### Is your feature request related to a problem? Please describe.

I played the stack game and it is very popular game in many online games but the problem in our game is that it has no best score ,Resume, Restart , Pause feature as well as the UI is also not that much attractive.

### Describe the solution you'd like.

I would like to add all of the above discussed feature in this game and also for UI , I want to change a bright background for the game and for start button I want to make its background color green.

### Describe alternatives you've considered.

Bright background, green background of start button
Restart, resume, pause, best score  feature .
Also I am thinking of a settings feature for sound, shapes of the sheets (such as rounds, square), and background(light and dark).

**Comment by Changingthegame** [comment]
Please assign this to me as I am very eager to work in this game .
Thankyou!

**Comment by swapnilsparsh** [comment]
@Changingthegame Thank you for providing your insight but it is not required as of now.
