### ISSUE TITLE
[Feature] your website is need makeover

### ISSUE THREAD

**Issue by pandeyji711** [swapnilsparsh/30DaysOfJavaScript#1377]
### Is your feature request related to a problem? Please describe.

Hello @swapnilsparsh,

I’ve taken a look at your website and I believe it has great potential. I would like to offer my services to revamp it and enhance its user-friendliness. I’m eager to undertake this project as part of **GSSoC 2024.** **Please consider assigning this task to me.**

### Describe the solution you'd like.

**User Experience Audit**: Conduct a thorough review of the current website to identify areas that can be improved for better user engagement and ease of use.
**Design Overhaul:** Implement a modern, clean design that aligns with your brand and improves the overall aesthetic appeal.
**Navigation and Structure**: Simplify the navigation to ensure that users can find information quickly and intuitively.

### Describe alternatives you've considered.

Template-Based Redesign: Instead of a custom design, you could opt for a high-quality, pre-designed template. This can be a cost-effective and time-saving option, though it might limit customization.

**Comment by pandeyji711** [comment]
please assign this task to me under Gssoc 2024

**Comment by pandeyji711** [comment]
@swapnilsparsh please assign  this task to me under Gssoc 2024

**Comment by swapnilsparsh** [comment]
@pandeyji711 Can you share some designs before I can assign you the issue.

**Comment by pandeyji711** [comment]
@swapnilsparsh, I am actively working on this task and am confident that my contributions will significantly enhance it. Could you kindly assign this task to me under GSSoC 2024, Level 3?

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/154527778/3515f8e9-7ea6-467a-a4ac-f3d4c1ccbe71

**Comment by swapnilsparsh** [comment]
@pandeyji711 We need to show the photos.

**Comment by pandeyji711** [comment]
@swapnilsparsh I will add this please assign this  in Gssoc24 and give some level

**Comment by swapnilsparsh** [comment]
@pandeyji711 I want UI like the below photo and Good Luck 👍🏻
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/827e8e6a-a049-41ea-aeb8-00943c9371eb)

**Comment by pandeyji711** [comment]
@swapnilsparsh what function you want in live button 
and is you have collection of image or i have to search for it

**Comment by swapnilsparsh** [comment]
@pandeyji711 When clicking on live button then that particular project should open and clicking on github that particular github project folder should open

You can find all the images [here](https://github.com/swapnilsparsh/30DaysOfJavaScript/tree/master/30DaysOfJavaScript/assets)

**Comment by pandeyji711** [comment]
okk

**Comment by pandeyji711** [comment]
@swapnilsparsh **please review and merge with Gssoc and level 3 label**
