### ISSUE TITLE
ADDING NEW RPS GAME

### ISSUE THREAD

**Issue by sakshiglaze** [swapnilsparsh/30DaysOfJavaScript#1378]
Hello @swapnilsparsh 
### Is your feature request related to a problem? Please describe.

User will have one more option among the listed options. It just you can play Rock-Paper-Scissor Game. Try to win against computer and guess it's movements.
I would like to add to this contribution under GSSOC'24.

### Describe the solution you'd like.

A Rock-Paper-Scissor game--
Computer Opponent: Develop an opponent that can make intelligent choices, providing a challenging gameplay experience for the human player.
Autoplay Mode: Include an autoplay mode where the computer player competes against itself.
Real-time Scoring: Keep track of the scores for both the human player and the computer opponent in real-time. Display the scores prominently on the game interface to provide a sense of competition and progress.

### Describe alternatives you've considered.

Implementing persistent scoring in a rock-paper-scissors game, ensuring scores are not lost even after page reloads unless and until player resets the score.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-15 155019](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/129287425/de2041f4-16a1-49e1-967e-aea9bc10bbc2)

**Comment by swapnilsparsh** [comment]
@sakshiglaze Thank you for providing your insight but it is not required as of now.
