### ISSUE TITLE
Meditation app using JS

### ISSUE THREAD

**Issue by Prajwal-ctrl** [swapnilsparsh/30DaysOfJavaScript#138]

**Comment by TushitaParashar** [comment]
Hey! I want to work on this, so please assign this issue to me.
I'm a participant in GSsoC'22

**Comment by sagnik2001** [comment]
Can you kindly elaborate on this issue??

**Comment by kalashvasaniya** [comment]
Hey I want to work on this issue!

**Comment by swapnilsparsh** [comment]
@Prajwal-ctrl Can you elaborate on why you opened this issue??

**Comment by Prajwal-ctrl** [comment]
@swapnilsparsh  we can make different js projects and push in this repo right ??

**Comment by swapnilsparsh** [comment]
@sagnik2001 @kalashvasaniya 
Don't open new issues by just adding your projects in this repo, you can directly make a PR if you have some JS project with you that is not yet on the website.
Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
@Prajwal-ctrl Update?

**Comment by Prajwal-ctrl** [comment]
I willl push it till tomorrow night 
just some UI changes doin

**Comment by Prajwal-ctrl** [comment]
Hii @swapnilsparsh i just made a PR of meditation app
Just one request can you made it under GSSOC'22 because I am a participant in it

**Comment by Prajwal-ctrl** [comment]
Hii @swapnilsparsh  why my pull request don't get merged is there any issue i made a PR yesterday but now its not showing on PULL request section

**Comment by Prajwal-ctrl** [comment]
HIi @swapnilsparsh can you guide me on above problem

**Comment by Prajwal-ctrl** [comment]
because yesterday i made a PR and it was visible on PR section but now its not seeing

**Comment by Prajwal-ctrl** [comment]
HIi @swapnilsparsh  @sagnik2001  @kalashvasaniya @ahamed please guide me on above issue i am stuck from yesterday it just related to pull request

**Comment by Prajwal-ctrl** [comment]
![Screenshot (379)](https://user-images.githubusercontent.com/63673431/156908808-2edf5c9a-9d5e-4ada-8b8e-aa5f98ae54b6.png)
![Screenshot (381)](https://user-images.githubusercontent.com/63673431/156908809-481d44c0-7a9d-4ef1-982d-d02c15743243.png)



here its showing that i made a PR but not showing in a PULL request section 
please help me

**Comment by kalashvasaniya** [comment]
Click on Compare & pull request
