### ISSUE TITLE
[113 MINESWEEPER] points count error

### ISSUE THREAD

**Issue by Gauranshgoel123** [swapnilsparsh/30DaysOfJavaScript#1380]
### What happened?

Even on clicking the tile whose point has already been counted, the points count keeps on increasing on clicking the same tile again,
for example see the image
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/121503835/96132b24-ad90-4ba3-b0f0-e8acfff3d6f4)
here the count of points is 81
but on clicking any opened tile again the point increases by 1, instead it should have remained constant
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/121503835/3c0cba93-6bde-4c3e-814e-ea8782e308fc)

### How can we reproduce this bug?

you may go to 113 minesweeper game.

### Urgency (Optional)

None

**Comment by swapnilsparsh** [comment]
@Gauranshgoel123 All the best 👍🏻

**Comment by Gauranshgoel123** [comment]
@swapnilsparsh pls merge PR #1434
