### ISSUE TITLE
Title: Speech to text convertor

### ISSUE THREAD

**Issue by m3kvt** [swapnilsparsh/30DaysOfJavaScript#1383]
### Is your feature request related to a problem? Please describe.

Yes, the feature request is related to improving accessibility and enhancing user experience. Currently, users who prefer or need to input text via speech rather than typing do not have an option to do so. This limitation can be particularly challenging for users with disabilities, users who are multitasking, or those who find typing cumbersome.

### Describe the solution you'd like.

- A microphone button that users can click to start and stop speech recognition.
- Real-time transcription of spoken words into text within input fields.

### Describe alternatives you've considered.

Providing enhanced typing assistance, such as predictive text or auto-complete features, to ease the typing process. 

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-15 174236](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/98379619/d5421349-d4b0-4b65-b989-bb345ed46a14)

**Comment by maniranjan2023** [comment]
kindly assign this task to me

**Comment by swapnilsparsh** [comment]
@m3kvt Thank you for providing your insight but it is not required as of now.
