### ISSUE TITLE
Adding new game: doodle-jump game

### ISSUE THREAD

**Issue by anushkab2508** [swapnilsparsh/30DaysOfJavaScript#1385]
### Is your feature request related to a problem? Please describe.

I had always wanted to contribute to open source. I'm familiar with the tech stack and I wanted to add a game that is made from the same tech stack. 

### Describe the solution you'd like.

This is a simple implementation of the popular game "Doodle Jump" using HTML, CSS, and JavaScript. The game involves controlling a character (doodler) to jump on platforms and reach higher scores.

### Describe alternatives you've considered.

Depending on the aim and project, which is 30 days of javascript, I think this game is quite useful in terms of learning.

**Comment by swapnilsparsh** [comment]
@anushkab2508 Thank you for providing your insight but it is not required as of now.
