### ISSUE TITLE
searching can be made easy if sort or filter option added

### ISSUE THREAD

**Issue by ishaa18** [swapnilsparsh/30DaysOfJavaScript#1386]
### Is your feature request related to a problem? Please describe.

when you want to search specific projects you can filter by categories.or if you want to sort it by newest or popular these feature is the only one you want.

### Describe the solution you'd like.

the filter option with categories like components or game or etc can be done and 
sort option can go with newest oldest mostly view etc.

### Describe alternatives you've considered.

no alternatives.

**Comment by swapnilsparsh** [comment]
@ishaa18 Website UI will be revamped so this will be needed after that, but thank you for your suggestions.
