### ISSUE TITLE
Title: Adding icon to search bar

### ISSUE THREAD

**Issue by harikasayani** [swapnilsparsh/30DaysOfJavaScript#1388]
### Which pre-existing JavaScript project will you be working on?

I want to add icons to search bar in home page.

### Describe your enhancement/improvement

I observed that search bar does not have search bar icon. So I want to work on it.

### Anything you need to say to the Reviewers

I am GSSOC'24 contributor.
please assign me this task.

**Comment by swapnilsparsh** [comment]
@harikasayani Thank you for providing your insight but it is not required as of now.
