### ISSUE TITLE
Title: Enhancing calculator project

### ISSUE THREAD

**Issue by harikasayani** [swapnilsparsh/30DaysOfJavaScript#1389]
### Which pre-existing JavaScript project will you be working on?

I want to work on calculator project.

### Describe your enhancement/improvement

I want to make calculator project more attractive.

### Anything you need to say to the Reviewers

Please assign this task to me.
I am GSSOC'24 Contributor.

**Comment by vignesh-0512** [comment]
Hello @Satakshijain, Already i have an experience on building calculator using html, css and javascript so I am willing to work on this issue so can you assign me this issue under Gssoc'24.

**Comment by eiva078** [comment]
I'd like to work on this issue as I have already done it. Please assign it under GSSOC

**Comment by swapnilsparsh** [comment]
@harikasayani Thank you for providing your insight but it is not required as of now.
