### ISSUE TITLE
want to try to make a blog website using html,css and javascript.

### ISSUE THREAD

**Issue by TadrupDas** [swapnilsparsh/30DaysOfJavaScript#139]
@swapnilsparsh I would like to contribute to this project by trying to make a simple blog website using html,css and javascript. 

Tadrup Das
GSSOC'22 contributor

**Comment by kalashvasaniya** [comment]
Hey assign this to me!

**Comment by swapnilsparsh** [comment]
> Hey assign this to me!

Don't open new issues by just adding your projects in this repo, you can directly make a PR if you have some JS project with you that is not yet on the website.
Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
@TushitaParashar Update?

**Comment by TadrupDas** [comment]
@swapnilsparsh working on the frontend part right now. Actually, exams were going on.

**Comment by TadrupDas** [comment]
@swapnilsparsh   i have already finished the frontend but stuck on the backend part. So can i contribute only the frontend?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh i have already finished the frontend earlier but was stuck on the backend part. So can i contribute only the frontend?

Sorry but no
