### ISSUE TITLE
Title: Adding a new drum sound in the existing Drums site

### ISSUE THREAD

**Issue by S-PADMANABAN-2001** [swapnilsparsh/30DaysOfJavaScript#1393]
### Which pre-existing JavaScript project will you be working on?

Day 1 Drums project,  Adding a new drum sound in the existing Drums site

### Describe your enhancement/improvement

Adding Boing Drum sound in drums project

### Anything you need to say to the Reviewers

Hi, I am a GSSOC ' 24 please review and assign me this issue

**Comment by swapnilsparsh** [comment]
@S-PADMANABAN-2001 Thank you for providing your insight but it is not required as of now.
