### ISSUE TITLE
Multpile Typos error

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [swapnilsparsh/30DaysOfJavaScript#1394]
Hey @swapnilsparsh,
I found typos in some scripts. 
For ex- Typing Platform/script.js - line 7,51...  "timming" should be "timing" + others.
I would like to fix them, Kindly assign this issue to me under GSSOC'24 label and the correct level.
Best Regards,
Nikhil Verma

**Comment by swapnilsparsh** [comment]
@NIKHIL0VERMA All the best 👍🏻
