### ISSUE TITLE
Adding New Project : Image Editor 

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1395]
### Is your feature request related to a problem? Please describe.

Users often find it difficult to find good Image editing websites for free.

### Describe the solution you'd like.

The Image Editor Extension would allow the users to edit their images, by adjusting the following features:
<ul>
<li>Brightness </li>
<li>Saturation</li>
<li>Contrast</li>
<li>Inversion</li>
<li>Blur</li>
<li>Flip</li>
<li>Rotate</li>
</ul>
The users will also be able to download the edited version of their images.

### Describe alternatives you've considered.

- None -

### Add any other context or screenshots about the feature request here.

The extension should have excellent working, with all the features working roperly, otherwise there might be a problem, in rocessing the image. Also, the UI must be clean, thus ensuring a great User Experience. The feature is trying to give the users the license to edit their images without having to test hundreds of apps, just through an extension. It'd definitely allow the user to save their time and efforts.

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
