### ISSUE TITLE
Title: Adding magic 8 ball game

### ISSUE THREAD

**Issue by anushkaaa34** [swapnilsparsh/30DaysOfJavaScript#1396]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like.

I would like to add a game Magic 8 balls, in which user can grab the 8 ball, ask it a question, shake it, and have the 8 ball respond with a somewhat enigmatic, somewhat applicable answer. It is an easy project , a newbie to JS can start with

### Describe alternatives you've considered.

I didn't found this game on website so I thought to share it

### Add any other context or screenshots about the feature request here.

@swapnilsparsh kindly assign me this issue

**Comment by tanishkaa08** [comment]
i would like to work in this project. please assign me this issue.

**Comment by swapnilsparsh** [comment]
@anushkaaa34 Thank you for providing your insight but it is not required as of now.
