### ISSUE TITLE
[DOCS] Grammar and Clarity Improvements Needed in Contributing Guidelines (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by thevijayshankersharma** [swapnilsparsh/30DaysOfJavaScript#1397]
### Description

The contributing guidelines in the `CONTRIBUTING.md` file need some attention to improve grammar and clarity. This issue is created to address the following areas for enhancement:

1. Correcting grammatical errors.
2. Enhancing clarity and readability for smoother understanding.
3. Ensuring consistency in language usage throughout the document.

**Comment by swapnilsparsh** [comment]
@thevijayshankersharma Thank you for providing your insight but it is not required as of now.
