### ISSUE TITLE
Title: Assign me the issue

### ISSUE THREAD

**Issue by PriyankaRaskhit** [swapnilsparsh/30DaysOfJavaScript#1398]
### Which pre-existing JavaScript project will you be working on?

I want to work on Quiz App project.

### Describe your enhancement/improvement

I want to make Quiz App project more attractive.
Making it more engaging to the users 

### Anything you need to say to the Reviewers

Please assign this task to me.
I am GSSOC'24 Contributor.

**Comment by swapnilsparsh** [comment]
@PriyankaRaskhit Thank you for providing your insight but it is not required as of now.
