### ISSUE TITLE
Title: Pagination indicator tells on which page the user is browsing .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [swapnilsparsh/30DaysOfJavaScript#1399]
### Is your feature request related to a problem? Please describe.

No actually is is not related to any problem but it help user to use pagination feature with its full potential .

### Describe the solution you'd like.

This can be done by changing some code in css and js file .

### Describe alternatives you've considered.

Alternatives me be to show the user in the form of text .

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-16 155041](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/118350936/dec91af9-c7f8-4bc9-8824-40ca6d981041)

**Comment by swapnilsparsh** [comment]
@Ayushmaanagarwal1211 Thank you for providing your insight but it is not required as of now.
