### ISSUE TITLE
News Website using api in Javascript

### ISSUE THREAD

**Issue by Jyo561** [swapnilsparsh/30DaysOfJavaScript#140]
GSSoC22

**Comment by swapnilsparsh** [comment]
@Jyo561 If you want to add your project to the repo then kindly don't open issues, you can do it by directly making a PR

**Comment by Jyo561** [comment]
ok

**Comment by Jyo561** [comment]
Please label this issue under GSSoC22

**Comment by swapnilsparsh** [comment]
#253
