### ISSUE TITLE
Issues with box width of certain project names

### ISSUE THREAD

**Issue by anvithagowda098** [swapnilsparsh/30DaysOfJavaScript#1406]
### What happened?

Width and height of certain text boxes of the project names are not rightly positioned or text has not been aligned properly. Same has been attached here showing differences between an ideal text box and textbox with an issue.
<img width="466" alt="Screenshot 2024-05-16 at 8 34 15 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/169017722/a0912aea-b7c7-46f9-80e8-a9414edf60bd">
<img width="472" alt="Screenshot 2024-05-16 at 8 34 22 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/169017722/549d4bfa-8745-4217-9522-3905237288f2">

### How can we reproduce this bug?

UI and UX can be better.

### Urgency (Optional)

Raising this under GSSoC '24. Please do consider this at the latest.

**Comment by swapnilsparsh** [comment]
@anvithagowda098 Thank you for providing your insight but it is not required as of now.
