### ISSUE TITLE
Title: Improve UI

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1407]
### Which pre-existing JavaScript project will you be working on?

113 - Minesweeper Game

### Describe your enhancement/improvement

Enhance the UI of the Minesweeper Game, to give a more vintage and classic game experience, like it used to be in Windows XP. Also, I'll implement Glassmorphism effect in order to provide a great User Experience.

### Anything you need to say to the Reviewers

Kindly assign me this issue under GSSoC '24.

### Add any other context or relevant screenshots about the enhancement here.

Below is a sample of the UI enhancements I want to make to make it visually apealing as well as to provide a great user experience.

![Screenshot 2024-05-16 204137](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138088550/5cd62855-169d-4ad0-a4c3-3ad7525ac4e1)

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now.
