### ISSUE TITLE
Add Guessing the Number game

### ISSUE THREAD

**Issue by varisha-025** [swapnilsparsh/30DaysOfJavaScript#141]
Add a game in which we have to guess the number randomly generated

**Comment by varisha-025** [comment]
Hey @swapnilsparsh . Can i work on this issue ?

**Comment by kalashvasaniya** [comment]
Hey assign this to me!

**Comment by swapnilsparsh** [comment]
@kalashvasaniya 
Don't open new issues by just adding your projects in this repo, you can directly make a PR if you have some JS project with you that is not yet on the website.
Good Luck 👍🏻
