### ISSUE TITLE
Title: Tracking High score in simon game [58]

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1414]
### Which pre-existing JavaScript project will you be working on?

i would like to work on Simon Game - 58. 

### Describe your enhancement/improvement

I would like to add an improvement where the game will automatically track your high-score and keep it stored.

before - no highscore
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/53d91f34-9a1a-4616-a7bf-006dbcfe714d)

after(for reference)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/a3648cb8-eeaa-479b-b329-202d23df202b)

I would like to work on this enhancement. please assign this issue to me under GSSOC'24.

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba All the best 👍🏻

**Comment by Dhruv-Gaba** [comment]
Sure. Do you also want me to track the current score?

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba yes and don't change anything else.

**Comment by ParthNakum21** [comment]
Hello @swapnilsparsh, I'm interested in contributing to the project by implementing current score and high score functionality. Could you please assign this task to me?

**Comment by shivathmikavemula** [comment]
hello @swapnilsparsh , I'm interested in contributing to the project. Could you please assign this task to me?

**Comment by shivathmikavemula** [comment]
Hello
As I'm in the beginner stage of coding. Can you suggest me some projects?
Thanking you
