### ISSUE TITLE
Title: SlideMaster Puzzle(NEW GAME)

### ISSUE THREAD

**Issue by pani2004** [swapnilsparsh/30DaysOfJavaScript#1415]
### Is your feature request related to a problem? Please describe.

The Tile Slider Puzzle, also known as the sliding puzzle, sliding block puzzle, or sliding tile puzzle, is a combination puzzle that challenges a player to slide pieces along certain routes (usually on a board) to establish a certain end-configuration. The game is often made up of a 3x3 grid where 8 tiles are numbered from 1 to 8, and one slot is left empty, allowing the adjacent tiles to be moved into the empty space.

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

**Comment by pani2004** [comment]
@swapnilsparsh Please assign me this I can add a new game to the repo!

**Comment by swapnilsparsh** [comment]
@pani2004 Thank you for providing your insight but it is not required as of now.
