### ISSUE TITLE
Title: Enhancing the search button in weather app 

### ISSUE THREAD

**Issue by ayush-848** [swapnilsparsh/30DaysOfJavaScript#1416]
### Which pre-existing JavaScript project will you be working on?

I will be working on the weather app

### Describe your enhancement/improvement

The search button is not round. I will make it into a proper circle and will add hover effect to it

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/126975547/e4b2f84b-477d-49a3-8f72-a381d2de71f9)

**Comment by ayush-848** [comment]
@swapnilsparsh please assign this issue to me. I am a GSSoC'24 contributor.

**Comment by swapnilsparsh** [comment]
@ayush-848 Thank you for providing your insight but it is not required as of now.
