### ISSUE TITLE
[Bug Title here]  01 - Drum kit keys. Unresponsive animation on long press. 

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1417]
### What happened?

Description
When you long press a key in the drum kit, it gets stuck, and the striking animation remains visible even after the key is released.

### How can we reproduce this bug?

On long press, the key animation gets stuck and remains visible even after the key is released. the animation is expected to disappear when the key is released but it does not happen.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/7ee5e4bc-c123-4371-a9e0-dc9509997c86

I would like to work on the above stated issue. please assign this issue to me under GSSOC'24.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba All the best 👍🏻
