### ISSUE TITLE
Title: Shell game

### ISSUE THREAD

**Issue by Tamilkumaran17** [swapnilsparsh/30DaysOfJavaScript#1418]
### Is your feature request related to a problem? Please describe.

A ball is hidden under one of three bowls, which are then shuffled. The player must find the bowl containing the ball and guess its position after the shuffle. It's a fun and challenging game of observation and memory.

### Describe the solution you'd like.

The user needs to find the ball where it was kept in the three balls.

### Describe alternatives you've considered.

NA

**Comment by swapnilsparsh** [comment]
@Tamilkumaran17 All the best 👍🏻

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.
