### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Soumya6Tiwari** [swapnilsparsh/30DaysOfJavaScript#1419]
### What happened?

There is a typo in the name of the game

### How can we reproduce this bug?

![Screenshot_20240517_124928](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/117037441/764698a9-2c0a-41f1-ad9c-5cc0ed32022b)
 Here the name should be Tic Tac Toe.

### Urgency (Optional)

None

**Comment by Soumya6Tiwari** [comment]
@swapnilsparsh  kindly assign me this issue

**Comment by infinitechapters** [comment]
Hey!! I'll be glad if you assign this issue to me.. please !

**Comment by swapnilsparsh** [comment]
@Soumya6Tiwari There is no such issue

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/e0742c1c-c2f5-49af-b7e6-cf323607ff7c)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/69387608/b00d9fdc-91d4-4485-954c-af0f50274d2a)
