### ISSUE TITLE
Title 💯:  Add New Project "Breakout Game"

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1420]
### Which pre-existing JavaScript project will you be working on?

#1343 I am work in this project

### Describe your enhancement/improvement

I am adding Breakout Game. the game is to use the paddle to bounce the ball towards the bricks and destroy them. You win when all the bricks are destroyed. But if the ball falls below the paddle into the fiery pits of doom, you lose the game. The paddle has "zones" which bounce the ball in different angles. Try out the game and you will notice it. If the ball bounces at the center, it goes straight up. As it goes to the sides, it's angle and speed increase. This gives you a certain degree of control over the direction of the ball.
![Screenshot 2024-05-17 161106](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/2c601b80-724d-47cf-b46d-0143faa6cc78)

**Comment by codewithganeshhh** [comment]
Hello mr @swapnilsparsh Assign me for This ASAP !

**Comment by swapnilsparsh** [comment]
@codewithganeshhh Thank you for providing your insight but it is not required as of now.
