### ISSUE TITLE
Title: A click navigating to the game

### ISSUE THREAD

**Issue by NeerajaGurram** [swapnilsparsh/30DaysOfJavaScript#1421]
### Is your feature request related to a problem? Please describe.

i think it would to better if i enter into the game/link(in the corresponding card) by just clicking on the card rather than clicking the link icon. Just an easy navigation.

### Describe the solution you'd like.

i would make changes in html and js to do the following:
- on one click on the cards, it navigates to the corresponding tab/link in web page
- on double click on the cards, it navigates to the corresponding tab/link in mobile.

### Describe alternatives you've considered.

just making the same i.e; on one click on the cards, it navigates to the corresponding tab/link in web page for easier navigation
since for mobile it might not be a big issue as the screen is smaller it might be easy to click on the icon navigate to the tab.

### Add any other context or screenshots about the feature request here.

i would like to work on this , so please assign me this under gssoc and also label the issue with appropriate level .
thankyou.

**Comment by swapnilsparsh** [comment]
@NeerajaGurram Thank you for providing your insight but it is not required as of now.
