### ISSUE TITLE
Title: Text Highlighter(New Project)

### ISSUE THREAD

**Issue by Sindhuja-Nigam** [swapnilsparsh/30DaysOfJavaScript#1422]
### Is your feature request related to a problem? Please describe.

In today's digital age, students, researchers, and professionals frequently read and analyze large amounts of text online. Text highlighting and annotating lack efficiency in digital spaces, hindering comprehension and information retention across platforms.

### Describe the solution you'd like.

Highlighting important information can significantly improve comprehension and retention. 

### Describe alternatives you've considered.

NA

**Comment by swapnilsparsh** [comment]
@Sindhuja-Nigam Thank you for providing your insight but it is not required as of now.
