### ISSUE TITLE
Bug in password generator 

### ISSUE THREAD

**Issue by jennifereunice** [swapnilsparsh/30DaysOfJavaScript#1423]
### What happened?

here what happend is even if we give no numbers then it is generating the previously given nunber of characters in password.
But here what we expect is not generation of password and the pop up message of enter the no of characters.

### How can we reproduce this bug?

here what happend is even if we give no numbers then it is generating the previously given nunber of characters in password.
But here what we expect is not generation of password and the pop up message of enter the no of characters.

### Urgency (Optional)

Medium priority

**Comment by infinitechapters** [comment]
Hey!! I can give a try to this issue if you will assign this task to me. I'll be glad to do that.

**Comment by Tarungupta18** [comment]
assign me

**Comment by swapnilsparsh** [comment]
@jennifereunice All the best

**Comment by jennifereunice** [comment]
You have not assigned the level

**Comment by jennifereunice** [comment]
Heyy

**Comment by jennifereunice** [comment]
@swapnilsparsh i  kept pull request may i know 
why you did not merged the task i have completed
