### ISSUE TITLE
Title: Modify some Home Page Ui Design

### ISSUE THREAD

**Issue by Kalyan190** [swapnilsparsh/30DaysOfJavaScript#1424]
### Is your feature request related to a problem? Please describe.

I have work to ui design some modification in home. your search bar is title written not good. i have fix this issue. and also some hover effect change.

### Describe the solution you'd like.

I have fix the issue to see the modified ui. better than previous ui.

### Describe alternatives you've considered.

I have design best look to see your website.

**Comment by swapnilsparsh** [comment]
@Kalyan190 Thank you for providing your insight but it is not required as of now.
