### ISSUE TITLE
Title:  Adding Guess The Shape Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1426]
### Which pre-existing JavaScript project will you be working on?

The player will tell the shape formed using dots.
Options are given in the game.
If player reaches to 10 points will win the game.
If player looses all the 5 lifes will lose the game.

### Describe your enhancement/improvement

**The player will tell the shape formed using dots.
Options are given in the game.
If player reaches to 10 points will win the game.
If player looses all the 5 lifes will lose the game.
Displaying the current score of the player.
Implementing a graphical user interface (GUI) for a more interactive experience.
Adding a background music so that user will not bored from the game as this game is for minded people.**

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot 2024-05-18 090713](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/cac69c30-b02b-420f-9ea3-d86aacce3ab3)

**Comment by swapnilsparsh** [comment]
@codewithganeshhh All the best 👍🏻

**Comment by Gauranshgoel123** [comment]
please assign me this! 
@swapnilsparsh @codewithganeshhh

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by katarianikita2003** [comment]
Hello @swapnilsparsh  , I want to work on this issue. Can you please assign it to me?
