### ISSUE TITLE
Title: Add a project 

### ISSUE THREAD

**Issue by adityakishore25** [swapnilsparsh/30DaysOfJavaScript#1428]
### Which pre-existing JavaScript project will you be working on?

1. This game will ask the user to guess a number between 1 and 100 within a fixed number of attempts. 

### Describe your enhancement/improvement

In this game user is required to guess  number between 1- 100 in 10 attempts and after each guess the user will get to know that the number which to be guessed in smaller of larger to the last guessed number.
In attaching the screenshot of the game UI :
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/107037851/6d43633e-d42a-4ea0-9a28-1cdc689615b0)
  

### Anything you need to say to the Reviewers

Assign me this issue under GSSoC'24.

**Comment by adityakishore25** [comment]
@lpizzinidev assign me this issue, I want to work on it unsder GSSoC'24.

**Comment by Paavni-Goyal** [comment]
I would want to work on this problem under GSSoC'24, therefore please assign it to me, @lpizzinidev.

**Comment by swapnilsparsh** [comment]
@adityakishore25 Thank you for providing your insight but it is not required as of now.
