### ISSUE TITLE
Adding a new JavaScript project Live codepen Editor

### ISSUE THREAD

**Issue by Arpcoder** [swapnilsparsh/30DaysOfJavaScript#1429]
A responsive website for Live Editor like Codepen, which helps developer to build a website, build test
cases to learn and debug.

It reflects the live changes made during the development of a website in real-time, incorporating HTML, CSS, and
JavaScript code updates

![Screenshot 2024-05-18 100206](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/100352419/26ef0250-9d09-45cb-82f5-be6b7316c8c2)

**Comment by swapnilsparsh** [comment]
@Arpcoder Thank you for providing your insight but it is not required as of now.
