### ISSUE TITLE
Title: Dice Game

### ISSUE THREAD

**Issue by Jagpreet153** [swapnilsparsh/30DaysOfJavaScript#1432]
### Is your feature request related to a problem? Please describe.

I will be adding a two player dice game the player whose number comes greater after shuffling wins

### Describe the solution you'd like.

It would be using html, css, js . It is a decent project for understanding the random generation concept of javascript

### Describe alternatives you've considered.

I would be adding images of dice along with the alert message of game over

### Add any other context or screenshots about the feature request here.

Kindly assign this task to me under GSSoC'24

**Comment by swapnilsparsh** [comment]
@Jagpreet153 Thank you for providing your insight but it is not required as of now.
