### ISSUE TITLE
Title: Escape room game 

### ISSUE THREAD

**Issue by NAVJOT-786** [swapnilsparsh/30DaysOfJavaScript#1436]
### Is your feature request related to a problem? Please describe.

🎮 Game Request
🎮 Game Request: Escape Room

Game Logic Description

Escape Room is a puzzle-solving game where players must solve a series of puzzles and find clues to escape from a locked room within a set time limit. The game challenges players' problem-solving and logical thinking skills with various types of puzzles, including riddles, code-breaking, and pattern recognition.

Initialization:

The game starts with an introductory screen explaining the rules and setting the story.
Players enter the escape room environment with interactive elements.

1: Player Interaction:

Players can click on different objects in the room to investigate and collect items.
Items can be used to solve puzzles and unlock new areas or clues.
A timer counts down the remaining time to escape.

2: Puzzle Solving:

The room contains multiple puzzles that must be solved in sequence.
Clues and items found in the room help to solve these puzzles.
Puzzles vary in type, including logic puzzles, pattern matching, and code-breaking.

3: Game End:

The game ends when the player successfully escapes the room or the timer runs out.
A summary screen shows the time taken and the puzzles solved.

### Describe the solution you'd like.

Point down the features
Features of the Game

1 : Interactive Environment:

Players can interact with various objects in the room.
Clues and items are hidden and require exploration to find.

2: Variety of Puzzles:

Different types of puzzles to solve, increasing in complexity.
Logical, pattern-based, and code-breaking puzzles.

3: Time Challenge:

Countdown timer to increase urgency and challenge.
Option to extend time with in-game actions or achievements.

4: Hint System:

Hints available for players who get stuck.
Limited hints to maintain the challenge.

5: Progress Tracking:

### Describe alternatives you've considered.

Progress is tracked, allowing players to see which puzzles have been solved.
Summary screen at the end showing performance and time taken.
I am contributing upon GSSOC24

**Comment by swapnilsparsh** [comment]
@NAVJOT-786 Thank you for providing your insight but it is not required as of now.
