### ISSUE TITLE
Title: Path Finder Puzzle

### ISSUE THREAD

**Issue by Harleen-786** [swapnilsparsh/30DaysOfJavaScript#1437]
### Is your feature request related to a problem? Please describe.

🎮 Game Request
🎮 Game Request: Path Finder Puzzle

Game Logic Description

Path Finder Puzzle is a grid-based game where players must find the shortest path from a start point to an end point. The game uses pathfinding algorithms like A* or Dijkstra's to teach and challenge players with increasing complexity.

1: Initialization:

The game board is a grid of cells.
Players can set the start and end points.
Obstacles can be placed on the grid to create barriers.

2: Player Interaction:

Players can click on cells to set the start point, end point, and obstacles.
A "Find Path" button initiates the pathfinding algorithm.

3: Pathfinding Algorithm:

The game uses pathfinding algorithms like A* or Dijkstra's to find the shortest path.
The algorithm visualizes the pathfinding process step by step.
4: Game End:

The game highlights the found path and displays the path length.
Players can reset the grid to try different configurations.

### Describe the solution you'd like.

Point down the features
Features of the Game

Interactive Grid:

Players can interact with the grid to set start and end points and place obstacles.

Algorithm Visualization:

Real-time visualization of the pathfinding algorithm.
Step-by-step animation showing how the algorithm explores the grid.

Difficulty Levels:

Multiple levels with varying grid sizes and obstacle densities.
Customizable grid for user-generated challenges.

Educational Aspect:

Explanation of the pathfinding algorithms used.
Option to switch between different algorithms to compare their performance.

### Describe alternatives you've considered.

Reset and Replay:

Button to reset the grid and start a new puzzle.
Option to save and share custom puzzles.

I am contributing From open source Gssoc24

**Comment by swapnilsparsh** [comment]
@Harleen-786 Thank you for providing your insight but it is not required as of now.
