### ISSUE TITLE
Snake Game[38] - The game starts on pressing any key (not just the arrow keys)

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1438]
### What happened?

Ideally the game should have started on pressing any one of the arrow keys, but instead the game starts when any random key is pressed and the snake starts going downwards on its own. This bug needs to be fixed and the snake should travel in the direction of the arrow keys.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/471f153a-0169-4011-b1cc-4745b51ee44b

### How can we reproduce this bug?

The snake starts moving downwards on pressing any random key.

I would like to work on this issue. Please assign this issue to me under GSSOC'24.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba Thank you for providing your insight but it is not required as of now.
