### ISSUE TITLE
[Bug] Movie Search App not working at ALL

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1439]
### What happened?

![Screenshot (273)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/4aa9b042-ad66-4531-8506-1bd3499d0961)
![Screenshot (274)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/fac82f56-ca86-457d-b943-1cfae243ea78)

None of the features of the Movie Search App is working. Not only the features but also the UI is somewhat unattractive. This application needs a complete rebuilt from scratch. I request the admin to label it under GSSoC level-3 problem and kindly assign it to me.

### How can we reproduce this bug?

The bug is inevitable. Its just present from the moment, the page is loaded. 

### Desktop Information (Optional)

OS - Windows 11 Home
Browser - Google Chrome
Device - Laptop

### Urgency (Optional)

High priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mondalsurojit** [comment]
@swapnilsparsh Hello sir, please assign me this under GSSoC-24

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any update on this ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh nearly done...will make a pr today or at max tomorrow
