### ISSUE TITLE
[Bug] Reaction Time App - boxes/circles not appearing within the screen

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1440]
### What happened?

![Screenshot (275)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/752b0100-a42f-448d-b48f-0e702e711e55)
![Screenshot (276)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/9db24f63-2365-4742-a1a5-3d44f2440505)
![Screenshot (277)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/f5081d6a-e9ec-4c44-b660-b061c5e5aca7)

Several times, the boxes/circles are not appearing within the 100vh/100vw screen size. User have to scroll any RANDOM length, which basically defies the main purpose of testing the reaction time.

### How can we reproduce this bug?

The bug can be reproduced, by simply playing for few times.

### Desktop Information (Optional)

OS: Windows 11 Home
Browser: Google Chrome
Device: Desktop

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit All the best 👍🏻 make it fit according to any screen size.

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any update on this ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh will take a bit more time, as currently I am engaged with the movie search app...
