### ISSUE TITLE
[Bug] Showing NaN instead of ERROR in the Calculator App

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1442]
### Desired Outcome

![Screenshot (280)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/74e171af-04e6-4e62-b595-6a8a5e6ae440)

### Present Situation

![Screenshot (278)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/7c77c29b-a1a3-4591-bf1e-45f568216ad5)

The calculator is displaying NaN (Not a Number - a datatype in JavaScript), instead of ERROR 

### How can we reproduce this bug?

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/1c630223-f8f6-4a78-a7c0-2ae91452f534

In this video, I have reproduced the bug in several ways.

### Desktop Information (Optional)

OS : Windows 11 Home
Browser : Google Chrome
Device : Laptop

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Please assign this to me

**Comment by Sara1428** [comment]
I want to work on this issue, please assign it to me

**Comment by swapnilsparsh** [comment]
@mondalsurojit Thank you for providing your insight but it is not required as of now.
