### ISSUE TITLE
Adding a navbar with proper categories on the top would enhance the project.

### ISSUE THREAD

**Issue by karishmaaa101** [swapnilsparsh/30DaysOfJavaScript#1443]
### Is your feature request related to a problem? Please describe.

The website would look more aligned if there **was a navbar with proper categories of the games.**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/6bc1b5fa-d470-4a17-8622-e56121ce50f3)

### Describe the solution you'd like.

I would like to add a **proper aligned navigation bar with categories** that would make me find the desired game more easily.
I am a GSSOC'24 contributor as well.

### Describe alternatives you've considered.

It would enhance the user experience.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/1413dc20-29a0-4c52-b154-960c80d9a7eb)

**Comment by karishmaaa101** [comment]
assign me this issue.

**Comment by swapnilsparsh** [comment]
@karishmaaa101 Thank you for providing your insight but it is not required as of now.
