### ISSUE TITLE
Title: Display day and date along with time in the digital clock. 

### ISSUE THREAD

**Issue by meetarora10** [swapnilsparsh/30DaysOfJavaScript#1444]
### Is your feature request related to a problem? Please describe.

A digital clock usually displays the date and day along with time. But in this particular digital clock only time is displayed.

### Describe the solution you'd like.

Day and date should also be displayed in the digital clock.

### Describe alternatives you've considered.

I can add date and day feature with proper styling to this digital clock.

**Comment by ISHWARISD** [comment]
Please assign the issue to me

**Comment by swapnilsparsh** [comment]
@meetarora10 Thank you for providing your insight but it is not required as of now.
