### ISSUE TITLE
[Bug] DOWN button & CHANGE button still working after Game Over in Tec]

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1445]
### What happened?

![Screenshot (283)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/c9362763-f90e-4816-a1a8-2b6d56d6d39f)
![Screenshot (284)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/dd19334f-72dc-4fa9-9a4c-d8dd91c07d32)

The DOWN ARROW button & the CHANGE/ROTATE button in the game is still working and is not disabled, when the game gets over. Moreover there is no reset button and the user has to refresh the whole game to play the game from beginning.

### How can we reproduce this bug?

Uploading Tetris Game - Google Chrome 2024-05-19 01-08-06.mp4…

I have shown in the video, how to reproduce the bug

### Desktop Information (Optional)

OS : Windows 11 Home
Browser: Google Chrome
Device: Laptop

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit All the best 👍🏻

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any update ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh Will be working on it...making a pr within 4 to 5 days
