### ISSUE TITLE
Title: Making a single Start/Stop button

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1447]
### Which pre-existing JavaScript project will you be working on?

Game #73 Casino Slot Machine Game
It is a game, that has a level selector, and two buttons 'START' which starts the slot, and 'STOP' which stops the slot.

### Describe your enhancement/improvement

Currently there are two buttons on the screen, one is 'START', another is 'STOP'.
When the slot is not running, the 'STOP' button is disabled, while when it is running, the 'START' is disabled, meaning that they are able to be pressed at mutually exclusive time.
What is propose it that, there be a single button, which can be used as both 'START' and 'STOP', depending on the running state of the game.

### Anything you need to say to the Reviewers

I think making a single button do both the things will be better for User Experience.

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/145102345/d67f037d-ef7a-4283-9331-8cd70926d8b9)
Instead of the two buttons, we can make a single one.

**Comment by KapsG23** [comment]
@swapnilsparsh , I really want to contribute and work on the enhancement in the project (Title :- Making a single start/stop button). Please assign me this project (enhancement).

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 All the best 👍🏻

**Comment by VijaySamant4368** [comment]
Please also add the level label.
