### ISSUE TITLE
Add Comprehensive Content on JavaScript Basics

### ISSUE THREAD

**Issue by Ramya-korupolu** [swapnilsparsh/30DaysOfJavaScript#1448]
### Description

Hey @animator, I am a GSSoC'24 Contributor. 

I would like to contribute by adding a comprehensive section on the basics of JavaScript. This will cover fundamental concepts such as variables, data types, functions, loops, and conditional statements. The content will be designed to provide beginners with a solid foundation in JavaScript, facilitating their understanding.

Kindly assign this issue to me.

**Comment by swapnilsparsh** [comment]
@Ramya-korupolu Thank you for providing your insight but it is not required as of now.
