### ISSUE TITLE
Prime Number Finder

### ISSUE THREAD

**Issue by Sindhu-2004** [swapnilsparsh/30DaysOfJavaScript#1450]
The main objective of this project is to allow users to input a number and check if it is a prime number or not. Prime numbers are those, that can only be divided by 1 and themselves.

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign it to me.

**Comment by Sara1428** [comment]
I want to work on this, please assign this to me

**Comment by Paavni-Goyal** [comment]
Could you please assign me this, I would like to contribute to the same.

**Comment by swapnilsparsh** [comment]
@Sindhu-2004 Thank you for providing your insight but it is not required as of now.

**Comment by Sindhu-2004** [comment]
Hi, may I know what does it mean that it is not planned or not required
now. As I have checked that the issue is not present and I reported it.
