### ISSUE TITLE
Percentage Calculator

### ISSUE THREAD

**Issue by Sindhu-2004** [swapnilsparsh/30DaysOfJavaScript#1451]
The percentage calculator is useful for students, and other needy people for solving basic mathematical problems related to percentages.

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign it to me.

**Comment by Sara1428** [comment]
I want to work on this. Please assign it to me.

**Comment by swapnilsparsh** [comment]
@Sindhu-2004 Thank you for providing your insight but it is not required as of now.
