### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by Sindhu-2004** [swapnilsparsh/30DaysOfJavaScript#1452]
The Body Mass Index (BMI) Calculator can be used to calculate BMI values based on height and weight. BMI is a fairly reliable indicator of body fatness for most people. By using this BMI calculator people can easily check if they are normal weight, overweight or underweight.

**Comment by LudoRNLT** [comment]
Hey! My friend @D-TheProgrammer and I would like to work on this. Can we get assigned to it?

We are computer science students and we have a course in which we have to make a contribution in a project. It would be great to do it with yours.

**Comment by swapnilsparsh** [comment]
@Sindhu-2004 Thank you for providing your insight but it is not required as of now.
