### ISSUE TITLE
Loan Calculator

### ISSUE THREAD

**Issue by Sindhu-2004** [swapnilsparsh/30DaysOfJavaScript#1453]
The Loan Calculator can be used to calculate the monthly EMI of the loan by taking the total amount, months to repay, and the rate of interest.

**Comment by LudoRNLT** [comment]
Hey! My friend @D-TheProgrammer and I would like to work on this. Can we get assigned to it?

We are computer science students and we have a course in which we have to make a contribution in a project. It would be great to do it with yours.

**Comment by swapnilsparsh** [comment]
@Sindhu-2004 Thank you for providing your insight but it is not required as of now.
