### ISSUE TITLE
Title: Footer 

### ISSUE THREAD

**Issue by keshavagr025** [swapnilsparsh/30DaysOfJavaScript#1454]
### Is your feature request related to a problem? Please describe.

I make a better footer on this project please assgin to me .

### Describe the solution you'd like.

I add Proper footer they give many detail for you link you github profile insta etc.

### Describe alternatives you've considered.

No this is a solution for it

### Add any other context or screenshots about the feature request here.

![2024-05-19 (1)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156112746/e0e37b53-14a2-4fe9-8483-adef3782958a)

**Comment by swapnilsparsh** [comment]
@keshavagr025 Thank you for providing your insight but it is not required as of now.
