### ISSUE TITLE
Title: Photoelectric Effect Simulation

### ISSUE THREAD

**Issue by Sara1428** [swapnilsparsh/30DaysOfJavaScript#1455]
### Photoelectric Effect Simulation

I want to add a new website where photoelectric effect simulation can be seen for a varied range of inputs given by user.
This idea seemed new to me from already existing projects.
Please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@Sara1428 Thank you for providing your insight but it is not required as of now.
