### ISSUE TITLE
An AI Chatbot with HTML, CSS, JavaScript, and an API Key

### ISSUE THREAD

**Issue by eiva078** [swapnilsparsh/30DaysOfJavaScript#1457]
It offers real-time responses powered by an AI API, enabling instant and relevant replies to user queries.
![Screenshot 2024-05-20 063931](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/100897650/bd6f7943-efe3-43e8-978a-6812bc55c336)
![Screenshot 2024-05-20 063959](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/100897650/da5b1a81-c17b-44c8-9b37-4bacab1d7d06)
![Screenshot 2024-05-20 064017](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/100897650/4beb17c5-205b-497f-8ddd-3d1db97e3140)

I would like to work on this issue. please assign it to me under GSSOC'24.

**Comment by Sanujkumar** [comment]
I want to work in this project please assign to me
