### ISSUE TITLE
Title:  add a sprite animation

### ISSUE THREAD

**Issue by Sypher0Dronzer** [swapnilsparsh/30DaysOfJavaScript#1458]
### Is your feature request related to a problem? Please describe.

I want to add my project of sprite animation that i made using js and HTML Canvas

### Describe the solution you'd like.

I will add a file containing the my code along with the screenshot of my page and description on the home page that will direct it to my project page.

please asssign this issue to me @swa

### Describe alternatives you've considered.

If it doesn't work, I will try submitting a different project.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/83546205/433eece6-08cf-409c-a12f-de77c07598a5)

**Comment by swapnilsparsh** [comment]
@Sypher0Dronzer Thank you for providing your insight but it is not required as of now.
