### ISSUE TITLE
Title: Adding Animations on Loading and Scrolling

### ISSUE THREAD

**Issue by MHusain22** [swapnilsparsh/30DaysOfJavaScript#1460]
### Is your feature request related to a problem? Please describe.

Animations will make the UI of the website more enhanced.

### Describe the solution you'd like.

I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.

### Describe alternatives you've considered.

using vanilla CSS and Animations library

**Comment by swapnilsparsh** [comment]
@MHusain22 Thank you for providing your insight but it is not required as of now.
