### ISSUE TITLE
Title: Add a Flappy Bird Game

### ISSUE THREAD

**Issue by Priyanshu2631** [swapnilsparsh/30DaysOfJavaScript#1461]
### Is your feature request related to a problem? Please describe.

I want to add a flappy bird game project made using HTML,CSS,Javascript where you need to take the game object forward i.e. a bird using your cursor and save it from the randomly generated pipes across the screen and add a score.

### Describe the solution you'd like.

The user will get an increase in his score till the time the game object is surviving and running without getting hitted from the pipelines.

### Describe alternatives you've considered.

NA

**Comment by swapnilsparsh** [comment]
@Priyanshu2631 Thank you for providing your insight but it is not required as of now.
