### ISSUE TITLE
[Bug Title here] Link broken of social 

### ISSUE THREAD

**Issue by YadlaMani** [swapnilsparsh/30DaysOfJavaScript#1466]
### What happened?

When clicking the link of every page of the pages of Jatin Yadav it's redirecting to error page
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133841094/be004f0a-8214-483b-951e-1cfd997368ce)
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133841094/1852761c-e535-4994-9a7a-a5a68097f433)

### How can we reproduce this bug?

click on the Jatin Yadav text on any page

### Urgency (Optional)

High priority

**Comment by swapnilsparsh** [comment]
@YadlaMani Thank you for providing your insight but it is not required as of now.
