### ISSUE TITLE
Create a auto assigning issue workflow

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#147]
Issues will be assigned to 1 person only and it will be done on a first come first serve basis

- Greeting Action greets contributor  
- Self-assign using `/assign`
- Preventing rogue issue spammers by limiting the number of self-assigns (by default, 2)

**Comment by bartick** [comment]
I would like to work on this issue. Can I work on this??

**Comment by bartick** [comment]
I completed this task. Can please you tell me how can i open a 2nd PR in this repo. My 1st PR is still under review. 
If I try to do a push now it will get pushed into the 1st PR.

**Comment by swapnilsparsh** [comment]
#217
