### ISSUE TITLE
[Bug Title here] Duplicate car in game number 76-CarGame

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1470]
### What happened?

A duplicate car appears, which though cannot be hit by enemy cars, is still ann ugly display
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/145102345/1af9b965-3f7a-48ac-a50a-715e087585d3)

### How can we reproduce this bug?

Pressing Space key, the duplicate car appears on the right edge of the road

### Desktop Information (Optional)

OS: Windows
Browser: Firefox

### Urgency (Optional)

Low priority

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 All the best 👍🏻
