### ISSUE TITLE
Title: NSFW toggle for jokes

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1472]
### Which pre-existing JavaScript project will you be working on?

Project number 15, Joke Generator

### Describe your enhancement/improvement

The project is fine in itself, there is just the thing that some of the jokes are NSFW, and there is not an option to toggle them.
I would like to add an option whether or not to show NSFW jokes.

### Anything you need to say to the Reviewers

A lot of Dark humor jokes, jokes about sex, and more. I don't think all jokes are suitable for all.

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 Thank you for providing your insight but it is not required as of now.
