### ISSUE TITLE
Title: Improve the UI of the theme toggle button. I want to contribute under GSSOC' 24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [swapnilsparsh/30DaysOfJavaScript#1473]
### Which pre-existing JavaScript project will you be working on?

I have worked on many JS projects and would like to contribute in this one as well. 

### Describe your enhancement/improvement

the button looks quite big and a bit unprofessional. So I want to improve the UI of the button rendering it a professional and appealing look.

**Comment by swapnilsparsh** [comment]
@ParnaRoyChowdhury777 Thank you for providing your insight but it is not required as of now.
