### ISSUE TITLE
Title: Scientific calculation

### ISSUE THREAD

**Issue by eiva078** [swapnilsparsh/30DaysOfJavaScript#1475]
### Which pre-existing JavaScript project will you be working on?

Calculator

### Describe your enhancement/improvement

The enhancement aims to upgrade the existing calculation functionalities from simple arithmetic operations to scientific calculations.

### Anything you need to say to the Reviewers

It allows to easily switch between simple and scientific calculation modes.

### Add any other context or relevant screenshots about the enhancement here.

Please assign this issue to me under GSSOC'24 @swapnilsparsh

**Comment by vipinmishra0852** [comment]
I want to work on this project. Please assign this project to me I'm proficient in HTML, CSS, JAVASCRIPT, and REACT  and made various projects and want to contribute to your amazing project looking forward to your response @eiva078

**Comment by PoojaGadagi08** [comment]
Hello @swapnilsparsh  sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by swapnilsparsh** [comment]
@eiva078 Thank you for providing your insight but it is not required as of now.
