### ISSUE TITLE
Title: Adding space invaders game 

### ISSUE THREAD

**Issue by chaanakyaaM** [swapnilsparsh/30DaysOfJavaScript#1476]
### Is your feature request related to a problem? Please describe.

Space invaders game using html and vanilla javascript

### Describe the solution you'd like.

I would like to add a JavaScript project as space invaders game.

### Describe alternatives you've considered.

This project would cover javascript topics such as:
- Game loop
- Keyboard input event
- Moving our enemies
- Collision detection
- Shooting bullets
and more

### Add any other context or screenshots about the feature request here.

would you assign it to me under gssoc'24.

**Comment by swapnilsparsh** [comment]
@chaanakyaaM Thank you for providing your insight but it is not required as of now.
