### ISSUE TITLE
Title: Enhancement of Weather-App

### ISSUE THREAD

**Issue by Vijayaa21** [swapnilsparsh/30DaysOfJavaScript#1479]
### Which pre-existing JavaScript project will you be working on?

Weather App

### Describe your enhancement/improvement

Now, you can access the 7-day weather forecast and check the temperature of your current location with a single click.

**Comment by swapnilsparsh** [comment]
@Vijayaa21 Thank you for providing your insight but it is not required as of now.

**Comment by swapnilsparsh** [comment]
@Vijayaa21 All the best 👍🏻

**Comment by meashishpatel** [comment]
I would like to work on this issue, please assign it to me.
