### ISSUE TITLE
Create a  dynamic formatted Contributors.md file

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#148]
The file should get updated automatically whenever a PR is merged using the GitHub Action/Workflow.

**Comment by shireenjain** [comment]
I would like to take up this issue.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by swapnilsparsh** [comment]
> I would like to take up this issue.

Update?

**Comment by Ash-KODES** [comment]
Can I work on this ? Its been more than 1 week 
@swapnilsparsh

**Comment by Ash-KODES** [comment]
If you dont mind! @shireenjain

**Comment by shireenjain** [comment]
> If you dont mind! @shireenjain

Actually I have my exams which is why it hasn't been done yet. I have started and would get it completed after a while.

**Comment by Ash-KODES** [comment]
> > If you dont mind! @shireenjain
> 
> Actually I have my exams which is why it hasn't been done yet. I have started and would get it completed after a while
okay,but do let me know if you want me to work on this:)

**Comment by swapnilsparsh** [comment]
@shireenjain Update?
