### ISSUE TITLE
Adding photo edtor project

### ISSUE THREAD

**Issue by Yashgabani845** [swapnilsparsh/30DaysOfJavaScript#1481]
one of my project on which i worked very hard
i wan to contribute in 30 days of js as a gssoc24 contributor 
it is photo editor
### it has certian fetaures
1. edit photo (enhance quality of image,brightness,roatate,flip it )
2. remove green screen from background 
3. enter text on image 

### here are few images of my editor
  **1. Home page**
  
![Screenshot (68)](https://github.com/amanjaiman1/Product_3D/assets/127788321/b0b212e5-e52d-4125-bed7-dbc15c8cb8e3)

**2. editor**
![Screenshot (70)](https://github.com/amanjaiman1/Product_3D/assets/127788321/8e5257d7-2e97-470c-b02a-58b694b39d52)

### please assign me this issue

**Comment by swapnilsparsh** [comment]
@Yashgabani845 Thank you for providing your insight but it is not required as of now.
