### ISSUE TITLE
[BUG] Footer overlapping with the Memory Matching Game. Does not display anything after winning.

### ISSUE THREAD

**Issue by karishmaaa101** [swapnilsparsh/30DaysOfJavaScript#1482]
### What happened?

The footer overlaps with the Memory Matching game.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/6c5d203d-5352-4dda-8a4a-50bdf274f185)

After winning the game, it does not display any message like "Congratulations!" or "Play Again".

I am a GSSOC'24 contributor.
I have followed all the guidelines.

### How can we reproduce this bug?

To reproduce the bug where the footer overlaps with the Memory Matching game and there's no message displayed after winning, we can check for:

- Check CSS Styling: Inspect the CSS styles for both the footer and the Memory Matching game elements. Ensure there are no conflicting styles or positioning issues that might cause overlap.

- Viewport Size: Resize the browser window to different dimensions and see if the overlap occurs at specific viewport sizes. This might indicate a responsive design issue.

- Inspect Game Logic: Review the JavaScript code responsible for handling the game, particularly the code related to displaying messages after winning. Ensure that there are no errors or conditions preventing the message from being displayed.

- Test Win Condition: Play the game and deliberately win by matching all the pairs. Note any unusual behavior or lack of message display upon winning.

- Check Console for Errors: Use the browser's developer tools to check for any JavaScript errors that might occur during gameplay. These errors could indicate the source of the problem.

- Debugging: Insert console.log statements or breakpoints in the JavaScript code to trace the flow of execution and identify any issues with displaying the winning message.

### Urgency (Optional)

High priority

**Comment by swapnilsparsh** [comment]
@karishmaaa101 All the best 👍🏻
