### ISSUE TITLE
[Bug]  The "extreme hard" level of the Maze game is too small in size.

### ISSUE THREAD

**Issue by karishmaaa101** [swapnilsparsh/30DaysOfJavaScript#1483]
### What happened?

The grid and the outline for the "extreme hard" level of the **Maze Game** is too small compared to other levels.
**Extreme Hard :** 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/701eac73-dd41-45fc-8fc0-234aeb33bc67)

**Medium Level :**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/cf205f7e-ca69-40d2-b26e-a757703c4625)

**Easy Level :**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/104766763/7fdd0d81-52ad-4294-8ac7-cb3bbbd1daeb)

### How can we reproduce this bug?

To reproduce the bug where the "extreme hard" level of the Maze game is too small in size, we can check:

- Check Level Settings: Review the settings or configuration for the "extreme hard" level in the Maze game. Ensure that the dimensions of the maze grid or the size of the maze itself are set appropriately for this difficulty level.

- Inspect Code: Examine the JavaScript code responsible for generating the maze for the "extreme hard" level. Look for any variables or parameters that define the size of the maze and make sure they are correctly configured.

- Test Different Devices and Resolutions: Try playing the "extreme hard" level on various devices with different screen resolutions. This will help identify if the issue is specific to certain screen sizes or aspect ratios.

- Review CSS Styling: Inspect the CSS styles applied to the maze elements. Ensure that there are no conflicting styles or fixed dimensions that might be causing the maze to appear smaller than intended.

- Debugging: Insert console.log statements or breakpoints in the JavaScript code to inspect the values of variables related to maze generation, such as width and height. This will help determine if the issue lies in how the maze dimensions are being calculated or applied.

- Cross-browser Testing: Test the "extreme hard" level on different web browsers to see if the issue is specific to a particular browser. Browser rendering differences or compatibility issues could affect the size of the maze.

- Compare with Other Levels: Play other difficulty levels of the Maze game and compare the size of the maze in the "extreme hard" level with those of other levels. This comparison can help identify any discrepancies in maze size.

### Urgency (Optional)

High priority

**Comment by swapnilsparsh** [comment]
@karishmaaa101 It is too small due to extreme hard level. Thank you for providing your insight but it is not required as of now.
