### ISSUE TITLE
Title:- Adding Chess Game

### ISSUE THREAD

**Issue by Ayush41** [swapnilsparsh/30DaysOfJavaScript#1484]
<b>This is a chess game where 2 people can play chess at a time in the same screen<b>

Demo:
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/74952106/2e2093e0-a5eb-4e50-b8ae-aec45ef093e2)

**Comment by Ayush41** [comment]
contributing under GSSoc'24 please label it as level 3 and gssoc

**Comment by PoojaGadagi08** [comment]
Hello @swapnilsparsh  sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by swapnilsparsh** [comment]
@Ayush41 Thank you for providing your insight but it is not required as of now.
