### ISSUE TITLE
Title: Anagram Checker Using Javascript

### ISSUE THREAD

**Issue by Damini2004** [swapnilsparsh/30DaysOfJavaScript#1488]
### Is your feature request related to a problem? Please describe.

The game generates two random words from a list of English words.
The game scrambles the letters of each word to create two anagrams.
The player is presented with the two anagrams and asked to unscramble them to form a valid English word pair.
If the player's guess is correct, they win the game.
If the player's guess is incorrect, they are given a hint about the possible word pair.
The player is given a certain number of attempts to guess the correct word pair. If they run out of attempts, they lose the game.

### Describe the solution you'd like.

The game involves generating two random words and scrambling their letters to create anagrams.
The player is asked to unscramble the anagrams to form a valid English word pair.
The game can be customized by changing the list of English words used to generate the anagrams.
The game can be implemented using a programming language such as Javascript.
The game can be used as a fun and educational way to teach players about anagrams and English vocabulary.
The game can be extended by adding additional features such as scorekeeping, time limits, or multiple rounds.
The game can be adapted for different age groups and skill levels by adjusting the length and difficulty of the words used to generate the anagrams.
The game can be played by a single player or in a multiplayer setting, where each player takes turns guessing the correct word pair.
The game can be integrated with a dictionary API or database to validate the player's guesses and provide hints.
The game can be made more challenging by increasing the number of anagrams or by adding a time limit for each guess.

### Describe alternatives you've considered.

Sure, here are some alternative approaches to building an anagram checker app:

Sorting characters: One approach is to sort the characters in each input string and compare the sorted strings to see if they are anagrams of each other. This approach is simple and efficient, but it may not be suitable for strings with non-alphanumeric characters or strings that contain spaces.
Character frequency count: Another approach is to count the frequency of each character in each input string and compare the frequency counts to see if they are anagrams of each other. This approach can handle strings with non-alphanumeric characters and spaces, but it may be less efficient than the sorting approach for large strings.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119414762/9b920e21-ab8f-4f2a-a39c-46ae9a22f745)

**Comment by PoojaGadagi08** [comment]
Hello  @swapnilsparsh sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by swapnilsparsh** [comment]
@PoojaGadagi08 Thank you for providing your insight but it is not required as of now.
