### ISSUE TITLE
Add the Similar web App like Postman (Pure JavaScript)

### ISSUE THREAD

**Issue by singhkunal01** [swapnilsparsh/30DaysOfJavaScript#149]
### WHAT I WANT TO DO?
Hey @swapnilsparsh this is Kunal singh , GSsOC'2022 particiapant and i want to add a project made by me using JavaScipt's fetch API.

### DESCRIPTION

- This will works like More similar to postman with less functions and only two methods GET/POST by which we can Fetch the data from any API

**_Thank You_**

**Comment by singhkunal01** [comment]
Hi @swapnilsparsh  in how much time I can do it ? Is there any specific time to do this ,because I'm going to start this.

**Comment by swapnilsparsh** [comment]
> Hi @swapnilsparsh Firstly Thanks a lot for assigning me.. and please tell me in how much time I can do it ? Is there any specific time to do this ,because I'm going to start this.

No specific time, take your time
(Max 3 days)

**Comment by singhkunal01** [comment]
hey @swapnilsparsh after cloning the project it shows that README file has deleted m should i make new one for my project or what can i do ?

**Comment by swapnilsparsh** [comment]
> 1. hey @swapnilsparsh after cloning the project it shows that README file has deleted m should i make new one for my project or what can i do ?
> 2. Is it mendatory that we need to deploy the final result on NETLIFY ?

Readme should not be deleted as it is available on the repo
You don't need to deploy the project on Netlify.

**Comment by swapnilsparsh** [comment]
#158
