### ISSUE TITLE
Title: Save option in Drawing pad project

### ISSUE THREAD

**Issue by Mediboyina** [swapnilsparsh/30DaysOfJavaScript#1492]
### Which pre-existing JavaScript project will you be working on?

The Drawing Pad Project is a JavaScript-based application that allows users to draw various shapes and lines on a canvas using different tools and colors.This drawing pad lacks save button.

### Describe your enhancement/improvement

The enhancement involves adding a Save button to the Drawing Pad interface. When clicked, this button will allow users to save their drawings as images directly onto their system. This feature will enable users to preserve their creations for future reference or sharing.

### Anything you need to say to the Reviewers

Please assign me this, I would like to solve it.

**Comment by swapnilsparsh** [comment]
@Mediboyina Thank you for providing your insight but it is not required as of now.
