### ISSUE TITLE
Overlapping Elements in Countdown Timer

### ISSUE THREAD

**Issue by Mediboyina** [swapnilsparsh/30DaysOfJavaScript#1499]
### What happened?

The Countdown Timer and Set Your Timer elements are overlapping on certain screen sizes.I expect the Countdown Timer and Set Your Timer elements to be positioned correctly without any overlap, ensuring readability.

### How can we reproduce this bug?

To reproduce the bug, accessing the Countdown Timer feature on devices with smaller screens or specific viewport sizes will help. The expected behavior is that the Countdown Timer and Set Your Timer elements should be positioned correctly without overlapping, ensuring clear visibility for users. To address the issue of elements overlapping in the Countdown Timer, adjustments will be made to their positioning or spacing.

### Desktop Information (Optional)

![Screenshot (337)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/107784738/f8654507-dae1-466a-b630-22e319c9a0e1)
f8a12a2f1)

### Urgency (Optional)

None

**Comment by Khushico** [comment]
i have good experience of solving these type of bugs because i have practiced a lot in this area and i am new to open source but i would really like to work on this ! It would be helpful if you assign me this issue

**Comment by swapnilsparsh** [comment]
@Mediboyina No issue is assigned to you related to this PR.
