### ISSUE TITLE
Issue/PR Auto Labeler  

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#150]
- ### Types :
    - Labels issues based on keywords found in Issue/PR
      - Action deprecated, so [Bot here](https://github.com/marketplace/keywordlabeler) *(Recommended)*
    - Labels PRs based on extension of file changed
      - [Action here](https://github.com/marketplace/actions/auto-label-action)  
  - Labels PRs based on branch  
    - [Action here](https://github.com/marketplace/actions/label-mastermind)
    
- ### On PR close
  - Finds & closes any linked issues to the PR
      - Example Workflow :  
      
- ### Close Stale Issues
  - Marks & closes stale issue after a pre-stipulated time.
      - [Action here](https://github.com/marketplace/actions/close-stale-issues)
        or
      - [Bot here](https://github.com/marketplace/stale) *(Recommended)*

**Comment by swapnilsparsh** [comment]
> Is this for GSSOC22. If then I could work on it.

Good Luck 👍🏻

**Comment by HarshKumarChoudary** [comment]
I created a PR @245
Please review and merge it.
