### ISSUE TITLE
Title: improve the BMI Calculator visual appeal and alignment

### ISSUE THREAD

**Issue by eiva078** [swapnilsparsh/30DaysOfJavaScript#1500]
### Which pre-existing JavaScript project will you be working on?

Body Mass Index Calculator

### Describe your enhancement/improvement

To improve the website's visual appeal and alignment, we will optimize the layout for consistent spacing and responsiveness across all devices. Enhancements include updating typography and color schemes for better readability. Content alignment will be refined for a clean, professional look.

### Add any other context or relevant screenshots about the enhancement here.

Sir, I would like to work on this issue, please assign this to me under GSSOC 24.

**Comment by swapnilsparsh** [comment]
@eiva078 Thank you for providing your insight but it is not required as of now
