### ISSUE TITLE
Title: Improve the ui and features of the note taking app

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [swapnilsparsh/30DaysOfJavaScript#1501]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

- The current overflow ui of the note card is not attractive, so improve the ui of the note cards by adding hover effects etc.
- Add search functionality
- Allow users to add title for each note.
- Display a seperate form for type note details as pop up

Kindly please assign this issue to me to add these features under gssoc

### Describe alternatives you've considered.

NA

**Comment by swapnilsparsh** [comment]
@DharshiBalasubramaniyam Thank you for providing your insight but it is not required as of now
