### ISSUE TITLE
Flappy Bird Game

### ISSUE THREAD

**Issue by Sindhu-2004** [swapnilsparsh/30DaysOfJavaScript#1502]
Flappy Bird is an endless game that involves a bird that the player can control. The player has to save the bird from colliding with the hurdles like pipes. Each time the bird passes through the pipes, the score gets incremented by one. The game ends when the bird collides with the pipes or falls down due to gravity.

I would like to work on this issue can you please assign me this

**Comment by swapnilsparsh** [comment]
@Sindhu-2004 Thank you for providing your insight but it is not required as of now
