### ISSUE TITLE
Title: Alphabet Clicker Game

### ISSUE THREAD

**Issue by MohanaSrinivas** [swapnilsparsh/30DaysOfJavaScript#1503]
### Is your feature request related to a problem? Please describe.

I Want To Add New Javascript Game

### Describe the solution you'd like.

Just Clicking The Alphabets Given To You

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-17 084516](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/128175768/63ff1014-dd5a-4f7c-ad1f-4fc277bf4fd4)

**Comment by swapnilsparsh** [comment]
@MohanaSrinivas Thank you for providing your insight but it is not required as of now
