### ISSUE TITLE
Title: Realtime clock

### ISSUE THREAD

**Issue by MohammadAsiya** [swapnilsparsh/30DaysOfJavaScript#1507]
### Is your feature request related to a problem? Please describe.

I want to add a clock made with javascript

### Describe the solution you'd like.

A realtime clock which shows the time.

### Describe alternatives you've considered.

This clock looks like a physical clock .

### Add any other context or screenshots about the feature request here.

![Screenshot (255)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/121110715/9ff3eb07-1711-4701-b925-2e609c42a520)

**Comment by RahaneSayali** [comment]
Assign this to me @MohammadAsiya

**Comment by swapnilsparsh** [comment]
@MohammadAsiya Thank you for providing your insight but it is not required as of now
