### ISSUE TITLE
The game doesn't end, remains active [94 - guess word]

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1509]
### Description
Even when we lose all our lives, the game doesn't end. we can continue to play even after losing all our lives until we win. the game should ideally restart when we lose all our lives.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/0bea87f7-e33c-418b-890a-0b6dcef214e6

### How can we reproduce this bug?

After exhausting all our lives in the game, the game should end, instead of remaining active.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba All the best 👍🏻
