### ISSUE TITLE
The background of few cards doesn't load [99 - BlackJack Game]

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1510]
### Description
The background of certain cards doesn't load properly, only their number and suit loads. The screenshot of the issue is given below.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/e350392b-6632-4988-b6f8-5841670ed26c)

### How can we reproduce this bug?

When we hit new cards, certain cards are generated without any background.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba All the best 👍🏻
