### ISSUE TITLE
Adding Different Difficulty Levels in the Game [95-Whack a Mole]

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1512]
### Description
The default movement of the mole is very fast, and its very difficult to play it.  

### Solution
To resolve this issue we can add, different difficulty modes in the game, namely easy, medium and hard, that will decide the speed of mole.

### Describe alternatives you've considered.

Adding an easy mode to slow down the mole will help the beginners to play the game as well.

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/da89af9b-eba9-472f-92c6-31467650aca7

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba Thank you for providing your insight but it is not required as of now
