### ISSUE TITLE
Title: Adding 'play again' button [Pop the Balloons]

### ISSUE THREAD

**Issue by bristiHalder** [swapnilsparsh/30DaysOfJavaScript#1513]
### Which pre-existing JavaScript project will you be working on?

Pop the Balloons game

### Describe your enhancement/improvement

Adding a 'play again' button to the game, so the players can play without reloading the page.

**Comment by swapnilsparsh** [comment]
@bristiHalder Thank you for providing your insight but it is not required as of now
