### ISSUE TITLE
Title: Tower of Hanoi Game

### ISSUE THREAD

**Issue by Praneeth-2602** [swapnilsparsh/30DaysOfJavaScript#1515]
### Is your feature request related to a problem? Please describe.

The Tower of Hanoi is a classic puzzle game that involves moving disks from one tower to another, following specific rules. This project creates an interactive Tower of Hanoi game using HTML, CSS, and JavaScript. The game is designed to be both visually appealing and easy to play, making it an excellent educational tool for learning about recursion and algorithmic problem-solving.

### Describe the solution you'd like.

The desired Tower of Hanoi game should be an interactive and visually appealing puzzle implemented using HTML, CSS, and JavaScript. It should allow players to drag and drop disks between three towers, enforcing the rules of the game by permitting only valid moves. The game should dynamically render the state of the towers and disks, updating in real-time with each move and displaying a move counter. Customization options should enable players to select the number of disks, with the game being fully responsive to different screen sizes and touch inputs. Additionally, the game should detect the win condition, display a congratulatory message upon completion, and offer hints and instructions to assist players.

### Describe alternatives you've considered.

Alternatives Considered for Tower of Hanoi Game:

1. Keyboard Controls: Use keyboard inputs to move disks between towers, simplifying implementation but less interactive than drag-and-drop.

2. Text-Based Interface: A console-based version with typed commands, lightweight and versatile but lacks visual appeal.

3. Predefined Moves: Step-by-step solution guide for learning, reducing challenge but educating players on optimal strategies.

4. Touchscreen Gestures: Swipe gestures for moving disks on mobile devices, enhancing mobile experience but less precise than drag-and-drop.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-24 171419](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/137754636/03a50518-29ec-4f0e-a74d-1d16bfe06d74)

**Comment by Praneeth-2602** [comment]
Hello @swapnilsparsh sir,
I would like to contribute to this project under GSSOC'24.
Looking forward to your reply.

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 All the best 👍🏻

**Comment by aggrhythm** [comment]
@swapnilsparsh can you assign me this issue?

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.
