### ISSUE TITLE
 Enhancing the UI of weather app

### ISSUE THREAD

**Issue by PunamDahal** [swapnilsparsh/30DaysOfJavaScript#1516]
### Which pre-existing JavaScript project will you be working on?

Weather App

### Describe your enhancement/improvement

The current UI of the weather app lacks visual appeal. To provide a better user experience, I propose UI enhancements. This will involve updating the header, icons, backgrounds, and other functionalities as required. 

### Add any other context or relevant screenshots about the enhancement here.

As part of my contribution to GSSoC, I would like to be assigned this issue to work on enhancing the UI of the weather app.

**Comment by swapnilsparsh** [comment]
@PunamDahal Thank you for providing your insight but it is not required as of now
