### ISSUE TITLE
Title:  Random Joke Generator

### ISSUE THREAD

**Issue by surendar-05** [swapnilsparsh/30DaysOfJavaScript#1518]
### Is your feature request related to a problem? Please describe.

Lighten the mood: Providing a quick joke can help lighten the mood, relieve stress, or add some levity to a conversation or user experience.
Entertainment: Random jokes can be a simple form of entertainment, especially in situations where users might be waiting or looking for a brief distraction.

### Describe the solution you'd like.

Joke Database: Maintain a database or collection of curated jokes.
API Endpoint: Create an API endpoint that accepts parameters like category, rating, etc. to filter jokes.
Random Selection: Implement logic to randomly select a joke from the filtered set.
API Response: Return the randomly selected joke as the API response (e.g., JSON).
Client Integration: Develop a client application (web, mobile, or other) that calls the API endpoint, passing desired filters, and displays the returned joke.
Monitoring and Updates: Monitor API usage, performance, and regularly update the joke database.

### Describe alternatives you've considered.

Static Joke Data File: Instead of a database, store the jokes in a static data file (e.g., JSON, CSV) and load it into memory when the API server starts. This can be simpler for smaller joke collections but may not scale well and requires restarting the server for updates.
Third-Party Joke API: Utilize an existing third-party joke API service instead of building your own. This could save development time but may have limitations in customization, filtering, and quality control.

### Add any other context or screenshots about the feature request here.

![output1](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/103345824/e151929e-be6e-41c0-9831-a071f78b1917)

**Comment by surendar-05** [comment]
Heyy I want to work on this issue Assign this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@surendar-05 Thank you for providing your insight but it is not required as of now
