### ISSUE TITLE
Title: Poker game

### ISSUE THREAD

**Issue by Swarnav-Kumar** [swapnilsparsh/30DaysOfJavaScript#1520]
### Is your feature request related to a problem? Please describe.

This game is simplified and focuses on the basic structure and card dealing.

### Describe the solution you'd like.

I want to make a game :-Poker A card game that combines strategy, skill, and luck. 
1.The structure includes sections for two players and the community cards with a deal button.
2. Basic styling to center elements and style the cards.
3.Creates and shuffles a deck of cards.
4.Deals two cards to each player and five community cards.
5.Renders the dealt cards to the screen.
6.Uses setTimeout to simulate the stages of dealing the community cards (flop, turn, river).

### Describe alternatives you've considered.

1.The structure includes sections for two players and the community cards with a deal button.
2. Basic styling to center elements and style the cards.
3.Creates and shuffles a deck of cards.
4.Deals two cards to each player and five community cards.
5.Renders the dealt cards to the screen.
6.Uses setTimeout to simulate the stages of dealing the community cards (flop, turn, river).

**Comment by swapnilsparsh** [comment]
@Swarnav-Kumar Thank you for providing your insight but it is not required as of now
