### ISSUE TITLE
Title : Bubble Game

### ISSUE THREAD

**Issue by kkhushie** [swapnilsparsh/30DaysOfJavaScript#1524]
## What makes it special?

- Your reflexes and number recognition skills are put to the test.
- You have 60 seconds to pop as many bubbles as possible.
- Each time you pop a bubble, a new target number appears. Focus on popping bubbles with the current target number for bonus points!
- Easy to learn and perfect for players of all ages.

Screenshot : 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/111669586/2cfe109d-329e-4cea-8da5-fe835dd93597)

**Comment by swapnilsparsh** [comment]
@kkhushie All the best 👍🏻

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by swapnilsparsh** [comment]
@kkhushie Any update ?

**Comment by 143divya** [comment]
can you please assign this to me?
