### ISSUE TITLE
Title: Adding more colors to Levitate Board

### ISSUE THREAD

**Issue by sujal-98** [swapnilsparsh/30DaysOfJavaScript#1526]
### Which pre-existing JavaScript project will you be working on?

Levitate Board - It consists of a board of square tiles which upon hovering mouse on them acquires a color and then when the cursor is gone returns to their normal state

### Describe your enhancement/improvement

Previously it consists of a colors array with only 7 colors and adds one from them to the square tiles only but now I am adding a random color generator to it so it can utilize way more colors than before.

### Add any other context or relevant screenshots about the enhancement here.

Here is a video of the changes made -

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/117587914/e0730f10-6f5a-434c-abae-6b0330820cb0

**Comment by swapnilsparsh** [comment]
@sujal-98 Thank you for providing your insight but it is not required as of now
