### ISSUE TITLE
Title: Endless Color Changer

### ISSUE THREAD

**Issue by Manish15559** [swapnilsparsh/30DaysOfJavaScript#1527]
### Is your feature request related to a problem? Please describe.

``This project will be built entirely with HTML, CSS, and JavaScript.
> Creating a webpage that continuously changes its background color at regular intervals.

Benefits and Learning Outcomes -
- This project reinforces fundamental JavaScript skills such as functions, loops, and working with intervals.
- By changing the background color dynamically, learner gain hands-on experience with manipulating the DOM.
- Creating and linking separate HTML, CSS, and JavaScript files helps in understanding the modular approach to web development.
please assign this issue to me under GSSOC'24.

### Describe the solution you'd like.

none

### Describe alternatives you've considered.

none

**Comment by swapnilsparsh** [comment]
@Manish15559 Thank you for providing your insight but it is not required as of now
