### ISSUE TITLE
Title : Knife Thrower

### ISSUE THREAD

**Issue by sharmi4590** [swapnilsparsh/30DaysOfJavaScript#1528]
Hey @swapnilsparsh 
I have a project made using javascript, which I wanted to add in the website. It is a game called Knife Thrower in whi
In this game the user has to click on the knife and it will go to the board , if two knives collapse the game will end. It has 4 different levels and each level has different strategy. If a player loses a level it will automatically goto the first level. I am a GSSoC'24 contributor.

The features
![Screenshot (368)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/102676949/ee4e03a7-5ac3-48ad-8d3f-6981077b7136)

It has 4 levels and after clearing 1 level only the user can go to another level.
There will only be particular number of knives and it will decrease on each throw.
It will look as follow.
![Screenshot (369)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/102676949/1e0796cc-31d1-483b-8320-e8f5e003b5c2)

**Comment by swapnilsparsh** [comment]
@sharmi4590 Thank you for providing your insight but it is not required as of now
