### ISSUE TITLE
[Bug Title here] Rock paper scissors game page is not working

### ISSUE THREAD

**Issue by nagamukesh** [swapnilsparsh/30DaysOfJavaScript#1529]
### What happened?

i tried to search for rock,paper and scissors game
which is present but when I clicked on it, it did gave a 404 not found page
which I gues due to the page not present or not redirected properly

### How can we reproduce this bug?

search for rock,paper and scissors and click on it
you can see the error
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/112798996/d2d9cbea-ccc4-4a2f-b1b6-46a5172ea49b)

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@nagamukesh All the best 👍🏻

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by swapnilsparsh** [comment]
@nagamukesh Any update ?

**Comment by yasharth-0910** [comment]
Hello @swapnilsparsh since this issue was taking time, I would like to tell You that, I have already solved this bug, and it would be appreciated if you can assign this to me.

**Comment by yasharth-0910** [comment]
https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/143637324/8809d18b-6150-4040-b2d4-9c1062b535c3

Here it is, tested in my local environment, read to create a PR on your permission
