### ISSUE TITLE
Adding Birthday CountDown Timer

### ISSUE THREAD

**Issue by rajprem4214** [swapnilsparsh/30DaysOfJavaScript#153]
Adding a Birthday CountDown Timer That wishes on your birthday.
Please assign me this issue.
I m contributor at GSSoC'22.

**Comment by rv602** [comment]
hey @swapnilsparsh , Rajagopalan this side. I wish to make this birthday countdown timer.

I plan on displaying a heading saying "Countdown to your birthday" below which there is the countdown timer with days, hours, minutes and seconds displayed. The background is animated for birthday celebrations.

Below I am attaching a prototype for the same.

<img width="892" alt="Screenshot 2022-03-02 at 1 32 20 AM" src="https://user-images.githubusercontent.com/92572013/156240224-76767a93-c0e8-447a-bc4e-736fe09c6b1d.png">

**Comment by swapnilsparsh** [comment]
@rajprem4214 @rv602 Countdown Timer is already there on the [website](https://30daysofjs.netlify.app/16%20-%20Countdown%20Timer/index.html) so look after some other projects.
