### ISSUE TITLE
Title:  Custom Scrollbar

### ISSUE THREAD

**Issue by dhruv389** [swapnilsparsh/30DaysOfJavaScript#1530]
### Is your feature request related to a problem? Please describe.

I want to add custom scrollbar according to website theme.

### Describe the solution you'd like.

i add color  related to website color theme.

### Describe alternatives you've considered.

i add color  related to website color theme.

**Comment by swapnilsparsh** [comment]
@dhruv389 Thank you for providing your insight but it is not required as of now
