### ISSUE TITLE
[FEAT] : Redesign Project Cards for Enhanced Visual Appeal and Attractiveness

### ISSUE THREAD

**Issue by dhruv389** [swapnilsparsh/30DaysOfJavaScript#1531]
### Is your feature request related to a problem? Please describe.

The current design of the project cards is not visually appealing and fails to attract user attention. These cards need a redesign to improve aesthetics, engagement, and user experience.

### Describe the solution you'd like.

Project cards should have a modern, attractive design that captures user attention and enhances the overall visual appeal of the page.

### Describe alternatives you've considered.

- Ensure the new design is responsive and looks good on all devices (desktop, tablet, mobile).
- Maintain consistency with the overall website design and branding.
- Test the new design with users to gather feedback and make necessary adjustments.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/117587892/5c9c60fa-6b03-4e96-9eb4-47753d0bb50b)

**Comment by swapnilsparsh** [comment]
@dhruv389 Thank you for providing your insight but it is not required as of now
