### ISSUE TITLE
RPS game not found

### ISSUE THREAD

**Issue by krishan-07** [swapnilsparsh/30DaysOfJavaScript#1532]
#### Cant load Rps game through search 
<br>
The search is redirecting to wrong link i.e.<br>
https://30daysofjs.netlify.app/37%20-%20RPS%20(Rock,%20Paper,%20Scissors)%20Game/index.html <br>
The actual link should be <br>
https://30daysofjs.netlify.app/37%20-%20rps%20game/index.html<br>

### How can we reproduce this bug?

Search rps in the search bar, then click on the dropdown suggestion
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/164178782/a03645d0-dafb-4a7e-a783-c29b103b23b8)

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@krishan-07 There is already an issue opened for this
