### ISSUE TITLE
Title:  Add Animation Effect on Cards on scroll

### ISSUE THREAD

**Issue by Skb08** [swapnilsparsh/30DaysOfJavaScript#1533]
### Which pre-existing JavaScript project will you be working on?

It enhances the overall attractiveness.

### Describe your enhancement/improvement

By adding animation effects on scroll, cards will display zoom in and zoom out effects, making them more attractive.

### Anything you need to say to the Reviewers

You can see how it looks and works here: https://michalsnik.github.io/aos/

### Add any other context or relevant screenshots about the enhancement here.

link: https://michalsnik.github.io/aos/

**Comment by Skb08** [comment]
can you assign this to me under gssoc 2024 @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Skb08 Thank you for providing your insight but it is not required as of now
