### ISSUE TITLE
Title: Redirecting to the game page

### ISSUE THREAD

**Issue by YadlaMani** [swapnilsparsh/30DaysOfJavaScript#1534]
### Is your feature request related to a problem? Please describe.

I have seen the website it's a really cool website i was hovering over the games then i found out that we are redirected to game only when we click the chain icons it would good if we can redirect to the game when we click on the game card it self.

### Describe the solution you'd like.

I would like to add feature such that when the user clicks on the project card he directly goes to that card.

### Describe alternatives you've considered.

i would like to implement this feature

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133841094/653076ca-dc2d-4e3a-b7e6-62ba4cf37d66)

**Comment by swapnilsparsh** [comment]
@YadlaMani Thank you for providing your insight but it is not required as of now
