### ISSUE TITLE
Title: Adding a image 

### ISSUE THREAD

**Issue by YadlaMani** [swapnilsparsh/30DaysOfJavaScript#1535]
### Is your feature request related to a problem? Please describe.

I would like to add a image to the no project found page

### Describe the solution you'd like.

I think adding an animated image would make the website more engaging

### Describe alternatives you've considered.

i would like to work on this issue.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133841094/091a8b2c-a2da-43e0-83e3-44b846764870)
or  i can  create a custom text instead of that plain text there

**Comment by swapnilsparsh** [comment]
@YadlaMani Thank you for providing your insight but it is not required as of now
