### ISSUE TITLE
Title: Add Live Language Translator#1536

### ISSUE THREAD

**Issue by AdityaNair07** [swapnilsparsh/30DaysOfJavaScript#1536]
### Is your feature request related to a problem? Please describe.

A language translator is good, but a live language translator that translates each word the user inputs to user selected language is awesome. Not just a normal live language translator; it has the functionality to copy the inputted text and the translated text to the clipboard. As well as the functionality to listen to the inputted text and the translated text. 
To make the application usage easier, instructions are given at the bottom as well.

### Describe the solution you'd like.

When the user navigates to the live language translator application, a simple UI is presented. The user can select from various languages to translate from or to. Then the user can input the text he wishes to translate and the text translates right in front of the user word to word. The switch/swap button can be used to swap the input language and translation language. 

The user has the functionality to copy the inputted text and the translated text into the clipboard for later use. As well as the user can listen to the audio of the inputted text and the translated text. This makes the translation process more interactive and user friendly. 

New users can find instructions written at the bottom for easy usage.

### Describe alternatives you've considered.

Considering to increase the character intake in the input section.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-05-23 201153](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/96580997/eb9d6531-ed19-436d-bc50-f6653a9dda50)

**Comment by swapnilsparsh** [comment]
@AdityaNair07 Thank you for providing your insight but it is not required as of now
