### ISSUE TITLE
Feature:Riddle Generator

### ISSUE THREAD

**Issue by Coding-Charvi** [swapnilsparsh/30DaysOfJavaScript#1539]
### Is your feature request related to a problem? Please describe.

I want to add riddle generator

### Describe the solution you'd like.

Random riddle generator

### Describe alternatives you've considered.

NA

**Comment by Coding-Charvi** [comment]
Pls assign this feature to me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Coding-Charvi Thank you for providing your insight but it is not required as of now
