### ISSUE TITLE
Uneven Size of cards and overflowing out of the box [99 - BlackJack Game]

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1542]
### Description
The size of all the cards is highly uneven. All the cards are of different sizes, making it look bad. Also some cards are so big that the cards overflow the space provided for them and this again makes the presentation poor as shown in the screenshot.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/3e3d09a8-1fff-4a9e-9e18-3e8123698bf7)

### How can we reproduce this bug?

When we play the game and hit cards, the cards are of uneven sizes and they overflow from the space provided for them.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba Thank you for providing your insight but it is not required as of now
