### ISSUE TITLE
Title: Bingo game

### ISSUE THREAD

**Issue by suhanigupta23** [swapnilsparsh/30DaysOfJavaScript#1543]
### Is your feature request related to a problem? Please describe.

We can add bingo game as well.

### Describe the solution you'd like.

This bingo game will be built in HTML,CSS,Javascript.
1.We can first chose the number of players then BINGO tickets will be generated . 
2.Chances are held turn by turn and each player cuts a number form its own ticket (is similar number is in other players ticket then he/she also cuts it.)
3. As soon as a player completes (fills/cuts a whole line) out  of  horizontal row/ vertical column/ or diagonal line , the word formation for BINGO word starts.
4. The player whose BINGO word first forms is the winner.

### Describe alternatives you've considered.

bingo game can be added which consists of multiple players.

### Add any other context or screenshots about the feature request here.

<img width="738" alt="Screenshot 2024-05-27 at 11 30 19 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/144280247/a7a9eab3-cfd3-4cf4-b734-622581ffce9c">
<img width="472" alt="Screenshot 2024-05-27 at 11 32 45 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/144280247/f51ab1fc-1cf0-46aa-8591-0a294db8034a">

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the 30DaysOfJavaScript project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by swapnilsparsh** [comment]
@suhanigupta23 Thank you for providing your insight but it is not required as of now
