### ISSUE TITLE
Title:Rock-Paper-Scissors game 

### ISSUE THREAD

**Issue by SunayP** [swapnilsparsh/30DaysOfJavaScript#1544]
### Which pre-existing JavaScript project will you be working on?

I would like to add Rock-Paper-Scissors game, which created a good practice of concepts for me while learning Javascript.

### Describe your enhancement/improvement

1. Choose your move by clicking on one of the three buttons:
    Rock (👊)
    Paper (✋)
    Scissors (✌)
2. The computer will also make its move.
3.The winner is determined by the following rules:
    Rock crushes Scissors
    Scissors cuts Paper
    Paper covers Rock
4.The result of each round will be displayed:
    "YOU WIN" if you win the round
    "YOU LOSE" if you lose the round
    "IT'S A TIE" if both you and the computer choose the same move

### Add any other context or relevant screenshots about the enhancement here.

![RPS](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/157937147/90a69fce-97f1-4d18-9b6a-4f14376069c2)

**Comment by akarshi19** [comment]
please assign this issue to me under GSSOC'24

**Comment by swapnilsparsh** [comment]
@SunayP Thank you for providing your insight but it is not required as of now
