### ISSUE TITLE
Title : Candy Crush Saga game

### ISSUE THREAD

**Issue by Yashgabani845** [swapnilsparsh/30DaysOfJavaScript#1545]
### Description:
Integrate the popular Candy Crush game into our repository to enhance collaboration and entertainment within our development team. This addition will provide a fun and interactive break from coding sessions and encourage team bonding through friendly competition.

### Rules of the Game:

- Candy Crush is a match-three puzzle game where players swap colorful candies to form matches of three or more of the same color in a row or column. 
- Matches can be made horizontally or vertically, and successful matches clear those candies from the board. 
- The goal varies per level but typically involves achieving a certain score, clearing a specified number of candies, or completing other objectives within a limited number of moves.

### Technologies Used:

-  html
- css
- js

### Image:
![Screenshot (107)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127788321/5967e425-630e-4c13-a66f-abcbd91ead5d)

**Comment by Yashgabani845** [comment]
@swapnilsparsh  please assign me this issue i want add this game on this project

**Comment by swapnilsparsh** [comment]
@Yashgabani845 Thank you for providing your insight but it is not required as of now
