### ISSUE TITLE
Title: Slot machine

### ISSUE THREAD

**Issue by saketh-05** [swapnilsparsh/30DaysOfJavaScript#1548]
**This project is the logical working of a slot machine which is entirely built using HTML , CSS and JavaScript.**\

### What makes this project special?

- Simplicity and Accessibility to understand and play game
- Randomness and Thrilling feel will make you play more
- Trying to get Jackpot creates high level of excitement
- In Game rewards system is used to ensure player motivation
- This project will have good appearance

Screenshot:
![slot](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/134281589/30e0ff23-b5d5-44fa-9f99-d4ea2eab6991)

Please assign me this issue under GSSOC 2024

**Comment by swapnilsparsh** [comment]
@saketh-05 Thank you for providing your insight but it is not required as of now
