### ISSUE TITLE
Title: Unit Length converter

### ISSUE THREAD

**Issue by Saimanjari777** [swapnilsparsh/30DaysOfJavaScript#1549]
### Is your feature request related to a problem? Please describe.

I want to add unit length converter which converts meter to km etc.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/130165687/9604fd36-ed5c-44bb-91c7-045319455a3b)

### Describe the solution you'd like.

I would like to add simple JS Unit length converter which converts m to km, cm to m, km.
Please assign this issue to me @sw

### Describe alternatives you've considered.

none

**Comment by swapnilsparsh** [comment]
@Saimanjari777 Thank you for providing your insight but it is not required as of now
