### ISSUE TITLE
Modify the music player

### ISSUE THREAD

**Issue by SO1ee** [swapnilsparsh/30DaysOfJavaScript#155]
Hello @swapnilsparsh this is Soma Halder , GSsOC'2022 participant , I want work on your existing "Music player" project, as it is not properly designed
and it is not working properly as well . I want to fix these things and i want to make it perfect.
Thank you for your time!! and looking forward to work on it.

**Comment by SO1ee** [comment]
Thank  you for assigning

**Comment by swapnilsparsh** [comment]
> Thank you for assigning

Update?

**Comment by SO1ee** [comment]
Yes Sir ! i am working on probably by tomorrow i will create a PR.

**Comment by SO1ee** [comment]
Hello sir ! when i am trying to clone the repository a blank folder is creating locally . and i am getting the warning "clone succeeded, but  checkout failed" . Could you please tell me how to solve this issue.

**Comment by swapnilsparsh** [comment]
> 

Can you provide a screenshot of the error which you are facing with all the commands that you ran?

**Comment by swapnilsparsh** [comment]
> Hello sir ! when i am trying to clone the repository a blank folder is creating locally . and i am getting the warning "clone succeeded, but checkout failed" . Could you please tell me how to solve this issue.

Maybe your disk space is full and there is not space left to store the cloned project
Have a look [here](https://stackoverflow.com/questions/22041752/github-clone-succeeded-but-checkout-failed)
