### ISSUE TITLE
ADD TETRIS GAME

### ISSUE THREAD

**Issue by Gauranshgoel123** [swapnilsparsh/30DaysOfJavaScript#1550]
### Is your feature request related to a problem? Please describe.

I would like to add a JavaScript project 'THE TETRIS GAME' into this repository

### Describe the solution you'd like.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/121503835/44140b8f-0105-4cdb-8d5b-b96ccc0b9f19)

### Describe alternatives you've considered.

i have created this game using HTML,CSS,JS
pls assign me this under GSSOC 24

**Comment by swapnilsparsh** [comment]
@Gauranshgoel123 Thank you for providing your insight but it is not required as of now
