### ISSUE TITLE
Title: Update UI of light theme

### ISSUE THREAD

**Issue by AbhishiktaRay03** [swapnilsparsh/30DaysOfJavaScript#1551]
### Which pre-existing JavaScript project will you be working on?

N/A

### Describe your enhancement/improvement

![Screenshot 2024-05-28 130925](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127621443/2cf1b1ea-dfb9-4ab7-8f30-605e40c2ce1b)
 I want to update this colour scheme to a lighter one while in light mode. I believe it will look decent and pleasant on the eyes.

**Comment by swapnilsparsh** [comment]
@AbhishiktaRay03 Thank you for providing your insight but it is not required as of now
