### ISSUE TITLE
Title: Add game "Escape the Maze"

### ISSUE THREAD

**Issue by Aditi22Bansal** [swapnilsparsh/30DaysOfJavaScript#1556]
### Is your feature request related to a problem? Please describe.

This game will feature a player who has to navigate through a randomly generated maze to reach the exit. It's interactive, challenging, and can be very engaging.

### Describe the solution you'd like.

Step Points: Award points for each step the player takes in the maze.
Time Bonus: Give bonus points based on how quickly the player completes the maze.
Difficulty Bonus: Offer extra points for completing harder mazes.
Penalty for Wall Hits: Deduct points for hitting walls while navigating.

### Describe alternatives you've considered.

Treasure hunt
Parkour runner

### Add any other context or screenshots about the feature request here.

This game will feature a player who has to navigate through a randomly generated maze to reach the exit. It's interactive, challenging, and can be very engaging.

**Comment by swapnilsparsh** [comment]
@Aditi22Bansal Thank you for providing your insight but it is not required as of now
