### ISSUE TITLE
Title: add header section 

### ISSUE THREAD

**Issue by shahidhussain07** [swapnilsparsh/30DaysOfJavaScript#1557]
### Which pre-existing JavaScript project will you be working on?

30DaysOfJavaScript 

### Describe your enhancement/improvement

- website should have a proper header
- mode switch button should be on right corner
- search bar shoul be at the center
- title "30Days of JavaScript" should be left orner

**Comment by shahidhussain07** [comment]
I want to work on this. Please assign me this issue under GSSoC label. @swapnilsparsh.

**Comment by swapnilsparsh** [comment]
@shahidhussain07 hank you for providing your insight but it is not required as of now

**Comment by shahidhussain07** [comment]
That's okay and thanks for response
