### ISSUE TITLE
Add a memory game

### ISSUE THREAD

**Issue by soumali28** [swapnilsparsh/30DaysOfJavaScript#156]
WHAT I WANT TO DO?
Hey @swapnilsparsh this is Soumali Gorai, GSsOC'2022 particiapant and i want to add a project made by me using JavaScipt.

DESCRIPTION
This is  a memory/ matching game that test your memory.
Thank You

**Comment by YathinRam** [comment]
Hey @swapnilsparsh I am Yathin, GSSOC'22 participant.

As per the context I understand that you are expecting a simple game, which makes the users to guess a pattern with respect to the previous inputs (something like simon game). I have build this before and I would like to contribute here.

Thank you😁

**Comment by swapnilsparsh** [comment]
@soumali28 Memory matching game is already been there on the website so try to work on something else.
