### ISSUE TITLE
Title: ADD AN BMI CALCULATOR .

### ISSUE THREAD

**Issue by Rajat-24227** [swapnilsparsh/30DaysOfJavaScript#1560]
### Is your feature request related to a problem? Please describe.

I CAN CONTRIBUTE BY ADDING AN BMI CALCULATOR . PLZ ASSIGN ME THIS ISSUE UNDER GSSOC'24?

### Describe the solution you'd like.

I will the take the heights, weight of the user , then calculate the bmi of the person .

### Describe alternatives you've considered.

Nothing more.

**Comment by swapnilsparsh** [comment]
@Rajat-24227 hank you for providing your insight but it is not required as of now
