### ISSUE TITLE
Title: improve sound on drup kit

### ISSUE THREAD

**Issue by Silentman87** [swapnilsparsh/30DaysOfJavaScript#1564]
### Which pre-existing JavaScript project will you be working on?

there are few button which not create appropriate sound i want to make changes on them...
please assign me this issue to me..

### Describe your enhancement/improvement

change button colour..
add shadow..
increase button..
change sound and add tune

**Comment by swapnilsparsh** [comment]
@Silentman87 Thank you for providing your insight but it is not required as of now
