### ISSUE TITLE
Title: New JS Project [Playing With Probability]

### ISSUE THREAD

**Issue by Sara1428** [swapnilsparsh/30DaysOfJavaScript#1565]
### Is your feature request related to a problem? Please describe.

The feature isn't related to any problem. It's a new project I want to add.

### Describe the solution you'd like.

This project can calculate the probability of a sum of the numbers appearing on the top of two unbiased die, when they are thrown randomly. 

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![ss3](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146193518/963be32c-62e5-41f9-b219-523380f2c7ce)

**Comment by swapnilsparsh** [comment]
@Sara1428 Thank you for providing your insight but it is not required as of now
