### ISSUE TITLE
Title: Add Pac-Man Gmae

### ISSUE THREAD

**Issue by AnanyaJain25** [swapnilsparsh/30DaysOfJavaScript#1566]
### Is your feature request related to a problem? Please describe.

 PAC-MAN is a beloved classic game that is missing from our website.Furthermore, integrating PAC-MAN is relatively straightforward with JavaScript and HTML5

### Describe the solution you'd like.

I propose adding a classic PAC-MAN game to the website, developed using JavaScript and HTML5. This would provide a fun, nostalgic experience for users, enhancing their engagement and encouraging them to spend more time on the site. 

### Describe alternatives you've considered.

.

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 All the best 👍🏻

**Comment by mukilan2815** [comment]
@swapnilsparsh Can i work on this??

**Comment by AnanyaJain25** [comment]
> @swapnilsparsh Can i work on this??

I am onto it.

**Comment by mukilan2815** [comment]
oh okok 👍🏻

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 Any updates ?
