### ISSUE TITLE
title : 16-puzzle game 

### ISSUE THREAD

**Issue by Yashgabani845** [swapnilsparsh/30DaysOfJavaScript#1567]
# Game logic and basic description
n this puzzle game, you have a grid with numbered tiles and one empty space. The objective is to slide the tiles around the grid to arrange them in a specific order, usually from lowest to highest number, with the empty space in a designated position (often at the bottom-right corner).

8-Puzzle: A 3x3 grid with 8 numbered tiles (1-8) and one empty space.
16-Puzzle: A 4x4 grid with 15 numbered tiles (1-15) and one empty space.

# Game points

- Starting Points: 1000
- Moves: 45 (45 points deducted)
- Time: 7 minutes (35 points deducted)
- Bonus: Solved under 50 moves (awarded 50 points)

# Screeenshot
![16_Puzzle](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127788321/5c186fe8-28ad-4762-a5e0-83843bf0f66b)

# why should be added

- fun to play
- everyone love number game
- already know the code in DSA(so fun to develop)
- interesting project

**Comment by Yashgabani845** [comment]
@swapnilsparsh please assign me this project
i think this project is very interesting add

**Comment by swapnilsparsh** [comment]
@Yashgabani845 Thank you for providing your insight but it is not required as of now

**Comment by Yashgabani845** [comment]
@swapnilsparsh hi , sir can you please tell me which kind of issues i should raise that are required in this repo to get assigned 
please answer it will follow you feedback

**Comment by swapnilsparsh** [comment]
@Yashgabani845 Try to find bugs in the existing projects which are there so you can resolve them or come with some new and unique ideas where some challenging js concepts are used which can be useful for others.
