### ISSUE TITLE
Title: Doodle Jump Game

### ISSUE THREAD

**Issue by AnanyaJain25** [swapnilsparsh/30DaysOfJavaScript#1568]
### Is your feature request related to a problem? Please describe.

We might need more exciting adn kind of addictive games which involves visible movements!

### Describe the solution you'd like.

Doodle Jump is a popular and addictive game known for its simple yet engaging mechanics, which can attract a wide audience. By incorporating this game, we can create a more captivating and enjoyable experience for our users

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

will implement this popular game 
![Screenshot 2024-05-30 151954](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/136808696/120ec239-e6fa-48f8-8b00-1aea02199b44)

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 Thank you for providing your insight but it is not required as of now

**Comment by AnanyaJain25** [comment]
hey @swapnilsparsh May I know whats the issue with this.. It will be same as other projects completely based on Javascript

**Comment by swapnilsparsh** [comment]
@AnanyaJain25 All the best 👍🏻 and make sure to use only HTML, CSS and JS with proper all screens responsiveness

**Comment by AnanyaJain25** [comment]
> @AnanyaJain25 All the best 👍🏻 and make sure to use only HTML, CSS and JS with proper all screens responsiveness

yes sir ! Sure sir
