### ISSUE TITLE
[DOCS] <Using GitHub Desktop in Contributing.md>

### ISSUE THREAD

**Issue by Priyanshu2631** [swapnilsparsh/30DaysOfJavaScript#1571]
### Description

I want to add instructions on using Github Desktop for contributing to this repository which makes it easy as well as simple for beginners to contribute. Please assign me this issue under GSSOC'24.

**Comment by swapnilsparsh** [comment]
@Priyanshu2631 Thank you for providing your insight but it is not required as of now
