### ISSUE TITLE
Title: Add Tip Calculator

### ISSUE THREAD

**Issue by Nayanika1402** [swapnilsparsh/30DaysOfJavaScript#1574]
### Is your feature request related to a problem? Please describe.

No just addition of a new project using javascript.

### Describe the solution you'd like.

Tip calculator:Calculates the tip amount and final amount on the basis of tip percentage and bill amount.

### Describe alternatives you've considered.

No alternatives as of now.

**Comment by swapnilsparsh** [comment]
@Nayanika1402 Thank you for providing your insight but it is not required as of now
