### ISSUE TITLE
Title: Adding a audio sound visulaizer

### ISSUE THREAD

**Issue by sidharth2829** [swapnilsparsh/30DaysOfJavaScript#1576]
### Is your feature request related to a problem? Please describe.

Yes, the feature request to add an audio visualizer addresses several problems and enhances the overall user experience:

### Describe the solution you'd like.

An audio sound visualizer takes audio input, processes it, and generates visual feedback that corresponds to the frequency and amplitude of the sound. By adding this to your project, users will be able to see a visual depiction of the audio they are interacting with, whether it's music, voice, or any other sound.

### Describe alternatives you've considered.

No alternative as of now.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/111569459/69a8e15d-5566-4134-9d10-0259faf50987)

**Comment by swapnilsparsh** [comment]
@sidharth2829 Thank you for providing your insight but it is not required as of now
