### ISSUE TITLE
Title: Coloron Game

### ISSUE THREAD

**Issue by AtharvaShinde253** [swapnilsparsh/30DaysOfJavaScript#1577]
### Is your feature request related to a problem? Please describe.

Adding a Coloron Game will be a fantastic inclusion to all the javascript projects. It is a game where you have to guide a bouncing ball as it traverses across a series of tiles, ensuring that the color of the tile matches the color of the ball at each bounce.

### Describe the solution you'd like.

You have to tap at the tiles to change its color in order to stay alive in the game. You lose if you fail to keep  up with your reflexes and you can play again using the play again button and compete with your friends.

### Describe alternatives you've considered.

Have features like-
 1.Responsive Game so that it can be played on any device
 2.Button for sharing your score on twitter  with your friends.

### Add any other context or screenshots about the feature request here.

<img width="959" alt="Coloron" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/101362085/c0d822e7-a134-4334-b395-51a49b9105cd">

**Comment by swapnilsparsh** [comment]
@AtharvaShinde253 Thank you for providing your insight but it is not required as of now
