### ISSUE TITLE
Title: Match - 3 Game

### ISSUE THREAD

**Issue by Praneeth-2602** [swapnilsparsh/30DaysOfJavaScript#1578]
### Is your feature request related to a problem? Please describe.

The tile-matching game allows players to swap adjacent tiles to form rows or columns of three or more identical tiles. Once matched, these tiles disappear, and new tiles drop down to fill the gaps. This basic mechanic needs enhancements to increase player engagement and provide a more dynamic gaming experience.

### Describe the solution you'd like.

To enhance the game, various levels should be introduced with increasing difficulty and unique layouts. Special tiles with unique effects, such as clearing entire rows or columns, should be added to create strategic depth. Score tracking will provide a sense of achievement, and smooth animations will make the gameplay more visually appealing and satisfying. The game has three levels. In each level the player has to reach a certain score limit in the limited number of moves.

### Describe alternatives you've considered.

1. Alternative Game Mechanics: Instead of a match-3 format, consider a different puzzle mechanic, such as a tile-sliding puzzle (like the 15 Puzzle), where players slide tiles into empty spaces to achieve a specific order or pattern.
2. Power-Ups and Boosters: Introducing power-ups that players can collect and use strategically to clear tiles or gain bonuses.
Time-Based Challenges: Implementing a timer for each level, adding pressure and making the game more challenging.
3. Multiplayer Mode: Allowing players to compete against each other in real-time, adding a competitive edge to the game.
4. Story Mode: Creating a narrative or adventure mode where players progress through a story by completing match-3 puzzles, adding context and motivation for gameplay.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/137754636/5813923b-5004-4f59-b138-0cec3b79fd98)

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 All the best 👍🏻
