### ISSUE TITLE
Title: Meme Generator

### ISSUE THREAD

**Issue by Archiesachin** [swapnilsparsh/30DaysOfJavaScript#1579]
### Is your feature request related to a problem? Please describe.

Creating a meme generator using HTML, CSS and JS. 
The implementation combines file handling, canvas drawing, text rendering, and file downloading to create a fully functional meme generator. 
Each step is designed to ensure ease of use and a smooth user experience, allowing anyone to create and download their memes effortlessly.

### Describe the solution you'd like.

<h2>Implementation</h2>

imageInput: This input element allows users to upload an image file from their local device. Once the image is uploaded, it will be used as the background of the meme.  OR   We can use memes.api to fetch random meme images from the internet. 

topText and bottomText: These are text input fields where users can enter the text they want to appear at the top and bottom of the meme image. The text will be drawn over the image on the canvas.

generateButton: A button that, when clicked, triggers the process of generating the meme. This involves drawing the uploaded image onto the canvas and overlaying the user-inputted text.

downloadButton: A button that allows users to download the generated meme as a PNG file. Clicking this button converts the canvas content to an image file and prompts a download.

canvas: This HTML element serves as the drawing area where the meme is created. The canvas will display the uploaded image and overlay the text entered by the user.

### Describe alternatives you've considered.

![Screenshot (718)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/103347688/ef514d07-a21a-47bf-813b-3c9d507494b8)

Please assign me this issue under GSSOC'24.

**Comment by swapnilsparsh** [comment]
@Archiesachin Thank you for providing your insight but it is not required as of now
