### ISSUE TITLE
Title: To-do list

### ISSUE THREAD

**Issue by P-lavanya16** [swapnilsparsh/30DaysOfJavaScript#1580]
### Is your feature request related to a problem? Please describe.

i want to view deleted tasks which i have done

### Describe the solution you'd like.

By using JS ,we can view deleted tasks too!!

### Describe alternatives you've considered.

i want to add del.html for a view

### Add any other context or screenshots about the feature request here.

we can add time for tasks

**Comment by swapnilsparsh** [comment]
@P-lavanya16 Thank you for providing your insight but it is not required as of now
