### ISSUE TITLE
Title: Sorting Visualizer 

### ISSUE THREAD

**Issue by P-lavanya16** [swapnilsparsh/30DaysOfJavaScript#1583]
### Is your feature request related to a problem? Please describe.

i want to add different sorting algo

### Describe the solution you'd like.

use different sorting techniques for visualizer

### Describe alternatives you've considered.

i will generate array size as user input

**Comment by swapnilsparsh** [comment]
@P-lavanya16 Thank you for providing your insight but it is not required as of now

**Comment by P-lavanya16** [comment]
@swapnilsparsh kindly assign some other issue
