### ISSUE TITLE
Title: New project: Pagination 

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [swapnilsparsh/30DaysOfJavaScript#1584]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

I would like to create a pagination for the list of items using HTML, CSS, and js, like in the screenshot.  I will display a custom list of items and apply pagination to browse them.

Kindly please assign this issue to me.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139672976/1d1dee47-bb3e-4f3e-9c7b-cd0fd60e089a)

**Comment by swapnilsparsh** [comment]
@DharshiBalasubramaniyam Thank you for providing your insight but it is not required as of now
