### ISSUE TITLE
Random Password generator is not working

### ISSUE THREAD

**Issue by SuhainaFathimaM** [swapnilsparsh/30DaysOfJavaScript#1585]
### What happened?

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/153417476/81c2c1bc-88a4-42de-8d9b-6e66e3e329aa)

### How can we reproduce this bug?

The random password generator is not generating passwords

### Urgency (Optional)

High priority

**Comment by SuhainaFathimaM** [comment]
@swapnilsparsh  I would like to work on this issue under GSSoC 2024

**Comment by swapnilsparsh** [comment]
@SuhainaFathimaM Can you provide more details because for me it is working.
