### ISSUE TITLE
Title: Password Strength Checker

### ISSUE THREAD

**Issue by kyra-09** [swapnilsparsh/30DaysOfJavaScript#1586]
### Is your feature request related to a problem? Please describe.

Decsription :- By checking the strength of the password , it allows users to create a unique key as a password to prevent any security breach and secures the data of user while creating an account.
    Tools I'll use :- I'll use HTML , CSS and JavaScript for the implementation of the web app.

### Describe the solution you'd like.

I would like to create a web app for the same .

### Describe alternatives you've considered.

I'll also include screenshots for the app .

**Comment by swapnilsparsh** [comment]
@kyra-09 Thank you for providing your insight but it is not required as of now

**Comment by kyra-09** [comment]
Hey @swapnilsparsh I don't understand the issue... it can be a great beginner project for JS and provide some insights into how it will work. Could you give some clarification please?

**Comment by swapnilsparsh** [comment]
@kyra-09 There is already a project similar to this so there is no need for this project.

**Comment by kyra-09** [comment]
Oh alright...thanks for clarification.
