### ISSUE TITLE
Title: celsius to fahrenheit convertor

### ISSUE THREAD

**Issue by dhruv8433** [swapnilsparsh/30DaysOfJavaScript#1587]
@swapnilsparsh 

### Is your feature request related to a problem? Please describe.

we can add celsius to fahrenheit convertor

### Describe the solution you'd like.

we take celsius from user and convert into fahrenheit

### Describe alternatives you've considered.

we can add some gui and take 1 input from user
after performing celsius to fahrenheit convertion we can display result

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114583978/7b83ea90-1e24-4544-88b3-7eb2680bd702)

**Comment by swapnilsparsh** [comment]
@dhruv8433 Thank you for providing your insight but it is not required as of now
