### ISSUE TITLE
Image Comparison Slider

### ISSUE THREAD

**Issue by iABn0rma1** [swapnilsparsh/30DaysOfJavaScript#1590]
### Is your feature request related to a problem? Please describe.

For the image comparison slider feature, imagine you have two images side by side, like "Before" and "After" shots of a renovation project. The user would have a draggable slider that divides the two images. By dragging the slider left or right, they can reveal more of one image while hiding the other, allowing for a direct visual comparison between the two states.

### Describe the solution you'd like.

Interactive Slider: Implement a draggable slider element that users can grab and move horizontally across the screen.

Visual Representation: Display two images side by side, with one representing the "Before" state and the other representing the "After" state.

Real-time Comparison: As the user moves the slider, dynamically adjust the visibility of each image accordingly, providing instant feedback.

### Describe alternatives you've considered.

Implementation Steps:

HTML Structure: Create a container to hold both images and the slider.

CSS Styling: Style the container, images, and slider to achieve the desired visual layout.

JavaScript Interaction: Implement event listeners to detect slider movement and update the visibility of the images accordingly.

Responsive Design: Ensure the feature works well on various screen sizes and devices, adjusting layout and functionality as needed.

### Add any other context or screenshots about the feature request here.

<img width="895" alt="image" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/75512370/066f89fb-8b67-4516-a8ec-6455f03f8a89">

**Comment by Ananya-Nair20** [comment]
Hello

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.


Thank you

**Comment by swapnilsparsh** [comment]
@iABn0rma1 Thank you for providing your insight but it is not required as of now
