### ISSUE TITLE
Title:  SIMON GAME (NEW GAME TO ADD)

### ISSUE THREAD

**Issue by Nih1tGupta** [swapnilsparsh/30DaysOfJavaScript#1594]
### Is your feature request related to a problem? Please describe.

I WANT TO ADD SIMON GAME (CREATED BY HTML,CSS AND JS)

### Describe the solution you'd like.

![SG](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119615342/bfca6fe7-bb3f-4983-947d-f9a66b205978)

### Describe alternatives you've considered.

SIMON GAME

**Comment by Nih1tGupta** [comment]
@swapnilsparsh , please Consider this issue and assign this to me under GSSOC'24

**Comment by MrPC7** [comment]
**This project is already available on website.**
[Link](https://30daysofjs.netlify.app/58%20-%20simon%20game/)

**Comment by swapnilsparsh** [comment]
@Nih1tGupta This project is already there
