### ISSUE TITLE
Title: New Game Touch-No-Fire Game

### ISSUE THREAD

**Issue by Anjaliavv51** [swapnilsparsh/30DaysOfJavaScript#1595]
Assign under GSSOC

# **Touch-No-Fire-Game** 
Enjoy The Game!!!
<br>

## **Description 📃**
- This is a Normal crossword game that we can play in virtually and blow I have print some tips for the beginners as well!
- The project will contain HTML, CSS and JavaScript files. The HTML file adds structure to the game followed by styling using CSS. JavaScript adds functionality to the game.

## **How to play? 🕹️**
- Controls :
    - Game Rules!
    - Eat the food to gain score
    - Do not touch the fire
    - The fire multiplies once with even scores
    - If you stay idle, the fire won't do anything
    - Do not touch the moving fire
    - Please play using arrow keys!

## **Screenshots 📸**

<br>
<img src="https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/8835bbe2-13a4-43d5-b986-bb30442f833c">

<br>

## **Working video 📹**
https://github.com/GameSphere-MultiPlayer/GameSphere/assets/154777864/a88f676a-69c8-4cc9-b6e6-98e5fca1aa59

**Comment by swapnilsparsh** [comment]
@Anjaliavv51 Thank you for providing your insight but it is not required as of now
