### ISSUE TITLE
Title: Monopoly Game using javascript

### ISSUE THREAD

**Issue by Damini2004** [swapnilsparsh/30DaysOfJavaScript#1596]
### Is your feature request related to a problem? Please describe.

Monopoly is a classic board game where players compete to acquire wealth through buying, renting, and trading properties. The objective is to drive opponents into bankruptcy, thus becoming the richest player by the end of the game.

### Describe the solution you'd like.

Players: 2 to 8 players.
Board: The board consists of 40 spaces, including 28 properties, 3 Chance spaces, 3 Community Chest spaces, 4 railroads, 2 utilities, a "Go" space, a "Jail" space, a "Free Parking" space, and a "Go to Jail" space.
Tokens: Each player selects a token to move around the board.
Money: Players start with a set amount of money.

### Describe alternatives you've considered.

Turns: Players take turns rolling two six-sided dice.
Movement: Players move their tokens the number of spaces indicated by the dice roll.
Property Transactions:
Buying: If a player lands on an unowned property, they can buy it.
Rent: If the property is owned, the player must pay rent to the owner.
Chance and Community Chest: Players draw cards that can result in various outcomes, such as paying fines, earning money, or moving to different board spaces.
Special Spaces:
Go: Players collect $200 each time they pass "Go".
Jail: Players can be sent to jail and must either roll doubles, use a "Get Out of Jail Free" card, or pay a fee to get out.
Free Parking: A neutral space where nothing happens.
Go to Jail: Sends the player directly to jail.
Development: Players can build houses and hotels on their properties to increase the rent they can charge.
Trading: Players can trade properties, money, and cards.
Bankruptcy: When a player cannot pay what they owe, they go bankrupt and are out of the game. Their assets are distributed to their creditors or returned to the bank.
Winning: The game ends when all but one player is bankrupt, or a set time limit is reached, and the wealthiest player wins.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119414762/bc9facfa-79e0-41f6-845b-65ba4d20922d)

Assign this project to me under GSSOC

**Comment by swapnilsparsh** [comment]
@Damini2004 Thank you for providing your insight but it is not required as of now
