### ISSUE TITLE
Title: Home(landing) Page Enhancement

### ISSUE THREAD

**Issue by PRAYAG0908** [swapnilsparsh/30DaysOfJavaScript#1597]
### Which pre-existing JavaScript project will you be working on?

None

### Describe your enhancement/improvement

I want to improve the overall home(landing)page, I would like to add a navbar with custom created Logo for 30dayofjs ,also would like to add a short description about the website, and make the footer look more modern
I'm contributor@gssoc
please assign this to me
![gssoc home page edit](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/115292072/b59b3c7f-e5ee-4b53-bb6b-0bc73bd6d04c)

**Comment by swapnilsparsh** [comment]
@PRAYAG0908 It is already in process
