### ISSUE TITLE
Dad Jokes

### ISSUE THREAD

**Issue by bristiHalder** [swapnilsparsh/30DaysOfJavaScript#1598]
### Is your feature request related to a problem? Please describe.

To present dad jokes using web technologies like HTML, CSS, and JavaScript.

### Describe the solution you'd like.

Develop a small web application that displays a random dad joke each time a button is clicked. This will involve creating an HTML structure, styling it with CSS, and adding interactivity using JavaScript.

### Describe alternatives you've considered.

.

**Comment by swapnilsparsh** [comment]
@bristiHalder Thank you for providing your insight but it is not required as of now
