### ISSUE TITLE
Title: Add a tip calculator

### ISSUE THREAD

**Issue by vaishali-gupta32** [swapnilsparsh/30DaysOfJavaScript#1599]
### Is your feature request related to a problem? Please describe.

Often we find a problem in thinking how much tip to give in a restaurant after dining. This feature will solve that problem.

Describe alternatives you've considered.
.

### Describe the solution you'd like.

It will calculate the amount of tip based on your dining experience and bill.

### Describe alternatives you've considered.

It can be used in restaurants and cafes. Also, for other services too.

**Comment by vaishali-gupta32** [comment]
@swapnilsparsh Please assign this issue to me. I am willing to contribute to this. Also, please add label to it.

**Comment by swapnilsparsh** [comment]
@vaishali-gupta32 Thank you for providing your insight but it is not required as of now
