### ISSUE TITLE
 Add a New Project: 3D Distance Calculator

### ISSUE THREAD

**Issue by MrPC7** [swapnilsparsh/30DaysOfJavaScript#1600]
### **Project Overview:**

I am looking to add a new project to the "30 Days of Code" website. This project will be a 3D Distance Calculator that allows users to compute the distance between two points in a three-dimensional space. The calculator should take the coordinates of two points as input and output the distance between them.

**Project Requirements:**

Input: The calculator should accept two sets of coordinates as input, each consisting of three values (x, y, z).
Output: The output should be the calculated distance between the two points.
Formula: Use the Euclidean distance formula:

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/91939963/ebce0ba6-2a0e-4d55-ac1e-68de793e1d14)

**User Interface:**
A clean and simple UI for users to input coordinates.
A "Calculate" button to trigger the distance computation.
Display the result in a user-friendly manner.

Responsive Web Design Basics

> Let's enhance the learning experience on "30 Days of Code" with this exciting new project! If you have any questions or need further clarification, feel free to ask. Happy coding!

### Assignment Request:
**Please assign this task to me under GSSoC'24.**

Labels: `GSSoC` `Level3`

**Comment by swapnilsparsh** [comment]
@MrPC7 All the best 👍🏻and make sure it is mobile responsive also.
