### ISSUE TITLE
Title: Add Flappy Bird Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [swapnilsparsh/30DaysOfJavaScript#1601]
### Is your feature request related to a problem? Please describe.

- Implement a functional Flappy Bird game for our website. 
- This game will serve as a fun and engaging feature for our users, showcasing our capability to develop interactive web applications.
- The game should include the core mechanics, a scoring system, and a user-friendly interface.

### Describe the solution you'd like.

- Initial Setup: Create repository and project structure.
- Bird Mechanics: Implement bird rendering, gravity, and flapping.
- Environment: Develop scrolling background and pipes.
- Collision Detection: Implement collision detection.
- Scoring: Set up scoring system and display.
- User Interface: Design start and game over screens.
- Sound Effects: Add optional sound effects.
- Testing: Test on different devices and browsers.
- Deployment: Deploy game on website.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![Imageg79l-1682602936960](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146121869/b787bcf3-a35d-4170-9975-b521997da762)
![flappy-bird](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146121869/1a1ba6d2-08cb-47f2-9cc8-8460c26bb550)

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by AsmitaMishra24** [comment]
> ### Is your feature request related to a problem? Please describe.
> * Implement a functional Flappy Bird game for our website.
> * This game will serve as a fun and engaging feature for our users, showcasing our capability to develop interactive web applications.
> * The game should include the core mechanics, a scoring system, and a user-friendly interface.
> 
> ### Describe the solution you'd like.
> * Initial Setup: Create repository and project structure.
> * Bird Mechanics: Implement bird rendering, gravity, and flapping.
> * Environment: Develop scrolling background and pipes.
> * Collision Detection: Implement collision detection.
> * Scoring: Set up scoring system and display.
> * User Interface: Design start and game over screens.
> * Sound Effects: Add optional sound effects.
> * Testing: Test on different devices and browsers.
> * Deployment: Deploy game on website.
> 
> ### Describe alternatives you've considered.
> .
> 
> ### Add any other context or screenshots about the feature request here.
> ![Imageg79l-1682602936960](https://private-user-images.githubusercontent.com/146121869/335824610-b787bcf3-a35d-4170-9975-b521997da762.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzI4NTksIm5iZiI6MTcxNzI3MjU1OSwicGF0aCI6Ii8xNDYxMjE4NjkvMzM1ODI0NjEwLWI3ODdiY2YzLWEzNWQtNDE3MC05OTc1LWI1MjE5OTdkYTc2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQyMDA5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOThmM2U1NTE5ZjNmNzVlMzEyZTA0OTA0YzNlODA0ZDU2MDdmNzk1N2IxNzkyMGZhZjNmMTRkZDY4NWMyNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5y2pDtWIJPsKoet6r3O3LrpDgiIhqESUl0MIGDqQ3Es) ![flappy-bird](https://private-user-images.githubusercontent.com/146121869/335824629-1a1ba6d2-08cb-47f2-9cc8-8460c26bb550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzI4NTksIm5iZiI6MTcxNzI3MjU1OSwicGF0aCI6Ii8xNDYxMjE4NjkvMzM1ODI0NjI5LTFhMWJhNmQyLTA4Y2ItNDdmMi05Y2M4LTg0NjBjMjZiYjU1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQyMDA5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWM4ZGIwZGE2ZDY3ZjIzZWY5OTkyMjI2ODRlNjcyNmM4NDliNzQ5NzU3NGM0M2IxMjhhZGJjNjI2NGZlNjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ht-7al5KgGI7Vtr4touEHW-q1JKN7RHDbxSxNH5cuuk)

Using HTML, CSS, JS

**Comment by swapnilsparsh** [comment]
@AsmitaMishra24 All the best 👍🏻 and make sure to use only HTML, CSS and JS with proper all screens responsiveness

**Comment by taneshagahtori** [comment]
@swapnilsparsh Please assign me this task under gssoc , I want to work on this isssue.
