### ISSUE TITLE
Title: Add Pokémon Stats Card 

### ISSUE THREAD

**Issue by Sypher0Dronzer** [swapnilsparsh/30DaysOfJavaScript#1603]
### Is your feature request related to a problem? Please describe.

No its just a new addition of a project.

### Describe the solution you'd like.

I want to add a site in which you can search the pokemon by typing its name or id and get the details of the pokemon.
I used this project to learn how to use API.

### Describe alternatives you've considered.

I have build it and it is functional in all screens 

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/83546205/1d95021f-53fb-433a-9938-69427f45be11

Please assign this issue to me @swapnilsparsh. I wont disappoint you

**Comment by swapnilsparsh** [comment]
@Sypher0Dronzer Thank you for providing your insight but it is not required as of now

**Comment by Sypher0Dronzer** [comment]
Whats wrong with it can you elaborate? Each time I ask for a project addition I am replied by the same answer. Its based of javascript so why can't i contribute? @swapnilsparsh
