### ISSUE TITLE
Title: Planetary Motion Calculator

### ISSUE THREAD

**Issue by Sara1428** [swapnilsparsh/30DaysOfJavaScript#1604]
### Is your feature request related to a problem? Please describe.

I want to add a calculator for measurement of various parameters of planetary motion, which I would like to add to this project.
It seemed a new idea to me in this project, please consider the issue.

### Describe the solution you'd like.

This calculator calculates various parameters of planetary motion such as, lengths of semi-major, semi-minor axis, time period and areal velocity of planets using Kepler's laws. I've also added quite a bit of information regarding that and mentioned the source of information as well.
The tech-stack I used is HTML, CSS, JS.
I've ensured that my website is mobile-responsive as well.
The units of measurement will be corresponding to that given by user.

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![page1](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146193518/367ea6b9-1229-44b4-b64e-4d3ec86185d1)

![page2](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146193518/f854815b-c05a-4a15-843f-fe53618e0c44)

![page3](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146193518/f623125d-2caf-445e-aab3-8ab4a6ff29ba)

**Comment by swapnilsparsh** [comment]
@Sara1428 Thank you for providing your insight but it is not required as of now
