### ISSUE TITLE
Title: Responsive Image Slider

### ISSUE THREAD

**Issue by Archiesachin** [swapnilsparsh/30DaysOfJavaScript#1605]
### Is your feature request related to a problem? Please describe.

I want to add a new feature of Responsive Image Slider Using HTML, CSS and JavaScript.  Since this is one of the most used frontend feature using javascript. 

### Describe the solution you'd like.

Using javascript creating a responsive image slideshow. This image carousel has manual controls with next and previous buttons. The images can also be accesed with a dot navigation that is provided below the image slider. 

### Describe alternatives you've considered.

![Screenshot (1043)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/103347688/c1ab3e3f-3487-4cf3-88cf-bc5e3ad6baf6)

### Add any other context or screenshots about the feature request here.

Assign me this issue under gssoc'24

**Comment by swapnilsparsh** [comment]
@Archiesachin Thank you for providing your insight but it is not required as of now
