### ISSUE TITLE
Title: Adding Ascii value calculator

### ISSUE THREAD

**Issue by agastya3636** [swapnilsparsh/30DaysOfJavaScript#1606]
### Is your feature request related to a problem? Please describe.

Calculates the ASCII value of any character.

### Describe the solution you'd like.

Calculates the ASCII value of any character.

### Describe alternatives you've considered.

Calculates the ASCII value of any character.

**Comment by swapnilsparsh** [comment]
@agastya3636 Thank you for providing your insight but it is not required as of now
