### ISSUE TITLE
Title: Proper Footer design

### ISSUE THREAD

**Issue by ayush-848** [swapnilsparsh/30DaysOfJavaScript#1608]
### Which pre-existing JavaScript project will you be working on?

I want to work on the main website

### Describe your enhancement/improvement

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/126975547/a6a9965a-c884-42b4-9f2d-2d40c5736f5b)
here the pages link 1,2,3,... falls under the footer.
I want to re-design the footer
I want to add 'COPYRIGHT © 30DaysOfJavascript 2024'

### Anything you need to say to the Reviewers

I also want to remove the below links
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/126975547/cb6608e0-333f-48b5-a1a8-8883502f108f)

I will replace them with line 'Contribute here', 'Follow Us', these will do the same work but I will align them properly

But ofcourse I will keep this part '< / > with ❤️ by Swapnil Srivastava' but it will be better to replace '< / >' by 'Made', if you permit

**Comment by ayush-848** [comment]
@swapnilsparsh please look into it and if you agree, then assign it to me. If you have suggestions or is not satisfied by some of my suggestion, you can instruct me.

**Comment by swapnilsparsh** [comment]
@ayush-848 Thank you for providing your insight but it is not required as of now
