### ISSUE TITLE
Title: Catch The Ball Game

### ISSUE THREAD

**Issue by shruti110503** [swapnilsparsh/30DaysOfJavaScript#1609]
### Is your feature request related to a problem? Please describe.

I want to add a new game. It is called Catch the ball.

### Describe the solution you'd like.

Description:
Catch the Ball is an engaging and addictive arcade game that challenges players to catch a bouncing ball with a paddle. 

Key Features:

1)Intuitive Gameplay:

Simple controls: Move the paddle left or right to catch the ball.
Easy to understand, making it accessible for players of all skill levels.

2) Responsive Design:

Mobile-friendly: Optimized for touch controls on smartphones and tablets.
Resizable canvas: Automatically adjusts to different screen sizes, providing a consistent gaming experience on any device.

3) Endless Challenge:

Increasing difficulty: The ball's speed increases over time, testing players' reflexes and coordination.
Score tracking: Players can see their score in real-time and aim to beat their high score.
![Screenshot 2024-06-02 132343](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/118251562/8036546f-3aea-4484-b1ad-73fc85133c3d)

### Describe alternatives you've considered.

Please assign me this issue under Gssoc'24

**Comment by swapnilsparsh** [comment]
@shruti110503 All the best 👍🏻
