### ISSUE TITLE
Title: i want to add Dice Roller Game

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1612]
### Is your feature request related to a problem? Please describe.

**Game logic and basic description** : we have one dice or many dices of different no of sides. we use the dice for play different games which needs dice to roll.

### Describe the solution you'd like.

_**Features**_
Game points : roll the dice
we can add more dices of diff no of sides.

### Working Video
Uploading DiceRoller.mp4…

### Describe alternatives you've considered.

no alternative

**Comment by Vipullakum007** [comment]
please assign issue to as GSSOC'24 . i already made it.

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now
