### ISSUE TITLE
Prayer Reminder

### ISSUE THREAD

**Issue by samarsajad** [swapnilsparsh/30DaysOfJavaScript#1614]
### Is your feature request related to a problem? Please describe.

people often forget to pray and lose connection with god

### Describe the solution you'd like.

creating a simple prayer reminder that sends alerts to users for prayers

### Describe alternatives you've considered.

Apps could be an alternative but they take a lot of your storage

**Comment by samarsajad** [comment]
please assign me this issue

**Comment by swapnilsparsh** [comment]
@samarsajad Thank you for providing your insight but it is not required as of now
