### ISSUE TITLE
Title: Weird jumping mechanism in game 103- Retro Mario Game 

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1616]
### Which pre-existing JavaScript project will you be working on?

The current jumping mechanism is currently not intuitive, like that of platformers like Mario games.

### Describe your enhancement/improvement

I will make sure to replicate the jumping mechanisms, like air time, downward and upward acceleration more like in popular platformers like Mario

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 Thank you for providing your insight but it is not required as of now
