### ISSUE TITLE
Title: Calculating largest Eigen value and Eigen vector of a  N x N - Dimensional matrix

### ISSUE THREAD

**Issue by saketh-05** [swapnilsparsh/30DaysOfJavaScript#1617]
This is a very knowledge building and exciting , fun project which is purely built in HTML, CSS AND JS.

**Why should this be added?**

- Easy to understand and fun to use 
- Very complex calculations made easy by this project.
- Introduction of Numerical methods and linear algebra project 
- This project will have modern look and feel with responsive design
- This project can serve as an educational tool for those learning both JavaScript and linear algebra
- Users enter the values of the matrix as input 
- Largest eigen value and vector are calculated and displayed.

Motivation: 
![Screenshot 2024-06-02 164719](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/134281589/2fc73aad-4bc3-4c88-a6d5-e846ca4074ce)
![Screenshot 2024-06-02 165048](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/134281589/81ff7f21-0f95-4eaa-8b1b-d8127e6e8884)

Please assign this to me under gssoc 2024. I will complete this ASAP.

**Comment by swapnilsparsh** [comment]
@saketh-05 All the best 👍🏻

**Comment by swapnilsparsh** [comment]
@saketh-05 Any update ?

**Comment by saketh-05** [comment]
@swapnilsparsh Most of the work is completed just make few adjustments.

**Comment by swapnilsparsh** [comment]
@saketh-05 Any update ?
