### ISSUE TITLE
New Game : DOODLE JUMP

### ISSUE THREAD

**Issue by jaydeep099** [swapnilsparsh/30DaysOfJavaScript#1618]
A gravity defying creature trying to reach wants to higher steps, with your help. So keep your fingers on the keyboard and help the doodler.

Functionalities:
By using the arrow keys try to move in different directions in air.
fully responsive design

<img width="1440" alt="Doodle_Jump_Game" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/148114163/172065bb-43fd-4586-ab96-b99a9582a01b">

**Comment by swapnilsparsh** [comment]
@jaydeep099 Thank you for providing your insight but it is not required as of now
