### ISSUE TITLE
Title: Adding an image generator 

### ISSUE THREAD

**Issue by shrreya24** [swapnilsparsh/30DaysOfJavaScript#1619]
### Is your feature request related to a problem? Please describe.

This feature is used to find the image with the help of given search bar .

### Describe the solution you'd like.

This is used to search an image of the object we want . Here we have to write the prompt in the search bar and according to it the user will be provided with number of images . 

### Describe alternatives you've considered.

No alternative 

### Add any other context or screenshots about the feature request here.

![Preview](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/170966754/77ca192a-a025-491e-835d-ef7435d19fe0)

This is how the basic look out is visible .

**Comment by shrreya24** [comment]
@swapnilsparsh please assign the task to me .

**Comment by swapnilsparsh** [comment]
@shrreya24 Thank you for providing your insight but it is not required as of now
