### ISSUE TITLE
Add Pop My Balloon Game

### ISSUE THREAD

**Issue by Nayanika1402** [swapnilsparsh/30DaysOfJavaScript#1620]
### Is your feature request related to a problem? Please describe.

No just a new game addition.

### Describe the solution you'd like.

The basic premise of the game remains the same, regardless of the difficulty level or the input method. There will be a range of numbers from which players can choose a number. If the manage to guess the randomly chosen number, the balloon will pop and they lose. If they manage to avoid the lucky number, the range decreases such that their guess either becomes the new lower bound or new upper bound, and the balloon inflates just a little bit more.

### Describe alternatives you've considered.

No alternatives as of now.

**Comment by swapnilsparsh** [comment]
@Nayanika1402 Thank you for providing your insight but it is not required as of now
