### ISSUE TITLE
Title: Add Bulls and Cows game

### ISSUE THREAD

**Issue by aRUsh-codes** [swapnilsparsh/30DaysOfJavaScript#1622]
### Is your feature request related to a problem? Please describe.

I want to add the famous Bulls and Cows game made in js.

### Describe the solution you'd like.

This is how it will work:-
The computer will have a unique 4-digit number while the player tries to guess it.

- The number to be guessed must be a 4 digit number, using only digits from 1 - 9, each digit atmost once. e.g. 1874 is valid, 0172 is not valid, 9877 is not valid, 9536 is valid.
- For every guess that the player makes, he gets 2 values - the number of bulls and the number of cows. 
    - 1 bull means the guess contains and the target number have 1 digit in common, and in the correct position. 
    - 1 cow means the guess and the target have 1 digit in common, but not in correct position. 

Eg. Let the target be 1234. Guessing 4321 will give 0 bulls and 4 cows. 3241 will give 1 bull and 3 cows. 4 bulls means you have won the game!
The player gets total 7 chances to correctly guess the entire number and is awarded points in accordance to the number of guesses it took to win
### Describe alternatives you've considered.

none

### Add any other context or screenshots about the feature request here.

none 
also please add gssoc and appropriate level label
Thank You

**Comment by swapnilsparsh** [comment]
@aRUsh-codes Thank you for providing your insight but it is not required as of now
