### ISSUE TITLE
Title: Change in the title of "Stick Hero" Game

### ISSUE THREAD

**Issue by rohitinu6** [swapnilsparsh/30DaysOfJavaScript#1623]
### Which pre-existing JavaScript project will you be working on?

Stick Hero Game

### Describe your enhancement/improvement

To make a change in the title of the index.hrml file from "Document" to "Stick Hero"

[
![Screenshot 2024-06-02 153140](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/113301503/a219e930-73a6-4eda-8f04-7d640015bec4)
](url)

### Anything you need to say to the Reviewers

I wish to make a small change in the title of an existing game called "Stick Hero" wherein the title of the file is named wrongly.
Hope that you assign this issue to me. Please assign with the gssoc label.

**Comment by swapnilsparsh** [comment]
@rohitinu6 Thank you for providing your insight but it is not required as of now
