### ISSUE TITLE
Title: Add new project - Bitwise Calculator

### ISSUE THREAD

**Issue by debangi29** [swapnilsparsh/30DaysOfJavaScript#1624]
### Is your feature request related to a problem? Please describe.

Bitwise operations are very frequent when it comes to electronics engg, Competitive programming, physics, mathematics and many more areas, Creating one such calculator by own self can test JS skills of basic calculations; and also help users in many ways

### Describe the solution you'd like.

Bitwise calculator which Calculates results of different bitwise operations based on inputs. **AND NAND OR NOR XOR XNOR** ; All these operations will be available...

### Describe alternatives you've considered.

I have searched online calculations of bitwise operations iteratively many times

**Comment by swapnilsparsh** [comment]
@debangi29 Thank you for providing your insight but it is not required as of now

**Comment by debangi29** [comment]
Okay , no problem 
Thank you
