### ISSUE TITLE
Title: Add new Project- AP, GP and HP calculator

### ISSUE THREAD

**Issue by debangi29** [swapnilsparsh/30DaysOfJavaScript#1625]
### Is your feature request related to a problem? Please describe.

Directly calculating nth term and sum of n terms of :
Arithmetic Progression 
Geometric Progression
Harmonic progression can be very helpful to students

### Describe the solution you'd like.

Adding a new Project- AP, GP, and HP calculator which can solve the problem in just one click!!!

### Describe alternatives you've considered.

The alternative solution is searching the internet/solving it tediously...!!

**Comment by swapnilsparsh** [comment]
@debangi29 Thank you for providing your insight but it is not required as of now
