### ISSUE TITLE
Title: Add a Ludo Game 

### ISSUE THREAD

**Issue by rohitinu6** [swapnilsparsh/30DaysOfJavaScript#1626]
### Which pre-existing JavaScript project will you be working on?

Ludo is a classic board game derived from the ancient Indian game Pachisi. Played by 2-4 players, each player has four tokens starting in their home base. The objective is to navigate all tokens around the board to the finish line, based on dice rolls.

### About Ludo

1. Blend of Luck and Strategy: Combines dice rolls with strategic decision-making, ensuring each game is unique and engaging.
2. Easy to Learn: Simple rules make it accessible to players of all ages.
3. Social Interaction: Encourages social bonding and friendly competition among players.
4. Colorful and Visual Appeal: The bright and colorful board adds to the game's fun and engaging nature.
5.Nostalgic Value: A timeless classic that evokes childhood memories and is enjoyed across generations.

![Screenshot 2024-06-02 230850](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/113301503/0568725c-bc8c-44f4-bfee-c2bd09c57e43)

### Anything you need to say to the Reviewers

I hope you assign me to add this game, which I have made purely using HTML, CSS & Javascript.
Please do add the GSSOC label.

**Comment by rohitinu6** [comment]
@swapnilsparsh Sir, this Ludo game is based completely on HTML, CSS & JavaScript and I believe that this project will surely add some value to the repository. If not then please let me know what is the issue with this.

**Comment by swapnilsparsh** [comment]
@rohitinu6 Come up with some new and unique ideas which are not present right not in our repo.
