### ISSUE TITLE
Title: Create a expense tracker

### ISSUE THREAD

**Issue by debangi29** [swapnilsparsh/30DaysOfJavaScript#1627]
### Is your feature request related to a problem? Please describe.

Tracking daily expenses is essential for college students who are new to handling money. It is very troublesome sometimes!!

### Describe the solution you'd like.

An app to keep track of daily expenses would make it easy

### Describe alternatives you've considered.

An alternative solution is writing it somewhere; But why not digitalise!? It will be more accurate than simply writing in a piece of paper

**Comment by swapnilsparsh** [comment]
@debangi29 Thank you for providing your insight but it is not required as of now

**Comment by debangi29** [comment]
Can you please provide me a detail about what kind of projects you are accepting as of now?
I want to contribute to your project...

**Comment by swapnilsparsh** [comment]
@debangi29 Come up with some new and unique ideas which are not present right not in our repo.
