### ISSUE TITLE
Title: Create a Concentration game(pair the matching cards)

### ISSUE THREAD

**Issue by aRUsh-codes** [swapnilsparsh/30DaysOfJavaScript#1628]
### Is your feature request related to a problem? Please describe.

Concentration is a round game in which all of the cards are laid face down on a surface and two cards are flipped face up over each turn. The object of the game is to turn over pairs of matching cards.

### Describe the solution you'd like.

I will develop a game using javascript with a beautiful UI and try different themes of cards like pokemon, trump, food, cartoons,etc.

### Describe alternatives you've considered.

none

### Add any other context or screenshots about the feature request here.

Please assign gssoc and level3 labels to this.
Thank You!

**Comment by swapnilsparsh** [comment]
@aRUsh-codes Thank you for providing your insight but it is not required as of now
