### ISSUE TITLE
Title: Add Day From The Date Calculator

### ISSUE THREAD

**Issue by Anshika14528** [swapnilsparsh/30DaysOfJavaScript#1630]
### Is your feature request related to a problem? Please describe.

I want to create a new calculator Like, if the date, month and year is given , we can instantly get the day.
For eg. : date : 19/05/2020
day : Tuesday

### Describe the solution you'd like.

I will make a  Day From The Date Calculator which will tell us the day from the date. 

### Describe alternatives you've considered.

I haven't considered any yet

**Comment by swapnilsparsh** [comment]
@Anshika14528 Thank you for providing your insight but it is not required as of now
