### ISSUE TITLE
Title: Add Area Calculator:

### ISSUE THREAD

**Issue by Anshika14528** [swapnilsparsh/30DaysOfJavaScript#1631]
### Is your feature request related to a problem? Please describe.

It will calculates the area of the any 2D shapes given for example rectangle , triangle , circle and square.
It will be really useful

### Describe the solution you'd like.

I want to make a calculator for this

### Describe alternatives you've considered.

I haven't considered any yet.

**Comment by swapnilsparsh** [comment]
@Anshika14528 Thank you for providing your insight but it is not required as of now
