### ISSUE TITLE
Title: Custom QR Code (12), can be made dynamic

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1633]
### Which pre-existing JavaScript project will you be working on?

Custom QR Code (12)

### Describe your enhancement/improvement

Custom QR Code (12), can be made dynamic. Currently, the QR code displayed is actually static...but it can be made to change everytime when a refresh button is pressed.

@swapnilsparsh 

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit It is made static only to follow one particular link.
