### ISSUE TITLE
Title: Adding erasing option in Drawing Pad (23)

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1634]
### Which pre-existing JavaScript project will you be working on?

Drawing Pad (23)

### Describe your enhancement/improvement

The current available option is the "Clear" option, which removes everything, thus its not a viable option for small changes. I want to add an eraser in the Drawing Pad (23). It will enhance the usability of the application, thus providing a better UX.

@swapnilsparsh 

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit All the best 👍🏻
