### ISSUE TITLE
[Bug] : Visitor Counter (14) is not working as intended

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1635]
### What happened?

The visitor counter application is not updating the visitor's count, as intended.

### How can we reproduce this bug?

![Screenshot (335)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/19f589c3-1c1e-4bb3-b4f2-e5cb8af87a38)

### Desktop Information (Optional)

Device: Laptop
OS : Windows 11 Home
Browser: Chrome

### Urgency (Optional)

High priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit All the best 👍🏻

**Comment by thecloudcode** [comment]
Hi, @swapnilsparsh , I have solved this issue earlier as well, kindly assign me this issue, I would love to work on it

**Comment by mondalsurojit** [comment]
@thecloudcode Hello, I am assigned and currently working on this...you can check other issues....If somehow, I fail to solve it, you can take over this issue...

**Comment by thecloudcode** [comment]
@mondalsurojit okey, go ahead

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any update ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh Actually I was pretty busy for past few day, really sorry for that...will be making a pr within 2-3 days

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any updates ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh I actually searched for any such API, that will give the visitor's count...but I didn't find any, so I decided to make my own API, its nearly made, just having some deployment issue....

https://github.com/mondalsurojit/Visitor-Counter-API

**Comment by swapnilsparsh** [comment]
@mondalsurojit No need to make your own visitor counter API, nevertheless I am going to remove this project.

**Comment by mondalsurojit** [comment]
@swapnilsparsh Its nearly made, actually. It will be very disheartening, if the project is removed now...
