### ISSUE TITLE
[Bug] : Image is getting repeated in Image Utility (49)

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1636]
### What happened?

While using the Image Utility (49) App, I found that as soon as I upload an image that is not an square. The image is getting repeted within the workspace

### How can we reproduce this bug?

This bug can be produced just by uploading an image. PS. The image should be a rectangular one (not a square one).

![Screenshot (336)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/41485102-c192-440a-baed-5ef410b27a72)

### Desktop Information (Optional)

Device: Laptop
OS: Windows 11 Home
Browser: Chrome

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit All the best 👍🏻
