### ISSUE TITLE
[Bug]: Reset button is not working in Projectile Motion Simulator (89) for several cases

### ISSUE THREAD

**Issue by mondalsurojit** [swapnilsparsh/30DaysOfJavaScript#1637]
### What happened?

When the velocity is high and the angle is steep, the body is moving out of the screen (which is okay), but when the reset button is pressed, its not getting reset and its getting restarted everytime.

### How can we reproduce this bug?

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/114282267/d7976022-0662-4770-a21f-7b34b231bada

In this video, I have reproduced the bug, with an example, velocity 900m/s and angle 89 degrees.

### Desktop Information (Optional)

Device: Laptop
OS: Windows 11 Home
Browser: Chrome

### Urgency (Optional)

Medium priority

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@mondalsurojit Fix both the things
1. Body is moving out of the screen.
2. Reset button not working properly.

**Comment by mondalsurojit** [comment]
@swapnilsparsh sure sir...

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any update ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh Within 4-5 days, I will be making a pr

**Comment by swapnilsparsh** [comment]
@mondalsurojit Any updates ?

**Comment by mondalsurojit** [comment]
@swapnilsparsh I actually searched for any such API, that will give the visitor's count...but I didn't find any, so I decided to make my own API, its nearly made, just having some deployment issue....

https://github.com/mondalsurojit/Visitor-Counter-API
