### ISSUE TITLE
Add a click cursor for light and dark theme

### ISSUE THREAD

**Issue by AkhilaSunesh** [swapnilsparsh/30DaysOfJavaScript#1639]
### What happened?

Replace arrow with click cursor for the buttons
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140897461/3b4bc420-d3ba-487e-8d8f-8416a00188de)

### How can we reproduce this bug?

Add specific code (edit)

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@AkhilaSunesh Thank you for providing your insight but it is not required as of now
