### ISSUE TITLE
Add Grocery Cart

### ISSUE THREAD

**Issue by NikhilMahana** [swapnilsparsh/30DaysOfJavaScript#164]
Wiring up a grocery cart for a ecommerce website.
I'm a gssoc'22 participant and want to take up this project.

**Comment by swapnilsparsh** [comment]
> Wiring up a grocery cart for a ecommerce website. I'm a gssoc'22 participant and want to take up this project.

Go ahead only if it's a basic JS project.
Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
> Wiring up a grocery cart for a ecommerce website. I'm a gssoc'22 participant and want to take up this project.

Update?

**Comment by NikhilMahana** [comment]
-Working on it.
