### ISSUE TITLE
Title: Add customised scrollbar

### ISSUE THREAD

**Issue by Sneha123-zudo** [swapnilsparsh/30DaysOfJavaScript#1640]
### Which pre-existing JavaScript project will you be working on?

I want to work on main page

### Describe your enhancement/improvement

I want to add customised scrollbar to the website which will improve the UI of the website.

### Add any other context or relevant screenshots about the enhancement here.

Please assign me this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Sneha123-zudo Thank you for providing your insight but it is not required as of now
