### ISSUE TITLE
Add the game of Yahtzee

### ISSUE THREAD

**Issue by pankhuri92** [swapnilsparsh/30DaysOfJavaScript#1641]
### Is your feature request related to a problem? Please describe.

I would like to add another game named 'Yahtzee' to the project.

### Describe the solution you'd like.

Yahtzee is a popular dice game played with five dice and a scorecard. The objective of the game is to score points by rolling specific combinations of dice. The game consists of thirteen rounds, and during each round, players take turns rolling the dice up to three times to try to achieve specific combinations.

Kindly assign me the issue under GSSOC'24

**Comment by pankhuri92** [comment]
Kindly assign me the issue.

**Comment by swapnilsparsh** [comment]
@pankhuri92 Thank you for providing your insight but it is not required as of now
