### ISSUE TITLE
Title: Spot the difference Game

### ISSUE THREAD

**Issue by Prabhatyadav60** [swapnilsparsh/30DaysOfJavaScript#1642]
### Is your feature request related to a problem? Please describe.

In this user has to spot the difference between two images and click on missing part then a pop up will show that he/she has marked correct point 
![pic1](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133522303/290aa5aa-0eb3-408b-9115-dbf2eab6a00f)
![pic2](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133522303/2890f111-7605-4da2-bd9c-ba413923afd1)

### Describe the solution you'd like.

in this I has used the concept of  bubbling and capturing of javascript .

### Describe alternatives you've considered.

No

### Add any other context or screenshots about the feature request here.

kindly assign me this issue with required  GSSoc'24 labels

**Comment by Prabhatyadav60** [comment]
@swapnilsparsh Kindly assign this issue to me . I can do it . I am GSSoC'24 contributor.

**Comment by swapnilsparsh** [comment]
@Prabhatyadav60 Thank you for providing your insight but it is not required as of now
