### ISSUE TITLE
Title: Add A Dark/Light Mode Animation

### ISSUE THREAD

**Issue by shreyash3087** [swapnilsparsh/30DaysOfJavaScript#1643]
### Is your feature request related to a problem? Please describe.

Various websites need custom made dark/light mode switch, web developers are always in the search of creative and cool looking switches for implementing this feature.

### Describe the solution you'd like.

Made a custom day/night animation using HTML/CSS/Javascript that can be used as a dark/light mode switch on website to enhance the user experience and provide a overall professional look to the website

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

**Demo Video-**

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/72603662/04c4b5a0-2bfd-42f6-bc84-065e453f40a4

**Additional Context:**

I am happy to contribute by implementing this feature myself. Please let me know if you have any feedback or additional requirements.

[X] I am a GSSOC'24 Contributor

Thank you for considering my request!

**Comment by swapnilsparsh** [comment]
@shreyash3087 Thank you for providing your insight but it is not required as of now
