### ISSUE TITLE
New game: Hit the hamster

### ISSUE THREAD

**Issue by suhanigupta23** [swapnilsparsh/30DaysOfJavaScript#1644]
### Is your feature request related to a problem? Please describe.

We can add a new game hit the hamster 

### Describe the solution you'd like.

A point is scored on each hit for hitting the hamster wherever appearing on the board and the total score is counted within a time frame of some seconds.

### Describe alternatives you've considered.

..

### Add any other context or screenshots about the feature request here.

<img width="1352" alt="Hit_the_hamster_game" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/144280247/c35a05ec-1f23-4dbc-9b17-ca24aaf48175">

**Comment by swapnilsparsh** [comment]
@suhanigupta23 Thank you for providing your insight but it is not required as of now
