### ISSUE TITLE
Title:  Add an UNO game with defined set of Rules Purely using JS, HTML, CSS

### ISSUE THREAD

**Issue by debangi29** [swapnilsparsh/30DaysOfJavaScript#1646]
### Is your feature request related to a problem? Please describe.

UNO game has many defined set of rules and can be very interesting playing with a computer!!
It can be a good Javascript Training as it has too many rules to handle
**Purely using JS, HTML, CSS**

### Describe the solution you'd like.

Adding a UNO game as a part of Tutorial

### Describe alternatives you've considered.

--

**Comment by debangi29** [comment]
Please assign me the issue @swapnilsparsh

**Comment by debangi29** [comment]
Please check the issue and assign it to me @swapnilsparsh 
thanks :)

**Comment by swapnilsparsh** [comment]
@debangi29 Thank you for providing your insight but it is not required as of now
