### ISSUE TITLE
Title: Add a candy Crush Game

### ISSUE THREAD

**Issue by debangi29** [swapnilsparsh/30DaysOfJavaScript#1647]
### Is your feature request related to a problem? Please describe.

 Candy Crush game has many defined set of rules and can be very interesting to play !!
It can be a good Javascript Training as it has too many rules to handle

### Describe the solution you'd like.

Adding a UNO game as a part of Tutorial

### Describe alternatives you've considered.

--

**Comment by swapnilsparsh** [comment]
@debangi29 Thank you for providing your insight but it is not required as of now
