### ISSUE TITLE
Add Cannibal and Missionaries game 

### ISSUE THREAD

**Issue by Rishi-Singhal21** [swapnilsparsh/30DaysOfJavaScript#1648]
### Is your feature request related to a problem? Please describe.

Cannibal and Missionaries is an AI based problem and this game is based on that Ai problem. In the missionaries and cannibals game three missionaries and three cannibals must cross a river using a boat which can carry at most two people, under the constraint that, for both banks, if there are missionaries present on the bank, they cannot be outnumbered by cannibals (if they were, the cannibals would eat the missionaries). The boat cannot cross the river by itself with no people on board. 

### Describe the solution you'd like.

I want to create a game named "Cannibal and Missionaries" using HTML, CSS and JavaScript only. 

### Describe alternatives you've considered.

I create this game in a way as mentioned: 
1. The game starts with all missionaries and cannibals on the right side.
2. Players move missionaries and cannibals to the boat by clicking on them, and then move the boat by clicking on it.
3. The game checks for invalid states (more cannibals than missionaries on either side) and winning states (all on the left side).

### Add any other context or screenshots about the feature request here.

@swapnilsparsh  Please assign me this issue under GSSoc'24 and add relevant labels as well.

**Comment by Rishi-Singhal21** [comment]
@swapnilsparsh Please assign me this issue under GSSoc'24.

**Comment by swapnilsparsh** [comment]
@Rishi-Singhal21 Thank you for providing your insight but it is not required as of now
