### ISSUE TITLE
Title: New Game Classing Pong Game

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1650]
### Which pre-existing JavaScript project will you be working on?

"Pong Game" is a two-player arcade game where each player controls a paddle. The players move their paddles vertically to hit a ball back and forth. The objective is to score points by getting the ball past the opponent's paddle.

### Describe your enhancement/improvement

Features
- **Responsive controls**: Each player can move their paddle up and down using designated keys.
- **Ball movement**: The ball moves across the screen, bouncing off the paddles and walls.
- **Scoring system**: Players earn points when the ball passes their opponent's paddle.
- **Game over condition**: The game ends when one player reaches a predetermined score.

### Anything you need to say to the Reviewers

There is a similar game, but it is for a single player, and it is more like Block Breaker game, rather than the classic Pong game.

### Add any other context or relevant screenshots about the enhancement here.

My game will look like this:
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/145102345/492a3818-0a99-4742-8b96-8a4d61dfaa55)

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 Thank you for providing your insight but it is not required as of now
