### ISSUE TITLE
Title: Gravity Game

### ISSUE THREAD

**Issue by Sara1428** [swapnilsparsh/30DaysOfJavaScript#1651]
### Is your feature request related to a problem? Please describe.

My issue is not related to any problem. 
I want to add an interesting project (game) in which one can enjoy a variety of gravity simulations.
First the user needs to select a celestial body of our solar system among the given options. Then a simulation of various balls of various shapes and colors colliding with each other and jumping under the influence of gravity is shown, until all the balls come at rest at the floor.
This way user can feel and enjoy the diverse gravitation of the planetary bodies our solar system.

### Describe the solution you'd like.

Objects of type Ball are created in JS, their colors and sizes are assigned randomly via Math.random().
Then, as per the type of celestial body selected by user, the value of gravity is adjusted, and then their motion is simulated by the adjusting the x and y attributes of the object according to the laws of motion.
**The collisions are assumed to be perfectly elastic.**

### Describe alternatives you've considered.

NAN

### Add any other context or screenshots about the feature request here.

![ss5](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146193518/d9048853-2fb3-4c8b-b0d1-f4b6e5bed93c)

**Comment by swapnilsparsh** [comment]
@Sara1428 Thank you for providing your insight but it is not required as of now
