### ISSUE TITLE
Search bar Modification

### ISSUE THREAD

**Issue by nileshsn** [swapnilsparsh/30DaysOfJavaScript#1652]
I can improve the search bar to be better than the current one. @swapnilsparsh , please assign me under GSSoC24.

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me. let's discuss

**Comment by Silentman87** [comment]
please assign me this issue i like to modify search bar..

**Comment by swapnilsparsh** [comment]
@nileshsn Thank you for providing your insight but it is not required as of now
