### ISSUE TITLE
One page for Contributors

### ISSUE THREAD

**Issue by pandeyji711** [swapnilsparsh/30DaysOfJavaScript#1653]
### Is your feature request related to a problem? Please describe.

@swapnilsparsh  I want to add one contributors page for your website

### Describe the solution you'd like.

With the help of api i fech contributos data 

Please assign me this issue

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me. let's discuss

**Comment by swapnilsparsh** [comment]
@pandeyji711 Thank you for providing your insight but it is not required as of now
