### ISSUE TITLE
Title: add copyright 

### ISSUE THREAD

**Issue by jayanththalla** [swapnilsparsh/30DaysOfJavaScript#1654]
### Is your feature request related to a problem? Please describe.

remove </> and add copyright

### Describe the solution you'd like.

add copyright 2024 with the symbol and remove the underline 
 making look good

### Describe alternatives you've considered.

it will looks good and better

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/121346142/4586e70d-c73c-4332-aa2f-a9c75506c8db)
please assign me @pa

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by swapnilsparsh** [comment]
@jayanththalla Thank you for providing your insight but it is not required as of now
