### ISSUE TITLE
Title:  Taash Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1655]
### Which pre-existing JavaScript project will you be working on?

I previously worked  on #1592 and #1365 

### Describe your enhancement/improvement

In Taash Game, the suits have no meaning. 
1. Number cards have a value equal to their number.
2. All the picture cards (Jacks, Queens, and Kings) are worth 10. 
3. Aces are worth 1.
4. The table keeps a record of total wins,loses and draws
5. Click on "Restart" Button to start a new game
6. Click on "Deal" Button to clear the field

### Add any other context or relevant screenshots about the enhancement here.

![Taash Game](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/ea10273f-69e4-4b39-b321-6d21e027fb8c)

**Comment by codewithganeshhh** [comment]
Assign me Mr @swapnilsparsh

**Comment by codewithganeshhh** [comment]
Can you please assign me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@codewithganeshhh All the best 👍🏻
