### ISSUE TITLE
Title: Binary To Decimal

### ISSUE THREAD

**Issue by divyansh-2005** [swapnilsparsh/30DaysOfJavaScript#1656]
### Is your feature request related to a problem? Please describe.

As project 33.Decimal To Binary already exists, but Binary To Decimal is not there.

### Describe the solution you'd like.

Converts binary numbers to decimal format.

### Describe alternatives you've considered.

Alternative approach could be to add a reverse button to 33.Decimal To Binary, so that is can do Binary To Decimal conversion.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/118552563/70674c5c-af37-4da3-9a0a-14daa66440eb)

**Comment by swapnilsparsh** [comment]
@divyansh-2005 Thank you for providing your insight but it is not required as of now
