### ISSUE TITLE
Title: Compound Interest Calculator

### ISSUE THREAD

**Issue by Ajita369** [swapnilsparsh/30DaysOfJavaScript#1658]
### Is your feature request related to a problem? Please describe.

There is no project which calculates compound interest in the project so I will like to add one . Please assign this issue to me under GSSOC'24. 

### Describe the solution you'd like.

I will create this using Javascipt , HTML & CSS.

### Describe alternatives you've considered.

No there is no alternative solution.

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me. let's discuss

**Comment by swapnilsparsh** [comment]
@Ajita369 Thank you for providing your insight but it is not required as of now
