### ISSUE TITLE
issue with BMI CALCULATOR

### ISSUE THREAD

**Issue by Lokeshsuwalka05** [swapnilsparsh/30DaysOfJavaScript#1659]
**Subject: GSSOC'24 Contribution: Handling Negative BMI Inputs in BMI Calculator**
Hi @swapnilsparsh ,

I'm interested in contributing to the project under GSSOC'24 and I came across the issue of the BMI calculator potentially accepting negative values for weight and height.

As BMI is a calculation involving only positive values, I believe it's important to address this to ensure accurate results.

I'd like to propose working on this issue to:

Implement checks to prevent negative weight and height inputs.
Handle these inputs gracefully, potentially by displaying an error message or indicating an invalid input state.
I've reviewed the BMI calculation and understand that a negative BMI wouldn't have a meaningful interpretation.

Please let me know if this issue is open for contribution under GSSOC'24 and if there are any specific guidelines I should follow.  I'm eager to contribute to the project.

Thanks,
Lokesh Suwalka

<img width="521" alt="first" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105945491/bc4ad697-32d3-4426-877e-89a09335cac9">
<img width="527" alt="second" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105945491/0bbb97e4-f826-4456-b0a4-828f152ee1d3">

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by swapnilsparsh** [comment]
@Lokeshsuwalka05 All the best 👍🏻

**Comment by Lokeshsuwalka05** [comment]
thank you @swapnilsparsh 
i will update you after two days,
because my exam is finally over.

**Comment by AratiAmbekar** [comment]
Please assign this issue to me
