### ISSUE TITLE
issue with angle in Projectile motion

### ISSUE THREAD

**Issue by Lokeshsuwalka05** [swapnilsparsh/30DaysOfJavaScript#1661]
**Title: Missing input validation for angle (0 ≤ theta ≤ 90)**

**Description:**

The current implementation allows users to enter angles outside the valid range (0 degrees to 90 degrees inclusive). While the code enforces the range mathematically, it doesn't provide any user feedback to indicate an invalid entry.

**Proposed improvement:**

To improve the user experience, it's recommended to implement a pop-up or error message that appears when the user enters an angle less than 0 degrees or greater than 90 degrees. This message should clearly state that the entered value is outside the valid range and guide the user to enter a value within the specified limits (0 ≤ theta ≤ 90).

<img width="960" alt="third" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105945491/ffac88f7-74a4-4359-8aa3-5d8e14d1a256">

**Comment by Lokeshsuwalka05** [comment]
@swapnilsparsh

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me. let's discuss

**Comment by swapnilsparsh** [comment]
@Lokeshsuwalka05 There is already an issue open related to this

**Comment by Lokeshsuwalka05** [comment]
Ok,sir
