### ISSUE TITLE
Title:Spy Number Checker

### ISSUE THREAD

**Issue by poseidonsanket** [swapnilsparsh/30DaysOfJavaScript#1662]
### Is your feature request related to a problem? Please describe.

Want to add a Spy Number Checker Feature.
A spy number is defined as a number whose sum of digits is equal to the product of its digits.

**Can you please assign me this issue under Gssoc 2024**

### Describe the solution you'd like.

![Spy-Number-Checker](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/112609618/16afbf04-e549-4de2-8fa6-7928bc8818cf)

### Describe alternatives you've considered.
Can also add a **Armstrong Number Checker** and **Prime Number Checker** in the Project

**Comment by poseidonsanket** [comment]
@swapnilsparsh please assign me this issue

**Comment by poseidonsanket** [comment]
![Capture](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/112609618/7e0e3453-f60a-453c-a190-58c73f37944f)

**Comment by swapnilsparsh** [comment]
@poseidonsanket Thank you for providing your insight but it is not required as of now
