### ISSUE TITLE
Title: Add a Fruit Slicer Game

### ISSUE THREAD

**Issue by sau-mili** [swapnilsparsh/30DaysOfJavaScript#1663]
### Is your feature request related to a problem? Please describe.

No, addition of a new game

### Describe the solution you'd like.

I would like to add this game

### Describe alternatives you've considered.

Add this game

**Comment by swapnilsparsh** [comment]
@sau-mili Thank you for providing your insight but it is not required as of now

**Comment by sau-mili** [comment]
@swapnilsparsh may I know what kind of projects you actually want? You closed my previous Issue as unplanned as well

**Comment by swapnilsparsh** [comment]
@sau-mili Come up with some new and unique ideas which are not present right not in our repo.

**Comment by sau-mili** [comment]
Your repo neither has none of the projects that I suggested.. anagram checker/ fruit slicer/ loan calculation..

**Comment by swapnilsparsh** [comment]
@sau-mili Come up with some new and unique ideas which are not present right not in our repo.
