### ISSUE TITLE
Title: Loan EMI Calculator

### ISSUE THREAD

**Issue by sau-mili** [swapnilsparsh/30DaysOfJavaScript#1664]
### Is your feature request related to a problem? Please describe.

There is no such project in this repo

### Describe the solution you'd like.

I would  like to add this project

### Describe alternatives you've considered.

![Screenshot 2024-06-04 172522](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146661411/f3da8888-b6d4-49d2-8d95-65781b104e9f)

**Comment by leo-1228** [comment]
It's not clear, describe more exactly. I am web developer with rich experience.

**Comment by swapnilsparsh** [comment]
@sau-mili Thank you for providing your insight but it is not required as of now
