### ISSUE TITLE
Title: Hovering effects in Cards

### ISSUE THREAD

**Issue by aanchalpahuja18** [swapnilsparsh/30DaysOfJavaScript#1665]
### Which pre-existing JavaScript project will you be working on?

The homepage of the entire website

### Describe your enhancement/improvement

Adding the hovering effects on cards will improve the UI of the entire website.

**Comment by aanchalpahuja18** [comment]
@swapnilsparsh Kindly assign me this issue I will solve it really quick. Thankyou!

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me.

**Comment by swapnilsparsh** [comment]
@aanchalpahuja18 Thank you for providing your insight but it is not required as of now
