### ISSUE TITLE
Title: Improving the footer of home page

### ISSUE THREAD

**Issue by tanushri1506** [swapnilsparsh/30DaysOfJavaScript#1666]
### Which pre-existing JavaScript project will you be working on?

Home page

### Describe your enhancement/improvement

Improving the footer of Home page.
![issue2](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/125864601/a043f706-3903-4873-abd8-c3f8c79b4019)

**Comment by leo-1228** [comment]
I am web developer with rich experience with rich experience. assign to me.

**Comment by swapnilsparsh** [comment]
@tanushri1506 Thank you for providing your insight but it is not required as of now
