### ISSUE TITLE
Title: Make the website more attractive

### ISSUE THREAD

**Issue by Sambit-Mondal** [swapnilsparsh/30DaysOfJavaScript#1668]
### Is your feature request related to a problem? Please describe.

I've checked the whole website, and it's too simple for such a great project like this. I believe the website has a great potential.

### Describe the solution you'd like.

I want to add some minimal colour effects to the background, hover effects to the buttons and the project boxes, and a simple cursor trail animation, which will definitely boost the overall UI of the website and make it more attractive, thus holding the user's attention.

### Describe alternatives you've considered.

- None -

**Comment by leo-1228** [comment]
this is my telegram @leo1228codeforce . contact me.

**Comment by 143divya** [comment]
I'm new to open source , can you please assign this to me under Gssoc 24

**Comment by swapnilsparsh** [comment]
@Sambit-Mondal Thank you for providing your insight but it is not required as of now
