### ISSUE TITLE
Title: Learn to Code a Live Web App Editor - (CodePen Clone)

### ISSUE THREAD

**Issue by harini-1597** [swapnilsparsh/30DaysOfJavaScript#1669]
### Is your feature request related to a problem? Please describe.

Codepen is the go-to website for all web developers, as it allows you to instantly code, edit and view your designs. Also, this project is 30 Days of JS, so the editor would be a good practical approach to view designs, **all in one place**

### Describe the solution you'd like.

The following is a Codepen clone coded exlusively in HTML CSS JS

### Describe alternatives you've considered.

HTML, CSS, JS

*Do assign it to me under the gssoc label, thanks.*

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/128628820/17c18ad0-72aa-4d84-ac08-631992a0c448

**Comment by swapnilsparsh** [comment]
@harini-1597 Thank you for providing your insight but it is not required as of now
