### ISSUE TITLE
Title:  Improvement in the header section.

### ISSUE THREAD

**Issue by agrwal697** [swapnilsparsh/30DaysOfJavaScript#1670]
### Which pre-existing JavaScript project will you be working on?

I will be working on the travel_website of the javascript project.

### Describe your enhancement/improvement

I think, If we add Improvement in the header section in the login page. It will change the looks good and improves the UI of the website.

So please Assign me this issue with the GSSOC Label and level also , I would like to work on it.

### Add any other context or relevant screenshots about the enhancement here.

screenshots:

Before:

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/128716726/911efee4-c5e5-468b-bebf-7e232f1a7308)

After:

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/128716726/157f14c2-5bf6-4f76-9ea4-c7295f01ddd7)

**Comment by swapnilsparsh** [comment]
@agrwal697 Thank you for providing your insight but it is not required as of now
