### ISSUE TITLE
Title: Adding customizable QR Code Generator 

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [swapnilsparsh/30DaysOfJavaScript#1671]
I would like to contribute to this repository by adding QR code generator. This QR code generator can generate QR code for text, contact information, WIFI network details and URL's. And will provide customization options like size, color and error correction level. And will provide download option with png extension.

I am a GSSoC contributor.
Could you please assign this issue to me?
@swapnilsparsh

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by swapnilsparsh** [comment]
@sarayusreeyadavpadala Thank you for providing your insight but it is not required as of now
