### ISSUE TITLE
Title:  Single Page Application

### ISSUE THREAD

**Issue by kyra-09** [swapnilsparsh/30DaysOfJavaScript#1672]
### Is your feature request related to a problem? Please describe.

SPA is a web app with a single page, limited features, and no refresh option. I will create a web page that doesn’t reload every time someone clicks on the side links but will change the content.  It will be a great project for me to work as a beginner.
Tech Stack :- HTML , CSS , JS

### Describe the solution you'd like.

Using HTML , CSS and JS creating a single page application about giving introduction to deep learning and machine learning and many more other functionalities.

### Describe alternatives you've considered.

Using HTML , CSS and JS creating a single page application about giving introduction to deep learning and machine learning and many more other functionalities.

**Comment by swapnilsparsh** [comment]
@kyra-09 Thank you for providing your insight but it is not required as of now

**Comment by kyra-09** [comment]
Pardon me @swapnilsparsh but I'm not able to understand why these projects addition requests of mine getting rejected ? I can make a responsive web page which will give introduction of basic machine learning and it's functionalities using HTML , CSS and Js.

**Comment by swapnilsparsh** [comment]
@kyra-09 Come up with some new and unique ideas which are not present right not in our repo.

**Comment by kyra-09** [comment]
I didn't see any existing projects related to machine learning web page...I have an idea of an impressive UI design and stuff to add also I have a deep understanding of ml/dl..I want to combine both of these ideas into this project.

**Comment by kyra-09** [comment]
I didn't see any existing project related to ml/dl web page..I have an idea of an impressive UI for the web page..I also have a deep understanding of ml/dl and I want to combine both of these ideas.
