### ISSUE TITLE
Title: Pairs Game using JS

### ISSUE THREAD

**Issue by kyra-09** [swapnilsparsh/30DaysOfJavaScript#1674]
### Is your feature request related to a problem? Please describe.

The logic of the game will be:
1.  There are a given number of cards on the table facing down.
2.  The player needs to find all the pairs.

### Describe the solution you'd like.

I will use different images to create match cards game and implement it using HTML , CSS and JS.
I can also integrate the time limiting feature as well as restrict the number of guesses to make it more fun and competitive.

### Describe alternatives you've considered.

None

@swapnilsparsh  kindly assign the issue to me.

**Comment by swapnilsparsh** [comment]
@kyra-09 Thank you for providing your insight but it is not required as of now
