### ISSUE TITLE
Title: Alarm Clock 

### ISSUE THREAD

**Issue by MadMax1311** [swapnilsparsh/30DaysOfJavaScript#1675]
### Is your feature request related to a problem? Please describe.

When we have an important meeting and we can't wake up early at that time, it works.

### Describe the solution you'd like.

Alarm clock that helps with waking up early using beep sounds.

### Describe alternatives you've considered.

Say to your for an important meeting and he/ she will call you and wake up early

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by swapnilsparsh** [comment]
@MadMax1311 Thank you for providing your insight but it is not required as of now
