### ISSUE TITLE
Title: Add a section to submit new project of Java Script

### ISSUE THREAD

**Issue by ananyag309** [swapnilsparsh/30DaysOfJavaScript#1676]
### Is your feature request related to a problem? Please describe.

Below at the end at footer we can add a form where user can submit new project, we can take project name and their git acc as input. 
Please assign me it under gssoc @swa

### Describe the solution you'd like.

This will be a great option to keep on adding new and updating project.

### Describe alternatives you've considered.

Either we can add a new page or better would be a pop up form on the same site.

**Comment by swapnilsparsh** [comment]
@ananyag309 Thank you for providing your insight but it is not required as of now
