### ISSUE TITLE
Title:  want to add hover to different boxes

### ISSUE THREAD

**Issue by Shreyaa173** [swapnilsparsh/30DaysOfJavaScript#1678]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like.

want to add hover to different boxes

### Describe alternatives you've considered.

no

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-06 171847](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/144673309/6b87c261-0884-4ff4-b14f-15c1f27817be)

**Comment by Gokilp** [comment]
please assign me this issue...

**Comment by kashi-verma** [comment]
As a enthusiastic contributor I'm willingly want to contribute in such good projects . so I request to @swapnilsparsh  to assign me this issue.

**Comment by swapnilsparsh** [comment]
@Shreyaa173 Thank you for providing your insight but it is not required as of now

**Comment by kashi-verma** [comment]
Ohkk no issue
