### ISSUE TITLE
Title:  Improved Design of Currency Converter

### ISSUE THREAD

**Issue by eiva078** [swapnilsparsh/30DaysOfJavaScript#1684]
### Which pre-existing JavaScript project will you be working on?

Currency Converter

### Describe your enhancement/improvement

Incorporate images for each currency flags and conversion arrows.
Choose a clean and professional font for better readability and style.
Optimize the layout for various devices, ensuring a seamless experience on desktops, tablets, and smartphones.

![Screenshot 2024-06-07 081305](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/100897650/998ffbe2-1afc-4940-bdfd-8cbf8a9daf1e)
This image is just for reference that each country will have its own flag also

### Add any other context or relevant screenshots about the enhancement here.

@swapnilsparsh Please assign this issue to me under GSSOC 24

**Comment by swapnilsparsh** [comment]
@eiva078 All the best 👍🏻

**Comment by eiva078** [comment]
> @eiva078 All the best 👍🏻

Sir please give the level also...
