### ISSUE TITLE
Title: i want to add Periodic table game

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1685]
### Is your feature request related to a problem? Please describe.

i want to add Periodic table game

### Describe the solution you'd like.

Game logic and basic description : there 2 page index => shows all elements , game page = > user needs to find symbol of provided elements.

### Describe alternatives you've considered.

Game points: if select correct element score increase . if wrong element selected then deducted.

### Add any other context or screenshots about the feature request here.

![Screenshot (694)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/599aa348-a806-41f9-9f8c-d457bd1faa3e)
![Screenshot (695)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/c1ffb98d-cedb-4283-82ab-cdbd7031cf4c)

**Comment by Vipullakum007** [comment]
hey @swapnilsparsh , please assign i have made it already.

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now
