### ISSUE TITLE
Title: Mancala Game

### ISSUE THREAD

**Issue by manishh12** [swapnilsparsh/30DaysOfJavaScript#1686]
### Is your feature request related to a problem? Please describe.

I want to add a new game. It is called Mancala.

### Describe the solution you'd like.

Mancala is a two-player board game that has been played for centuries across various cultures. The game typically consists of a wooden board with 12 small pits or cups, arranged in two rows, with a larger scoring pit at each end called the "mancala". Each player controls the six cups on their side of the board, and the goal is to collect the most stones or seeds in your mancala by the end of the game.

### Describe alternatives you've considered.

Game points
Multiplayer modes
Engaging visuals and animations

### Add any other context or screenshots about the feature request here.

I am GSSOC'24  Contributor.

**Comment by manishh12** [comment]
@swapnilsparsh Kindly assign me this issue.

**Comment by swapnilsparsh** [comment]
@manishh12 All the best 👍🏻

**Comment by swapnilsparsh** [comment]
@manishh12 Any update ?

**Comment by manishh12** [comment]
@swapnilsparsh  yes will create the PR  till tonight.
