### ISSUE TITLE
Title: i want to add Toast notification 

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1687]
### Which pre-existing JavaScript project will you be working on?

Game logic and basic description : The toast notification game is a simple web-based game where clicking a button generates toast notifications with random messages and types. These notifications appear on the screen and disappear after a short duration.

### Describe your enhancement/improvement

Game logic and basic description : The toast notification game is a simple web-based game where clicking a button generates toast notifications with random messages and types. These notifications appear on the screen and disappear after a short duration.

## Game points :
Randomized Content: Generates notifications with random messages and types (info, success, error) for variety.
Auto-Removal: Notifications disappear after 3 seconds, ensuring a clean UI.
Dynamic Creation: Clicking the button creates a new notification, enhancing interactivity.
Reusable Functions: Separate functions handle random message/type generation, making the code modular and easy to extend.

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/400d74fc-902d-4029-8127-363dcf47140b)

**Comment by Vipullakum007** [comment]
hey @swapnilsparsh , please assign i have already made it .

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now
