### ISSUE TITLE
Title: FOOTER CAN BE BEAUTIFIED

### ISSUE THREAD

**Issue by Aashka19** [swapnilsparsh/30DaysOfJavaScript#1689]
### Which pre-existing JavaScript project will you be working on?

NONE

### Describe your enhancement/improvement

USING CSS FOOTER CAN BE BEAUTIFIED TO SOMETHING MORE SOOTHING TO USER'S EYES

### Add any other context or relevant screenshots about the enhancement here.

![Uploading Screenshot 2024-06-07 at 11.56.34 AM.png…]()

**Comment by Aashka19** [comment]
Please assign this issue to me

**Comment by swapnilsparsh** [comment]
@Aashka19 Thank you for providing your insight but it is not required as of now
