### ISSUE TITLE
Title: NAVBAR

### ISSUE THREAD

**Issue by Aashka19** [swapnilsparsh/30DaysOfJavaScript#1690]
### Which pre-existing JavaScript project will you be working on?

NONE

### Describe your enhancement/improvement

Adding a navbar can enhance the website and the space looking bland can be utilised and site will be easier for users to use

### Add any other context or relevant screenshots about the enhancement here.

<img width="1168" alt="Screenshot 2024-06-07 at 11 59 59 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/157134139/e880519d-3354-41b0-b98c-91e0124f5368">

**Comment by Aashka19** [comment]
Please assign this issue to me

**Comment by swapnilsparsh** [comment]
@Aashka19 Thank you for providing your insight but it is not required as of now
