### ISSUE TITLE
Title: Adding Background Changer Project

### ISSUE THREAD

**Issue by Pranav0606** [swapnilsparsh/30DaysOfJavaScript#1691]
### Is your feature request related to a problem? Please describe.

A simple background color changer which will help developers to pick the colors for the projects.

### Describe the solution you'd like.

I will provide the simple solution with simple UI user will be able to pick the color and his color code will be available to user for further use.

### Describe alternatives you've considered.

Simple clean UI which will help user to pick the colors for their pojects.

### Add any other context or screenshots about the feature request here.

**Screenshot of working model :** 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/97611449/47d08b60-9afb-4a21-86da-baa6d2818011)

**Comment by swapnilsparsh** [comment]
@Pranav0606 Thank you for providing your insight but it is not required as of now
