### ISSUE TITLE
Title: Drag and Drop API

### ISSUE THREAD

**Issue by zalabhavy** [swapnilsparsh/30DaysOfJavaScript#1692]
### Which pre-existing JavaScript project will you be working on?

I want to add Drag and Drop API code with Java-Script.

### Describe your enhancement/improvement

I will make two div in that there is li present.
You can drag and drop to another div box.

**Comment by zalabhavy** [comment]
@swapnilsparsh please assign me this task!

**Comment by swapnilsparsh** [comment]
@zalabhavy Thank you for providing your insight but it is not required as of now
