### ISSUE TITLE
Title: adding social media icons

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1693]
### Is your feature request related to a problem? Please describe.

communication

### Describe the solution you'd like.

adding social media

### Describe alternatives you've considered.

adding social media

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by Pjdash** [comment]
I will add all the required social media icons from the icon library will add the hover effect . Can you plz assign this issue to me .Also plz add the labels

**Comment by swapnilsparsh** [comment]
@Pjdash Thank you for providing your insight but it is not required as of now
