### ISSUE TITLE
[Bug Title here] no hover effect in footer and search bar

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1694]
### What happened?

hover effect

### How can we reproduce this bug?

adding hover effect

### Urgency (Optional)

High priority

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
