### ISSUE TITLE
Title: adding nav bar.

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1695]
### Is your feature request related to a problem? Please describe.

no nav bar.

### Describe the solution you'd like.

adding nav bar.

### Describe alternatives you've considered.

adding nav bar.

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by Pjdash** [comment]
I will add the add the responsive navbar .Can you plz assign this issue to me

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
