### ISSUE TITLE
Title: updating footer

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1696]
### Is your feature request related to a problem? Please describe.

bad footer

### Describe the solution you'd like.

updating footer

### Describe alternatives you've considered.

updating footer

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by manojk765** [comment]
The navbar is an essential component of a website at present your website does not contain any Navbar, A Beautiful navbar can be added to catch viewer's attention. I want to work on this project by adding a sleek and subtle navbar with a simple description of the site and a search bar implementation.  Please assign this to me.

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
