### ISSUE TITLE
Title: updating complete UI of web site

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1697]
### Is your feature request related to a problem? Please describe.

no attractive thing

### Describe the solution you'd like.

updating complete UI of web site

### Describe alternatives you've considered.

updating complete UI of web site

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
