### ISSUE TITLE
Title: adding Currency Converter using JS

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1698]
### Is your feature request related to a problem? Please describe.

new project

### Describe the solution you'd like.

adding Currency Converter using JS

### Describe alternatives you've considered.

adding Currency Converter using JS

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by Pjdash** [comment]
I can  work with this issue it will just need me to fetch the Api .I will also design  a nice frontend for this currency converter .Plz assign this issue to me

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
