### ISSUE TITLE
Title: adding Rock Paper Scissors game using JS

### ISSUE THREAD

**Issue by dnyandeepchute** [swapnilsparsh/30DaysOfJavaScript#1699]
### Is your feature request related to a problem? Please describe.

new project

### Describe the solution you'd like.

adding Rock Paper Scissors game using JS

### Describe alternatives you've considered.

adding Rock Paper Scissors game using JS

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by Mehul237** [comment]
Please assign to me ASAP!

**Comment by mondalsurojit** [comment]
@dnyandeepchute This game is already available...See 37 - RPS Game

**Comment by swapnilsparsh** [comment]
@dnyandeepchute Thank you for providing your insight but it is not required as of now
