### ISSUE TITLE
Add a Tip Calculator

### ISSUE THREAD

**Issue by yashikhare** [swapnilsparsh/30DaysOfJavaScript#170]
I want to add a Tip calculator which takes billing amount, type of service, and a number of persons as input.
 As per the three inputs it generates a tip for the serving person.
can you please assign this issue to me?

**Comment by yashikhare** [comment]
hello, I have to work on this issue or not?
as i have already made the project and I have to just make a pull request for it

**Comment by swapnilsparsh** [comment]
> 

There is a deadline for an Issue that is assigned to you and if you are unable to make a PR or inform me then the issue will be transferred to someone else.
So try to be active and Good Luck 👍🏻

**Comment by yashikhare** [comment]
ok

**Comment by yashikhare** [comment]
Actually this is my first time making the contribution, so I thought atleast Four days would be given to complete the project.

**Comment by swapnilsparsh** [comment]
> Actually this is my first time making the contribution, so I thought atleast Four days would be given to complete the project.

Appreciate your efforts but 3 days were given if you want extra time then you have to inform that you want extra time.

**Comment by yashikhare** [comment]
ok
