### ISSUE TITLE
Title: Footer Update

### ISSUE THREAD

**Issue by manojk765** [swapnilsparsh/30DaysOfJavaScript#1700]
### Which pre-existing JavaScript project will you be working on?

I am currently not working on any pre-existing java script projects.

### Describe your enhancement/improvement

The footer is a crucial component of a website as it provides an overview of important site details at a glance. While the current footer serves its purpose, there is an opportunity to enhance its design to make it more engaging and visually appealing.Hence I would like t0 contribute for this project by creating a beautiful footer. Please assign this role to me.

**Comment by manojk765** [comment]
It would be my great pleasure to work on this project please assign this role to me.

**Comment by swapnilsparsh** [comment]
@manojk765 Thank you for providing your insight but it is not required as of now
