### ISSUE TITLE
Title: Implementing Word Shuffle Game using JavaScript

### ISSUE THREAD

**Issue by thevijayshankersharma** [swapnilsparsh/30DaysOfJavaScript#1701]
### Is your feature request related to a problem? Please describe.

Currently, there is a need for an engaging word game within our application, and integrating Word Shuffle using JavaScript provides an ideal solution.

### Describe the solution you'd like.

I propose to implement the Word Shuffle game using JavaScript, allowing users to enjoy a fun and interactive word puzzle experience directly within our application. This implementation will provide users with entertainment and cognitive stimulation while enhancing user engagement and retention.

### Describe alternatives you've considered.

Alternative options such as developing a different word game from scratch or integrating a third-party word game library exist, but they may require more development time and resources. Integrating Word Shuffle using JavaScript offers a convenient and efficient solution due to its simplicity and popularity.

**Comment by Mehul237** [comment]
Please assign to me this Task, ASAP!

**Comment by swapnilsparsh** [comment]
@thevijayshankersharma Thank you for providing your insight but it is not required as of now
