### ISSUE TITLE
I want to add a Meme Generator Project made using HTML, CSS and Javascript  with proper API fetching. I want to contribute under GSSOC'24. 

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [swapnilsparsh/30DaysOfJavaScript#1703]
### Is your feature request related to a problem? Please describe.

No it is not a problem. It is an addition to the list of projects.

### Describe the solution you'd like.

I wish to add my project made using the tech stacks HTML, CSS and Javascript  using proper APIs.

### Describe alternatives you've considered.

I wish to add this project in the list and will work on this to the best of my ability. 

### Add any other context or screenshots about the feature request here.

Here is an SS of my project : 

![Screenshot_20240607-192833_Samsung Internet](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/123104247/6cb967fa-844c-406e-bfea-4d5b416f8871)

@swapnilsparsh Thank you for considering my issue.

**Comment by mondalsurojit** [comment]
@ParnaRoyChowdhury777 Actually a simillar project exists...15 - Joke Generator

**Comment by swapnilsparsh** [comment]
@ParnaRoyChowdhury777 Thank you for providing your insight but it is not required as of now
