### ISSUE TITLE
Title:Add styling to project cards. 

### ISSUE THREAD

**Issue by soniya-malviy** [swapnilsparsh/30DaysOfJavaScript#1704]
### Which pre-existing JavaScript project will you be working on?

Adding styling to project cards for better user experience and enhance website.

### Describe your enhancement/improvement

Adding hover on cards.
Adding hover on buttons.
Adding colour.

**Comment by swapnilsparsh** [comment]
@soniya-malviy Thank you for providing your insight but it is not required as of now
