### ISSUE TITLE
Interactive Key Code Display: Real-time Key Identification and Display

### ISSUE THREAD

**Issue by deepak00944** [swapnilsparsh/30DaysOfJavaScript#1706]
### Which pre-existing JavaScript project will you be working on?

It is an addition to this list.

### Describe your enhancement/improvement

This JavaScript project is an interactive tool designed to display key codes and names in real-time as you press any button on your keyboard. The application captures keypress events and dynamically updates the screen to show the corresponding key code and name, providing an immediate and intuitive way to identify any key on the keyboard.

### Add any other context or relevant screenshots about the enhancement here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119965267/932d818c-3591-460d-a943-316ab258c23e)

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119965267/8277942a-8cf9-4d3f-87d8-8c2de6c10aa1)

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119965267/1e673575-d32f-4524-8fe3-552d9c08fc9c)

**Comment by swapnilsparsh** [comment]
@deepak00944 Thank you for providing your insight but it is not required as of now
