### ISSUE TITLE
BUG 🐞: Dark mode gets turned off on refreshing the page 

### ISSUE THREAD

**Issue by aslams2020** [swapnilsparsh/30DaysOfJavaScript#1708]
### What happened?

Hey @swapnilsparsh,
Here is the issue - 
The dark mode preference does not persist across page refreshes.
Each time the page is refreshed, the mode resets to the default instead of maintaining the user-selected mode (dark or light).
I think it is due to the theme state is not being persisted when the page is refreshed.

### How can we reproduce this bug?

**To Reproduce**
1. Go to the website.
2. Toggle the dark mode switch to change the theme.
3. Refresh the page.
4. Observe that the theme reverts to the default mode instead of retaining the selected mode.

**Screenshots** 
- Before refreshing the page looks like(currently in dark mode) :

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/131389695/1020986c-2324-463c-a9e8-6fd7c2371af2)

- After refreshing the page :

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/131389695/28f94380-6f5c-4201-a7ce-98a0c2d999f5)

**Expected behavior**
The selected dark or light mode should persist across page refreshes.
If a user selects dark mode, the page should remain in dark mode even after refreshing.

I hope I was able to explain the issue.
If so, Could you please assign this issue to me under GSSoC 24?

### Desktop Information (Optional)

OS : Windows
Browser : Google Chrome

### Urgency (Optional)

Medium priority

**Comment by aslams2020** [comment]
@swapnilsparsh, Could you Please take a look and review it ?

**Comment by swapnilsparsh** [comment]
@aslams2020 All the best 👍🏻
