### ISSUE TITLE
Title: i want to add Technical Mind Game

### ISSUE THREAD

**Issue by Vipullakum007** [swapnilsparsh/30DaysOfJavaScript#1709]
### Which pre-existing JavaScript project will you be working on?

i want to add project technical mind game. there is memory game for technical persons

### Describe your enhancement/improvement

i want to add project technical mind game. there is memory game for technical persons

### Anything you need to say to the Reviewers

play the game and fun . if any issue found then say to me

### Add any other context or relevant screenshots about the enhancement here.

Home Page:

![Screenshot 2024-06-08 133704](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/06e3ade5-3bef-4594-bd0a-5f39d516cf2e)

After start

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/127659443/6d367393-4a73-4ec3-8e76-6d3b445f042b)

**Comment by Vipullakum007** [comment]
hey @swapnilsparsh , please assign to me i have already made it.

**Comment by swapnilsparsh** [comment]
@Vipullakum007 Thank you for providing your insight but it is not required as of now
