### ISSUE TITLE
Summary for each Challenge

### ISSUE THREAD

**Issue by techSun-07** [swapnilsparsh/30DaysOfJavaScript#171]
I want to add a short summary for each and every challenge so that a newbie when lands to the website can get to know about the  particular challenge.
Things we can add in summary :-
1)Description of the project.
2)language in which the particular challenge is made
3)FunFact of the same challenge

**Comment by swapnilsparsh** [comment]
> I want to add a short summary for each and every challenge so that a newbie when lands to the website can get to know about the particular challenge. Things we can add in summary :- 1)Description of the project. 2)language in which the particular challenge is made 3)FunFact of the same challenge

Great idea 😍
Just one correction that language used in all projects are JS so you can add what new things are there rather than plain JS

**Comment by techSun-07** [comment]
ok great 
thanks for assigning 
will work on it.

**Comment by swapnilsparsh** [comment]
> ok great thanks for assigning will work on it.

Update?
