### ISSUE TITLE
added random dice winner

### ISSUE THREAD

**Issue by shuhaki** [swapnilsparsh/30DaysOfJavaScript#1710]
### Is your feature request related to a problem? Please describe.

two players play the game the value of player is win

### Describe the solution you'd like.

two players play the game the value of player is win

### Describe alternatives you've considered.

two players play the game the value of player is win

### Add any other context or screenshots about the feature request here.

![Uploading Screenshot 2024-06-01 at 2.30.44 PM.png…]()

**Comment by swapnilsparsh** [comment]
@shuhaki Thank you for providing your insight but it is not required as of now
