### ISSUE TITLE
Add a one piece anime quiz game

### ISSUE THREAD

**Issue by samarsajad** [swapnilsparsh/30DaysOfJavaScript#1716]
### Is your feature request related to a problem? Please describe.

A simple game to enhance your one piece knowledge

### Describe the solution you'd like.

Quick recap of all the major fun arcs of one piece

### Describe alternatives you've considered.

mobile apps but they take up a lot of your phone storage

**Comment by samarsajad** [comment]
Please assign this issue to me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@samarsajad Thank you for providing your insight but it is not required as of now
