### ISSUE TITLE
Title: Hover effect on cards

### ISSUE THREAD

**Issue by dishathakurata** [swapnilsparsh/30DaysOfJavaScript#1717]
### Which pre-existing JavaScript project will you be working on?

HTML and CSS

### Describe your enhancement/improvement

Adding hover effect on each cards will make it look attractive.

### Add any other context or relevant screenshots about the enhancement here.

Assign this issue to me under GSSoC.
My code is ready, I'm just waiting for this issue to be assigned to me.

**Comment by root-0101** [comment]
Hey @swapnilsparsh please assign me this issue

**Comment by swapnilsparsh** [comment]
@dishathakurata Thank you for providing your insight but it is not required as of now
