### ISSUE TITLE
Title: Adding dynamic copyright year

### ISSUE THREAD

**Issue by dishathakurata** [swapnilsparsh/30DaysOfJavaScript#1718]
### Which pre-existing JavaScript project will you be working on?

Copyright

### Describe your enhancement/improvement

Adding dynamic copyright year which will change every year automatically without any manual effort, will make your website look more professional.

### Anything you need to say to the Reviewers

Assign this issue to me under GSSoC.

**Comment by swapnilsparsh** [comment]
@dishathakurata Thank you for providing your insight but it is not required as of now
