### ISSUE TITLE
Title: Hover effect on buttons

### ISSUE THREAD

**Issue by dishathakurata** [swapnilsparsh/30DaysOfJavaScript#1719]
### Which pre-existing JavaScript project will you be working on?

Hover effect

### Describe your enhancement/improvement

Adding hover effects on card buttons like glow effect, background color change effect, zoom effect, and anything else you want to add.

### Anything you need to say to the Reviewers

Assign this issue to me under GSSoC.

**Comment by root-0101** [comment]
Hey @swapnilsparsh Please assign me this issue

**Comment by swapnilsparsh** [comment]
@dishathakurata Thank you for providing your insight but it is not required as of now
