### ISSUE TITLE
Adding new project.

### ISSUE THREAD

**Issue by Braj-01** [swapnilsparsh/30DaysOfJavaScript#1720]
### Is your feature request related to a problem? Please describe.

Addition of BMI calculator project for users.

### Describe the solution you'd like.

There is no BMI calculator project in the site and I would like to add this .

### Describe alternatives you've considered.

N/A

**Comment by Braj-01** [comment]
Please assign me this task so that I can do it under GSSOC'24

**Comment by swapnilsparsh** [comment]
@Braj-01 Thank you for providing your insight but it is not required as of now
