### ISSUE TITLE
Title: Add Binary-Calculator 

### ISSUE THREAD

**Issue by parikhitritgithub** [swapnilsparsh/30DaysOfJavaScript#1721]
### Is your feature request related to a problem? Please describe.

We might need more exciting and usefull  project   .

### Describe the solution you'd like.

Using a binary calculator, we can easily calculate binary to decimal or hexadecimal conversions. We can also perform operations such as multiplication, addition, and finding the 1's complement.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/124444610/844e1af7-3d33-4878-a22f-17e82aec017f)
 i will improve the ui ..

**Comment by parikhitritgithub** [comment]
please assign this issue under GSSOC 2024

**Comment by swapnilsparsh** [comment]
@parikhitritgithub Thank you for providing your insight but it is not required as of now

**Comment by parikhitritgithub** [comment]
ok thank you for your reply
