### ISSUE TITLE
Title:  Crossy Road Game addition

### ISSUE THREAD

**Issue by Damini2004** [swapnilsparsh/30DaysOfJavaScript#1722]
### Is your feature request related to a problem? Please describe.

The Crossy Road game is an endless arcade-style game where players guide a character across various obstacles such as roads, rivers, and train tracks, aiming to travel as far as possible without getting hit or falling into the water. The game has simple controls, typically involving moving forward, backward, left, and right. Key elements of this feature include:

Character Movement: Allow the character to move in four directions (forward, backward, left, right).
Obstacles: Include moving cars, logs, and trains as obstacles.
Levels/Scenes: Implement different scenes like roads, rivers, and tracks with increasing difficulty.
Score System: Track the distance covered and increase the score as the player progresses.
Lives and Game Over: Allow a certain number of lives or immediate game over upon hitting an obstacle.
Graphics and Sound: Use simple, appealing graphics and sound effects to enhance the gaming experience.

### Describe the solution you'd like.

Adding a Crossy Road game feature will transform the project into an interactive entertainment platform, providing users with a fun and engaging way to spend their time. It will make the project more versatile and attractive to a broader audience, including casual gamers and those looking for a quick and enjoyable distraction.

How it Enhances Usage:

Entertainment: Adds a fun and interactive element, increasing user engagement and retention.
Diversification: Expands the project's scope beyond its current functionality, making it more appealing to various users.
Educational Value: Demonstrates game development principles, including collision detection, character movement, and score tracking, which can be educational for developers and students.

### Describe alternatives you've considered.

Not to disclose

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/119414762/e67f47f4-1a07-44d8-9208-3ddf95929814)

**Comment by swapnilsparsh** [comment]
@Damini2004 Thank you for providing your insight but it is not required as of now
