### ISSUE TITLE
Footer is not properly aligned 

### ISSUE THREAD

**Issue by Sowmyatiwari** [swapnilsparsh/30DaysOfJavaScript#1723]
### What happened?

The footer of this website is not properly aligned , and also not in proper font size.

### How can we reproduce this bug?

![footer](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/133684872/65cc538b-e08f-48f0-a942-7a5ebe5f578f)

### Urgency (Optional)

None

**Comment by Sowmyatiwari** [comment]
I want to work on this issue @swapnilsparsh

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by swapnilsparsh** [comment]
@Sowmyatiwari Thank you for providing your insight but it is not required as of now
