### ISSUE TITLE
Title:  Adding gitwar Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1729]
### Which pre-existing JavaScript project will you be working on?

I am previously working on #1688 #1592  #1365 This three 

### Describe your enhancement/improvement

**Its a war of Two Different Github profile**
**We can simply type the user name of github profile**
**last result shown who will win**

### Add any other context or relevant screenshots about the enhancement here.

![gitwar](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/de894da7-d6e0-484d-a857-e36382a95100)

**Comment by codewithganeshhh** [comment]
Dear @swapnilsparsh please assign me

**Comment by swapnilsparsh** [comment]
Thank you for providing your insight but it is not required as of now
