### ISSUE TITLE
Adding health risk assessment calculator

### ISSUE THREAD

**Issue by suhanigupta23** [swapnilsparsh/30DaysOfJavaScript#1730]
### Is your feature request related to a problem? Please describe.

we can add a health risk assessment calculator

### Describe the solution you'd like.

Assesses an individual's risk factors for common health conditions (e.g., heart disease, diabetes) based on lifestyle habits, family history, it asses the risk level.

### Describe alternatives you've considered.

<img width="1434" alt="Screenshot 2024-06-11 at 2 08 18 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/144280247/9b398c09-cd36-40a6-affa-cc1f76c7ed10">

**Comment by swapnilsparsh** [comment]
@suhanigupta23 Thank you for providing your insight but it is not required as of now
