### ISSUE TITLE
Title: Responsiveness of the home page cards

### ISSUE THREAD

**Issue by Speedysays01** [swapnilsparsh/30DaysOfJavaScript#1731]
### Which pre-existing JavaScript project will you be working on?

The home page itself

### Describe your enhancement/improvement

The cards describing the projects can be made more responsive with hover effects

### Anything you need to say to the Reviewers

Adding this slight enhancement can make the UI a lot better.

**Comment by Speedysays01** [comment]
Please assign me this project under GSSoc24 with the right labels so I can add the functionality.

**Comment by swapnilsparsh** [comment]
@Speedysays01 Thank you for providing your insight but it is not required as of now
