### ISSUE TITLE
Title: Developing snake and ball game

### ISSUE THREAD

**Issue by DiwareNamrata23** [swapnilsparsh/30DaysOfJavaScript#1732]
### Is your feature request related to a problem? Please describe.

<img width="1440" alt="Screenshot 2024-05-28 at 10 01 59 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/142529986/b6ddd51b-520c-40dc-b766-a68d6d2f5462">

### Describe the solution you'd like.

To implement a Snake game using js . Below given some functionalities of this game:

The snake is represented with a (yellow) symbol.
The fruit is represented with an (red) symbol.
The snake can move in any direction according to the user with the help of the keyboard (up, down, right and left  keys).
When the snake eats a fruit the score will increase by 1 point.
The fruit will generate automatically within the boundaries.
Whenever the snake will touch the boundary the game is over. 

### Describe alternatives you've considered.

Steps to create this game:
Build a boundary within which the game will be played.
The fruits are generated randomly.
Then increase the score whenever the snake eats a fruit.

**Comment by DiwareNamrata23** [comment]
@swapnilsparsh please assign this task to me

**Comment by swapnilsparsh** [comment]
@DiwareNamrata23 This game is already there in the repo.
