### ISSUE TITLE
Title: A mouse follower

### ISSUE THREAD

**Issue by Speedysays01** [swapnilsparsh/30DaysOfJavaScript#1733]
### Is your feature request related to a problem? Please describe.

The mini-projects are amazing! But they are too simple in UI point of view. 

### Describe the solution you'd like.

I would like to add a mouse follower feature to make the user interaction interesting and fun! All the projects have a dark background so a subtle mouse follower with some blurred effect will look the mini-projects looks even better

### Describe alternatives you've considered.

I have considered different types of mouse follower designs for this. I will attach my favorite one below

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/150716736/ff551a38-6b9f-4bf1-9695-bae65753b09a

**Comment by Speedysays01** [comment]
Please assign me the task under GSSOC24 so I can add this feature!

**Comment by swapnilsparsh** [comment]
@Speedysays01 Thank you for providing your insight but it is not required as of now
