### ISSUE TITLE
News app

### ISSUE THREAD

**Issue by paulkrishanu4** [swapnilsparsh/30DaysOfJavaScript#1734]
### Is your feature request related to a problem? Please describe.

want to add news app in the list

### Describe the solution you'd like.

will create a news app using javascript that will fetch news using Api

### Describe alternatives you've considered.

![Screenshot_12-6-2024_0152_paulkrishanu4 github io](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/169196836/57c4993b-73f3-47bb-ac69-8968845d5123)

**Comment by swapnilsparsh** [comment]
@paulkrishanu4 Thank you for providing your insight but it is not required as of now
