### ISSUE TITLE
Title: Create an Expense Tracker

### ISSUE THREAD

**Issue by rohitinu6** [swapnilsparsh/30DaysOfJavaScript#1735]
### Is your feature request related to a problem? Please describe.

We humans are always frustrated when we can't keep track of my daily expenses efficiently. Using multiple apps for different purposes makes it cumbersome to monitor and manage my spending habits effectively.

### Describe the solution you'd like.

I would like to develop a web-based Expense Tracker that allows users to input and categorize their daily expenses, view summaries and trends over time, and set budget limits. The application should include features such as:

- Adding new expenses with date, amount, and category
- Editing and deleting existing expenses
- Viewing expense summaries by day, week, month, or custom range
- Setting and tracking budget limits for different categories
- Visualizing spending trends with charts and graphs

### Describe alternatives you've considered.

I've considered using existing expense tracking applications, but they often come with unnecessary features or lack the customization I need. Developing a custom solution will allow for a more tailored experience.

### Add any other context or screenshots about the feature request here.

Preview:

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/113301503/503425f6-f118-4112-8e0c-1ae4d3d30657)

**I would like to create this tool, please assign it to me under the gssoc label.**

**Comment by swapnilsparsh** [comment]
@rohitinu6 Thank you for providing your insight but it is not required as of now
