### ISSUE TITLE
Title: New game, Starry Night

### ISSUE THREAD

**Issue by VijaySamant4368** [swapnilsparsh/30DaysOfJavaScript#1738]
### Is your feature request related to a problem? Please describe.

A game where stars falls from the sky, and player has to catch them with a pad

### Describe the solution you'd like.

Stars will drop from the top of the sky, and we will have to collect them with a pad, using the arrow keys. If any star misses, the game is lost. If a star is caught, score increases. Here is the basic idea for the game:
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/145102345/f237993e-96b4-4026-a03f-8303ec4d215f)

### Describe alternatives you've considered.

I thought of changing the visuals in the following way.
- The falling stars will be meteors, leaving trails of fire, and coming at any angle.
- The pad can be a space shuttle that deflects the incoming meteors, protecting the Earth below.
- If Earth is hit, it loses its population depending the size of the meteor.
- The population increases exponentially over time(due to reproduction) till a certain threshold. The population also decreases (due to deaths). 
- If the population reaches 0, the game is lost.
Scoring will be don on the basis of time of survival.

**Comment by swapnilsparsh** [comment]
@VijaySamant4368 Thank you for providing your insight but it is not required as of now
