### ISSUE TITLE
Title: Responsive site

### ISSUE THREAD

**Issue by Vibha17** [swapnilsparsh/30DaysOfJavaScript#1739]
### Is your feature request related to a problem? Please describe.

I would like to make site more responsive and improve ui

I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

### Describe the solution you'd like.

make it more attractive using css

### Describe alternatives you've considered.

..

**Comment by swapnilsparsh** [comment]
@Vibha17 Thank you for providing your insight but it is not required as of now
