### ISSUE TITLE
Title:issue with sorting visualizer

### ISSUE THREAD

**Issue by Lokeshsuwalka05** [swapnilsparsh/30DaysOfJavaScript#1740]
### Is your feature request related to a problem? Please describe.

If a person wants to visualize the previous pattern again, it is not possible to do.

### Describe the solution you'd like.

 I want to add a reset button so that users can visualize the previous pattern again.

### Describe alternatives you've considered.

Want to add a reset button

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105945491/746227cb-4f05-486e-b5f6-40d658a14093

**Comment by Lokeshsuwalka05** [comment]
@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Lokeshsuwalka05 Thank you for providing your insight but it is not required as of now
