### ISSUE TITLE
Add a New Project: Calorie Counter

### ISSUE THREAD

**Issue by sandy-queen** [swapnilsparsh/30DaysOfJavaScript#1741]
### About:

I want to add a calorie counter that will tell the amount of calories that a person will need to consume in order to gain/maintain/lose weight.

### Description:

1.  Ask the person about their height, weight, gender and exercise levels. We will then calculate the calories they will burn on an average based on these factors. 
2. The average calories burnt is the TDEE (Total Daily Energy Expenditure). 

> TDEE = BMR (Basal Metabolic Rate) * Exercise Levels

> BMR: 
   MEN: 66 + ( 13.7 x weight in kg ) + ( 5 x height in cm ) - ( 6.8 x age )
   WOMEN: 655 + ( 9.6 x weight in kg ) + (1.8 x height in cm ) - ( 4.7x age ) 

>Then, multiply BMR by exercise levels:
   
![bmr](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/147652780/5ae56780-5a66-459f-a7bb-ffcbc4897d5d)

3. This will give the average calories a person should eat in a day. Then: 
    -Weight maintain: Eat the same calories
    -Weight lose: Consume less than average calories
    -Weight gain: Consume more than average calories

Thus, this is a simple calorie counter tool that can help people in managing their weight. I will add a nice look to the project so that it doesn't look like a plain and simple calculator. 

**Please assign this project to me under GSSOC'24 as I would like to work on it**

**Comment by swapnilsparsh** [comment]
@sandy-queen Thank you for providing your insight but it is not required as of now
