### ISSUE TITLE
Title: Expense and Income Tracker

### ISSUE THREAD

**Issue by Shukria-Arghawan** [swapnilsparsh/30DaysOfJavaScript#1742]
### Is your feature request related to a problem? Please describe.

Most of the time we fail to manage our money because we do not calculate or expenses and income and spend accordingly. 

### Describe the solution you'd like.

For solving this issue there should be an app to calculate the income and expenses. So I have built an app to solve this issue with HTML, CSS and JavaScript.

### Describe alternatives you've considered.

Besides calculating the expenses and income, you can add other details like the category the income or expense is related. The date that the expense or income is made can also be added. So this will help you to have a clear idea of your expense or income.

### Add any other context or screenshots about the feature request here.

![Screenshot (1639)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/130974437/d28088f4-a187-4793-8469-132274aa7122)

**Comment by swapnilsparsh** [comment]
@Shukria-Arghawan Thank you for providing your insight but it is not required as of now
