### ISSUE TITLE
Title: Lights Out

### ISSUE THREAD

**Issue by Praneeth-2602** [swapnilsparsh/30DaysOfJavaScript#1744]
### Is your feature request related to a problem? Please describe.

Lights Out is a puzzle game where the goal is to turn off all the lights on a grid. Clicking on a light toggles it and the adjacent lights. The challenge is to find the right sequence of moves to turn off all the lights.

### Describe the solution you'd like.

To enhance the user experience, I propose adding a visual glow effect to the lights when they are on, making it more intuitive and visually appealing. Additionally, I will implement a smooth transition for the toggling action to improve the overall gameplay experience.

### Describe alternatives you've considered.

1. Different Visual Effects
- Color Change: Instead of a glow effect, the lights could simply change color when toggled. This could involve a change from a bright color (e.g., yellow) to a dark color (e.g., black) without the glow.
- Image-Based Lights: Using images for the lights that switch between "on" and "off" states could provide a more polished look but may increase the complexity of the implementation and load times.

2. Grid Size Variation
 - Dynamic Grid Size: Allowing users to choose the size of the grid (e.g., 3x3, 4x4, 5x5) could add variability and challenge to the game. This would require additional logic to handle different grid sizes and their respective win conditions.
 - Predefined Levels: Creating levels with different grid sizes and predefined light configurations to increase difficulty progressively.

3.Gameplay Mechanics
- Limited Moves: Introducing a limit to the number of moves a player can make to solve the puzzle. This would add a strategic element to the game, requiring players to think more critically about each move.
- Timed Challenges: Implementing a timer to challenge players to solve the puzzle within a certain amount of time.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/137754636/db17d35e-83a9-4696-a9c8-e69a418429b8)

I will improve the ui of course. this is just for reference

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 All the best 👍🏻
