### ISSUE TITLE
Title: Flow Free

### ISSUE THREAD

**Issue by Praneeth-2602** [swapnilsparsh/30DaysOfJavaScript#1745]
### Is your feature request related to a problem? Please describe.

Flow Free is a popular puzzle game where players connect matching colored dots with pipes to create a flow. The challenge is to cover the entire grid with pipes without overlapping or leaving any empty spaces. This game provides a fun and engaging way to enhance problem-solving and strategic thinking skills.

### Describe the solution you'd like.

I would like to implement a Flow Free game that includes:

- A grid-based puzzle where players connect matching colors with pipes.

- Different grid sizes and difficulty levels.
- A visually appealing interface with smooth animations and clear visual cues.
- A scoring system that tracks the number of moves and completion time.
- An option to reset the puzzle or undo moves.

### Describe alternatives you've considered.

Different Game Mechanics:

#### 1. Minimalist Design:

  - Opting for a simple, clean design with fewer animations.
  - Theme Customization: Allowing users to choose from different visual themes or color schemes.

#### 2. Additional Features:

 - Hint System: Providing hints to guide players when they are stuck.
 - Timer and Leaderboard: Introducing a timer to challenge players to complete the puzzle faster and a leaderboard to compare scores.

#### 3. Alternative Puzzle Games:

 - Minesweeper: A classic puzzle game where players clear a board without detonating hidden mines.
 - Lights Out: A puzzle game where the goal is to turn off all the lights on a grid.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/137754636/64c22c36-5a5a-4b8d-a4fd-b8719447b3cc)

**Comment by Praneeth-2602** [comment]
@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 All the best, make it compatible for mobile also. 👍🏻

**Comment by swapnilsparsh** [comment]
@Praneeth-2602 Any updates ?
