### ISSUE TITLE
Title: Adding Hover effect on button inside each card

### ISSUE THREAD

**Issue by HJ2207** [swapnilsparsh/30DaysOfJavaScript#1747]
### Which pre-existing JavaScript project will you be working on?

I would like to add an enhancement on the main style.css file of the whole project under gssoc.

### Describe your enhancement/improvement

I would like to add hover effect on "live" and "github" button on each card.
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146331595/59f401f1-7814-4ad0-87bd-318be1718845)

**Comment by swapnilsparsh** [comment]
@HJ2207 Thank you for providing your insight but it is not required as of now
