### ISSUE TITLE
Title: Decision tree

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [swapnilsparsh/30DaysOfJavaScript#1748]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when trying to make complex decisions based on a series of questions and answers without a clear visual representation. It can be difficult to keep track of various decision paths and outcomes without an intuitive tool to guide the process.

### Describe the solution you'd like.

I would like to add a decision tree extension to this repository. This interactive tool will help users make decisions based on a series of questions and answers. The decision tree will visually represent different decision paths and outcomes, allowing users to navigate through the decision-making process more easily and logically. The decision tree extension is interactive, allowing users to add, edit, delete, expand, collapse nodes, questions, and outcomes dynamically.
It visually represent the decision paths with connectors and provide a clear, user-friendly interface.

### Describe alternatives you've considered.

Using flowchart software to manually create decision trees, which is time-consuming and not interactive.
Relying on static diagrams or charts that do not allow for real-time updates or user interaction.
Employing complex spreadsheet formulas and conditional formatting to simulate decision paths, which can be cumbersome and error-prone.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139672976/78a5fa48-7e19-46db-9ad8-b6f650ccdbae)

**Comment by swapnilsparsh** [comment]
@DharshiBalasubramaniyam Thank you for providing your insight but it is not required as of now
