### ISSUE TITLE
Buttons of Drum Kit are not visible on small screens.

### ISSUE THREAD

**Issue by bhumii-ka** [swapnilsparsh/30DaysOfJavaScript#1751]
### Which pre-existing JavaScript project will you be working on?

I'll be working on Drum Kit project under GSSoC'24

### Describe your enhancement/improvement

On minimizing the screen size the width of the buttons is not decreasing in equal manner and the corner buttons are getting hidden.
Like here 'A' is hidden even though the scroll bar is at leftmost side. 
#### Current page
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/151030407/8647f0e2-585c-4bc6-a7a3-03a67df24d26)

This could be corrected by wrapping the buttons and fixing the width in this way
#### Enhanced Page
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/151030407/958b8fe0-64d0-45eb-9d12-d1494b8f2f6f)

### Anything you need to say to the Reviewers

Please assign this issue to me under GSSoC'24.

**Comment by swapnilsparsh** [comment]
@bhumii-ka All the best 👍🏻
