### ISSUE TITLE
Title: Rock paper scissor game

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1753]
### Is your feature request related to a problem? Please describe.

No it's just to add some additional games

### Describe the solution you'd like.

I want to add a rock paper scissor game.

### Describe alternatives you've considered.

A rock paper scissor game would be more fun

**Comment by swapnilsparsh** [comment]
@maradadivyasree020 Thank you for providing your insight but it is not required as of now
