### ISSUE TITLE
Title: Display day and date along with time in the digital clock.

### ISSUE THREAD

**Issue by meetarora10** [swapnilsparsh/30DaysOfJavaScript#1754]
### Which pre-existing JavaScript project will you be working on?

I will be working on Digital clock project.

### Describe your enhancement/improvement

A digital clock usually displays the date and day along with time. But in this particular digital clock only time is displayed.
Day and date should also be displayed in the digital clock.

### Anything you need to say to the Reviewers

I can add date and day feature with proper styling to this digital clock.

**Comment by swapnilsparsh** [comment]
@meetarora10 Thank you for providing your insight but it is not required as of now
