### ISSUE TITLE
Title: Enhancing theme toggle

### ISSUE THREAD

**Issue by Jasleen1210** [swapnilsparsh/30DaysOfJavaScript#1755]
### Which pre-existing JavaScript project will you be working on?

Theme toggle on top left corner.

### Describe your enhancement/improvement

I would like to add more css to the toggle to create a sun and moon that do not conflict with the background and complements it.

**Comment by swapnilsparsh** [comment]
@Jasleen1210 Thank you for providing your insight but it is not required as of now
