### ISSUE TITLE
Title: Contributors section

### ISSUE THREAD

**Issue by Jasleen1210** [swapnilsparsh/30DaysOfJavaScript#1756]
### Is your feature request related to a problem? Please describe.

The site has no area dedicated to display contributor count.

### Describe the solution you'd like.

I would like to add a section (footer) to display the count of contributors and github avatars of recent contributors. 

### Describe alternatives you've considered.

An alternative can be making a new page dedicated for the contributors, however i think a glimpse of contributors in the footer will be more accessible. 

### Add any other context or screenshots about the feature request here.

Please assign this issue to me under gssoc'24

**Comment by swapnilsparsh** [comment]
@Jasleen1210 Thank you for providing your insight but it is not required as of now
