### ISSUE TITLE
Add a notes maker app

### ISSUE THREAD

**Issue by yashg-116** [swapnilsparsh/30DaysOfJavaScript#176]
Hello @swapnilsparsh, myself Yash Gupta, GSSOC '22 participant, and I want to add a Notes maker app made by me using Javascript.
Can you assign this to me?
DESCRIPTION
In this app, user can make their notes (that includes the heading of topic and description), and also they can delete their previous notes.
Thank you,

**Comment by swapnilsparsh** [comment]
#178
