### ISSUE TITLE
Adding hover effect to "Live" and "Github" buttons

### ISSUE THREAD

**Issue by yashwagh30** [swapnilsparsh/30DaysOfJavaScript#1760]
### Which pre-existing JavaScript project will you be working on?

I have worked on making forums using js. I had also made a club website for university and even a NGO website. So i can work on multiple js projects.

### Describe your enhancement/improvement

I will add hovering effect to live and github button this will enhance the look of website.

**Comment by swapnilsparsh** [comment]
@yashwagh30 Thank you for providing your insight but it is not required as of now
