### ISSUE TITLE
Title: Loan Calculator

### ISSUE THREAD

**Issue by Explorer003** [swapnilsparsh/30DaysOfJavaScript#1761]
### Is your feature request related to a problem? Please describe.

Yes, the loan calculator aims to provide users with quick and accurate monthly payment estimates based on their inputs of loan amount, interest rate, and duration. This feature request ensures the calculator operates smoothly and effectively.

### Describe the solution you'd like.

I want to add a loan calculator which will help the user to calculate their monthly payment. This will provide users with a comprehensive understanding of their repayment schedule and financial commitments.

### Describe alternatives you've considered.

It includes various features like:
- enter the loan amount 
- enter the interest rate
- enter the months to pay
and then it will display the monthly payment 

### Add any other context or screenshots about the feature request here.

![Screenshot (1193)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/107935613/b4b42884-1534-4b0e-819d-a9ec7209534e)

**Comment by swapnilsparsh** [comment]
@Explorer003 Thank you for providing your insight but it is not required as of now
