### ISSUE TITLE
Title: Typing test game

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1764]
### Is your feature request related to a problem? Please describe.

No I want to add the typing game.

### Describe the solution you'd like.

It tells the user:
1. Mistakes 
2. WPM(Words Per Minute)
3. CPM(Characters Per Minute)

### Describe alternatives you've considered.

This game is based on a fixed time either 60/120 seconds.

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me

**Comment by maradadivyasree020** [comment]
please assign it to me

**Comment by swapnilsparsh** [comment]
@maradadivyasree020 Thank you for providing your insight but it is not required as of now
