### ISSUE TITLE
Title: Add 2048 game

### ISSUE THREAD

**Issue by shraddhha** [swapnilsparsh/30DaysOfJavaScript#1765]
### Is your feature request related to a problem? Please describe.

**2048 Game:  Description**
The 2048 game is a single-player sliding tile puzzle game. The objective is to combine numbered tiles on a grid to create a tile with the number 2048. A clear and concise description of the problem:

_Game Setup_

- The game is played on a 4x4 grid.
- Initially, two tiles appear on the grid, each with a value of either 2 or 4.
- Tiles can have values that are powers of 2 (e.g., 2, 4, 8, 16, 32, ..., 2048).

_Game Mechanics_
_Sliding Tiles:_

The player can slide all tiles on the grid up, down, left, or right.
When the player slides the tiles, all tiles move as far as possible in the chosen direction until they either hit the edge of the grid or another tile.

_Combining Tiles:_

If two tiles of the same value collide while sliding, they merge into a single tile with a value equal to the sum of the two tiles.
Each merge increases the player’s score by the value of the new tile.
A tile can only merge once per move.

_Adding New Tiles:_

After each slide, a new tile (with a value of 2 or 4) randomly appears in an empty spot on the grid.

_Game Objective_

- The goal is to create a tile with the value of 2048.
- The game continues after reaching 2048, allowing players to achieve higher scores.

_Losing Condition_
The game ends when there are no empty spots on the grid and no adjacent tiles can be combined.

### Describe the solution you'd like.

1. Game Initialization
Display a 4x4 grid.
Randomly place two tiles on the grid with a value of either 2 or 4.

2. Tile Movement
Allow the player to swipe or use arrow keys to slide all tiles in one of four directions: up, down, left, or right.
Tiles should move as far as possible in the chosen direction, stopping at the grid edge or another tile.

3. Tile Merging
When two tiles of the same value collide, they should merge into a single tile with a value equal to the sum of the two tiles.
Ensure that each tile can only merge once per move.
Increase the player's score by the value of the new tile created by the merge.

4. Adding New Tiles
After each move, add a new tile with a value of 2 or 4 to a random empty spot on the grid.
 
5. Game Continuation and Winning
The game continues until there are no more valid moves (no empty spaces and no adjacent tiles can merge).
The player wins when a tile with a value of 2048 is created, but the game can continue beyond this point to allow for higher scores.

6. Game Over
Display a "Game Over" message when there are no more valid moves left.
Provide an option to restart the game.

7. User Interface
Display the current score.
Optionally, display the best score.
Provide a "New Game" button to reset the game.

### Describe alternatives you've considered.

Using HTML and CSS to create the game grid and display and JavaScript to handle game logic, tile movement, merging, and scorekeeping.
Ensuring smooth animations for tile movement and merging for a better user experience.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-14 210526](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/125660723/5a24a9f1-6ccd-483e-9f6a-1177aeb00b83)

 I'll improve the ui of the game. Please assign me this issue under GSSOC.

**Comment by swapnilsparsh** [comment]
@shraddhha This is already there in the repo.
