### ISSUE TITLE
Title: Grade Calculator App

### ISSUE THREAD

**Issue by dongala-keerthi** [swapnilsparsh/30DaysOfJavaScript#1766]
### Which pre-existing JavaScript project will you be working on?

I am working on a grade calculator app to calculate grade points in CGPA with grades and credits given for the subject.

### Describe your enhancement/improvement

the grade calculator app helps in easy calculation of CGPA without much efforts and can be efficient.I am currently working on it

**Comment by swapnilsparsh** [comment]
@dongala-keerthi Thank you for providing your insight but it is not required as of now
