### ISSUE TITLE
Title: Dragon's World Game

### ISSUE THREAD

**Issue by Explorer003** [swapnilsparsh/30DaysOfJavaScript#1768]
### Is your feature request related to a problem? Please describe.

I want to add a dragon world game.

### Describe the solution you'd like.

Dragon’s World is a game in which one dragon tries to save itself from the other dragon by jumping over the dragon which comes in its way. The score is updated when one dragon saves himself from the other dragon. 

### Describe alternatives you've considered.

It contains various features like: 
- Player score
- It will contain the obstacle from which the dragon has to save itself.
- It will contain the dragon which has to be saved from the obstacle i.e. the other dragon.

### Add any other context or screenshots about the feature request here.

![Screenshot (1196)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/107935613/fce3ff37-f5aa-4702-a15f-af79ca6416f8)

**Comment by Explorer003** [comment]
@swapnilsparsh kindly assign me this.

**Comment by swapnilsparsh** [comment]
@Explorer003 Thank you for providing your insight but it is not required as of now
