### ISSUE TITLE
BaseN Converter

### ISSUE THREAD

**Issue by XZANATOL** [swapnilsparsh/30DaysOfJavaScript#177]
A calculator that can convert numbers from base-X to base-Y. Example: `` Decimal to Binary ``, `` Binary to Octal ``, `` Base 3 to Base 6 ``, ..etc.

- The calculator will be able to also deal with decimal numbers.
- The calculator will not be limited to the known bases of Binary, Octal, Decimal, and Hexadecimal. The user will be able to enter/ convert-to the desired base number.

Issue created under GSSoC'22 Contributions

**Comment by swapnilsparsh** [comment]
> 

It is already there on the website, have a look [here](https://30daysofjs.netlify.app/35%20-%20decimal%20to%20binary/)
Anything new which you will be doing in this?
