### ISSUE TITLE
Title: Amazon clone

### ISSUE THREAD

**Issue by Riya1922** [swapnilsparsh/30DaysOfJavaScript#1770]
### Is your feature request related to a problem? Please describe.

Yes, my feature request will enhance the user experience allowing users to buy products and it will streamline the shopping process.

### Describe the solution you'd like.

I want to add Amazon Clone which will improve the e-commerce experience giving users various functionalities for their ease.
overall it will enhance the shopping process and will increase customer shopping satisfaction. Interactive features for the orders and cart sections will make the user experience more seamless and efficient.

### Describe alternatives you've considered.

It has various features like:
- Search bar
- displaying of various items 
- Reviews and ratings
- sorting and filtering options
- user can add item to the cart
- checkout and customer support

### Add any other context or screenshots about the feature request here.

![amazon clone](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105075030/fbf305f0-c1af-4a64-8162-dd04c4b2ac2f)

**Comment by Riya1922** [comment]
@swapnilsparsh kindly assign me this.

**Comment by swapnilsparsh** [comment]
@Riya1922 Thank you for providing your insight but it is not required as of now
