### ISSUE TITLE
Title: Open project in new blank page

### ISSUE THREAD

**Issue by mehrun171** [swapnilsparsh/30DaysOfJavaScript#1771]
### Which pre-existing JavaScript project will you be working on?

All of the projects i.e whole website

### Describe your enhancement/improvement

When we try to open a app/game and click on live or git hub repo...it opens in the same existing tab...instead we can change to open it in new blank tab which will be more efficient and easy to use for user as he can open any number or apps in new tabs and also stay in the 30daysofjs tab...which improves user usability...
So please assign me this task

**Initial tab of website**
![Screenshot 2024-06-14 233855](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116735695/6dd774ac-7538-4672-880b-8d6146403dfa)

**when we open a app it opens in same tab**
![Screenshot 2024-06-14 233904](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/116735695/a2f5ad6d-cf6e-4ad1-8dfa-418ddde55385)

**Comment by swapnilsparsh** [comment]
@mehrun171 Thank you for providing your insight but it is not required as of now
