### ISSUE TITLE
Title: change in the apprence in the website as it is very very boring looking

### ISSUE THREAD

**Issue by kavyachandarkar** [swapnilsparsh/30DaysOfJavaScript#1772]
### Which pre-existing JavaScript project will you be working on?

none at this moment

### Describe your enhancement/improvement

Revamp the website by incorporating vibrant colors, dynamic images, and modern fonts. Enhance user engagement with interactive elements and streamlined navigation. Add eye-catching visuals, engaging content, and a responsive design to create a more appealing and user-friendly experience.
<img width="889" alt="image" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156076079/cfdc432f-7589-4992-b2f4-8ec16c69560c">

**Comment by swapnilsparsh** [comment]
@kavyachandarkar Thank you for providing your insight but it is not required as of now
