### ISSUE TITLE
Title: Password Strength Checker

### ISSUE THREAD

**Issue by revanth1718** [swapnilsparsh/30DaysOfJavaScript#1775]
### Is your feature request related to a problem? Please describe.

In today's digital age, ensuring strong passwords is crucial for the security of user accounts. However, many users struggle to understand how to create strong passwords and often end up using weak ones, which can lead to security vulnerabilities. A visual aid that provides real-time feedback on password strength can significantly help users create stronger passwords.

### Describe the solution you'd like.

I propose adding a Glowing Password Strength Checker to the repository. This tool will evaluate the strength of a password in real-time and provide immediate visual feedback to the user. The strength checker will use a combination of HTML, CSS, and JavaScript to analyze the password and display its strength using glowing color indicators.

### Describe alternatives you've considered.

An alternative solution could be providing only text feedback without the glowing visual indicators. However, visual feedback is more intuitive and engaging for users.

### Add any other context or screenshots about the feature request here.

![password](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/109272714/cc94ff2f-0549-4511-8651-7087fabac4e7)

**Comment by swapnilsparsh** [comment]
@revanth1718 Thank you for providing your insight but it is not required as of now
