### ISSUE TITLE
Title: Analog Clock with Dark & White Mode

### ISSUE THREAD

**Issue by revanth1718** [swapnilsparsh/30DaysOfJavaScript#1777]
### Is your feature request related to a problem? Please describe.

Currently, the repository lacks a visually appealing and functional analog clock that can adapt to different lighting conditions. 

### Describe the solution you'd like.

I propose the addition of an Analog Clock with Dark & White Mode. 

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![clcok](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/109272714/b2bf8a51-cc39-44d3-a894-5721b7391706)

**Comment by swapnilsparsh** [comment]
@revanth1718 Thank you for providing your insight but it is not required as of now
