### ISSUE TITLE
Title:  Wordle is a popular online word-guessing game

### ISSUE THREAD

**Issue by jennifereunice** [swapnilsparsh/30DaysOfJavaScript#1779]
### Is your feature request related to a problem? Please describe.

Setup:

The game displays a grid with six rows and five columns, representing the maximum six attempts to guess the correct word.
Players enter their guesses into the grid using the provided input field.
Input and Feedback:

After submitting a guess, each letter of the word is color-coded to indicate its accuracy:
Green: The letter is in the correct position.
Yellow: The letter is in the word but in the wrong position.
Grey: The letter is not in the word at all.
This feedback helps players refine their guesses in subsequent attempts.
Winning and Losing:

The game is won if the player guesses the correct word within six attempts.
If the player fails to guess the word in six tries, the game ends, and the correct word is revealed.
Key Features
Daily Challenge: Wordle presents a new word each day, creating a shared experience among players who all attempt to guess the same word.
No Repeats: Each word is unique, preventing repetition and keeping the game fresh.
Social Sharing: Players often share their results on social media, showcasing their guessing prowess without revealing the actual word.

### Describe the solution you'd like.

HTML:

Creates the basic structure of the game, including the board for displaying guesses, an input field for entering guesses, and a button for submitting guesses.
CSS:

Styles the game board and input elements for a clean and centered layout.
JavaScript:

Initializes the game board by creating a grid of tiles.
Handles user input, checking the guess against the solution.
Colors the tiles based on the correctness of each letter (green for correct, yellow for present but wrong position, grey for absent).
This implementation gives you a simple, playable version of Wordle. You can further enhance it by adding features such as a list of possible words for random solutions, better handling of duplicate letters, and more sophisticated UI elements.

### Describe alternatives you've considered.

HTML:

Creates the basic structure of the game, including the board for displaying guesses, an input field for entering guesses, and a button for submitting guesses.
CSS:

Styles the game board and input elements for a clean and centered layout.
JavaScript:

Initializes the game board by creating a grid of tiles.
Handles user input, checking the guess against the solution.
Colors the tiles based on the correctness of each letter (green for correct, yellow for present but wrong position, grey for absent).
This implementation gives you a simple, playable version of Wordle. You can further enhance it by adding features such as a list of possible words for random solutions, better handling of duplicate letters, and more sophisticated UI elements.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105411915/2925d367-0606-4118-baad-b8bf75ad882e)

**Comment by swapnilsparsh** [comment]
@jennifereunice Thank you for providing your insight but it is not required as of now

**Comment by jennifereunice** [comment]
why are you closing
