### ISSUE TITLE
Title: TOWER BLOCK GAME

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1780]
### Is your feature request related to a problem? Please describe.

Develop a tower building game where players stack blocks to build the tallest tower.

### Describe the solution you'd like.

Features:  Score tracking

### Describe alternatives you've considered.

Features:  Score tracking

**Comment by swapnilsparsh** [comment]
@maradadivyasree020 Thank you for providing your insight but it is not required as of now
