### ISSUE TITLE
wish to add {1} Palindrome Checker App {2} Sliding Image Puzzle Javascript {3} Detect Internet Speed Javascript {4} Text Similarity Checker {5} Rock Paper Scissor Game with Javascript

### ISSUE THREAD

**Issue by sheetal-81** [swapnilsparsh/30DaysOfJavaScript#1781]
@swapnilsparsh pls assign the task so i can add all this projects
{1} Palindrome Checker App 
{2} Sliding Image Puzzle Javascript 
{3} Detect Internet Speed Javascript 
{4} Text Similarity Checker 
{5} Rock Paper Scissor Game with Javascript

**Comment by swapnilsparsh** [comment]
@sheetal-81 Thank you for providing your insight but it is not required as of now
