### ISSUE TITLE
Title: Advice Generator

### ISSUE THREAD

**Issue by meetarora10** [swapnilsparsh/30DaysOfJavaScript#1782]
### Is your feature request related to a problem? Please describe.

A random advice generator app 

### Describe the solution you'd like.

This random advice generator app will generate a new and random advice each time on the click of a button.

### Describe alternatives you've considered.

A button is provided which on click will generate a random advice.

**Comment by swapnilsparsh** [comment]
@meetarora10 Thank you for providing your insight but it is not required as of now
