### ISSUE TITLE
Tracking highScore in [56 - Stick Hero Game] 

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1783]
### Is your feature request related to a problem? Please describe.

I would like to add a feature to track a person's highscore in the game. Right now person can not know what his highscore was and the score resets to 0 when we restart. Tracking Highscore would enhance the experience.

### Describe the solution you'd like.

I would like to track the highscore of the person and keep it saved. So that they can see their highscore at any point.

### Describe alternatives you've considered.

I would like to work on the above stated issue. please assign this issue to me under GSSOC'24.

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/861af659-afd9-4117-ad50-abbabe297a3a

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba Thank you for providing your insight but it is not required as of now
