### ISSUE TITLE
speed not stopping

### ISSUE THREAD

**Issue by jennifereunice** [swapnilsparsh/30DaysOfJavaScript#1784]
### What happened?

here in text speed control the text is not stopping when the speed is 0

### How can we reproduce this bug?

here in text speed control the text is not stopping when the speed is 0 and continuing with the previously mentioned speed

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105411915/fe713294-919c-477b-ba30-b7711922748b)

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@jennifereunice Thank you for providing your insight but it is not required as of now
