### ISSUE TITLE
maths addition

### ISSUE THREAD

**Issue by jennifereunice** [swapnilsparsh/30DaysOfJavaScript#1785]
### What happened?

it is giving the output as incorrect when i did not enter anything

### How can we reproduce this bug?

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/105411915/cac9724a-7854-417c-a6c4-dd1df08b3d5e)

### Urgency (Optional)

None

**Comment by swapnilsparsh** [comment]
@jennifereunice All the best 👍🏻
