### ISSUE TITLE
Title: Spelling Bee

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1786]
### Is your feature request related to a problem? Please describe.

Create a spelling bee game where players spell words based on audio or text prompts.

### Describe the solution you'd like.

It's would have 3 features 
1. Generate a New Word
2. Speak
3. Submit
Using js to check the written answer is correct or not.

### Describe alternatives you've considered.

This project could be easily done using HTML,CSS,JS

**Comment by swapnilsparsh** [comment]
@maradadivyasree020 Thank you for providing your insight but it is not required as of now
