### ISSUE TITLE
Title: Piano Tiles Game

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1787]
### Is your feature request related to a problem? Please describe.

Create a Piano Tiles game where players tap tiles to play music.

### Describe the solution you'd like.

It includes the following feature:
1. Start the game
2. End if user has missed the tile
3. Score Tracking

### Describe alternatives you've considered.

To use only HTML,CSS,JS and will do the changes accordingly.

**Comment by swapnilsparsh** [comment]
@maradadivyasree020 Thank you for providing your insight but it is not required as of now
