### ISSUE TITLE
Title: Word Scrabble

### ISSUE THREAD

**Issue by maradadivyasree020** [swapnilsparsh/30DaysOfJavaScript#1788]
### Is your feature request related to a problem? Please describe.

Develop a Scrabble game where players create words on a board with letter tiles.

### Describe the solution you'd like.

The features are:
1. Time would be displayed on the screen.
2. User can enter the word and check it.
3. User can click refresh button to generate new word.

### Describe alternatives you've considered.

There are not much alternatives to these just I want to use HTML,CSS,JS

**Comment by sanjay-kv** [comment]
@swapnilsparsh Need access to this repo please. there is lot of spam happening in this repo.

**Comment by swapnilsparsh** [comment]
@sanjay-kv I am trying to handle that only, if it continues happening then will let you know. 
@maradadivyasree020 Thank you for providing your insight but it is not required as of now

**Comment by sanjay-kv** [comment]
No, I mean i only need write access, there is already lot of spams with level3. 
i got access to 170 repos already. I'm not sure whats the issue in write access?

Let me know. @swapnilsparsh
