### ISSUE TITLE
A javascript clock

### ISSUE THREAD

**Issue by Khushi-Mattu** [swapnilsparsh/30DaysOfJavaScript#179]
A clock (or a code that shows the current time in hours,minutes and seconds) using javascript.

**Comment by swapnilsparsh** [comment]
> A clock (or a code that shows the current time in hours,minutes and seconds) using javascript.

It is already there on the website, check it out [here](https://30daysofjs.netlify.app/02%20-%20Clock/index.html)

Try to work on a project which is not there on the website yet.
Good Luck 👍🏻
