### ISSUE TITLE
Title: Adding Arcade Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1790]
### Which pre-existing JavaScript project will you be working on?

I previously Worked on #1688 #1592 #1365 

### Describe your enhancement/improvement

**A pure CSS game where the user controls a stack of blocks by clicking and dragging the mouse.** 
- Use the mouse to move the stack of blocks slowly and carefully.
- Try to stack the blocks in a way that they support each other.
- Avoid stacking the blocks too high, or they will fall off the screen.
- If you see that the stack of blocks is about to fall, try to move it to a more stable position.

### Anything you need to say to the Reviewers

- Use the mouse to move the stack of blocks slowly and carefully.
- Try to stack the blocks in a way that they support each other.
- Avoid stacking the blocks too high, or they will fall off the screen.
- If you see that the stack of blocks is about to fall, try to move it to a more stable position.

### Add any other context or relevant screenshots about the enhancement here.

![Arcade_Game](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/0645004e-edd3-4e86-9a08-e3d3de770516)

**Comment by codewithganeshhh** [comment]
Assign me @swapnilsparsh ASAP !

**Comment by swapnilsparsh** [comment]
@codewithganeshhh All the best 👍🏻and also make it compatible for mobile.
