### ISSUE TITLE
Title: Ant smasher Game

### ISSUE THREAD

**Issue by mukilan2815** [swapnilsparsh/30DaysOfJavaScript#1794]
I have created a ant smashing game where users need to kill the ant by clicking the ant, and user can gain points. 

![Ant_Smasher_Demo](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/71129858/121d4ffd-58bc-42ba-973f-b6c1f2d096ec)

**Comment by swapnilsparsh** [comment]
@mukilan2815 Thank you for providing your insight but it is not required as of now
