### ISSUE TITLE
Title: THREE NUMBER

### ISSUE THREAD

**Issue by P-lavanya16** [swapnilsparsh/30DaysOfJavaScript#1795]
### Which pre-existing JavaScript project will you be working on?

Add some footer to it!!

### Describe your enhancement/improvement

we can add footer and also high score to it!!

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot (123)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/145569662/27d7a90d-7400-44f8-8419-48f64ef06bed)

**Comment by swapnilsparsh** [comment]
@P-lavanya16 Thank you for providing your insight but it is not required as of now
