### ISSUE TITLE
Title: Add Reverse Memory Game

### ISSUE THREAD

**Issue by tanyagupta01** [swapnilsparsh/30DaysOfJavaScript#1797]
### Is your feature request related to a problem? Please describe.

The Reverse Memory Game is a fun and challenging memory game where you must recall a sequence of colors in reverse order. With each successful recall, the sequence length increases, making the game progressively harder.

### Describe the solution you'd like.

add the aforementioned game.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

<img width="1362" alt="Screenshot 2024-06-17 at 1 14 38 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156044894/c98ed308-f3dd-40c6-9b87-709016be341d">

**Comment by swapnilsparsh** [comment]
@tanyagupta01 All the best 👍🏻and make it compatible for mobile also

**Comment by tanyagupta01** [comment]
Okay
