### ISSUE TITLE
Title:  Piano

### ISSUE THREAD

**Issue by tanyagupta01** [swapnilsparsh/30DaysOfJavaScript#1798]
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

<img width="1336" alt="Screenshot 2024-06-17 at 1 24 05 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156044894/875cbe5d-e5dd-4e0c-be1d-b5eac98f2199">

**Comment by swapnilsparsh** [comment]
@tanyagupta01 Thank you for providing your insight but it is not required as of now
