### ISSUE TITLE
Title: Add Othello Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [swapnilsparsh/30DaysOfJavaScript#1799]
### Is your feature request related to a problem? Please describe.

Integrate a functional Othello (Reversi) game using only JavaScript, HTML, and CSS.. This classic board game will provide an engaging and strategic gameplay experience for our users, showcasing our ability to develop interactive web applications.

### Describe the solution you'd like.

**Game Setup:**
- Implement Othello game board using HTML for structure and CSS for styling.
- Use JavaScript for game logic, including placing pieces and flipping opponent pieces.

** User Interface:**
- Design a responsive and intuitive interface using CSS for layout and visual design.
- Include clear instructions and visual cues for valid moves directly within the game interface.

**Gameplay Mechanics:**
- Develop core Othello gameplay mechanics in JavaScript, ensuring adherence to standard rules.
- Implement turn-based gameplay with functionality for both players to make moves sequentially.

Accessibility and Compatibility:
- Ensure accessibility features such as keyboard navigation and screen reader support.
- Optimize game performance across browsers and devices without relying on backend technologies.

### Describe alternatives you've considered.

- Game Development Libraries: Phaser.js or Impact.js for enhanced features.
- AI Integration: Minimax algorithm or Monte Carlo Tree Search for AI opponents.
- Multiplayer: WebSocket integration or Firebase Realtime Database for real-time gameplay.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-17 021609](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/146121869/69d85a3b-6c81-4cf7-ade9-192cc0866d54)

**Comment by swapnilsparsh** [comment]
@AsmitaMishra24 All the best 👍🏻and make it compatible for mobile also

**Comment by swapnilsparsh** [comment]
@AsmitaMishra24 Any updates ?
