### ISSUE TITLE
Title:  Doraemon Run game using HTML, CSS, JS

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1800]
### Is your feature request related to a problem? Please describe.

Doraemon Run is an adventurous game where players will be able to navigate through through top,left,right,bottom .Players must navigate Doraemon through obstacles like mazes while collecting cakes and avoiding traps. It offers engaging gameplay with intuitive controls and increasing difficulty levels. As Doraemon dashes through challenging mazes to devour delicious Dora cakes ,it will loose his score and health . It will track the high Score and Score and as soon as it health reaches 0 or it will crash to the boundary line , the game will end.

### Describe the solution you'd like.

Doraemon Run is an adventurous maze navigation game where players control Doraemon to collect cakes and avoid traps. The game should feature:

Intuitive Controls: Use arrow keys or swipe gestures for movement.
Engaging Gameplay: Navigate through procedurally generated mazes, collect cakes to increase score, and avoid traps that reduce health.
Progressive Difficulty: Mazes become more complex as the player progresses.
Health and Score Tracking: Display current score, high score, and health meter. The game ends when health reaches zero or Doraemon crashes into a boundary.

### Describe alternatives you've considered.

The desired solution for Doraemon Run is a well-rounded, engaging game that offers fun and challenging gameplay with intuitive controls and a rewarding scoring system. By focusing on smooth mechanics, increasing difficulty, and a clean user interface, the game aims to provide an enjoyable experience for players of all ages. Future updates and additional features can expand the game’s appeal and longevity.

## Screenshot section 

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/dd626f60-abd7-4925-b980-835bc786203d)

## Demo Video section

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/905d7f95-429a-427f-94d1-da132c300313

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , please /assign me under this

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , but this is not existing in the website, it is based only html , css , js . It will be very engaging and differnet from others.
