### ISSUE TITLE
Title:  Snake Bites game purely using html,css,js

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1801]
### Is your feature request related to a problem? Please describe.

Snakebites, an exciting and fast-paced arcade game that brings a modern twist to the classic snake game. Players control a snake, navigating it to consume food items that appear randomly on the screen. Each food item consumed causes the snake to grow longer, increasing the challenge of avoiding collisions with the snake's own body and the game boundaries.

### Describe the solution you'd like.

Overview:
Snake Bites is a modern twist on the classic Snake game, offering an engaging and challenging experience for players of all ages. Control the hungry snake as it slithers around the screen, eating food to grow longer while avoiding collisions with the walls and its own tail. With multiple difficulty levels, Snake Bites provides endless fun and tests your reflexes and strategic thinking.

Features:

Difficulty Levels:

Choose from three difficulty levels to match your skill and preference:
Easy (Speed: 5): A slower pace, perfect for beginners and those looking to relax.
Medium (Speed: 10): A moderate pace for experienced players seeking a challenge.
Hard (Speed: >15): A fast-paced, intense experience for experts who crave a real test of their reflexes.

Simple Controls:

Use the arrow keys or swipe gestures (on touch devices) to guide the snake in the desired direction.
Responsive controls ensure a smooth and enjoyable gameplay experience.

### Describe alternatives you've considered.

Earn points by eating food items that appear randomly on the screen.
Your score increases with each item consumed, and the snake grows longer, making the game progressively more challenging.
Track your current score and high score to compete with yourself and others.

### Add any other context or screenshots about the feature request here.

 # Screenshot Section
### The User can select levels according to the difficulty

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/2a27fb56-ccc2-4e65-86fa-e8ef5b583794)

The game tracks the HighScore everytime the user plays!!
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/a783d872-d4af-40e9-b187-e8a18eec620d)

### Demo Video Section

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/ce30c356-20a9-4921-940b-2c993258680a

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , please assign me under this issue

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , This game is unique and user enagaging game , this is different from pre-existing game as it provides SOUND EFFECTS and Animations , you can also look at the video, and also it has an ability to select the level of the game and with these features , the game is more user friendly and engaging !!!

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , please say what type of js projects , would you like to provide..... This snake game is different from other, it includes sound effects also , you can also refer the video !!! I will ensure to make it different from ither games.

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Snake Game already exists on the repo.
