### ISSUE TITLE
Title:  HandCricket Game

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1802]
### Is your feature request related to a problem? Please describe.

My hand cricket game provides an engaging single-player experience where players compete against a bot opponent. The game starts with a toss feature, letting the winner decide whether to bat or bowl first. With a user-friendly interface and captivating graphics, players are sure to remain immersed in the gameplay. An instructions page is included to help newcomers easily understand the rules and mechanics.

### Game Features:

- Toss feature to determine the batting or bowling order.
- Captivating graphics that enhance user engagement.
- Instructions page for easy comprehension of game rules.

### Describe the solution you'd like.

I would like to propose adding the game of Hand Cricket to the 30DaysOfJavaScript repository. Hand Cricket is a simple yet entertaining game that requires minimal resources and can be easily integrated into the existing structure of the repository. Players can compete against the computer making it a versatile addition to the repository's offerings.

### Describe alternatives you've considered.

While considering different games or interactive features, Hand Cricket stands out due to its simplicity, widespread popularity, and ease of implementation. It provides a unique, engaging experience that aligns well with the objectives of the 30DaysOfJavaScript repository.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/ccb7d14d-2a93-41c9-9894-9331426f4cba)

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , please assign me under this issue

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now
