### ISSUE TITLE
Title:  Dinosaur Game

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1803]
### Is your feature request related to a problem? Please describe.

In this single-player game I will create Chrome Dinosaur game using HTML, CSS, and JavaScript. It involves building a simple, offline game where a dinosaur character runs across a desert landscape, jumping over obstacles to avoid collisions. The objective is to achieve the highest score possible by running for as long as one can without hitting any obstacles.

### Describe the solution you'd like.

Character Movement: Use keyboard controls to make the dinosaur jump.
Obstacle Generation: Dynamically create and move obstacles across the screen.
Collision Detection: Detect collisions between the dinosaur and obstacles to end the game.
Score Keeping: Update and display the score based on the time survived.

### Describe alternatives you've considered.

While there are many potential alternatives, the Chrome Dinosaur game stands out due to its simplicity, recognizable gameplay, and minimal resource requirements. Its straightforward mechanics make it an excellent project for demonstrating basic game development concepts using HTML, CSS, and JavaScript. Additionally, the familiarity and nostalgia associated with the Chrome Dinosaur game will likely resonate well with users.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/596699f5-449d-4df1-a686-8364992fb856)

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now
