### ISSUE TITLE
Title: Slide Puzzle Game

### ISSUE THREAD

**Issue by SrijaVuppala295** [swapnilsparsh/30DaysOfJavaScript#1804]
### Is your feature request related to a problem? Please describe.

The game consists of a 3x3 grid with numbered tiles and one empty tile. The objective of the game is to arrange the numbered tiles in ascending order by sliding them into the empty tile.

### Describe the solution you'd like.

Create a grid (e.g., 3x3, 4x4) of tiles that represent the scrambled pieces of the image.
Allow players to slide tiles into the empty space to rearrange the puzzle pieces.
Randomly shuffle the tiles at the beginning of the game to ensure a challenging puzzle.
Detect when the puzzle is correctly solved and display a congratulatory message or animation.
Include buttons to reset and shuffle the puzzle for a new game.
Track the time taken and the number of moves made by the player.

### Describe alternatives you've considered.

The Doraemon Slide Puzzle game is an engaging, visually appealing project that showcases fundamental HTML, CSS, and JavaScript skills. It's simple to understand, challenging to play, and provides a satisfying user experience. This game will be a delightful addition to any portfolio or educational repository, offering both fun and learning.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/140592148/552ed7f2-1b41-4914-852e-5134e8481a18)

**Comment by SrijaVuppala295** [comment]
@swapnilsparsh , it is purely using HTML , CSS , JS please \assign me under this issue

**Comment by swapnilsparsh** [comment]
@SrijaVuppala295 Thank you for providing your insight but it is not required as of now
