### ISSUE TITLE
Title: Pictionary game 

### ISSUE THREAD

**Issue by Jagpreet153** [swapnilsparsh/30DaysOfJavaScript#1805]
### Is your feature request related to a problem? Please describe.

I would like to add a picture guessing game using html, css, js

### Describe the solution you'd like.

It is a multiuser game in which the user has to guess word by the drawing of the other players .

### Describe alternatives you've considered.

The game would be responsive for all screens and the points will be increased accordingly . 

### Add any other context or screenshots about the feature request here.

Kindly assign this task to me under GSSoC'24

**Comment by swapnilsparsh** [comment]
@Jagpreet153 Thank you for providing your insight but it is not required as of now
