### ISSUE TITLE
Title: Invaders of space game

### ISSUE THREAD

**Issue by taneeshaa15** [swapnilsparsh/30DaysOfJavaScript#1806]
### Is your feature request related to a problem? Please describe.

"Invaders of Space" is a retro-inspired arcade game that draws on the classic "Space Invaders" formula, offering players a nostalgic yet refreshing experience of defending Earth from an alien invasion.

### Describe the solution you'd like.

Players can fire lasers or projectiles upwards to destroy incoming enemies. Precision and timing are key, as the invaders move in patterns that become more complex with each wave.

### Describe alternatives you've considered.

Occasionally, power-ups will appear on the screen. These can provide temporary advantages such as rapid fire, shields, or multi-shot capabilities.

Levels and Waves

### Add any other context or screenshots about the feature request here.

"Invaders of Space" combines classic arcade gameplay with modern enhancements, providing an engaging and challenging experience for both nostalgic players and newcomers. The game’s simple yet addictive mechanics, along with its polished graphics and sound design, make it a timeless addition to the arcade genre.

**Comment by taneeshaa15** [comment]
@swapnilsparsh Please assign me this issue under gssoc'24

**Comment by swapnilsparsh** [comment]
@taneeshaa15 Thank you for providing your insight but it is not required as of now
