### ISSUE TITLE
website unorganized and clumsy

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1809]
### What happened?

The parent website that hosts all the games is not well organized, some of the cards are so huge that they cover the entire screen. The Screenshot of this bug is provided below. Please review it.

### Screenshots
**bug**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/3afaad88-4477-458a-a828-e40834fec749)

**bug**
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/992111a3-50be-4a24-a51c-f811e7e39b1f)

**expected** 
![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/8bef0832-1541-4bdf-855b-a5ad27c941d4)

Please assign this issue to me under GSSOC'24.

### Urgency (Optional)

High priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba This is the old UI, will be updating the new UI soon.
