### ISSUE TITLE
Game Card doesn't load

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1810]
### What happened?

The card of the Taash game - 119 in the parent website does not load properly. The bug is shown in the Screen Shot below.

### Screen Shot

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/05708176-e0a3-4db0-8bc3-0fb46490f219)

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba This is the old UI, will be updating the new UI soon.
