### ISSUE TITLE
No. of guesses don't reduce on pressing the wrong key continuously

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1811]
### What happened?

If we press the wrong key again and again the lives don't reduce. This bug is demonstrated in the video below.

### How can we reproduce this bug?

_Constantly pressing 'v' key_

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/dc37fed2-7c07-4e49-96f3-185e583b8488

Please assign this issue to me under GSSOC'24.

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba There are two similar projects like this so will be removing one.
