### ISSUE TITLE
Adding a new ToDo List WebApplication

### ISSUE THREAD

**Issue by Dhruv-Gaba** [swapnilsparsh/30DaysOfJavaScript#1812]
### Is your feature request related to a problem? Please describe.

I wish to add a new To do list application that i created. The preview for the same is given below. please review it.

### Describe the solution you'd like.

Adding a new To Do app.

### Describe alternatives you've considered.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/141745373/a6e112ac-49a1-4cc0-b89f-580e8306093b

Please assign this issue to me under GSSOC'24.

**Comment by swapnilsparsh** [comment]
@Dhruv-Gaba This type of project is already exist on the repo.
