### ISSUE TITLE
Title: Loan Calculator

### ISSUE THREAD

**Issue by Ayushvishwakarma04** [swapnilsparsh/30DaysOfJavaScript#1815]
### Is your feature request related to a problem? Please describe.

Yes, this feature request addresses the common problem of individuals needing a quick and easy way to calculate loan payments. People often find it challenging to manually compute loan details such as monthly payments, total interest, and total repayment amounts. A loan calculator tool would simplify this process, providing users with accurate and instant calculations.

### Describe the solution you'd like.

I would like to develop a loan calculator using HTML, CSS, and JavaScript that allows users to input loan details such as the loan amount, annual interest rate, and loan term (in years or months). The calculator will then compute and display the following:

Monthly Payment: The fixed monthly payment amount that the borrower needs to pay.
Total Payment: The total amount paid over the entire loan term, including principal and interest.
Total Interest: The total interest paid over the life of the loan.
The user interface should be intuitive and user-friendly, with input fields for the loan amount, interest rate, and loan term, and a button to calculate the results.

### Describe alternatives you've considered.

I explored using existing online calculators, but they lack the educational value of building from scratch with HTML, CSS, and JavaScript. Other options included different frameworks or languages, but sticking with fundamental web technologies ensures broader accessibility and educational benefits. Manual calculation methods with spreadsheets were also considered but lack the real-time interactivity of a web-based application

**Comment by Ayushvishwakarma04** [comment]
I'd appreciate being assigned this task under GSSoC 24.

**Comment by swapnilsparsh** [comment]
@Ayushvishwakarma04 Thank you for providing your insight but it is not required as of now
