### ISSUE TITLE
Title: Add 16 Puzzle Game

### ISSUE THREAD

**Issue by katarianikita2003** [swapnilsparsh/30DaysOfJavaScript#1816]
### Is your feature request related to a problem? Please describe.

16 Puzzle Game using HTML, CSS and JavaScript

### Describe the solution you'd like.

Add game

### Describe alternatives you've considered.

No idea

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-18 111803](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/158465309/5cd51722-713c-405e-9935-ff1dd94ce81b)

**Comment by katarianikita2003** [comment]
@swapnilsparsh please assign it to me

**Comment by swapnilsparsh** [comment]
@katarianikita2003 Thank you for providing your insight but it is not required as of now
