### ISSUE TITLE
Title: Add Tetris Game

### ISSUE THREAD

**Issue by Tanishka023** [swapnilsparsh/30DaysOfJavaScript#1818]
### Is your feature request related to a problem? Please describe.

Tetris is a beloved classic game that is missing from our website. Furthermore, integrating Tetris is relatively straightforward with JavaScript and HTML5

### Describe the solution you'd like.

I propose adding a classic Tetris game to the website, developed using JavaScript and HTML5. This would provide a fun, nostalgic experience for users, enhancing their engagement and encouraging them to spend more time on the site.

### Describe alternatives you've considered.

**No response**

**Comment by swapnilsparsh** [comment]
@Tanishka023 This project is already exist in the repo
