### ISSUE TITLE
Title: Chess 

### ISSUE THREAD

**Issue by Tanishka023** [swapnilsparsh/30DaysOfJavaScript#1821]
### Is your feature request related to a problem? Please describe.

Chess is the most beloved classic game that is missing from our website. Furthermore, integrating this is relatively straightforward with JavaScript and HTML5

### Describe the solution you'd like.

I propose adding a classic PAC-MAN game to the website, developed using JavaScript and HTML5. This would be fun for users, enhancing their engagement and encouraging them to spend more time on the site.

### Describe alternatives you've considered.

**No response**

**Comment by swapnilsparsh** [comment]
@Tanishka023 Thank you for providing your insight but it is not required as of now
