### ISSUE TITLE
Title: Body Metrics Master

### ISSUE THREAD

**Issue by happyrao78** [swapnilsparsh/30DaysOfJavaScript#1822]
### Is your feature request related to a problem? Please describe.

It will calculate the average body mass index of a user.

### Describe the solution you'd like.

Using html , css  and js to build it.

### Describe alternatives you've considered.

I have just prompted user to enter his/her details and get the result.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/9c3c27e0-b60f-4986-98b1-f258943fa8b9)

**Comment by swapnilsparsh** [comment]
@happyrao78 This project already exits in the repo.
