### ISSUE TITLE
Title: Hue Harmony

### ISSUE THREAD

**Issue by happyrao78** [swapnilsparsh/30DaysOfJavaScript#1823]
### Is your feature request related to a problem? Please describe.

No problem related.

### Describe the solution you'd like.

I would just like to add colors and on clicking on that color the background color will be changed to that particular color.

### Describe alternatives you've considered.

Nothing, just javascript code integrated into html & css.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/1744cec1-630f-4535-946b-a71276017262)

**Comment by swapnilsparsh** [comment]
@happyrao78 This type of project already exits in the repo.
