### ISSUE TITLE
Title: Mystery Number Challenge

### ISSUE THREAD

**Issue by happyrao78** [swapnilsparsh/30DaysOfJavaScript#1824]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

I would  like to add a game of guessing a number in which user will be provided out with 10  chances  to guess the correct number and also he/she will be able to see the numbers entered so far.

### Describe alternatives you've considered.

no,only css ,js and  html.

### Add any other context or screenshots about the feature request here.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/57d76f5d-fbb9-4eb7-8bf5-ec4361281d10)

**Comment by laxmi09-walker** [comment]
hi, i would like to contribute to the mystery number challenge task . I  can  implement this efficiently. Looking forward o contributing!

**Comment by swapnilsparsh** [comment]
@happyrao78 This type of project already exits in the repo.
