### ISSUE TITLE
Title: Key checker

### ISSUE THREAD

**Issue by happyrao78** [swapnilsparsh/30DaysOfJavaScript#1825]
### Is your feature request related to a problem? Please describe.

Early users are not able to identify the  keys entered  by them, so this will allow the users to check which key is entered by them along with the key code.

### Describe the solution you'd like.

Key checker.

### Describe alternatives you've considered.

only html, css and js.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-18 192116](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/41cba001-b9b4-4cf9-9c2c-382f2a17f943)
![Screenshot 2024-06-18 192129](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/2d01cc7f-4d81-4304-b37a-4477e4808e4c)

**Comment by swapnilsparsh** [comment]
@happyrao78 This type of project already exits in the repo.
