### ISSUE TITLE
Title: Background Hue

### ISSUE THREAD

**Issue by happyrao78** [swapnilsparsh/30DaysOfJavaScript#1826]
### Is your feature request related to a problem? Please describe.

Not  problem related.

### Describe the solution you'd like.

I would just like to add two buttons start and stop clicking on start would start the background color changer and with a ease in-out transformation the color change will be intensively smooth. It will be helpful to make website more user interactive.

### Describe alternatives you've considered.

only html, css and js using math.random.

### Add any other context or screenshots about the feature request here.

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138770813/19284892-7dc2-4877-aa60-cc1069f62704

**Comment by swapnilsparsh** [comment]
@happyrao78 This type of project already exits in the repo.
