### ISSUE TITLE
Title: feat: Implement card flip hover effect

### ISSUE THREAD

**Issue by Miran-Firdausi** [swapnilsparsh/30DaysOfJavaScript#1828]
### Is your feature request related to a problem? Please describe.

Currently the way of showing description of project on hover is very instant and basic which can be improved by adding animation to it.

### Describe the solution you'd like.

To make the user interface and user experience better we can implement a card flip animation effect on hover.
Preview: https://codepen.io/Priyamaheshwari/pen/dyOxNXw

### Describe alternatives you've considered.

Text Popup animation: Instead of a card flip animation, we can use a popup effect to display the project description when the user hovers over the project card. This approach is more straightforward and doesn't require complex animations, but it may not be as visually appealing as the card flip effect.

Assign me this under gssoc'24

**Comment by swapnilsparsh** [comment]
@Miran-Firdausi Thank you for providing your insight but it is not required as of now
