### ISSUE TITLE
Title: Add Make Over Game using JavaScript

### ISSUE THREAD

**Issue by abckhush** [swapnilsparsh/30DaysOfJavaScript#1829]
### Is your feature request related to a problem? Please describe.

Integrate a functional Make-Over game using only JavaScript, HTML, and CSS. This classic game will provide an engaging gameplay experience for our users, allowing them to showcase their creativity.

### Describe the solution you'd like.

Game Setup:
Implement the game board using HTML for structure and CSS for styling.
Use JavaScript for game logic, including sliding over various dress options.

User Interface:
Design a visually engaging and easy-to-style interface with visuals.

Game Mechanics:
1. Choose from a variety of clothing items, including tops, bottoms, dresses, and shoes.
2. Customize hairstyles and hair colors.

### Describe alternatives you've considered.

1. Increasing Styling Options : Every dress, hair, and skin type can be adjusted using `Hue`, `Brightness` and `Intensity` to add more variety.
2. Saving Styles: We can add an option to let them save the outfit they made.

**Comment by swapnilsparsh** [comment]
@abckhush Thank you for providing your insight but it is not required as of now
