### ISSUE TITLE
Infinity Loop

### ISSUE THREAD

**Issue by starashdeep** [swapnilsparsh/30DaysOfJavaScript#183]
Hello swapnilsparsh I have built a creative graphic of infinity rainbow loop using HTML, CSS and JavaScript. 
Can I make a pr of this to your folder Will this count in GSsoc?

**Comment by swapnilsparsh** [comment]
> Hello swapnilsparsh I have built a creative graphic of infinity rainbow loop using HTML, CSS and JavaScript. Can I make a pr of this to your folder Will this count in GSsoc?

Good Luck 👍🏻
