### ISSUE TITLE
Title: Adding Bird Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1830]
### Which pre-existing JavaScript project will you be working on?

#1813 #1688 #1592 #1365 

### Describe your enhancement/improvement

- The game is made using html and CSS only and is a simple shooting game.
- We simply need to aim the cursor on the flying bird and click in order to shoot.
  The number of birds you aimed at reflects your score.

### Anything you need to say to the Reviewers

- The game is made using html and CSS only and is a simple shooting game.
- We simply need to aim the cursor on the flying bird and click in order to shoot.
  The number of birds you aimed at reflects your score.

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot 2024-06-19 064303](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/2340aa81-7a09-497d-baf8-acd0788ea3e8)

**Comment by codewithganeshhh** [comment]
dear @swapnilsparsh Please assign me

**Comment by swapnilsparsh** [comment]
@codewithganeshhh Thank you for providing your insight but it is not required as of now
