### ISSUE TITLE
Title: ADD Ball in a Maze Game

### ISSUE THREAD

**Issue by Nikhil11200** [swapnilsparsh/30DaysOfJavaScript#1831]
### Which pre-existing JavaScript project will you be working on?

I will be adding a game known as ball in a maze , which is a very interesting game.

### Describe your enhancement/improvement

The game addition will be making this project one step close towards the best pool of gaming projects . Ball in a maze is a very intersting and innovative game in which one needs to make the ball cross the maze and in its way the ball needs to be protected from the holes.

**Comment by swapnilsparsh** [comment]
@Nikhil11200 Thank you for providing your insight but it is not required as of now
