### ISSUE TITLE
Title: Add Tower Of Hanoi Game

### ISSUE THREAD

**Issue by tanyagupta01** [swapnilsparsh/30DaysOfJavaScript#1832]
### Is your feature request related to a problem? Please describe.

The Tower of Hanoi is a classic mathematical puzzle that consists of three towers and a set of disks of various sizes. 

The objective of the game is to move all the disks from one tower to another, while following certain rules, using one of the towers as an intermediate.

### Describe the solution you'd like.

Add the aforementioned game.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

<img width="1509" alt="Screenshot 2024-06-19 at 11 45 20 AM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156044894/2c88f55e-88fc-465e-b897-d10e1e13e074">

**Comment by swapnilsparsh** [comment]
@tanyagupta01 This type of project already exits in the repo.
