### ISSUE TITLE
Title: Addition of an Interactive Art Gallery Feature

### ISSUE THREAD

**Issue by Swapnilden** [swapnilsparsh/30DaysOfJavaScript#1833]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like.

I would like to propose the addition of an "Interactive Art Gallery" project. This feature would include:

1. A homepage displaying a gallery of artwork thumbnails.
2. A detailed view for each artwork, including a larger image, title, description, and comments section.
3. An interactive comment system where users can add and view comments.
4. This feature will enhance user engagement and provide a richer experience for art lovers.

### Describe alternatives you've considered.

Another alternative was using a simple image slideshow, but it lacks interactivity and user engagement features like commenting.

### Add any other context or screenshots about the feature request here.

![Screenshot (80)](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/142904704/f0dbeea9-a426-4d26-b6f2-6239faacbd4d)
This feature can be expanded in the future to include user authentication for comments, ratings for artworks, and more. 
Thank you for considering this feature request. Looking forward to your feedback and suggestions for this project to contribute in GSSOC'24.

**Comment by swapnilsparsh** [comment]
@Swapnilden Thank you for providing your insight but it is not required as of now

**Comment by Swapnilden** [comment]
Okay no problem
