### ISSUE TITLE
Title: Add Bullseye Game

### ISSUE THREAD

**Issue by tanyagupta01** [swapnilsparsh/30DaysOfJavaScript#1834]
### Is your feature request related to a problem? Please describe.

This is an archery game, It allows the user to drag and release an arrow, shooting at a target. 

It has a bow and arrow and a target
If the user misses the target then it shows its a "miss".
if the user hits the board other than the center part of the target, it shows "hit".
If the user hits at the middle circle of the target then it's a bullseye.

### Describe the solution you'd like.

Add the aforementioned game.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

<img width="1494" alt="Screenshot 2024-06-19 at 12 01 23 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156044894/3d54faed-2e61-4819-a0f7-39d4a23693ba">

**Comment by swapnilsparsh** [comment]
@tanyagupta01 Thank you for providing your insight but it is not required as of now
