### ISSUE TITLE
Title: Make Wave Effect Responsive

### ISSUE THREAD

**Issue by m3kvt** [swapnilsparsh/30DaysOfJavaScript#1837]
### Which pre-existing JavaScript project will you be working on?

21 - Wave Effect

### Describe your enhancement/improvement

Wave Effect feature is not responsive in mobile view. Some of the dots in the edges are not visible. Therefore I would like to fix this.

![Screenshot 2024-06-19 201847](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/98379619/d1b622c2-4667-4eb9-acf5-1b328734a514)

### Anything you need to say to the Reviewers

Please assign me this issue.

**Comment by swapnilsparsh** [comment]
@m3kvt All the best 👍🏻
