### ISSUE TITLE
Title:  Adding Blackjack Card Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1838]
### Which pre-existing JavaScript project will you be working on?

#1813 #1688 #1592 #1365 

### Describe your enhancement/improvement

The player has to get a hand with a value as close to 21 as possible without going over. 
A hand that goes over 21 is a bust. 
The players in a Taash Game plays against the dealer. Each player has to beat the dealer's hand in order to win.

### Anything you need to say to the Reviewers

The player has to get a hand with a value as close to 21 as possible without going over. 
A hand that goes over 21 is a bust. 
The players in a Taash Game plays against the dealer. Each player has to beat the dealer's hand in order to win.

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot 2024-06-19 202717](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/ed77c7b5-373a-4bbe-9859-531b1784bfb2)

**Comment by codewithganeshhh** [comment]
@swapnilsparsh assign me

**Comment by swapnilsparsh** [comment]
@codewithganeshhh Not required as of now.
