### ISSUE TITLE
Title: Misplacement of Link Icon

### ISSUE THREAD

**Issue by m3kvt** [swapnilsparsh/30DaysOfJavaScript#1839]
### Which pre-existing JavaScript project will you be working on?

05 - Random Password Generator

### Describe your enhancement/improvement

It is noted that the link icon is not responsive in mobile view. It is placed outside the box since the name of the feature is long. I would like to change the font size of the name so as to include the icon in the box.

![image](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/98379619/f19c18ee-7be4-48ec-8a5f-d07531869352)

### Anything you need to say to the Reviewers

Kindly assign me this issue.

**Comment by swapnilsparsh** [comment]
@m3kvt New UI is under process so this fix is not required as of now.
