### ISSUE TITLE
Title: Target Game

### ISSUE THREAD

**Issue by codewithganeshhh** [swapnilsparsh/30DaysOfJavaScript#1840]
### Which pre-existing JavaScript project will you be working on?

#arcade

### Describe your enhancement/improvement

A game in which you have to hit maximum number of targets within a given time frame
Made using HTML CSS and JS click on target to score a point

### Anything you need to say to the Reviewers

A game in which you have to hit maximum number of targets within a given time frame
Made using HTML CSS and JS click on target to score a point

### Add any other context or relevant screenshots about the enhancement here.

![Screenshot 2024-06-19 203314](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/139307139/18820f02-c441-4b3c-84de-846fa02d0abf)

**Comment by codewithganeshhh** [comment]
This one @swapnilsparsh

**Comment by codewithganeshhh** [comment]
It was palnned or not ?

**Comment by swapnilsparsh** [comment]
@codewithganeshhh Not accepting any new projects.

**Comment by codewithganeshhh** [comment]
It repository was closed ?

**Comment by swapnilsparsh** [comment]
@codewithganeshhh No
