### ISSUE TITLE
Title: Roulette Game

### ISSUE THREAD

**Issue by tanyagupta01** [swapnilsparsh/30DaysOfJavaScript#1842]
### Is your feature request related to a problem? Please describe.

Roulette is a classic casino game of chance that involves a spinning wheel, a small ball, and a betting table. Here’s a brief overview of how it works:

The Wheel
Design: The roulette wheel is divided into numbered pockets ranging from 0 to 36.
Colors: The numbers alternate between red and black, except for 0 , which are green.

The Table
The table displays all the numbers and the different types of bets that can be placed.
Bets can be made on individual numbers, groups of numbers, colors (red or black), odd or even, and high or low numbers.

Gameplay
Placing Bets: Players place their chips on the betting table, choosing their desired bets.

Payouts: The croupier announces the winning number and color, and winning bets are paid out according to a predetermined pay table, while losing bets are collected.

The primary goal is to predict which numbered pocket the ball will land in. Players can make a variety of bets, each offering different odds and payouts.
Roulette is known for its simplicity and excitement, attracting players with its wide range of betting options and the thrill of watching the ball bounce and settle into a pocket.

### Describe the solution you'd like.

add the aforementioned game.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

<img width="1182" alt="Screenshot 2024-06-19 at 10 04 01 PM" src="https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/156044894/e9d48f94-dda6-4a58-bfaa-b362704cce24">

**Comment by swapnilsparsh** [comment]
@tanyagupta01 Not accepting any new projects.
