### ISSUE TITLE
Feat: Adding FAQ (frequently asked question ) page

### ISSUE THREAD

**Issue by Husan7** [swapnilsparsh/30DaysOfJavaScript#1853]
### Is your feature request related to a problem? Please describe.

By adding FAQ PAGE THIS WEBSITE become more user friendly

It is responsive FAQ page

It creates " 30 days of javascript " more attractive .

### Describe the solution you'd like.

AFTER

https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/162671639/2ffb2ffe-1086-46ce-a36d-df3ed2369c49

![Screenshot 2024-05-24 145821](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/162671639/1339f375-732a-4403-b5f2-8012f091fec2)

### Describe alternatives you've considered.

I want to work on this issue 
Please assign me this issue

**Comment by swapnilsparsh** [comment]
@Husan7 Thank you for providing your insight but it is not required as of now
