### ISSUE TITLE
Title:  Adding CHATBOT FEATURE

### ISSUE THREAD

**Issue by Husan7** [swapnilsparsh/30DaysOfJavaScript#1854]
### Is your feature request related to a problem? Please describe.

By adding CHATBOT  THIS WEBSITE become more user friendly

### Describe the solution you'd like.

It will provide basic information to user .

### Describe alternatives you've considered.

I want to work on this issue  
Please assign me this issue

**Comment by swapnilsparsh** [comment]
@Husan7 Thank you for providing your insight but it is not required as of now
