### ISSUE TITLE
Title: Adding new js Project BMI Calculator

### ISSUE THREAD

**Issue by nikki-05** [swapnilsparsh/30DaysOfJavaScript#1855]
### Is your feature request related to a problem? Please describe.

The BMI (Body Mass Index) Calculator is a simple web application that allows users to input their weight and height to calculate their BMI. The BMI measures a person's weight and height to gauge whether they are underweight, normal weight, overweight, or obese according to standardized categories.

### Describe the solution you'd like.

User inputs for weight (in kilograms) and height (in centimetres).
A button to calculate BMI.
Display of the calculated BMI along with a category indicating the BMI range with appealing visuals

### Describe alternatives you've considered.

Creating a simple application using HTML, CSS and JavaScript

**Comment by swapnilsparsh** [comment]
@nikki-05 This project already exist.
