### ISSUE TITLE
Title: Dino Game

### ISSUE THREAD

**Issue by mohitmuktikant** [swapnilsparsh/30DaysOfJavaScript#1864]
### Is your feature request related to a problem? Please describe.

Google Chrome offline Dyno game using HTML, CSS, and JS

### Describe the solution you'd like.

Moreover like this
![Screenshot 2024-06-22 at 6 54 44 PM](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/101824646/211d823f-75f1-4cba-968d-bf2b9aa54c45)

### Describe alternatives you've considered.

This version of the game can be played on a  **touch screen**  or with a  **keyboard**.  The game will scale to fit on any size screen.

The goal of the game is for the dinosaur to avoid the obstacles by jumping over them. As the dinosaur runs along the desert, it will encounter plant. If you don't jump over them, it's game over. Our dino can perform a low or high jump. A low jump is achieved with a quick tap of the screen or a quick press of the **space bar**. A high jump requires taping the screen longer or pressing the space bar longer.

**Comment by mohitmuktikant** [comment]
@swapnilsparsh can you assign me this issue under GSSOC'24

**Comment by swapnilsparsh** [comment]
@mohitmuktikant No new projects.
