### ISSUE TITLE
Title: Improve the UI of Website

### ISSUE THREAD

**Issue by Vin205** [swapnilsparsh/30DaysOfJavaScript#1871]
### Is your feature request related to a problem? Please describe.

The color contrast and UI  of overall website needs to be improved to make website user appealing and improve user experience.

### Describe the solution you'd like.

Changing color contrast, font style and alignment of elements.

### Describe alternatives you've considered.

Background images can also be changed.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-06-23 203807](https://github.com/swapnilsparsh/30DaysOfJavaScript/assets/138381350/6cbc56bf-b9a3-42e0-8873-379198c0da27)

**Comment by riyasaxena32** [comment]
please assign me this issue to me under gssoc 24
i will complete it very soon
