### ISSUE TITLE
Title: Let's add a CUSTOM SCROLLBAR

### ISSUE THREAD

**Issue by mehrun171** [swapnilsparsh/30DaysOfJavaScript#1878]
### Which pre-existing JavaScript project will you be working on?

whole webiste

### Describe your enhancement/improvement

We can add a custom scroll bar to the website to improve the UI of website visibility

**Comment by mehrun171** [comment]
Please assign me this issue @swapnilsparsh

**Comment by vermagithubcs** [comment]
Please assign me this issue and I make a custom scrollbar @swapnilsparsh Sir!
