### ISSUE TITLE
Want to add weather app created with vanilla JS, GSSOC 22 Participant

### ISSUE THREAD

**Issue by AmolShelke2** [swapnilsparsh/30DaysOfJavaScript#188]
Hey, SwapnilSparsh I've created a very beginner-friendly weather app using vanilla JS where a user can search for the city and after hitting the Enter Keycode it will show the weather of that city I've made it look even nicer with good UI. Hope you will go through my Issue and assign me this issue to work on it.
I've also attached the ScreenShot of my Project.  give it a look 🙂

![weather png](https://user-images.githubusercontent.com/95171638/156401854-74295c80-bfb3-4b55-b7bd-a93b7abf0464.png)

**Comment by swapnilsparsh** [comment]
> Hey, SwapnilSparsh I've created a very beginner-friendly weather app using vanilla JS where a user can search for the city and after hitting the Enter Keycode it will show the weather of that city I've made it look even nicer with good UI. Hope you will go through my Issue and assign me this issue to work on it. I've also attached the ScreenShot of my Project. give it a look 🙂
> 
> ![weather png](https://user-images.githubusercontent.com/95171638/156401854-74295c80-bfb3-4b55-b7bd-a93b7abf0464.png)

Great project but weather app is already there on the website which you can check out [here](https://30daysofjs.netlify.app/25%20-%20weather%20app/)

Try looking out for some other projects which are not there on the website yet.
Good Luck 👍🏻

**Comment by AmolShelke2** [comment]
Okayy thanks for the reply✨
