### ISSUE TITLE
Title: [Project Addition] video-trailer-popup

### ISSUE THREAD

**Issue by bristiHalder** [swapnilsparsh/30DaysOfJavaScript#1889]
### Is your feature request related to a problem? Please describe.

This will display a movie poster with a title, description, and a "Watch now" button. When the button is clicked, a video trailer popup appears, allowing users to watch the trailer. The popup can be closed by clicking a close icon, pausing, and resets the video. 

### Describe the solution you'd like.

HTML Structure:
- Implement a main container to display the movie poster, title, description, and a "Watch now" button.
- Include a hidden trailer container holding the video element and a close icon.

CSS Styling:
- Use an external style sheet to style the page elements.
- Incorporate Font Awesome for the close icon and any other necessary icons.

JavaScript Functionality:
- Add event listeners to the "Watch now" button and the close icon.
- Show the trailer container and play the video when clicking the "Watch now" button.
- Hide the trailer container and pause/reset the video when the close icon is clicked

### Describe alternatives you've considered.

.

**Comment by riyasaxena32** [comment]
please assign me this issue to me under gssoc 24
i will complete it very soon
