### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by vedsom** [swapnilsparsh/30DaysOfJavaScript#189]
I want to make a search bar which will help users to find different options easily.
I am a GSSOC 2022 participant kindly assign this to me.

**Comment by KhushiRana2003** [comment]
Please assign this to me i want to work on this and i am gssoc 2022 participant...

**Comment by vedsom** [comment]
@swapnilsparsh  Sir please open this again

**Comment by vedsom** [comment]
@swapnilsparsh sir currently I have my end sem exams that's why I didn't get time to do this

**Comment by vedsom** [comment]
@swapnilsparsh  Sir please open it, I am very eager to do this issue, due to exams currently I have no time for this. I will complete it soon

**Comment by swapnilsparsh** [comment]
> 

It is already resolved by someone else.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Sir please open it, I am very eager to do this issue, due to exams currently I have no time for this. I will complete it soon

It is already resolved by someone else.
