### ISSUE TITLE
Title: Add a new project Jpg to png and png to jpg image converter

### ISSUE THREAD

**Issue by nikki-05** [swapnilsparsh/30DaysOfJavaScript#1910]
### Is your feature request related to a problem? Please describe.

I would like to propose a new project that provides functionality for converting images between JPG and PNG formats. This project would be beneficial for users who frequently need to convert images for various purposes, such as web development, graphic design, and content creation.

### Describe the solution you'd like.

The project allows us to 

Convert JPG images to PNG format.
Convert PNG images to JPG format.

### Describe alternatives you've considered.

Ensure the application works across all major browsers and platforms.

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-07-13 193834](https://github.com/user-attachments/assets/05d70188-3998-44b8-bed4-151f697d407d)
This is the attached sample

**Comment by nikki-05** [comment]
@swapnilsparsh can you assign me this issue

**Comment by ishag8** [comment]
@swapnilsparsh can u assign me this issue please?
