### ISSUE TITLE
Title: Adding smooth transitioning effect while changing the theme from dark to light

### ISSUE THREAD

**Issue by nameishyam** [swapnilsparsh/30DaysOfJavaScript#1913]
### Which pre-existing JavaScript project will you be working on?

I will work on the website, which is hosting all these javascript projects. That is, the main website

### Current Condition:
The current website gives the option to toggle from light theme to dark theme, which can be of great help for the users in the night time or while using the website in the low light enviornments. But the **Transition effect is'nt present**.
### My Modification:
I would like to **Improve the transition effect** in the project.

### Anything you need to say to the Reviewers

Sir I'm a GSSOC aspirant, and I have found this issue, which I have already solved. Please mark it as **gssoc**. Please assign me with this issue, I have already been came up with the solution for this.

**Comment by Sathwik279** [comment]
I too found this issue please resolve this as soon as possible
