### ISSUE TITLE
 Roman Calculator is merged but not available in the Live Page 

### ISSUE THREAD

**Issue by isid555** [swapnilsparsh/30DaysOfJavaScript#1925]
### What happened?

A JS project ,roman calculator has been merged and working succesfully ,but it not avaible for the users on the live web-page.
![image](https://github.com/user-attachments/assets/a9817816-caa0-46c9-8ca0-5393e7cc2045)

### How can we reproduce this bug?

To fix this ,we must move that folder into the projects folder and update the _data.json_ file accordingly.
**I kindly request the admin of this repo ,to assign this issue to me ,under _hacktoberfest-accpted_ label.
Thank you!**

### Urgency (Optional)

Medium priority

**Comment by swapnilsparsh** [comment]
@isid555 Thank You for reporting this, will fix this soon.

**Comment by isid555** [comment]
I would give a working PR for this issue , 
 if needed
