### ISSUE TITLE
Title: Add Search Bar Functionality

### ISSUE THREAD

**Issue by isid555** [swapnilsparsh/30DaysOfJavaScript#1926]
### Is your feature request related to a problem? Please describe.

Currently, our application does not have a search feature, making it difficult for users to find specific content quickly. Implementing a search bar would enhance user experience by allowing users to filter and locate information more efficiently.

### Describe the solution you'd like.

# Solution Description
Objective: Implement a search bar that allows users to quickly find and filter content within the application.

### Describe alternatives you've considered.

Instead of a standard search bar, implement a dropdown autocomplete feature that suggests possible matches as the user types.

## I kindly request you to add this issue with **_hacktoberfest-accepted label_** and assign to me

**Comment by swapnilsparsh** [comment]
@isid555 Good Luck 👍🏻

**Comment by isid555** [comment]
I have raised a PR ,kindly review it @swapnilsparsh
