### ISSUE TITLE
Adding smooth theme toggle transition

### ISSUE THREAD

**Issue by VrindaTyagi** [swapnilsparsh/30DaysOfJavaScript#194]
The current theme transitions abruptly while changing themes. I want to add **_a smooth transition effect_** while toggling between light and dark modes.

The new smooth transition effect will look somewhat like [this](https://cdn.dribbble.com/users/1054642/screenshots/7635203/media/006d6821c260c719f8baeeeefc3cab5d.gif)

**Comment by swapnilsparsh** [comment]
> The current theme transitions abruptly while changing themes. I want to add **_a smooth transition effect_** while toggling between light and dark modes.
> 
> The new smooth transition effect will look somewhat like [this](https://cdn.dribbble.com/users/1054642/screenshots/7635203/media/006d6821c260c719f8baeeeefc3cab5d.gif)

Use the same button which is shown in the design which you have mentioned.
