### ISSUE TITLE
Currency Converter

### ISSUE THREAD

**Issue by priyanshi-2001** [swapnilsparsh/30DaysOfJavaScript#196]
I want to create a simple currency converter using Html, CSS and JavaScript. The conversion of currency will be done by using API.

Please assign this issue to me.

**Comment by satyam1511** [comment]
hey Myself Kumar Satyam . I would like to contribute on this issue under Gssoc 22 . Please assign it to me.

**Comment by priyanshi-2001** [comment]
Sir I was recently trying to make a file in my forked repo. I don't know why its showing on your repo page at above. I am sorry for the mistake. I am new to open source. I will make PR in right way now. Sorry again.
