### ISSUE TITLE
Working on to-do list

### ISSUE THREAD

**Issue by Rhydham2809** [swapnilsparsh/30DaysOfJavaScript#197]
I can make to-do list more realistic along with timings and certain other features

**Comment by swapnilsparsh** [comment]
> I can make to-do list more realistic along with timings and certain other features

It is already there on the website which you can check out [here](https://30daysofjs.netlify.app/29%20-%20To%20Do%20List/index.html)

Look after some ideas, Good Luck 👍🏻
