### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by OussamaSALAHOUELHADJ** [swapnilsparsh/30DaysOfJavaScript#20]
Hey, I think the website needs a better UI, I'll build a better design for it.

**Comment by swapnilsparsh** [comment]
> Hey, I think the website needs a better UI, I'll build a better design for it.

Best of Luck 😀

**Comment by OussamaSALAHOUELHADJ** [comment]
a PR for this issue here: https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/33

**Comment by swapnilsparsh** [comment]
Issue resolve by @OussamaSALAHOUELHADJ #33
