### ISSUE TITLE
Add  a text to speech converter

### ISSUE THREAD

**Issue by ManaliPawar** [swapnilsparsh/30DaysOfJavaScript#202]
This converts text into speech of chosen language

**Comment by ManaliPawar** [comment]
please assign this issue to me

**Comment by ManaliPawar** [comment]
will be using HTML,CSS,JS @swapnilsparsh

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?
