### ISSUE TITLE
29- To-Do-List UI change

### ISSUE THREAD

**Issue by vanshi1405** [swapnilsparsh/30DaysOfJavaScript#206]
whenever we open application in desktop mode footer is overlapping to the container.
I want to solve this issue so please assign this issue to me.

**Comment by swapnilsparsh** [comment]
> 

Can you provide a screenshot for the same?

**Comment by swapnilsparsh** [comment]
> whenever we open application in desktop mode footer is overlapping to the container. I want to solve this issue so please assign this issue to me.

Can you provide a screenshot for the same?

**Comment by vanshi1405** [comment]
![Screenshot (38)](https://user-images.githubusercontent.com/84830835/156600992-0c468605-e5a6-47a8-8da4-92da9584dd03.png)
