### ISSUE TITLE
Guess the Number Game

### ISSUE THREAD

**Issue by IshitaBisaria** [swapnilsparsh/30DaysOfJavaScript#207]
Myself Ishita Bisaria,
I have built a web game, Guess the Number, its a fun game and I want to add it in this repository.
Kindly assign this issue to me.
Thanking you.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by prachi0011** [comment]
Hey, I have created the guess the number using Python already, please assign me this issue I will create guess the number using Javascript.
