### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by salahashraf253** [swapnilsparsh/30DaysOfJavaScript#214]
I want to create a simple Weather App using Html, CSS , JavaScript and Open Weather Map API

Please assign this issue to me.

I'm contributor at GSSoC'22.

**Comment by swapnilsparsh** [comment]
> I want to create a simple Weather App using Html, CSS , JavaScript and Open Weather Map API
> 
> Please assign this issue to me.
> 
> I'm contributor at GSSoC'22.

Weather app is already there on the website which you can check out [here](https://30daysofjs.netlify.app/25%20-%20weather%20app/)

Try looking out for some other projects which are not there on the website yet.
Good Luck 👍🏻
