### ISSUE TITLE
Add a Captcha Generator App

### ISSUE THREAD

**Issue by Atharv-110** [swapnilsparsh/30DaysOfJavaScript#215]
##### This project would be under GSSoC'22.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by Atharv-110** [comment]
Hey @sceary-expert, this project is again assigned to me. This issue was raised by me first so get some other project.
