### ISSUE TITLE
Jokes Chrome Extension (GSSOC'22)

### ISSUE THREAD

**Issue by sejalc22** [swapnilsparsh/30DaysOfJavaScript#216]
A simple chrome extension which when clicked upon gives us a random joke every time (extracted from an API)

GSSOC'22
could you assign this to me?

**Comment by swapnilsparsh** [comment]
> A simple chrome extension which when clicked upon gives us a random joke every time (extracted from an API)
> 
> GSSOC'22 could you assign this to me?

Will it be a simple HTML, CSS, JS project?

**Comment by swapnilsparsh** [comment]
@sejalc22 
It should be not like [this](https://30daysofjs.netlify.app/15%20-%20Joke%20Generator/index.html) as it is already there on the website.
Good Luck 👍🏻
