### ISSUE TITLE
Modify the Drum Kit

### ISSUE THREAD

**Issue by Shel-2607** [swapnilsparsh/30DaysOfJavaScript#218]
Hello  @swapnilsparsh this is Shelja Sharma , GSSOC'2022 participant , I want work on your existing "Drum Kit" project, as it is not properly designed
  I want to fix some things and I want to make it look more perfect and attractive.
Thank you for your time!! and looking forward to work on it.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?
