### ISSUE TITLE
Add more functionality in (08- number counter)

### ISSUE THREAD

**Issue by zaidm124** [swapnilsparsh/30DaysOfJavaScript#22]
I can add a save button to save the numbers and display below 

Reset button to reset the count to 0

**Comment by Johnisaig** [comment]
Hi, I would like to work on this, could you assign it to me?

**Comment by swapnilsparsh** [comment]
> Hi, I would like to work on this, could you assign it to me?

@Johnisaig Sorry but @zaidm124 is already working on this issue, Please look after some other issues.

**Comment by swapnilsparsh** [comment]
Issue resolved by @zaidm124 #26
