### ISSUE TITLE
Sudoku solver

### ISSUE THREAD

**Issue by Supriya2922** [swapnilsparsh/30DaysOfJavaScript#221]
A sudoku solver using Javascript,HTML,CSS
I would like to work on this.

**Comment by YatinDawar** [comment]
I would like to work on this.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903 can you assign me?

**Comment by SonikeshKumar14** [comment]
plz assigned me i made this project

**Comment by satyam1511** [comment]
hey myself Kumar Satyam . I am Gssoc Contributor . I would like to contribute on this issue  under Gssoc22 . Please assign it to me.
