### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by YatinDawar** [swapnilsparsh/30DaysOfJavaScript#222]
I want to make the classic snake game using javascript,HTML5,CSS.
I am a GSSOC 2022 participant kindly assign this to me.

**Comment by swapnilsparsh** [comment]
> I want to make the classic snake game using javascript,HTML5,CSS. I am a GSSOC 2022 participant kindly assign this to me.

It is already there on the website, you can checkout it [here](https://30daysofjs.netlify.app/38%20-%20Snake-Game/index.html)
Look after some other ideas.
