### ISSUE TITLE
Title: Update README.md 

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#226]
### Is your feature request related to a problem? Please describe.

Right Now I think we need to improve README.md file to make is best!

### Describe the solution you'd like.

Improve & make attractive README.md file

### Describe alternatives you've considered.

Improve UI

**Comment by kalashvasaniya** [comment]
Hey I really want to work on this issue

**Comment by Navi68** [comment]
can i work on this issue

**Comment by vickyrules** [comment]
Please assign this to me. If they are unable to complete in time.

**Comment by AnushaSP07** [comment]
Hi I'm from GSSOC 22 can you please assign the above task to my name, I will work on it
