### ISSUE TITLE
Title: Adding background color changer

### ISSUE THREAD

**Issue by nitishsaini706** [swapnilsparsh/30DaysOfJavaScript#227]
### Is your feature request related to a problem? Please describe.

it's a simple background color changer

### Describe the solution you'd like.

This background changer changes the color of background and displays the color , it has 2 features one is simple background and second is hexadecimal background

### Describe alternatives you've considered.

no

**Comment by swapnilsparsh** [comment]
It is already there, you can check out [here](https://30daysofjs.netlify.app/11%20-%20color%20picker/)
Don't start the work before getting assigned.
Good Luck 👍🏻
