### ISSUE TITLE
Pong classic-tennis game

### ISSUE THREAD

**Issue by Neelima-git** [swapnilsparsh/30DaysOfJavaScript#231]
Hi!

I'm a GSSoC'22 contributor. I would like to add a **Classic Pong game** built using HTML Canvas, CSS, and Javascript to this repository!

**Comment by swapnilsparsh** [comment]
> Hi!
> 
> I'm a GSSoC'22 contributor. I would like to add a **Classic Pong game** built using HTML Canvas, CSS, and Javascript to this repository!

Already in process
