### ISSUE TITLE
Title: Have added a new JS project named Calcify but cant raise a PR due to some issue.....please merge it 

### ISSUE THREAD

**Issue by pabak2002** [swapnilsparsh/30DaysOfJavaScript#232]
### Is your feature request related to a problem? Please describe.

Have added a new JS project named Calcify but cant raise a PR due to some issue.....please merge it 

### Describe the solution you'd like.

Have added a new JS project named Calcify but cant raise a PR due to some issue.....please merge it 

### Describe alternatives you've considered.

Have added a new JS project named Calcify but cant raise a PR due to some issue.....please merge it

**Comment by pabak2002** [comment]
I am a GSSOC'22 contributor so please merge it....earnest request.

**Comment by swapnilsparsh** [comment]
Can you explain you issue?
