### ISSUE TITLE
Add Rock Paper Scissors game  

### ISSUE THREAD

**Issue by sceary-expert** [swapnilsparsh/30DaysOfJavaScript#239]
You should add rock, paper, scissors game as many of the learning such as if/else  can be utilized make this kind of a basic game .

**Comment by AbhaHimani** [comment]
Please assign me this issue

**Comment by swapnilsparsh** [comment]
> 

It is already there on the website, which you can check out [here](https://30daysofjs.netlify.app/37%20-%20RPS%20Game/start.html)
