### ISSUE TITLE
Title:  Greeting Card

### ISSUE THREAD

**Issue by Simran2337** [swapnilsparsh/30DaysOfJavaScript#241]
### Is your feature request related to a problem? Please describe.

The greeting card project wishes the person, Good Morning, Good Afternoon and Good Evening based on the current day and time.

### Describe the solution you'd like.

This is built using -  HTML, CSS, Javascript

**Comment by Simran2337** [comment]
@swapnilsparsh  I created a pull request and updated the same, Can u please check?

**Comment by swapnilsparsh** [comment]
#255
