### ISSUE TITLE
Title:  Add Tip Calculator

### ISSUE THREAD

**Issue by 13-Joban** [swapnilsparsh/30DaysOfJavaScript#246]
### Is your feature request related to a problem? Please describe.

TipCalculator Project - A Simple Project where you can add the Bill amount and Number of People sharing the bill. Based Upon The service it will Calculate the Tip Amount. So you need not to worry about calculations Enjoy Your Food because Tip Calculator is There For You Always

### Describe the solution you'd like.

Hi Swapnil, Myself Jobanpreet Singh, GSSOC Contributor. I like to add my Tip Calculator Project to this repository. Kindly assign me with this issue. Tip Calculator using HTML, CSS, Javascript.

### Describe alternatives you've considered.

Hi Swapnil, Myself Jobanpreet Singh, GSSOC Contributor. I like to add my Tip Calculator Project to this repository. Kindly assign me with this issue. Tip Calculator using HTML, CSS, Javascript.

**Comment by swapnilsparsh** [comment]
#170 Already there.

**Comment by swapnilsparsh** [comment]
@13-Joban Good Luck 👍🏻
