### ISSUE TITLE
Title: Modify Notes taking App

### ISSUE THREAD

**Issue by vkukrolia0807** [swapnilsparsh/30DaysOfJavaScript#248]
After completion task if we want to delete the note there is not any delete note option.
Also there is no feature for highlights important note. 
I want to solve this issue , so I request you to assign this issue to me.

Here its shows the notes
![Screenshot (573)](https://user-images.githubusercontent.com/90061957/156779920-4098795d-c91e-4c44-8079-ca1016b89293.png)

After task completion remove the content so its shows empty  note there is no option for deleting a note.
![Screenshot (574)](https://user-images.githubusercontent.com/90061957/156780231-9be2a68a-cbd2-4ab7-961d-0c55e34c5183.png)

**Comment by Atharv-110** [comment]
@vkukrolia0807 there is deleting functionality by double clicking the note, an deletion popup will appear. 😀

**Comment by vkukrolia0807** [comment]
> @vkukrolia0807 there is deleting functionality by double clicking the note, an deletion popup will appear. 😀

Yes you are right but if new user can use this he/she will not getting that for deleting a note they have to double click it , so there has to be a button or else any note kind of thing to inform new users.
