### ISSUE TITLE
Title: Adding Titile option and Bookmark option in every note in Notes Taking App.

### ISSUE THREAD

**Issue by FaisalAI541** [swapnilsparsh/30DaysOfJavaScript#250]
### Is your feature request related to a problem? Please describe.

When ever I want to make a note, I will need the title option so that I can understand on what my note is based on.

And I will need a bookmark option so that I can find the note easily. 

### Describe the solution you'd like.

I will make the Tiltle option available.
I will make the bookmark option available.

### Describe alternatives you've considered.

There is not any alternatives.

To make the app more useful we have to make this changes.

### Add any other context or screenshots about the feature request here.

**Make this changes to make the app more efficient and useful**

**Comment by swapnilsparsh** [comment]
Can you mention the project number on which you want to work? or if you want to make a new project?

**Comment by swapnilsparsh** [comment]
> ### Is your feature request related to a problem? Please describe.
> When ever I want to make a note, I will need the title option so that I can understand on what my note is based on.
> 
> And I will need a bookmark option so that I can find the note easily.
> 
> ### Describe the solution you'd like.
> I will make the Tiltle option available. I will make the bookmark option available.
> 
> ### Describe alternatives you've considered.
> There is not any alternatives.
> 
> To make the app more useful we have to make this changes.
> 
> ### Add any other context or screenshots about the feature request here.
> **Make this changes to make the app more efficient and useful**

Can you mention the project number on which you want to work? or if you want to make a new project?

**Comment by FaisalAI541** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > When ever I want to make a note, I will need the title option so that I can understand on what my note is based on.
> > And I will need a bookmark option so that I can find the note easily.
> > ### Describe the solution you'd like.
> > I will make the Tiltle option available. I will make the bookmark option available.
> > ### Describe alternatives you've considered.
> > There is not any alternatives.
> > To make the app more useful we have to make this changes.
> > ### Add any other context or screenshots about the feature request here.
> > **Make this changes to make the app more efficient and useful**
> 
> Can you mention the project number on which you want to work? or if you want to make a new project?

Project No. 53 Notes (Notes Taking App)

**Comment by swapnilsparsh** [comment]
#248 It is already in process
