### ISSUE TITLE
Title: Want to add My Random anime profile pic generator to the list...

### ISSUE THREAD

**Issue by AmolShelke2** [swapnilsparsh/30DaysOfJavaScript#264]
### Is your feature request related to a problem? Please describe.

Hey, Project admin I'm a GSSOC participant this is my second issue in your project as you tell me that create something that is not in this so I've come with up my original project which is a Random Anime profile pic. this project is my own idea own features, Now I hope that you will go through my issue and assign me this issue to work on...

Thanks

### Describe the solution you'd like.

this can help the beginner developer to get to know how to work with web APIS this can be a great choice for that...

### Describe alternatives you've considered.

no..

### Add any other context or screenshots about the feature request here.

![192 168 187 73_5501_Random%20Anime%20Profile%20Pic_index html](https://user-images.githubusercontent.com/95171638/156879387-553ae19f-06d3-4ccb-bb75-68b6b14ac847.png)

**Comment by AmolShelke2** [comment]
I'm trying to clone the repository on my system but it is being failed that some branch doesn't have perfectly managed..

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.

**Comment by swapnilsparsh** [comment]
> I'm trying to clone the repository on my system but it is being failed that some branch doesn't have perfectly managed..

Now try cloning and let me know if it is not resolved.

**Comment by AmolShelke2** [comment]
I have opened the pull request please check
