### ISSUE TITLE
Title: Certificate Generaotr 

### ISSUE THREAD

**Issue by isha614** [swapnilsparsh/30DaysOfJavaScript#265]
### Is your feature request related to a problem? Please describe.

It's about adding a new simple project.

### Describe the solution you'd like.

I want to add a new project using HTML,CSS,JS Library which will help to download a certificate with your name in the existing template.

### Describe alternatives you've considered.

Libraries in JS have wide uses which makes work easy.

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.

**Comment by swapnilsparsh** [comment]
@isha614 Update?

**Comment by isha614** [comment]
> @isha614 Update?

 I am facing issue in cloning the repo.

**Comment by swapnilsparsh** [comment]
> > @isha614 Update?
> 
> I am facing issue in cloning the repo.

Try doing it now
