### ISSUE TITLE
Title: Simon Game 

### ISSUE THREAD

**Issue by shubham2-002** [swapnilsparsh/30DaysOfJavaScript#266]
### Is your feature request related to a problem? Please describe.

Adding New project 
**Simon game** is the exciting electronic game of lights and sounds in which players must repeat random sequences of lights by pressing the colored pads in the correct order

### Describe the solution you'd like.

I want re-create this game using html css and js 
Under **GSSOC** 

### Describe alternatives you've considered.

Na

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.
