### ISSUE TITLE
Title: Multiple card slider

### ISSUE THREAD

**Issue by Navi68** [swapnilsparsh/30DaysOfJavaScript#267]
### Is your feature request related to a problem? Please describe.

card sliders like in the amazon product section.

### Describe the solution you'd like.

by using mouse click function on Carousel, it will slide the cards.

### Describe alternatives you've considered.

we can also use the slick slider

**Comment by swapnilsparsh** [comment]
> ### Is your feature request related to a problem? Please describe.
> card sliders like in the amazon product section.
> 
> ### Describe the solution you'd like.
> by using mouse click function on Carousel, it will slide the cards.
> 
> ### Describe alternatives you've considered.
> we can also use the slick slider
> 
> ### Add any other context or screenshots about the feature request here.
> _No response_

Already there on the website, check out [here](https://30daysofjs.netlify.app/46%20-%20Image%20Slider/index.html)
