### ISSUE TITLE
Title: Tic-Tac-Toe online multiplayers

### ISSUE THREAD

**Issue by sudip-mondal-2002** [swapnilsparsh/30DaysOfJavaScript#277]
### Is your feature request related to a problem? Please describe.

I am adding a backend enabled project. That's a multiplayer game of tic tac toe, but it can be used for any multiplayer game further.

### Describe the solution you'd like.

Using sockets we can build communications between clients.

### Describe alternatives you've considered.

Developed a basic 2 player game, hosted on a Nodejs server. Bound socket endpoints in the server to connect different clients through the node-express server. Handled the socket connection on the frontend side with the help
of JS DOM. Broadcasted deltas instead of the whole state of a player to optimize the use of bandwidth up to 90%.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/74463091/156896963-98226f7b-2d40-4ad2-9f7f-c46e5cb680ed.png)

**Comment by sudip-mondal-2002** [comment]
@swapnilsparsh please assign me this issue

**Comment by swapnilsparsh** [comment]
Already there on the website [here](https://30daysofjs.netlify.app/30%20-%20Tic%20Tac%20Toe/index.html)
