### ISSUE TITLE
Title:Want  to modify Dynamic form field and  want to change the style and also want to add coding standard

### ISSUE THREAD

**Issue by Sohana4567** [swapnilsparsh/30DaysOfJavaScript#282]
### Is your feature request related to a problem? Please describe.

Yes,when  I  write number in name input  it is not showing  the error that name should be alphabet,same for email.I am not satisfy with the css styling and coding standard is not followed.

### Describe the solution you'd like.

if  anyone  write number,special symbol etc in name input,I want to  add the error name should be alphabet similarly for email.I want to change little bit of styling

### Describe alternatives you've considered.

if  anyone  write number,special symbol etc in name input,I want to  add the error name should be alphabet similarly for email.I want to change little bit of styling

### Add any other context or screenshots about the feature request here.

![Dynamic](https://user-images.githubusercontent.com/47296277/156910786-5021693b-41b7-443f-b6b8-9c73b16a846c.png)

**Comment by swapnilsparsh** [comment]
@Sohana4567 If name field is there then name should be entered not number so this issue is invalid

**Comment by Sohana4567** [comment]
if anyone wrongly give number,special character etc in name input so we can display the error  that name should be alphabet,In email,if anyone wrongly gave #gmail.com so we can display the error that email should be @gmail.com.
