### ISSUE TITLE
Title: Want to add new Project

### ISSUE THREAD

**Issue by Karan11000** [swapnilsparsh/30DaysOfJavaScript#285]
### Is your feature request related to a problem? Please describe.

It is a Food delivery Site based on HTML, CSS, BOOTSTRAP and JAVASCRIPT

### Describe the solution you'd like.

It is food delivery site having the feature to add food items into the cart and the UI is designed using css and bootstrap

### Describe alternatives you've considered.

I have used bootstrap as an alternative for css in some cases

**Comment by swapnilsparsh** [comment]
@Karan11000 Good Luck 👍🏻
