### ISSUE TITLE
Add a better function in clock

### ISSUE THREAD

**Issue by DAP2506** [swapnilsparsh/30DaysOfJavaScript#29]
instead of changing second hand in every 1sec it will be changing every micro sec so that sec clock hand become smooth and also feels good

**Comment by swapnilsparsh** [comment]
> instead of changing second hand in every 1sec it will be changing every micro sec so that sec clock hand become smooth and also feels good

Good Luck 🙂

**Comment by swapnilsparsh** [comment]
Issue resolved by @DAP2506 #41
