### ISSUE TITLE
Add a flappy bird game

### ISSUE THREAD

**Issue by KIET7UKE** [swapnilsparsh/30DaysOfJavaScript#293]
### Is your feature request related to a problem? Please describe.

I just made a game by using JavaScript

### Describe the solution you'd like.

This is only a single-player & end-user game

### Describe alternatives you've considered.

I used Html,Css & javascript

**Comment by KIET7UKE** [comment]
I'll like to contribute on this, Kindly assign me!!

**Comment by swapnilsparsh** [comment]
@KIET7UKE Can you provide more details regarding the game which you want to add?

**Comment by KIET7UKE** [comment]
It's a basically Single Player game built with the use of proper JavaScript

**Comment by swapnilsparsh** [comment]
@KIET7UKE Good Luck 👍🏻
