### ISSUE TITLE
Title: Dice Game

### ISSUE THREAD

**Issue by dsasaank-369** [swapnilsparsh/30DaysOfJavaScript#294]
### Is your feature request related to a problem? Please describe.

A fun game to play when looking for something easy and enjoyable to do. It helps to generate random numbers in dices and makes a player win. 

### Describe the solution you'd like.

I want to add a Dice Game made using HTML, CSS, and JS.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/80057285/156934186-26edc877-7cc3-4deb-bb0d-81e7ed62c8e3.png)

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.
You can visit my repo link - https://github.com/kunarkrawat/Dice-Challenge

**Comment by swapnilsparsh** [comment]
Already there on the website
