### ISSUE TITLE
Add a Bottom to Top Button onn 30DaysOfJS Website

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#3]
`Website` https://30daysofjs.netlify.app/

**Comment by suprabhat25** [comment]
I am interested in working on this issue.

**Comment by suprabhat25** [comment]
can you send me the repo link of this website ?

**Comment by swapnilsparsh** [comment]
> can you send me the repo link of this website ?
https://github.com/swapnilsparsh/30DaysOfJavaScript

**Comment by swapnilsparsh** [comment]
Issue resolved by @suprabhat25 #9
