### ISSUE TITLE
Add Password Strength checker Project

### ISSUE THREAD

**Issue by AnushaV-2002** [swapnilsparsh/30DaysOfJavaScript#300]
Myself Anusha, I'm GSSOC Contributor. I like to add my password strength checker Project using HTML, CSS and Javascript to this repository. Kindly, assign me with this issue.

**Comment by satyam1511** [comment]
Hii , i want to contribute on this issue  under @Gssoc22 . Please assign it to me.

**Comment by swapnilsparsh** [comment]
@AnushaV-2002 Good Luck 👍🏻
