### ISSUE TITLE
[Bug Title here] Add a image in assets for Notes Taking App

### ISSUE THREAD

**Issue by Neha9849** [swapnilsparsh/30DaysOfJavaScript#302]
### What happened?

Currently there is no image for this project in the assets Folder. 
 
Which is causing this issue -
![image](https://user-images.githubusercontent.com/85057583/157057556-4ae6463a-a3cd-4b78-8e02-a602bdb125c0.png)

### How can we reproduce this bug?

Just add an image in the assest folder with the name used in the main index.html.

**Comment by anirudh357** [comment]
Hi I want to work on this, can you assign this to me.

**Comment by swapnilsparsh** [comment]
Someone else is already working on this issue
