### ISSUE TITLE
Title: Random Joke Generator

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#305]
### Is your feature request related to a problem? Please describe.

Making Random Joke Generator Using API

### Describe the solution you'd like.

Use  API to generator joke! 

### Describe alternatives you've considered.

Made with use of HTML, CSS, JS.

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue

**Comment by swapnilsparsh** [comment]
It is already there on the website.
