### ISSUE TITLE
Title: Maths Addition Game

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#306]
### Is your feature request related to a problem? Please describe.

Making Maths Addition Game.

### Describe the solution you'd like.

Maths Addition Game Is very useful.

### Describe alternatives you've considered.

I make this game using HTML, CSS, JS.

**Comment by kunarkrawat** [comment]
Hey I would like to work on this issue.

**Comment by kalashvasaniya** [comment]
HEy Pls. Open this issue again Due to my college exam I can't make PR on that!
