### ISSUE TITLE
Title: Countdown Clock Project

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#307]
### Is your feature request related to a problem? Please describe.

 Countdown Clock Project is useful.

### Describe the solution you'd like.

I make Countdown Clock Project with the help of HTML, CSS, JS.

### Describe alternatives you've considered.

 Countdown Clock.

**Comment by satyam1511** [comment]
hey @kalashvasaniya  , I would like to contribute in this issue . Please assign it to me.

**Comment by swapnilsparsh** [comment]
Already there on the website
