### ISSUE TITLE
An Quiz App using javascript

### ISSUE THREAD

**Issue by Dharmesh177** [swapnilsparsh/30DaysOfJavaScript#308]
Is your feature request related to a problem? Please describe.
Quiz App using Javascript

Describe the solution you'd like.
I have been created Quiz App using HTML CSS and javascript.

Describe alternatives you've considered.
 For testing purposes, I am adding 4 Questions may be in the future we can add more and more questions. 

I have hosted it on GitHub which URL is given below:

https://dharmesh177.github.io/KUDOZU-QUIZ-APP/

![2022-03-08](https://user-images.githubusercontent.com/77879603/157167105-a649667c-ebf9-43e8-a353-9350fcf00582.png)

**Comment by swapnilsparsh** [comment]
@Dharmesh177 Good Luck 👍🏻
