### ISSUE TITLE
Title: Adding a navbar and global search on that navbar to easily access the projects

### ISSUE THREAD

**Issue by Simran2337** [swapnilsparsh/30DaysOfJavaScript#309]
### Is your feature request related to a problem? Please describe.

Its a feature request!!

### Describe the solution you'd like.

Having a navbar and a search bar makes the website look more proficient and search bar helps easy search for the project

@swapnilsparsh  if u find this enhancement a good one ... do assign it to me

**Comment by swapnilsparsh** [comment]
@Simran2337 Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
#346
