### ISSUE TITLE
Add 2048 Game

### ISSUE THREAD

**Issue by itaintkevin** [swapnilsparsh/30DaysOfJavaScript#314]
Hi @swapnilsparsh, I would like to add a 2048 game.
- It is a simple game, where u add tiles each with a value starting of 2, all the way up to 2048 in a concise 4x4 Grid.
- It tracks your score too.

**Stack Used for this Project:**
- [X] HTML
- [X] CSS
- [X] JavaScript

**I am GSSOC participant, please assign this issue to me.**

**Comment by swapnilsparsh** [comment]
@itaintkevin Good Luck 👍🏻
