### ISSUE TITLE
Add FlipBook

### ISSUE THREAD

**Issue by shivam123-dev** [swapnilsparsh/30DaysOfJavaScript#317]
## Project Name
My FlipBook

## Stack Used for in the Project:
- [x] HTML
- [x] CSS
- [x] JavaScript

## Screenshots
![image](https://user-images.githubusercontent.com/81038095/157377286-7d91205c-0515-4448-a29d-7f38dc795eb2.png)
![image](https://user-images.githubusercontent.com/81038095/157377324-0b3b5e21-1562-4af7-b7b5-58ade11f3d7a.png)

@swapnilsparsh I am GSSOC'22 participant, please assign me this issue.

**Comment by swapnilsparsh** [comment]
@shivam123-dev Good Luck 👍🏻
