### ISSUE TITLE
Title: New Game Addition 

### ISSUE THREAD

**Issue by bhumikatewary** [swapnilsparsh/30DaysOfJavaScript#325]
Hi @swapnilsparsh, I would like to add a bet game and have also made a pull request for the same: Added new game website #324

It is a betting game where you can bet the amount of money between two players and see who wins which is all random.

Stack Used for this Project:

 HTML
 CSS
 JavaScript
I am GSSOC participant, please assign this issue to me.

**Comment by Srushti-Naik** [comment]
I would like to add Tic-tac-toe game using CSS and tower block game.
I'm GSSOC'22 participant please assign this project to me.
