### ISSUE TITLE
Title: Random Movie/TV Series Quote Generator

### ISSUE THREAD

**Issue by abhilipsasahoo03** [swapnilsparsh/30DaysOfJavaScript#326]
# Project Description

Hi, I'm a GSSOC'22 Contributor and I'd like to add a Random Famous Movie/TV Series Quote Generator project

# Stack Used

•HTML
•CSS
•JS

**Comment by abhilipsasahoo03** [comment]
Hi @swapnilsparsh kindly assign me this issue under GSSOC'22 Contribution so that I can start working on it.

**Comment by swapnilsparsh** [comment]
@abhilipsasahoo03 Good Luck 👍🏻
