### ISSUE TITLE
Title: Falling Ball Game

### ISSUE THREAD

**Issue by priyanshu688** [swapnilsparsh/30DaysOfJavaScript#327]
### Is your feature request related to a problem? Please describe.

Falling Ball Game using JavaScript.

### Describe the solution you'd like.

I have created this falling ball game using HTML, CSS, JavaScript.

### Describe alternatives you've considered.

Libraries in JS have uses which makes the work easy. 

### Add any other context or screenshots about the feature request here.

I have hosted this game on GitHub Pages for which the URL is given below :-
[https://priyanshu688.github.io/Falling_Ball_Game/](url)

**Comment by priyanshu688** [comment]
@swapnilsparsh Kindly assign this issue to me

**Comment by priyanshu688** [comment]
I am a participant under GSSOC 2022. I would like to work on the issue. Please assign it to me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@priyanshu688 Good Luck 👍🏻

**Comment by priyanshu688** [comment]
@swapnilsparsh Thank you!
