### ISSUE TITLE
Title : Adding spin the wheel game

### ISSUE THREAD

**Issue by TG922** [swapnilsparsh/30DaysOfJavaScript#328]
**Project title**
Adding Spin the wheel game

**Project Description**
You will play spin the wheel game and receive reward if you win.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by swapnilsparsh** [comment]
@TG922 Good Luck 👍🏻

**Comment by TG922** [comment]
I've almost worked on it will send PR Tommorow
