### ISSUE TITLE
Title: Body Mass Index Calculator

### ISSUE THREAD

**Issue by Chandana-23** [swapnilsparsh/30DaysOfJavaScript#329]
### Is your feature request related to a problem? Please describe.

Yes.
We can build this body mass index calculator using HTML, CSS, JavaScript. 

### Describe the solution you'd like.

This can be developed using frames in HTML and javascript logic will help us to calculate body mass index value and classify a person's health as underweight or overweight or normal. 

### Describe alternatives you've considered.

Body mass index can be calculated in both standard units and metric units.

**Comment by aditi10701** [comment]
I am interested in working with this issue. Please assign me. I will try my best to and complete this project with full dedication to provide desired results.

**Comment by Mennapika** [comment]
I am interested in working with this issue. Please assign me. I will try my best to and complete this project

**Comment by swapnilsparsh** [comment]
@Chandana-23 Good Luck 👍🏻

**Comment by Chandana-23** [comment]
@swapnilsparsh Thank You, Sir. I raised a PR for this issue. Kindly review it.

**Comment by Chandana-23** [comment]
I created a PR with the required changes. Kindly review it.
