### ISSUE TITLE
Title: PacMan 

### ISSUE THREAD

**Issue by Mennapika** [swapnilsparsh/30DaysOfJavaScript#332]
### Is your feature request related to a problem? Please describe.

************************* **PacMan** ********************************
  Creating Pac man Game using JS , PURE CSS AND HTML

### Describe the solution you'd like.

**1. Win when reaching 274 points 
2. eat fruits and the ghosts freeze 
3. if ghost eat you you lose** 

### Describe alternatives you've considered.

cosider using keyboard keys

### Add any other context or screenshots about the feature request here.

![pacMan](https://user-images.githubusercontent.com/38566183/158308182-45303a9f-61c3-488d-a25c-cf56665f9d08.PNG)

**Comment by swapnilsparsh** [comment]
@Mennapika Good Luck 👍🏻
