### ISSUE TITLE
car Game

### ISSUE THREAD

**Issue by nitishsaini706** [swapnilsparsh/30DaysOfJavaScript#333]
### Is your feature request related to a problem? Please describe.

Car game using html ,CSS , JS

### Describe the solution you'd like.

Using basic concepts of js

### Describe alternatives you've considered.

To further improve game in design and features

**Comment by swapnilsparsh** [comment]
@nitishsaini706 Good Luck 👍🏻

**Comment by nitishsaini706** [comment]
@swapnilsparsh I already opened a pr
