### ISSUE TITLE
Title: URL Bookmark

### ISSUE THREAD

**Issue by Salma-Hamed** [swapnilsparsh/30DaysOfJavaScript#335]
### Is your feature request related to a problem? Please describe.

Creating a URL bookmark web application that saves URLs in the local storage.

### Describe the solution you'd like.

1. To add a URL:
      - Enter the name you want to save the URL as.
      - Enter the URL.
      - Click on the (Save) button.
      - The URL will appear at the bottom of the page.
2. To visit a saved URL, click on the (Visit) button next to it.
3. To delete a saved URL, click on the (Delete) button next to it.

I am a GSSoC'22 participant. Please assign it to me.

### Describe alternatives you've considered.

1. The URL can be saved with the original website name or any other name.
2.  The URL can be entered with or without the protocol part. If it's not entered by the user, it will be considered as (https://).

### Add any other context or screenshots about the feature request here.

I have uploaded it on GitHub which URL is given below:
(https://github.com/Salma-Hamed/URL-Bookmark).

![Screenshot](https://user-images.githubusercontent.com/71777717/158380155-4d5b9c8d-d948-410e-b2e1-dd0868e1dcd8.PNG)

**Comment by swapnilsparsh** [comment]
@Salma-Hamed Good Luck 👍🏻

**Comment by Salma-Hamed** [comment]
@swapnilsparsh please review and merge my PR
