### ISSUE TITLE
Title: Transpose of 3X3 Matrix Calculator

### ISSUE THREAD

**Issue by ShruthiKartik** [swapnilsparsh/30DaysOfJavaScript#336]
### Is your feature request related to a problem? Please describe.

I want to add Transpose of 3X3 Matrix Calculator as a project to be made during the 30 days of the JavaScript challenge.

### Describe the solution you'd like.

This Calculator calculates the transpose of a given 3X3 matrix in very few seconds. This is built with- HTML,CSS and JavaScript. It is responsive and supports all devices.

I am GSSOC 2022 Contributor. Please assign me this issue.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/99183334/156987108-cded0866-634b-4d60-970f-dfb93915cdab.png)

**Comment by swapnilsparsh** [comment]
@ShruthiKartik Good Luck 👍🏻
