### ISSUE TITLE
Title: Tetris game 

### ISSUE THREAD

**Issue by Akriti-007** [swapnilsparsh/30DaysOfJavaScript#338]
### Is your feature request related to a problem? Please describe.

Hello! I am GSSoC 2022 contributor. Wouldn't it be great be great if we have a good pass time to make up our mood as well as improve our thinking skills?

### Describe the solution you'd like.

For solving that I would like to create a Tetris game which engages our minds and is a good pass-time activity.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

.

**Comment by swapnilsparsh** [comment]
@Akriti-007 Good Luck 👍🏻 and use HTML, CSS, and JS only.
