### ISSUE TITLE
Formatter Color Codes

### ISSUE THREAD

**Issue by XZANATOL** [swapnilsparsh/30DaysOfJavaScript#341]
### Is your feature request related to a problem? Please describe.

Adding a a converter that converts a provided color codes into its equivalent values in other formats. The calculator will support converting from and to RGB / CMYK / Hex / HsL as input will be validated through Regex.

### Describe the solution you'd like.

The converter will make use of HTML / CSS / JS

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/64689436/158792327-9a927c7c-488b-4e44-b845-e3cab29eb49e.png)

Issue made under GSSoC'22 contributions.

**Comment by swapnilsparsh** [comment]
@XZANATOL Good Luck 👍🏻
