### ISSUE TITLE
Third Degree Equations solver

### ISSUE THREAD

**Issue by XZANATOL** [swapnilsparsh/30DaysOfJavaScript#342]
### Is your feature request related to a problem? Please describe.

Add a responsive calculator that prints out the 3 roots of a third degree equation (ax^3 + bx^2 + cx + d = 0)

### Describe the solution you'd like.

The calculator will be able to:
* Handle complex/imaginary solutions.
* Reponsive on both desktop and mobile devices.
* Make use of HTML / Bootstrap5 / CSS / JS.

### Describe alternatives you've considered.

none

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/64689436/158792746-56b00d22-95b6-4a53-b418-946c64f514ba.png)

Issue made under GSSoC'22 contributions.

**Comment by swapnilsparsh** [comment]
@XZANATOL Good Luck 👍🏻
