### ISSUE TITLE
Audio visualizer with js 

### ISSUE THREAD

**Issue by MonarchGitHub** [swapnilsparsh/30DaysOfJavaScript#350]
### Is your feature request related to a problem? Please describe.

I want to build an **Audio Visualizer** in js, it will show the **spectrum waves** corresponding to the voice input given to it. This will be a really great project for beginners to understand the deep working of js and HTML.

### Describe the solution you'd like.

I'm planning to use CSS and HTML for the frontend, I also want to try a few GUI libs for this project.

### Describe alternatives you've considered.

I'm working on a Figma prototype for this project and will attach the projected design asap here.

**Comment by MonarchGitHub** [comment]
Kindly assign me this issue.

**Comment by swapnilsparsh** [comment]
@MonarchGitHub Good Luck 👍🏻

**Comment by MonarchGitHub** [comment]
@swapnilsparsh I am still working on this issue, kindly reopen it. I will raise a PR to review by today positively.
