### ISSUE TITLE
Make the 08 - Number Counter Responsive.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#36]

**Comment by SK02K1** [comment]
Hey Swapnil, I would like to solve this issue can you please assign it to me

**Comment by swapnilsparsh** [comment]
> Hey Swapnil, I would like to solve this issue can you please assign it to me

Good Luck

**Comment by SK02K1** [comment]
hey, @swapnilsparsh I have added responsiveness to the app, please review my PR and merge it 😊

**Comment by swapnilsparsh** [comment]
> hey, @swapnilsparsh I have added responsiveness to the app, please review my PR and merge it 😊

Issue resolved by @SK02K1 #51
