### ISSUE TITLE
Windows 11 using JS 

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#362]
Hi, I am **TRIDIB BAG**. I'm a GSSoC22 participant.
I want to make a **Windows 11** clone using HTML, CSS, JS and wanted to add in this repo .

Can @swapnilsparsh you please assign it to me?

**Comment by swapnilsparsh** [comment]
@Mrjoy832 Good Luck 👍🏻
