### ISSUE TITLE
Changing the theme of the Greeting page 

### ISSUE THREAD

**Issue by rajutkarsh07** [swapnilsparsh/30DaysOfJavaScript#365]
### Is your feature request related to a problem? Please describe.

I will change the theme of the greetings page by changing its gradient and font family by using css

### Describe the solution you'd like.

I will change the gradient used in the page with much better gradient and also change the font used in the page

### Describe alternatives you've considered.

I will write CSS to make the changes in the page

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/49344502/159956556-54c99b89-8b5e-4477-8cb3-7496bf889807.png)

**Comment by swapnilsparsh** [comment]
@rajutkarsh07 Not necessary
