### ISSUE TITLE
Images of some cards are not visible in the website.

### ISSUE THREAD

**Issue by VartikaB** [swapnilsparsh/30DaysOfJavaScript#371]
### What happened?

Images of some cards are not visible in the website.
![Screenshot (139)](https://user-images.githubusercontent.com/81951781/160187942-6f1a21a5-b165-43cc-8b42-c7dbe7cf74be.png)

### How can we reproduce this bug?

This bug can be fixed by adding images to the respective projects.

**Comment by swapnilsparsh** [comment]
@VartikaB Take the screenshot of every project whose images are missing in full-screen by pressing F11 on the keyboard

**Comment by VartikaB** [comment]
sure!

**Comment by swapnilsparsh** [comment]
@VartikaB Update?

**Comment by swapnilsparsh** [comment]
@VartikaB Try to fix these links or leave these links and push the rest of the code.

**Comment by VartikaB** [comment]
sure!

**Comment by swapnilsparsh** [comment]
> 

You have to click the screenshot of the project and then store it in the asset folder with the proper folder number for that project then the images will get loaded.

**Comment by swapnilsparsh** [comment]
> Images are missing in asset folder. This is creating problem for images to load.

You have to click the screenshot of the project and then store it in the asset folder with the proper folder number for that project then the images will get loaded.

**Comment by VartikaB** [comment]
On it

**Comment by swapnilsparsh** [comment]
@VartikaB All the sites are now working, have a look now and update the images ASAP as you are working on this issue for quite a long time.

**Comment by GaganpreetKaurKalsi** [comment]
Hi! I would like to work on this issue. Could you please assign it to me! 
I would also like to alter css a little bit as I have seen, in case of missing images, the project heading is being shifted to the top instead of remaining in it's original place at the bottom.
Thanks!

**Comment by swapnilsparsh** [comment]
@GaganpreetKaurKalsi DO the necessary changes and take the screenshot of every project whose images are missing in full-screen by pressing F11 on the keyboard
