### ISSUE TITLE
Text-To-Speech

### ISSUE THREAD

**Issue by ishika1501** [swapnilsparsh/30DaysOfJavaScript#377]
### Is your feature request related to a problem? Please describe.

Sir, i wanted to make a text -to -speech  using **Js,  HTML, CS** .
Please assign it to me.
![WhatsApp Image 2022-03-20 at 7 56 31 PM (1)](https://user-images.githubusercontent.com/86921052/160318931-5c60b940-49a0-45e9-883b-49410e15413a.jpeg)

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

**Comment by swapnilsparsh** [comment]
@ishika1501 Thank you for your contribution. Looking forward to more such amazing contributions 🥂
