### ISSUE TITLE
Custom Emoji sliders

### ISSUE THREAD

**Issue by Kumar-Ankit56** [swapnilsparsh/30DaysOfJavaScript#379]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a custom emoji slider.

### Idea behind this project
This is a very mini project of an e-commerce site, as whenever we visit any site then after purchasing there is a popup for giving a review regarding the project. sometimes you have to give in a star rating or you can have an emoji slider by which you can express yourself, so the idea is from there only.

### How does it works 
whenever you will slide the range bar then after with respect to range there will match emoji preview and parallelly you will observe background changing.

please refer to this image

![Screenshot (96)](https://user-images.githubusercontent.com/73521123/160627449-b22879c3-f84b-4af6-ad4f-d1062d625298.png)
![Screenshot (97)](https://user-images.githubusercontent.com/73521123/160627464-f1381d68-8359-40b6-8402-a5e18f54cbee.png)

Thanku

**Comment by swapnilsparsh** [comment]
@Kumar-Ankit56 Good Luck 👍🏻
