### ISSUE TITLE
Web Scraper (GSSOC'22)

### ISSUE THREAD

**Issue by sejalc22** [swapnilsparsh/30DaysOfJavaScript#381]
scraping data from websites using javascript packages

assign this to me
gssoc'22

**Comment by swapnilsparsh** [comment]
> scraping data from websites using javascript packages
> 
> assign this to me gssoc'22

Can you explain your issue?

**Comment by sejalc22** [comment]
hey,
the application would scrape required data from a given URL and store it into an array
packages: axios, cheerio, express
(eg: scraping name and price of products from an e-commerce website)

**Comment by swapnilsparsh** [comment]
> > > scraping data from websites using javascript packages
> > > assign this to me gssoc'22
> > 
> > 
> > Can you explain your issue?
> 
> hey, the application would scrape required data from a given URL and store it into an array packages: axios, cheerio, express (eg: scraping name and price of products from an e-commerce website)

You have to make a project using simple HTML, CSS and JS only
