### ISSUE TITLE
BlackJack Game

### ISSUE THREAD

**Issue by MrunalHedau4102** [swapnilsparsh/30DaysOfJavaScript#385]
Hello Myself Mrunal Hedau I would like to contribute to your repo. I have made a blackjack game Using JavaScript, HTML, CSS.

- This is an intermediate level project where a user has to Hit the hit button to generate a random card from given selected cards along with that the score is been calculated and if the score reaches a maximum score ie 30 it will get burst.

- Then the user has to click the Stand button to check whether his score is greater than the computer score or not. if yes then it will display your won else you lose or draw.
- 
- The most interesting part is that we can tally the gameplay in the table below our gameplay area that how many wins, loses, and draws are being happened.  Along with that if the user wins the game the sound is produced the same, if the user losses the game.

- The Deal button’s function is to compare user and computer scores to tell who else wins or loses.

![Output_1](https://user-images.githubusercontent.com/79844456/161114738-04023b30-dabc-49a7-abca-56ebc80a40bb.png)
![Output_2](https://user-images.githubusercontent.com/79844456/161114750-78bf563e-bf34-443c-82d5-47e33b294973.png)

**Comment by MrunalHedau4102** [comment]
Please assign this to me, it would be very helpful.
Thank You!!

**Comment by swapnilsparsh** [comment]
@MrunalHedau4102 Good Luck 👍🏻

**Comment by MrunalHedau4102** [comment]
gh repo clone MrunalHedau4102/BlackJack-Game

**Comment by MrunalHedau4102** [comment]
Please tell me how should I add my code to your repo? Because it is showing permission denied.

**Comment by MrunalHedau4102** [comment]
Please tell me how should I add my code to your repo? Because it is showing permission denied.

**Comment by swapnilsparsh** [comment]
> 

You have to fork the repo and then make a commit thereafter that create a Pull Request for the same.

**Comment by swapnilsparsh** [comment]
> Please tell me how should I add my code to your repo? Because it is showing permission denied.

You have to fork the repo and then make a commit thereafter that creates a Pull Request for the same.
