### ISSUE TITLE
Title: Not Responsive 

### ISSUE THREAD

**Issue by Sunil4510** [swapnilsparsh/30DaysOfJavaScript#398]
### **The Current Behavior**
![Screenshot (102)](https://user-images.githubusercontent.com/77005171/161293728-b19c4e35-193c-4ab8-ae88-19cc4f5e62a9.png)

- As you can see in the image, the dark/light mode icon is not placed at good position.
- It is hiding the heading also.

### **The Expected Behavior**

- [ ] Needs to fix the position of dark/light mode icon, so we need to set the position to the left of the client side. 

### We  need to go into the toggleButton class. 
`.toggleButton{
left:0;
}`
![Screenshot (103)](https://user-images.githubusercontent.com/77005171/161295736-e7491384-cb46-42eb-a394-d30cbd245572.png)

**Comment by Rishita489** [comment]
Hey @swapnilsparsh , I am a GSSOC'22 contributor . I have solved the issue of making title responsive . Can you please assign this issue to me . I have send the PR . Please review and merge it .
