### ISSUE TITLE
Title: lightBulb Effect project

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#408]
### Is your feature request related to a problem? Please describe.

Hey I madelightBulb Effect project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!
<img width="614" alt="Screenshot 2022-04-02 at 4 27 51 PM" src="https://user-images.githubusercontent.com/88212870/161380172-d462fde2-f7e5-443e-a982-d903d0790e01.png">
<img width="614" alt="Screenshot 2022-04-02 at 4 27 49 PM" src="https://user-images.githubusercontent.com/88212870/161380175-36439525-1b61-41a4-994b-446ac5b4cad4.png">

**Comment by swapnilsparsh** [comment]
It's like a simple toggle button which is not a quite good project.

**Comment by kalashvasaniya** [comment]
> It's like a simple toggle button which is not a quite good project.

ok np :)
