### ISSUE TITLE
Grammarly 

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#410]
Hi, I am **TRIDIB BAG.** I'm a GSSoC22 participant.
I want to add **Grammarly (Character Counter ) website** with proper documentation as there is nothing regarding this . I'm really want to contribute in this topic .
- It's a clone of grammarly with some additional feature. I have added Character count feature into it which shows typed and remaining character into screen and also here is a major feature is that we can copy Text with the button provided.

**Comment by swapnilsparsh** [comment]
It's already there like you explain in the issue, check it out [here](https://30daysofjs.netlify.app/24%20-%20word%20counter/)
