### ISSUE TITLE
Title: Youtube Link Downloader

### ISSUE THREAD

**Issue by StillAbeginnerr** [swapnilsparsh/30DaysOfJavaScript#419]
### Is your feature request related to a problem? Please describe.

I want to make  youtube video downloader project.

### Describe the solution you'd like.

HTML CSS and JAVASCRIPT TECH STACK
MOBILE RESPONSIVE
API to download videos of link posted

### Describe alternatives you've considered.

GOOD UI

### Add any other context or screenshots about the feature request here.
![image](https://user-images.githubusercontent.com/88205668/161426083-611e34a0-b0f9-43c7-9b9f-735fde5c10b5.png)

_No response_

**Comment by StillAbeginnerr** [comment]
I am a GSSoC participant and please assign this to me

**Comment by StillAbeginnerr** [comment]
and What is criteria for level 2 or 3 label?

**Comment by StillAbeginnerr** [comment]
@swapnilsparsh

**Comment by swapnilsparsh** [comment]
@StillAbeginnerr Great project but currently downloading Youtube videos using third-party API is against the rules/policy of YouTube so adding your project will risk other projects too.

**Comment by StillAbeginnerr** [comment]
Okay no problem
