### ISSUE TITLE
Speech Recognition 

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#420]
Hi, I am **TRIDIB BAG.** I'm a GSSoC22 participant.
I want to make a **Speech Recognition** using HTML, CSS, JS and wanted to add in this repo .

Can @swapnilsparsh you please assign it to me?

**Comment by Kushal997-das** [comment]
@swapnilsparsh Remove the tags as it is already exits 
https://github.com/khushi-purwar/WebDev-ProjectKart/pull/491
