### ISSUE TITLE
Title:  YouTube to mp4 converter

### ISSUE THREAD

**Issue by AnIkeT126** [swapnilsparsh/30DaysOfJavaScript#430]
### Is your feature request related to a problem? Please describe.

Some youtube videos are just too good to not be downloaded in our local machine and I intend to create a downloader for the same.

### Describe the solution you'd like.

A web-based calculator using ReactJs

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

None as of now.

**Comment by AnIkeT126** [comment]
@swapnilsparsh assign this issue to me and please add a level and GSSoC label.

**Comment by swapnilsparsh** [comment]
@AnIkeT126 Great project but currently downloading Youtube videos is against the rules/policy of YouTube so adding your project will risk other projects too.
