### ISSUE TITLE
Random Color Gnerator 

### ISSUE THREAD

**Issue by AnIkeT126** [swapnilsparsh/30DaysOfJavaScript#446]
### Is your feature request related to a problem? Please describe.

Well as the name suggests, it will randomly assign a new colour to the body of HTML page.

### Describe the solution you'd like.

This project aims to create a random color generator and in such a case comes with a handful of options from generating random colors, to going from infinite darkness to infinite brightness to going to generate a color gradient.

It can also revert back to last color.

### Describe alternatives you've considered.

None as of now

### Add any other context or screenshots about the feature request here.

None as of now

**Comment by AnIkeT126** [comment]
@swapnilsparsh please assign this issue to me and add a level label if possible.

**Comment by swapnilsparsh** [comment]
@AnIkeT126 It is already there on the website.
