### ISSUE TITLE
Add Palindrome Checker

### ISSUE THREAD

**Issue by abhilipsasahoo03** [swapnilsparsh/30DaysOfJavaScript#451]
I'm a GSSoC'22 Contributor and I'd like to add a Palindrome checker to check if any random string (whether a word, sentence or a number) is a palindrome or not. The output message is displayed through an alert box.

**Comment by abhilipsasahoo03** [comment]
Hi @swapnilsparsh kindly assign me this issue so that I can start working on it asap.

**Comment by Chandana-23** [comment]
@swapnilsparsh, Kindly assign this to me.  I will finish it off.

**Comment by abhilipsasahoo03** [comment]
> @swapnilsparsh, Kindly assign this to me.  I will finish it off.

Sorry I have already made a PR.
