### ISSUE TITLE
Snake game using speech recognition in javascript

### ISSUE THREAD

**Issue by ranimanya** [swapnilsparsh/30DaysOfJavaScript#456]
I intend to add a snake game which is voice controlled. It utilizes 'up', 'left', 'right', 'down' commands for moving the snake so that it can reach its food and consume it to become bigger in size by one unit every time it encounters food.

Please assign me this issue, I'm a GSSoc22 participant.

**Comment by swapnilsparsh** [comment]
> I intend to add a snake game which is voice controlled. It utilizes 'up', 'left', 'right', 'down' commands for moving the snake so that it can reach its food and consume it to become bigger in size by one unit every time it encounters food.
> 
> Please assign me this issue, I'm a GSSoc22 participant.

Will it be using HTML, CSS and JS only or any other tech also?

**Comment by ranimanya** [comment]
It will use HTML, CSS and JS Web APIs

**Comment by ranimanya** [comment]
It will use HTML, CSS and JS Web speech API
