### ISSUE TITLE
Title: hex gradient color

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#459]
### Is your feature request related to a problem? Please describe.

Hey I made hex gradient color Project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by swapnilsparsh** [comment]
Already there on the website

**Comment by kalashvasaniya** [comment]
Any idea you give me me?

**Comment by swapnilsparsh** [comment]
> Any idea you give me me?

Try to be more innovative.
