### ISSUE TITLE
Title: Triple congo 

### ISSUE THREAD

**Issue by Ajoe12** [swapnilsparsh/30DaysOfJavaScript#466]
### Is your feature request related to a problem? Please describe.

three drum with sound effect
built with HTML, Css and javascript

### Describe the solution you'd like.

Add a new website

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

![Screenshot (384)](https://user-images.githubusercontent.com/54743791/162249333-466716d4-952f-4bd4-adfd-ca3ab5684450.png)

**Comment by swapnilsparsh** [comment]
It is already there on the website
