### ISSUE TITLE
Google Sign up 

### ISSUE THREAD

**Issue by StillAbeginnerr** [swapnilsparsh/30DaysOfJavaScript#471]
### Is your feature request related to a problem? Please describe.

I want to add a project which shows google sign up API usage in html , css and javascript

### Describe the solution you'd like.

HTML CSS JS JQUERY

### Describe alternatives you've considered.
I am gssoc participant
.

**Comment by swapnilsparsh** [comment]
Not required now.

**Comment by StillAbeginnerr** [comment]
okay
