### ISSUE TITLE
Leap Year Checker

### ISSUE THREAD

**Issue by eswarbhageerath** [swapnilsparsh/30DaysOfJavaScript#473]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Leap Year Checker.

The idea behind this project
This is a very mini project which can be used to know the information about any year that is leap or not.

###How does it work
Whenever you enter a number in the input box and click submit, we can see the result in a box below .

please refer to these images
![leap](https://user-images.githubusercontent.com/76146796/162554377-ad528631-ad8f-4742-87f2-d2d50003f6e9.png)
![leap2](https://user-images.githubusercontent.com/76146796/162554750-2821df0d-513e-4aee-b7eb-aa1f6aae8beb.png)

**Comment by eswarbhageerath** [comment]
@swapnilsparsh Please review my PR

**Comment by eswarbhageerath** [comment]
@swapnilsparsh  I made PRs for 2 projects in this repository(Number Facts #472 and Leap Year Checker #473) ...But on GSSOC leaderboard, I can see only 1PR was merged and my score was only 25..please help me in this..I solved 2 issues using the same PR https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/494

**Comment by eswarbhageerath** [comment]
I am eligible for both the issues right..As I am new to git, I was unable to make 2 PRs , solved both the issues using same PR..Please check this issue, I think I can be scored for both the issues PR..Should I open any issue again with another PR to get score of second one?

**Comment by swapnilsparsh** [comment]
> I am eligible for both the issues right..As I am new to git, I was unable to make 2 PRs , solved both the issues using same PR..Please check this issue, I think I can be scored for both the issues PR..Should I open any issue again with another PR to get score of second one?

You made the PR for both the issues in one PR.

**Comment by eswarbhageerath** [comment]
Yes ..as I am new to git I made mistake and made PR for both issues in same branch at same time and made a single PR..but both issues were perfectly solved and they were merged too..please solve this sir..thank you

**Comment by eswarbhageerath** [comment]
May I open one of those issues again to get score for second one sir?

**Comment by swapnilsparsh** [comment]
> May I open one of those issues again to get score for second one sir?

I will convert your level2 label to level3 label.
Let me know your pr number.

**Comment by eswarbhageerath** [comment]
Thank you sir, This is my PR :    https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/494

**Comment by swapnilsparsh** [comment]
> Thank you sir, This is my PR :    https://github.com/swapnilsparsh/30DaysOfJavaScript/pull/494

Done the changes ✅
