### ISSUE TITLE
Title: Full Functional Html Form

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#477]
### Is your feature request related to a problem? Please describe.

So, basically this project is very big like I have to give 7-8 days on this!

### Describe the solution you'd like.

If a user fill form and submit its directly send to the mail of the other user - this project is big because I have to work on frontend as well as backend.

### Describe alternatives you've considered.

Pls. assign to level 3 :)

**Comment by swapnilsparsh** [comment]
Not required as of now.
