### ISSUE TITLE
Title: CSS Flex gallery 

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#478]
### Is your feature request related to a problem? Please describe.

Hey I made CSS Flex gallery Project Which Is Very Good!

### Describe the solution you'd like.

This Project is very Helpfull,
I Make This Project With the help of HTML&CSS.

### Describe alternatives you've considered.

The CSS Code are Available in very well mannered! & Easy to understand!

**Comment by swapnilsparsh** [comment]
This is JS repo,only HTML and CSS projects are not allowed as you have to use JS also.
