### ISSUE TITLE
Palindrome checker

### ISSUE THREAD

**Issue by eswarbhageerath** [swapnilsparsh/30DaysOfJavaScript#479]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Leap Year Checker.

The idea behind this project
This is a very mini project which can be used to know the information about any year that is leap or not.

###How does it work
Whenever you enter a number in the input box and click submit, we can see the result in a box below .

please refer to these images
![ss1](https://user-images.githubusercontent.com/76146796/162605068-7a476077-4d32-4f0b-aeaa-a0106cff32a8.png)
![ss2](https://user-images.githubusercontent.com/76146796/162605069-68814b6e-fad8-4e58-83c1-a30bc83cfb53.png)

**Comment by Pranav108** [comment]
I would love to work on it, can I take it?

**Comment by eswarbhageerath** [comment]
@swapnilsparsh  Please review my PR..Thank you
