### ISSUE TITLE
Title: I want to add  A new year countdown project to the 30DaysOfJavaScript repository

### ISSUE THREAD

**Issue by AmolShelke2** [swapnilsparsh/30DaysOfJavaScript#480]
### Is your feature request related to a problem? Please describe.

No It is not related to a problem,

### Describe the solution you'd like.

Hey project admin I'm a GSSOC participant and I have come up with your project and I would love to contribute to your project one more time I want to add a New year countdown project it is a very basic project for beginners who don't know how to work with dates and DOM it can give them an idea of how things work so I hope that you will go through my issue and assign me this issue to work on...

### Describe alternatives you've considered.

I'm also attaching the screenshot of my project you can give it a look😊
![New Year Countdown - Google Chrome 10-04-2022 12 24 49 PM](https://user-images.githubusercontent.com/95171638/162606387-24f42b72-4e55-4d61-af5d-0e92ef4882de.png)

**Comment by swapnilsparsh** [comment]
Use an algorithm such that every year it gets reset automatically.
