### ISSUE TITLE
Adding A textutilty with a button to switch between dark<->light mode 

### ISSUE THREAD

**Issue by MR-DHRUV** [swapnilsparsh/30DaysOfJavaScript#499]
Sir, I would like Text-Based utility that can be used to convert text to uppercase, lowercase, capitalize, remove extra spaces if present, parse content from HTML tags etc.

It will have a button to switch between dark and light mode
It will be react based

Here is the sample: https://mr-dhruv.github.io/Textify.me/

**Comment by swapnilsparsh** [comment]
Only HTML, CSS, and Vanilla JS only.
