### ISSUE TITLE
Title: Add Temperature converter website

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [swapnilsparsh/30DaysOfJavaScript#509]
### Is your feature request related to a problem? Please describe.

I want to add a temperature converter website that helpful in without calculating the conversion from Fahrenheit to Celsius.User just need to add input values in input fields,

### Describe the solution you'd like.

The user will input a temperature in either Fahrenheit or Celsius and press a "convert" button. The converted temperature will then be displayed with the correct unit.

Your UI should include four main elements:

Input field for the user to type in their temperature -

Dropdown menu or radio button for the user to choose if they are inputting in Celsius or Fahrenheit

"Convert" button to trigger the temperature conversion

Display area for the final converted temperature and unit

### Describe alternatives you've considered.

For an extra challenge: I can add in a third conversion option to convert from and to Kelvin as well.

### Add any other context or screenshots about the feature request here.

<img width="660" alt="Temperature converter mobile app" src="https://user-images.githubusercontent.com/89297894/163343900-b93561cc-c7e7-4969-a092-40b910715037.png">

**Comment by AsmaIbrahimButt** [comment]
@swapnilsparsh kindly assign me this issue

**Comment by AKD-01** [comment]
@swapnilsparsh Could you please assign me this issue.
