### ISSUE TITLE
Title: Dice Game

### ISSUE THREAD

**Issue by Mennapika** [swapnilsparsh/30DaysOfJavaScript#515]
### Is your feature request related to a problem? Please describe.

a two player roll the dice and sum what they get the one who reached >=20first is the winner 

### Describe the solution you'd like.

Using pure Html ,CSS & JS to solve it  

### Describe alternatives you've considered.

when its the turn of player1  it disable player2 and vice verse

### Add any other context or screenshots about the feature request here.

![Capture](https://user-images.githubusercontent.com/38566183/163512835-1e5840e9-afb0-4d23-876b-d06190179ad6.PNG)

**Comment by LB540** [comment]
I would like to work on this, please assign this to me
