### ISSUE TITLE
EMI Calculator

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#531]
This is a Calculator used to calculate EMI of Your taken Loan amount entered by user.
### Tech Stack Used:
- HTML,CSS,Javascript

**Comment by Mrjoy832** [comment]
@swapnilsparsh , Hey! please assign

**Comment by Mrjoy832** [comment]
@swapnilsparsh  Why it's closed?

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.

**Comment by Mrjoy832** [comment]
> Try to be more innovative with your project idea as we already have many projects like this.

okay sure
