### ISSUE TITLE
Sum Of numbers from 1 to given number

### ISSUE THREAD

**Issue by eswarbhageerath** [swapnilsparsh/30DaysOfJavaScript#532]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Sum Of Numbers.

The idea behind this project
This is a very mini project which can be used to know the Sum Of Numbers. from 1 to given number
###How does it work
Whenever you enter a number in the input box and click submit, we can see the result in a box below .

**Comment by eswarbhageerath** [comment]
@swapnilsparsh Why was this issue closed?

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.
