### ISSUE TITLE
Title: Polynomial Long Division Calculator

### ISSUE THREAD

**Issue by Salma-Hamed** [swapnilsparsh/30DaysOfJavaScript#533]
### Is your feature request related to a problem? Please describe.

This application performs the long division of polynomials.

### Describe the solution you'd like.

1. To divide a polynomial by another one:
    - Enter each polynomial in terms of x or X, without spaces between each term.
    - Use the power symbol (^) for terms with order more than one.
2. Click on (Divide) button.
3. To perform another division operation click on (Clear) button. 

I am a GSSoC'22 participant. Please assign it to me.

### Describe alternatives you've considered.

--

### Add any other context or screenshots about the feature request here.

I have uploaded it on GitHub which URL is given below:
(https://github.com/Salma-Hamed/Polynomial-Long-Division-Calculator).

![calc](https://user-images.githubusercontent.com/71777717/163731387-55044c7c-aa8d-4827-bdda-39a6294ed8ab.PNG)

**Comment by Salma-Hamed** [comment]
@swapnilsparsh why did you close this issue

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.
