### ISSUE TITLE
Title: Music Player!

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#534]
### Which pre-existing JavaScript project will you be working on?

Hey I made Music Player Which Is Very Good!

### Describe your enhancement/improvement

This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript.

### Anything you need to say to the Reviewers

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by kalashvasaniya** [comment]
Any specific for closing all my issue :(

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this, also we already have a music player on the repo.
