### ISSUE TITLE
Title: Dark mode toggle

### ISSUE THREAD

**Issue by kalashvasaniya** [swapnilsparsh/30DaysOfJavaScript#536]
### Which pre-existing JavaScript project will you be working on?

on single click website convert normal to dark mode

### Describe your enhancement/improvement

Helpful project

### Anything you need to say to the Reviewers

NA

**Comment by kalashvasaniya** [comment]
Any specific reason for closing all my issue :(

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.

**Comment by kalashvasaniya** [comment]
> Try to be more innovative with your project idea as we already have many projects like this.

Can you pls. suggest me some idea plssss.

**Comment by swapnilsparsh** [comment]
> > Try to be more innovative with your project idea as we already have many projects like this.
> 
> Can you pls. suggest me some idea plssss.

You have to think it by your own or take help from the google.
