### ISSUE TITLE
Tech Number Checker

### ISSUE THREAD

**Issue by abhilipsasahoo03** [swapnilsparsh/30DaysOfJavaScript#537]
### Is your feature request related to a problem? Please describe.

A number is called Tech number, if it has an even number of digits, and when we split the number into two halves then the square of the sum of those halves is equal to the number itself. For example, 2025 is a Tech number.
My feature request helps to verify if whether a number is a Tech number or not. 

### Describe the solution you'd like.

I'd like to create a Tech Number checker which takes a number as input and displays if it's a Tech number Or not. I'd like to be assigned this issue under GSSOC'22

### Describe alternatives you've considered.

None.

### Add any other context or screenshots about the feature request here.

None.

**Comment by abhilipsasahoo03** [comment]
Hi @swapnilsparsh I don't get why this issue has been closed as completed?

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.
It is not completed, issue has been closed.
