### ISSUE TITLE
Tic tac toe game using React js

### ISSUE THREAD

**Issue by anshumanlite** [swapnilsparsh/30DaysOfJavaScript#539]
I have created an amazing tic tac toe game using React js with some cool animation and designing. I want to contribute in this repo and add my work in this repository.

**Comment by anshumanlite** [comment]
Do i have to change something? I dont know you closed this issue.

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this, also we already have a tic tac toe game on the repo.
