### ISSUE TITLE
Trigonometric Calculator🧮 

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#547]
Trigonometric calculator is a calculator which will help to calculate the sin, cos,tan value of any given angle and it will display the relevant result . It's made using HTML,CSS,JS

![image](https://user-images.githubusercontent.com/77873383/163897642-52c88ab6-d7b1-4188-995f-356bae5bb84a.png)

It's already created ..please @swapnilsparsh  assign on this issue, I have make PR

**Comment by swapnilsparsh** [comment]
Try to be more innovative with your project idea as we already have many projects like this.
