### ISSUE TITLE
Analog + digital clock 

### ISSUE THREAD

**Issue by Kumar-Ankit56** [swapnilsparsh/30DaysOfJavaScript#550]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is an analog+digital clock in a single unit.

### The idea behind this project
The idea behind this project is just a by taking inspiration from the home hanging clock and big digital screen clock at the railway station.

### How does it work
Firstly this clock functionality is totally based on javascript functionality so the js code will fetch the machine date and timing then it will parse hr, min, sec from this date and implement some different -different logic for analog and digital clocks.

for more details please refer to the attached images.
![Screenshot (127)](https://user-images.githubusercontent.com/73521123/164026614-b94b71d7-9d07-48d2-8097-f2c097db92e7.png)

**Comment by shivamagarwal2510** [comment]
I want to contribute in this issue. Please assign it to me.

**Comment by Kumar-Ankit56** [comment]
Sorry to say, It's not possible buddy, 
This issue is generated by me first I will be only able to contribute

**Comment by swapnilsparsh** [comment]
Analog and Digital both clocks are already there on the repo.

**Comment by Kumar-Ankit56** [comment]
@swapnilsparsh Yeah in the repo analog and digital clocks are available but both are in the separated clocks.
Please check out once again my project analog and digital clock both are in the same project.
review it please.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Yeah in the repo analog and digital clocks are available but both are in the separated clocks. Please check out once again my project analog and digital clock both are in the same project. review it please.

No need for the same project

**Comment by Kumar-Ankit56** [comment]
No issue.
