### ISSUE TITLE
Switchable Image Gallery

### ISSUE THREAD

**Issue by Kumar-Ankit56** [swapnilsparsh/30DaysOfJavaScript#551]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a Switchable IMG gallery.

### The idea behind this project
Like we often visit e-commerce sites for shopping so in the product section there is a gallery of product which compose of 4 and 5 img as one is on big screen and rest of then in the mini frame, whenever we wish to look minify img at big frame we just click on small img. Project idea from there only.

### How does it work.
Here in this project, four images are available in the left minify frame, and among one image on the right side of the screen, functionality is similar as I have stated above.

for more details please refer to this attached images.
![Screenshot (121)](https://user-images.githubusercontent.com/73521123/164027945-497235a0-933f-4287-8580-2e4cb25377ea.png)
![Screenshot (122)](https://user-images.githubusercontent.com/73521123/164027969-09e63e03-5e1f-4f44-84a5-b50b48e4d44b.png)

**Comment by Kumar-Ankit56** [comment]
@swapnilsparsh any reason for this closing the issue, please let me know sir as there is no message while closing from your side.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh any reason for this closing the issue, please let me know sir as there is no message while closing from your side.


Try to be more innovative with your project idea as we already have many projects like this.

**Comment by Kumar-Ankit56** [comment]
oh I got it, definitly I will
