### ISSUE TITLE
Split The Bill

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#570]
I want to add an application about **Split The Bill** which will be made to split the bills in any restaurant among the friends or family members . It will be made using HTML,CSS,JS.
It will have 4 Functionalites ->
- Total Ordered Amount
- Tip % on that amount
- No of customers wanted to split the bill
By taking these data from users ...it will split the bill

**Comment by Mrjoy832** [comment]
@swapnilsparsh please assign

**Comment by Mrjoy832** [comment]
@swapnilsparsh As it wasn't there..that why i created the issue🙂🙂

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh As it wasn't there..thats why i created the issue🙂🙂

Try to be more innovative as we already have many basic/simple algorithm projects.
