### ISSUE TITLE
Adding skip, next, prev and more songs in Music Player (Project Number 28)

### ISSUE THREAD

**Issue by ramanabhinav7** [swapnilsparsh/30DaysOfJavaScript#58]
1>it have problem with script part, that __audio  player is unable to play songs__

**Comment by swapnilsparsh** [comment]
> 1>it have problem with script part, that **audio player is unable to play songs**

Can you please elaborate on your issue and the project name?🙂

**Comment by ramanabhinav7** [comment]
Respected sir,

Project name is "audio player"
 Issue - it is unable to play the song and and also unable to skip the song
too.
I have written the functionality of " play and skip song" code in script
tag

So any one who want to correct it he/she can directly jump to script tag .



Thanks & Regards
Abhinav Kumar dubey
