### ISSUE TITLE
Image not Displayed in the Website

### ISSUE THREAD

**Issue by DragonUncaged** [swapnilsparsh/30DaysOfJavaScript#590]
### What happened?

Some of the Project Doesn't have the image uploaded

![image](https://user-images.githubusercontent.com/72241207/165040539-0858a2b0-81c4-434a-967e-89d776745e16.png)

### How can we reproduce this bug?

- Image Not Uploaded

### Urgency (Optional)

Low priority

**Comment by swapnilsparsh** [comment]
Take the screenshots of the projects in full screen by using the F11 key and then use it.

**Comment by DragonUncaged** [comment]
i know how to take the screenshots.

But i don't now how the https://30daysofjs.netlify.app/ fetches the image and adds to the thumbnail.

most of the projects doesn't have the preview image uploaded

**Comment by DragonUncaged** [comment]
139 missing
