### ISSUE TITLE
Space Shooter Game🚀

### ISSUE THREAD

**Issue by Mrjoy832** [swapnilsparsh/30DaysOfJavaScript#600]
### Is your feature request related to a problem? Please describe.

I am GSSoC'22 Contributor want to add **Space Shooter Game** which will be made using **HTML,CSS,JS** , and The code will be responsive .

### Describe the solution you'd like.

I will make this using HTML,CSS,JS

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

I have not made it till now

**Comment by Mrjoy832** [comment]
@swapnilsparsh , please assign

**Comment by Mrjoy832** [comment]
@swapnilsparsh what happened with this one?🙂

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh what happened with this one?🙂

Already there in the repo
