### ISSUE TITLE
Adding a preloader to the website

### ISSUE THREAD

**Issue by samipak458** [swapnilsparsh/30DaysOfJavaScript#603]
### Is your feature request related to a problem? Please describe.

Website is very simple. I think by adding pre-loader website look better. Some picture are taking time in loading. One more benefit of pre-loader when website is fully ready it will be shown in the mean time pre-loader will run.

### Describe the solution you'd like.

Simple pre-loader but visually appealing.

### Describe alternatives you've considered.

Describe as above

**Comment by swapnilsparsh** [comment]
Keep preloader related to JavaScript

**Comment by samipak458** [comment]
30days of JavaScript index.html is not in the repository. 

![image](https://user-images.githubusercontent.com/52650290/166137498-68a1eb7f-1a6e-4802-a4dc-36a8d9193a27.png)
File with name index.html has random choice picker project.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh 30days of JavaScript index.html is not in the repository.
> 
> ![image](https://user-images.githubusercontent.com/52650290/166137498-68a1eb7f-1a6e-4802-a4dc-36a8d9193a27.png) File with name index.html has random choice picker project.

Fixed ✅
