### ISSUE TITLE
Title: Math Game

### ISSUE THREAD

**Issue by iamrahulmahato** [swapnilsparsh/30DaysOfJavaScript#626]
### Is your feature request related to a problem? Please describe.

Sometimes math is difficult for students to learn 

### Describe the solution you'd like.

We will make a math game which will be fun to play and learn about math

### Describe alternatives you've considered.

ss:
![Web capture_30-4-2022_13447_](https://user-images.githubusercontent.com/49890655/166122082-2a62d53e-097a-4be8-8366-c54d736f8a25.jpeg)

**Comment by swapnilsparsh** [comment]
@iamrahulmahato Good Luck 👍🏻
