### ISSUE TITLE
Add a web chat app

### ISSUE THREAD

**Issue by DAP2506** [swapnilsparsh/30DaysOfJavaScript#67]
adding a web chat ui after that adding the server side using sockets

**Comment by swapnilsparsh** [comment]
> adding a web chat ui after that adding the server side using sockets

Can you please elaborate this issue ?

**Comment by AkhilChoubey** [comment]
Hello @DAP2506 , I can add a web chatting app to this repo with server side created using nodejs and with the help of soket.io web-socket for real-time end to end updation . Please assign this issue to me  , so that I can start working on this.

**Comment by swapnilsparsh** [comment]
> Hello @swapnilsparsh , I can add a web chatting app to this repo with server side created using nodejs and with the help of soket.io web-socket for real-time end to end updation . Please assign this issue to me , so that I can start working on this.

You will be adding a project in this repo then Good Luck 👍🏼

**Comment by DAP2506** [comment]
Hello @swapnilsparsh i thought it will be assigned to me.
Can i make a pr for this issue as it is not assigned to me.
i have solved this issue but it is not assigned to me that what to do sir?
