### ISSUE TITLE
Title: Implement a validation form 

### ISSUE THREAD

**Issue by TANYA-CHAN** [swapnilsparsh/30DaysOfJavaScript#714]
### Is your feature request related to a problem? Please describe.

I want to add a new project which to Implement a validation form 

### Describe the solution you'd like.

A client-side form validator built using HTML5, SCSS & JavaScript with no frameworks or libraries.

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

Screenshots will be in projects README

**Comment by TANYA-CHAN** [comment]
@swapnilsparsh could you please tell what happened I just wanted to contribute.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh could you please tell what happened I just wanted to contribute.

It is already there.
