### ISSUE TITLE
Light / dark mode switcher

### ISSUE THREAD

**Issue by srinjoy-26** [swapnilsparsh/30DaysOfJavaScript#758]
### Is your feature request related to a problem? Please describe.

NO , I want to add a new project to this repo.

### Describe the solution you'd like.

My project will consist of a webpage with a slide button to switch light and dark mode of the entire page.
Tech stack :- 
- HTML5
- CSS3
- JS

### Describe alternatives you've considered.

No alternatives.

### Add any other context or screenshots about the feature request here.

<img width="269" alt="Screenshot 2022-05-13 220329" src="https://user-images.githubusercontent.com/91176055/168328878-80ad0837-2601-438f-9099-830d4cb25acb.png">
<img width="262" alt="Screenshot 2022-05-13 220417" src="https://user-images.githubusercontent.com/91176055/168328914-4b6e5dcd-e907-4ebf-adc5-107f56a26542.png">

**Comment by srinjoy-26** [comment]
@swapnilsparsh sir why u closed my issue

**Comment by yash-25log** [comment]
@srinjoy-26 it might be already existing

**Comment by srinjoy-26** [comment]
> @srinjoy-26 it might be already existing

Ok sir 😞
