### ISSUE TITLE
Guess My Number Game

### ISSUE THREAD

**Issue by Khushi-Mattu** [swapnilsparsh/30DaysOfJavaScript#824]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/82451914/169478921-e810d937-f38d-44c0-928d-5fb9e5150cbb.png)

### Describe the solution you'd like.

You have to guess the number
![image](https://user-images.githubusercontent.com/82451914/169479006-25576883-b5be-4d2c-9658-2e573df0c5c7.png)
It gives hints like this whether the number entered is lower or higher than the number to be guessed.
![image](https://user-images.githubusercontent.com/82451914/169479143-a366b139-de1e-4270-bb79-a23b81580ff4.png)
When we enter the correct number
we can play again using the again button

### Describe alternatives you've considered.

.

**Comment by Khushi-Mattu** [comment]
please assign this issue to me

**Comment by swapnilsparsh** [comment]
@Khushi-Mattu  Good Luck 👍🏻
