### ISSUE TITLE
Arrange projects w.r.t. difficulty

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#846]
1. Divide all the projects which are there on the repo on the basis of 3 categories which are:
    i.Easy
    ii. Medium
    iii. Hard
**Make changes [here](https://github.com/swapnilsparsh/30DaysOfJavaScript/blob/master/index.html) by making new headings**

2. Edit the ReadMe also with the same info and proper difficulty as changed on the website with proper headings.

**Comment by swapnilsparsh** [comment]
> will you pls elaborate this issue as i have some confusion how to distinguish easy ,medium and hard one

On the basis of the JS concept used in making the project.

**Comment by DragonUncaged** [comment]
assign me

**Comment by DragonUncaged** [comment]
i can make the folder and separate it.

**Comment by Abhishek786-Kolvekar** [comment]
@thisisharsh7 Can I work on this issue?
I will send the finalized cleaned repo by evening.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Can I work on this issue?
> I will send the finalized cleaned repo by evening.

New assigning of issues has been closed.
