### ISSUE TITLE
Remove the social media handles from footer and contrast the footer text

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#85]
![Annotation 2021-10-08 012942](https://user-images.githubusercontent.com/69387608/136453809-2cfe0ebf-911a-4be6-88f7-473d20dd5c48.png)

**Comment by MuckHub** [comment]
I will take this one

**Comment by jatiinyadav** [comment]
This issue has been resolved by @MuckHub
