### ISSUE TITLE
Kids Learning Website

### ISSUE THREAD

**Issue by Sukriti-m** [swapnilsparsh/30DaysOfJavaScript#937]
### Is your feature request related to a problem? Please describe.

Kids Learning Website

### Describe the solution you'd like.

I will add a website in which the kids will be able to learn alphabets, numbers, shapes, fruits, animals, stories,rhymes,etc. easily.

### Describe alternatives you've considered.

.

### Add any other context or screenshots about the feature request here.

I am contributor at GSSoC '22. Please assign this issue to me.

@swapnilsparsh

**Comment by swapnilsparsh** [comment]
No new assigning of issues.
