### ISSUE TITLE
204- linguisticAcademy

### ISSUE THREAD

**Issue by Alidhuniya** [swapnilsparsh/30DaysOfJavaScript#947]
I want to add, linguistic academy center website which is fetched by js fetch API from json local data
previous pull request was empty folder and I'm sorry for taking your time

![Screenshot (316)](https://user-images.githubusercontent.com/39728698/193512860-b6d8d569-0da4-40e9-94f4-183bef6542cc.png)

**Comment by swapnilsparsh** [comment]
No package.json projects allowed
Only pure HTML/CSS/JS projects.
