### ISSUE TITLE
204 - carRacing

### ISSUE THREAD

**Issue by Alidhuniya** [swapnilsparsh/30DaysOfJavaScript#953]
car racing game in vanilla js in browser

**Comment by himanshu17-2000** [comment]
can i work on this issue please ,Thank you

**Comment by Alidhuniya** [comment]
> can i work on this issue please ,Thank you

it's info for pull request. see pull request tab, project is in queue. waiting admin to merge pull request

**Comment by swapnilsparsh** [comment]
Already there
