### ISSUE TITLE
Make new Landing Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#981]
Inspired from current layout make a new design using only HTML, CSS with more better UI/UX.

Current Layout/Webiste -> https://30daysofjs.netlify.app/

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Hello sir Please assign this to me

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-09 17-33-13](https://user-images.githubusercontent.com/108119109/217807702-2d7bcf18-03c4-4605-9423-e045df7ad41c.png)
