### ISSUE TITLE
 Writing Documentation of Project in HIndi Language

### ISSUE THREAD

**Issue by Bharadwajshivam28** [swapnilsparsh/30DaysOfJavaScript#990]
Hello Respected sir/mam
   If you like my idea then we can write a Documentation on this project in Hindi Language

Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language well so one can read the documentation in Hindi language and understand Project well

If you like my idea than we can move ahead

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh   If you find it valueable then please assign me this under iwoc with any difficulty tag

**Comment by swapnilsparsh** [comment]
Not Needed
