### ISSUE TITLE
Creating a Process of how the project work in Readme file

### ISSUE THREAD

**Issue by Bharadwajshivam28** [swapnilsparsh/30DaysOfJavaScript#991]
It will be good if process of project will be added in Readme file so one can easily understand how the project works

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh  If you find it valueable then please assign me this under iwoc with any difficulty tag

**Comment by swapnilsparsh** [comment]
Not Needed

**Comment by Bharadwajshivam28** [comment]
ok sir
