### ISSUE TITLE
Title: UI of Password Strength Checker can be made better using some effects

### ISSUE THREAD

**Issue by A91y** [swapnilsparsh/30DaysOfJavaScript#992]
### Which pre-existing JavaScript project will you be working on?

204 - Password Strength Checker

### Describe your enhancement/improvement

UI can be made better using better colour pattern and effect such as hover.

**Comment by A91y** [comment]
Please assign me this issue under IWOC

**Comment by A91y** [comment]
Why is this issue closed without any comment?

**Comment by swapnilsparsh** [comment]
No changes required
