### ISSUE TITLE
Show toast message in Random Color Generator

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#995]
In [Random Color Generator](https://30daysofjs.netlify.app/03%20-%20random%20color%20generator/) when clicking on the color the color gets copied so it should show some toast message "Color Copied" with color code

**Use Vanilla JS only.**

**Comment by RohanHandore** [comment]
is anyone working on this issue?

**Comment by swapnilsparsh** [comment]
> is anyone working on this issue?

No, I have assigned you.
