### ISSUE TITLE
Fix Countdown Timer

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#996]
[Countdown Timer](https://30daysofjs.netlify.app/16%20-%20Countdown%20Timer/index.html)
1. When time is not set then Start button should be disbaled, once the time is set then only start button should be active.
2. Put a sub heading below Countdown Timer stating "Set Your Timer"

**Comment by ananyakushal** [comment]
Hey @swapnilsparsh please assign me this task under IWOC'23.

**Comment by swapnilsparsh** [comment]
Resolved by @ananyakushal #1010
