### ISSUE TITLE
Fix Drawing Pad

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#997]
[Drawing Pad](https://30daysofjs.netlify.app/23%20-%20drawing%20pad/)

When I am drawing line, rectangle, circle it should show how big is the line/rectangle/circle is being getting drawn.

**Comment by ananyakushal** [comment]
Hey @swapnilsparsh I am interested in this issue and would love to contribute in it. Please assign me this task under IWOC'23.

**Comment by subhamkumarr** [comment]
@swapnilsparsh I would like to work on this please assign it to me

**Comment by shauryakushwaha08** [comment]
please assign this issue to me
