### ISSUE TITLE
Enhance Music Player

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#998]
[Music Player](https://30daysofjs.netlify.app/23%20-%20drawing%20pad/)

1. Change the Header Title and make it "Music Player"
2. Use the font which is mentioned [here ](https://github.com/swapnilsparsh/30DaysOfJavaScript/tree/master/21%20-%20Wave%20Effect)by making a seperate font folder inside Music Player Folder 
3. Add Volume Control options below the play/prev/next button

**Comment by GitWiz01** [comment]
@swapnilsparsh I would like to work on it, please assign me this under iwoc'23

**Comment by subhamkumarr** [comment]
Please assign it to me

**Comment by subhamkumarr** [comment]
@swapnilsparsh Sir i have to fork entire repo? ya music player folder

**Comment by subhamkumarr** [comment]
Sir I have done the required changes

**Comment by subhamkumarr** [comment]
sir please check, i have done the required changes

**Comment by subhamkumarr** [comment]
@swapnilsparsh required changes are correct?
