### ISSUE TITLE
Fix Pop the Balloons

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/30DaysOfJavaScript#999]
[Pop the Balloons](https://30daysofjs.netlify.app/31%20-%20pop%20the%20balloons/)

1. Fix the spelling of Ballons in the Title of the webpage
2. Sometime balloons get poped when mouse is not near the balloons when moving the cursor fast so fix it

**Comment by Bharadwajshivam28** [comment]
assign to me sir @swapnilsparsh

**Comment by Marin303** [comment]
I would like to be assigned here.

**Comment by Marin303** [comment]
Is the task here aimed at slowing down the speed of the cursor or use mouseenter? Also, there is bigger problem of not using forEach, querySelectorAll and unnecessary removeEvent function. Right now game can be finished if user crossing few times on already cracked balloon so maybe is that what is asked on issue?

**Comment by swapnilsparsh** [comment]
I have assigned you . Good Luck 👍
